### ISSUE TITLE
Error in file(con, "r") : invalid 'description' argument

### ISSUE THREAD

**Issue by emsweene** [swirldev/swirl#107]
I have created my own module.  When I run it the first time, it runs perfectly.  When I try again I always get the output: 

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

I'
m unable to get the module to work unless I delete the lesson, create a new one, and copy all of the code into this.   Then it will work the first time I run it and then fail again.  I'm using a Mac 

sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RColorBrewer_1.0-5 swirl_2.1.1       

loaded via a namespace (and not attached):
 [1] digest_0.6.4   httr_0.2       openintro_1.4  plotrix_3.5-3  pwr_1.1.1     
 [6] RCurl_1.95-4.1 stringr_0.6.2  testthat_0.8.1 tools_3.0.2    whisker_0.3-2 
[11] yaml_2.1.10 

Thanks! 
Elizabeth

**Comment by lpace** [comment]
Nick,

If you wouldn't mind, could you take a look at the following and tell me what is going on? I am creating the Test1 course in the Test2 lesson directory. I am using Windows--long story. In RStudio, my course builds correctly, loads correctly, but when I get to the option 1 select it, I get the following, which I have replicated numerous times. I am porting everything over to Linux, but am stuck in the Windows world for the moment:

| Please choose a course, or type 0 to exit swirl.

1: Data Analysis
2: MyCourse
3: R Programming
4: Test2
5: UserLearnR
6: Take me to the swirl course repository!

Selection: 4

| Please choose a lesson, or type 0 to return to course menu.

1: Test1

Selection: 1

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

I have a very recent download of the development versions of swirl and swirlify.

Thanks for any insight you can offer. This is an incredibly useful tool. I like YAML and applaud your choices for swirl.

Best,

Larry Pace (I am an old geezer who loves to program in R and write statistics books and R books). I also did a stint in corporate training at Xerox, so I learned curriculum development. If I can help you guys in any way, give me a shout out: lpace@keiseruniversity.edu.

**Comment by lpace** [comment]
By the way, here's my traceback if that will help any:

> traceback()
14: file(con, "r")
13: readLines(input)
12: paste(readLines(input), collapse = "\n")
11: yaml.load(paste(readLines(input), collapse = "\n"), ...)
10: yaml.load_file(file)
9: parse_content.yaml(dataName, e)
8: parse_content(dataName, e)
7: loadLesson.default(e, courseU, lesson)
6: loadLesson(e, courseU, lesson)
5: mainMenu.default(e)
4: mainMenu(e)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)

**Comment by WilCrofter** [comment]
Hi Larry. I am also an old geezer, and also relatively well preserved =D. I've been a swirl developer since Nick first released the app. I hope I can help.

The diagnostic, `Error in file(con, "r") : invalid 'description' argument`,  indicates that `file`'s first argument, `con`, is invalid. Here's a likely way for that to happen
```
con <- NULL
temp <- file(con, "r")
Error in file(con, "r") : invalid 'description' argument
```
Looking through the swirl and yaml source code, the `con` argument traces back to the first argument, `dataName`, of `parse_content`. (See [line 300, menu.R](https://github.com/swirldev/swirl/blob/master/R/menu.R#L300) and to the code on lines 272-274 above it.) Something went wrong there, probably. I can't say exactly what. I'd guess a file format or directory structure is the culprit, but I'm not sure.

I have a very short swirl course [here](https://github.com/WilCrofter/ErrFind) which was recently used for debugging something. Comparing its files and structure with yours might reveal something. Note the header in the `lesson` file.
```
- Class: meta
  Course: ErrFind
  Lesson: ErrTrack
  Author: Swirl Coders
  Type: Standard
  Organization: Johns Hopkins Bloomberg School of Public Health
  Version: 2.2.0
```
There is a utility which Nick and I wrote and which some people like [here](https://github.com/swirldev/swirlify/blob/master/R/yaml_writer.R). It takes care of a lot of the yaml cruft.

BTW, two courses are under development at the moment. One is a swirl companion to Roger Peng's Exploratory Data Analysis. The [other](https://github.com/WilCrofter/calc_for_data_science) (in very preliminary stages) is a calculus and linear algebra primer designed to bridge a gap between the data science specialization and an anticipated linear models MOOC. We can always use help.

**Comment by lpace** [comment]
Hi Will,

Thanks! I just ported everything over to Lubuntu on one of my otherwise useless laptops, and I have it all working now. Swirl is pretty nifty. I'm working on a site for people in the behavioral and social sicences (my background is psychometrics) to teach the to use R for data analysis and get away from SPSS, to which I would say good riddance. Give me something to do, and I'll be happy to pitch in.

LAP

**Comment by WilCrofter** [comment]
Hey, Larry. Yours is an excellent project, IMO. 

Gina and I are a retired applied math couple. In addition to swirl we're involved in a [neuroimaging project](http://wilcrofter.github.io/know_brainR/) which, though peripheral to psychometrics, seems harmless to mention in context.

We'd be delighted with any original course material you'd care to contribute. Sean intends to design a more formal, centralized repository for courses not necessarily related to the Data Science Specialization. We may even get material on the statistics of Higgs boson detection.

If you're inclined, the Exploratory Data Analysis course which Gina is writing, and should be finished by the end of the month, will need beta testing. Currently it's in the [EDA branch of swirl_courses](https://github.com/swirldev/swirl_courses/tree/eda). (I'll surely be one of the beta testers myself.) As far as I know, the only way to install it at the moment is to check out the branch with git and use `install_course_directory`. 

Bill

**Comment by gtramont** [comment]
Hello everybody! I'm starting to use R (I really have no previous knowledge) and I have the same error when I want to select a course:

| Please choose a course, or type 0 to exit swirl.

1: swirldev-swirl courses-df512b2
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

1: R Programming

Selection: 1

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

> traceback()
15: file(con, "r")
14: readLines(input)
13: paste(readLines(input), collapse = "\n")
12: yaml.load(paste(readLines(input), collapse = "\n"), ...)
11: yaml.load_file(file)
10: parse_content.yaml(file, e)
9: parse_content.default(dataName, e)
8: parse_content(dataName, e)
7: loadLesson.default(e, courseU, lesson)
6: loadLesson(e, courseU, lesson)
5: mainMenu.default(e)
4: mainMenu(e)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)

So, there I leave the error and the traceback. I hope I can get some help :D
I have already tried updating to the latest dev version of swirl by typing:

devtools::install_github("swirldev/swirl")

But I get another error:

Error in loadNamespace(name) : there is no package called ‘devtools’

I'm really really bad at R :( so any help will be useful! 
Thanks!!!

**Comment by WilCrofter** [comment]
@gtramont,  your course installation is messed up. Try this:
```
library(swirl)
uninstall_course("swirldev-swirl courses-df512b2")
install_from_swirl("R Programming")
```

**Comment by gtramont** [comment]
Thank you so much WilCrofter! Problems solved :D

**Comment by Gouravgupta0420** [comment]
I am having the following problem:

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Don't install anything for me. I'll do it myself.

Selection: 1

| Sorry, but I'm unable to fetch <U+0091>R Programming: The basics of programming in R<U+0092>
| right now. Are you sure you have an internet connection? If so, would you like to
| try again or visit the course repository for instructions on how to install a
| course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.

Even manual installation is not working using zip file.

> install_course_zip("~/Downloads/swirl_courses-master.zip", multi = TRUE, which_course = "R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/Gaurav Gupta/Documents/Downloads/swirl_courses-master.zip' cannot be opened.

**Comment by WilCrofter** [comment]
Try unziping `swirl-courses-master.zip` manually and using `install_course_directory`. If you unzipped to your Downloads directory, you would do the following:
```
library(swirl)
setwd('C:/Users/Gaurav Gupta/Documents/Downloads/')
install_course_directory('swirl_courses/R_Programming')
```
It's possible the space in the path to your Downloads directory is causing problems. I don't think so, but if the `setwd` step doesn't work, you may have to move the unzipped folder.

**Comment by Oriehi** [comment]
Hello everyone, am new to R and am interested in working with mass spect data on CM10 chips at 1800 energy level to predict possible proteins that could be represented in a sample analysis.
Questions
1. Has any one done anything in this direction?
2. How do I bring in the CSV file into R bioconductor then analyze the data contained in the CSV file and relate it to a protein database? 
3. Which protein database can this be related to and how can the relation be drawn to pick the proteins that are contained in the data contained in the chip.
Thank you so much for the anticipated help!

**Comment by WilCrofter** [comment]
For reading a csv file in R, see the documentation for the R functions `read.csv` and `read.table`, e.g., type `help(read.csv)` from the R prompt.

For specific ChIP help you will have to consult the Bioconductor site. You may find the EdX courses by [Rafael Irazarry](https://www.edx.org/bio/rafael-irizarry) helpful.

**Comment by Oriehi** [comment]
Thanks WilCrofter, I got through reading in the csv file using the following code 

library("MSnbase")
f0 <- dir(system.file ("extdata" , package = "pRolocdata"),
           full.names = TRUE, pattern = "normalCM10_1800.csv")
csv < read.csv(f0)
But only got the following error that brought me to this site.
Error in file(file, "rt") : invalid 'description' argument

I am wondering how do I get pass this point?

**Comment by WilCrofter** [comment]
I think you must be on the wrong forum. As far as I know, MSnbase and pRolocdata have nothing to do with this project. Please seek some basic R help.

The particular error you've posted is that f0 is not the path to a valid file. You can inspect f0 simply by typing its name a the R prompt. However, this question is inappropriate here and, though I wish you luck, I'll ignorerfurther posts along these lines.

**Comment by Oriehi** [comment]
Thanks

**Comment by ab4data** [comment]
Hi,  I am getting a similar error.  I have just reinstalled R to have 3.2.4 and then reinstalled swirl and the course.  Win10/64.  More details below.  Any pointers would be appreciated?

| Please choose a course, or type 0 to exit swirl.

1: Manipulating Data with dplyr
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

1: 2014-07-08.csv
2: customTests.R
3: dependson.txt
4: initLesson.R
5: lesson.yaml
6: outline.R

Selection: 1

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

> traceback()
15: file(con, "r")
14: readLines(input)
13: paste(readLines(input), collapse = "\n")
12: yaml.load(paste(readLines(input), collapse = "\n"), ...)
11: yaml.load_file(file)
10: parse_content.yaml(file, e)
9: parse_content.default(dataName, e)
8: parse_content(dataName, e)
7: loadLesson.default(e, courseU, lesson)
6: loadLesson(e, courseU, lesson)
5: mainMenu.default(e)
4: mainMenu(e)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)
>

**Comment by seankross** [comment]
@ab4data try the following:

1. `library(swirl)`
2. `uninstall_all_courses()`
3. Download [this](http://swirlstats.com/scn/Getting_and_Cleaning_Data.swc) file.
4. `install_course()` and select the file you just downloaded.
5. `swirl()`

Let me know if that works for you.

**Comment by ab4data** [comment]
Thanks Sean. That was a step in the right direction
A new error presents as follows.  I have tried a few times and then rerun
the uninstall and reinstall.
Once again this is R Gui v3.2.4 64 bit on Win 10

| This lesson requires the ‘dplyr’ package. Would you like me to install it
for you now?

1: Yes
2: No

Selection: 1

| Trying to install package ‘dplyr’ now...
also installing the dependency ‘Rcpp’


  There is a binary version available but the source version is later:
     binary source needs_compilation
Rcpp 0.12.3 0.12.4              TRUE

  Binaries will be installed
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL '
https://cran.stat.auckland.ac.nz/bin/windows/contrib/3.2/Rcpp_0.12.3.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL '
https://cran.stat.auckland.ac.nz/bin/windows/contrib/3.2/Rcpp_0.12.3.zip':
HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘Rcpp’ failed
package ‘dplyr’ successfully unpacked and MD5 sums checked
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :
  there is no package called ‘Rcpp’

| Could not install package ‘dplyr’!


|


|
|   0%Error in seq.default(0, 1, length = nrow(e$les)) :
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Try: 
1. `install.packages("Rcpp")`
2. `install.packages("dplyr")`
3. `swirl()`

**Comment by ab4data** [comment]
Thanks Sean.
The error seems to be the same.  I also tried going direct to the zip in
Auckland though this failed aswell.

> install.packages("Rcpp")
Installing package into ‘C:/Users/Tony/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
     binary source needs_compilation
Rcpp 0.12.3 0.12.4              TRUE

  Binaries will be installed
trying URL '
https://cran.stat.auckland.ac.nz/bin/windows/contrib/3.2/Rcpp_0.12.3.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL '
https://cran.stat.auckland.ac.nz/bin/windows/contrib/3.2/Rcpp_0.12.3.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open URL '
https://cran.stat.auckland.ac.nz/bin/windows/contrib/3.2/Rcpp_0.12.3.zip':
HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘Rcpp’ failed
>

**Comment by seankross** [comment]
Try: `install.packages("Rcpp", type = "source")`

Make sure you have [RTools](https://cran.r-project.org/bin/windows/Rtools/) installed.

**Comment by ab4data** [comment]
Hi Sean,
I tried a complete reinstall of R 3.2.4 revised before doing this.  It
failed again.

> install.packages("Rcpp", type = "source")
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/src/contrib/Rcpp_0.12.4.tar.gz'
Content type 'application/x-gzip' length 2402065 bytes (2.3 MB)
downloaded 2.3 MB

* installing *source* package 'Rcpp' ...
** package 'Rcpp' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
Warning: running command 'make -f "Makevars.win" -f
"C:/Users/Tony/DOCUME~1/R-32~1.4RE/etc/i386/Makeconf" -f
"C:/Users/Tony/DOCUME~1/R-32~1.4RE/share/make/winshlib.mk"
SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)'
SHLIB="Rcpp.dll" OBJECTS="Date.o Module.o Rcpp_init.o api.o attributes.o
barrier.o"' had status 127
ERROR: compilation failed for package 'Rcpp'
* removing 'C:/Users/Tony/Documents/R-3.2.4revised/library/Rcpp'

The downloaded source packages are in
        ‘C:\Users\Tony\AppData\Local\Temp\RtmpEPlsZy\downloaded_packages’
Warning messages:
1: running command '"C:/Users/Tony/Documents/R-3.2.4revised/bin/x64/R" CMD
INSTALL -l "C:\Users\Tony\Documents\R-3.2.4revised\library"
C:\Users\Tony\AppData\Local\Temp\RtmpEPlsZy/downloaded_packages/Rcpp_0.12.4.tar.gz'
had status 1
2: In install.packages("Rcpp", type = "source") :
  installation of package ‘Rcpp’ had non-zero exit status
>

**Comment by seankross** [comment]
@ab4data do you have admin rights on this computer?

**Comment by ab4data** [comment]
Hi Sean, Yes I have admin rights, though I installed into 'My Documents as
there was one error reporting inability to change something in C:\Program
Files

**Comment by ab4data** [comment]
Hi Sean.  This is resolved now thanks. The Rcpp install failed again with
type=source though succeeded without that additional argument.

**Comment by seankross** [comment]
Strange behavior. Sorry for the inconvenience.
