### ISSUE TITLE
Swirl behind proxy. 

### ISSUE THREAD

**Issue by KazimierzKurz** [swirldev/swirl#137]
If You are looking for suggestions about swirl enhancements, I would like to suggests to incorporate any mechanism for proxy. Usually You have to define http_proxy variable, or proxy wariable, pinting on proxy address. And if You use for example install.packages() You may pass argument method="wget", and it support such environment variables.

As from installation dependencies follows - You use curl for downloading content, so probably it supports downloading and uploading behind proxy as well, but documentation do not say a word how to use it, or You probably do not use it inside switl.
It should be relatively easy to add support for http_proxy variable -  - http://stackoverflow.com/questions/5211887/how-to-use-curl-via-a-proxy

**Comment by hosford42** [comment]
Is there any sort of workaround? This issue has rendered swirl unusable from my environment. I'm working on Windows, if that's relevant.

**Comment by seankross** [comment]
Hi @hosford42,

Are you using Swirl as part of the Data Science Specialization or are you just using it on your own?

**Comment by hosford42** [comment]
On my own. I found [this page](https://github.com/swirldev/swirl_courses#install-and-run-a-course-manually) which gave me the help I needed. Thanks.

**Comment by noussan** [comment]
Hi, I'm using swirl in Data Science Specialization.
I'm working with Rstudio 0.99 on Windows, behind a proxy. Swirl seems not be able to reach the web, while Rstudio works well for package installations.
It is a problem for getting the web-related services in swirl (e.g. coursera credits for swirl exercises).
Is there a way to set a proxy in swirl?
Thanks.
