### ISSUE TITLE
Swirl not successfully starting a course under R programming [R version 3.1.1 on Windows 8;  64bit]

### ISSUE THREAD

**Issue by Sarpwus** [swirldev/swirl#179]
I get the following error message when I select one of the 6 modules under the R programming course.

```
     Error in gzfile(file, mode) : cannot open the connection
      | Leaving swirl now. Type swirl() to resume.
```

My R console starts in my documents directory. ["C:/Users/MyName/Documents/]. The following steps were successfully carried out, over and over again, to see whether the above error would be solved.

```
 install.packages("swirl")
 library(swirl)
 install_from_swirl("R Programming")
 swirl()
```

From there onwards, I select the 1: R programming which brings up the list of the 6 modules. Then whenever I select a module, the following displays:

```
  Error in gzfile(file, mode) : cannot open the connection
   | Leaving swirl now. Type swirl() to resume.
```

**Comment by Sisok01** [comment]
Thank you!!!
