### ISSUE TITLE
Assigning swirl as homework in a Course

### ISSUE THREAD

**Issue by andreashandel** [swirldev/swirl#193]
I'm teaching a course and would like to assign my students an existing swirl course (R Programming) as homework. What I'm looking for is a way to get a verification that they did the assignment. I took some of the Coursera Courses which used swirl and had that functionality. For now, I don't need anything complicated with password and such. It would be enough if students at the beginning of the session could enter my email address, and then once they are done I get a notification. I could envision that as having at the beginning of the module a question that says "Do you want to notify anyone of your successful completion of this course?". Then they can enter an email address, which once they are done receives a message saying "XXX has successfully completed Module/Course YYY". Is something like that already possible? If not, could that be implemented? Thanks.

**Comment by sbainter** [comment]
Thank you so much for giving us a version to use in class! I am also interested in doing this. Currently, I see 13 modules for R_Programming and 15 for R_Programming_Alt. Would it be possible to add the last two modules to the Alt course?

**Comment by seankross** [comment]
If you're interested in modifying R Programming to use in your classroom
you should take a look at: http://swirlstats.com/swirlify/classroom.html

**Comment by sbainter** [comment]
Hi thanks for your response. I don't think I need detailed log info, just
notification of completion. My understanding was collecting emails through
the ALT course would work, but is this course no longer being updated?

**Comment by seankross** [comment]
Are you planning on just using the R Programming course? I can make an updated version that uses email.

**Comment by sbainter** [comment]
Hi! yes just the R Programming course. I have decided to go by the honors
system though, but thank you!

**Comment by seankross** [comment]
See: https://github.com/seankross/Google_Forms_Course/

**Comment by dayashka** [comment]
hi.
 i am an instructor and for my course related to R, I want to assign students a task to complete by doing 
"R Programming with Email Notification" course and sending me email but I am unable to receive their completion email. please guide to resolve

**Comment by Nkomatisamu** [comment]
assignment is very hard to understand please can you make it easy?
