### ISSUE TITLE
not available for 3.0.2

### ISSUE THREAD

**Issue by brouthwaite** [swirldev/swirl#203]
Hi,

I have tried to install swirl but am getting the error: 
"package 'swirl' is not available (for R version 3.0.2)"

As far as I am aware this is the most up to date R?

Thanks, Blair

**Comment by bruceherve** [comment]
a big thank you.It also worked for me on Ubuntu 14.04

**Comment by jwo4ever8** [comment]
Very much appreciated.

sudo apt-get install r-cran-testthat

worked on Ubuntu 14.04 and R 3.0.2

**Comment by JBeber** [comment]
R 3.0.2, have performed all of the above suggestions; am still receiving the following output:

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
File curl.h not found. Make sure the curl development library is installed, e.g. libcurl4-openssl-dev (deb) or libcurl-devel (rpm).
ERROR: configuration failed for package ‘curl’
* removing ‘/home/eewthreed/R/x86_64-pc-linux-gnu-library/3.0/curl’
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status
* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/home/eewthreed/R/x86_64-pc-linux-gnu-library/3.0/RCurl’
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status
ERROR: dependency ‘curl’ is not available for package ‘httr’
* removing ‘/home/eewthreed/R/x86_64-pc-linux-gnu-library/3.0/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies ‘httr’, ‘RCurl’ are not available for package ‘swirl’
* removing ‘/home/eewthreed/R/x86_64-pc-linux-gnu-library/3.0/swirl’
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

**Comment by modsaid** [comment]
@JBeber glad you followed up with an edit,  I was just going to post that :smile:

**Comment by fcholanda** [comment]
Worked perfectly with sudo apt-get install r-cran testthat

**Comment by renjiushuihan** [comment]
sudo apt-get install r-cran-testthat

worked on Ubuntu 14.04 and R 3.0.2

**Comment by nwhoffman** [comment]
Used Software Manager to install r-cran-testthat
Worked on Linux Mint 17 and R 3.0.2

**Comment by rohit2503** [comment]
@mtds :+1:  thanks for the quick fix. I was struggling to install testthat after looking your suggestion "sudo apt-get install libcurl4-openssl-dev" it worked perfectly

**Comment by zhengyi13** [comment]
I realize this is rather old, but I've had the same exact problem. I got here by trying what I was told at

http://swirlstats.com/students.html, and
https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux

... both of which claim that Swirl requires >=3.0.2. However, https://cran.rstudio.com/web/packages/swirl/index.html is quite clear that:

Version:	2.4.2
Depends:	R (≥ 3.1.0)

I assume the docs should be updated then, given this mismatch?

Alternatively, is there a way to get a more reasonably up-to-date version of R on Ubuntu 14.04?

**Comment by seankross** [comment]
@zhengyi13, you're right, I'll change those requirements. Try looking at this as far as updating R: http://askubuntu.com/questions/218708/installing-latest-version-of-r-base
