### ISSUE TITLE
Installing a lesson

### ISSUE THREAD

**Issue by Jorgeewa** [swirldev/swirl#219]
I am unable to install R programming course in zipped file keeps returning this error Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/George/Documents/Desktop/swirl_courses-master.zip' cannot be opened

**Comment by CGUTA** [comment]
I had the same issue, then searched frantically for answers. Then the course got installed successfully using install_course_zip when trying again... I believe the problem was that I tried to install the package too quickly after starting the download on the browser, Did not expect the 9Mb size. I'm on Ubuntu 14.04 using Firefox. BE PATIENT.

**Comment by udayguntupalli** [comment]
I am having the same problem , but using the suggested solution did not help me . 
Here is a step by step process that I followed : 
1. I installed R 
2. install.packages("swirl")
3.library(swirl)
4. install_from_swirl("R Programming") 

After performing steps 1 to 4 , I saw an error . I manually unzipped the file for AppData where it was downloaded to and placed it in my working directory. 
I retried and got the same error . Then I tried 
install_course_zip("My Path")

In unzip(path, exdir = file.path(system.file(package = "swirl"),  :
  error 1 in extracting from zip file

Please guide 

Best 
Uday

**Comment by seankross** [comment]
Hi @udayguntupalli,

1. Download the zip file from [this page](https://github.com/swirldev/swirl_courses) by clicking **Download ZIP**.
2. Enter the following into the R console:

```r
install_course_zip(file.choose(), multi = TRUE, which_course = "R Programming")
```
and select the zip file you just downloaded.

Let me know if that works.

**Comment by udayguntupalli** [comment]
Error: could not find function "install_course_zip"

**Comment by seankross** [comment]
Try:

```r
library(swirl)
install_course_zip(file.choose(), multi = TRUE, which_course = "R Programming")
```

**Comment by udayguntupalli** [comment]
That worked , but what can you throw a little more light on why install.packages fails even after manually finding the zip file and pasting it in the working directory @seankross

**Comment by seankross** [comment]
`install_from_swirl()` is likely failing because it needs to download a large file which is hosted in the US. Many of these course installation issues will be solved in the next version of swirl.

**Comment by udayguntupalli** [comment]
@seankross  : where are these lessons installed . Since "R" is sensitive about the physical memory available - how do I make sure after I am done with the lesson , I free up the space so that I dont choke up R ?

**Comment by seankross** [comment]
To find out where the lessons are installed on your computer use `find.package("swirl")`. To clean up the global environment use `rm(list = ls())`. There are no swirl lessons that I am aware of that take up a significant amount of memory.

**Comment by yasmin44** [comment]
For me it´s okey using   -->   **install_course_directory("file path without network drive and with "/" not! "\"")** --> to start whith an R course in Coursera Platform. Regards.

**Comment by yasmin44** [comment]
For me it´s okey using --> install_course_directory("file path without network drive and with "/" not! """) --> to start with an R course in Coursera Platform. Regards.
