### ISSUE TITLE
Solving **testthat** library availability

### ISSUE THREAD

**Issue by EPlanas** [swirldev/swirl#222]
Environment : Xubuntu, 3.13.0-32-generic
I could not install swirl via RStudio with the command install.packages("swirl").
I had a message telling that the 'testhat' library was not available.
I solved this by installing the **r-cran-testthat** package with Xubuntu package manager
Hope it helps.
Emmanuel.

**Comment by gpremer** [comment]
I does help. For those looking for a cut&paste solution: execute, in a shell:

`sudo apt-get install r-cran-testthat`
