### ISSUE TITLE
location of user_data directory is probably read-only for shared libraries

### ISSUE THREAD

**Issue by cmhh** [swirldev/swirl#230]
Hi

I have installed swirl in a shared library at work.  The installation itself is read-only for R users, and so swirl stops the first time there is an attempt to save anything to the user_data directory.  

Users can re-install the package to their personal libraries, but that's not really the model we want.  Plus, users will be behind a fairly restrictive proxy server, so downloads are a bit hit or miss.  It would be nice if the package could refer to a user-specific user_data directory that is outside of the site library... unless it does this already and I just did a bad job of reading the documentation.

In dir.create(udat, recursive = TRUE) :
   cannot create dir '/srv/R/site-library/swirl/user_data', reason 'Permission denied'

| leaving swirl now.  Type swirl to resume.

**Comment by seankross** [comment]
Fixed with `swirl_options()`
