### ISSUE TITLE
i get the following error when trying to load swirl

### ISSUE THREAD

**Issue by millertry** [swirldev/swirl#244]
> library(swirl)
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘bitops’ not found: maybe not installed for this architecture?
Error: package or namespace load failed for ‘swirl’

any thoughts on what this might be?

**Comment by ncarchedi** [comment]
Something went wrong with installation. Try `install.packages("bitops")` to install this dependency manually. If you get this message again regarding another missing R package, rinse and repeat.
