### ISSUE TITLE
RStudio 0.98.1091 on Linux: Error while installing swirl: Cannot find curl-config

### ISSUE THREAD

**Issue by pavloskatsonis** [swirldev/swirl#247]
While installing the swirl package I get the following errors:

    ....
    * installing *source* package ‘RCurl’ ...
    ** package ‘RCurl’ successfully unpacked and MD5 sums checked
    checking for curl-config... no
    Cannot find curl-config
    ERROR: configuration failed for package ‘RCurl’
    ....

More errors follow, but this is the first one and all the trailling errors concern the RCurl package.

**Comment by WilCrofter** [comment]
That diagnostic usually indicates a missing Linux package. In Ubuntu derivatives:
```
sudo apt-get install libcurl4-openssl-dev
```
will install the package. After installing libcurl4-openssl-dev, try to install RCurl again. For more detail and other Linux distros [see this page](https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux).

**Comment by pavloskatsonis** [comment]
Thank you very much! It solved the problem :)
