### ISSUE TITLE
list.files(recursive=TRUE) very slow

### ISSUE THREAD

**Issue by inspire22** [swirldev/swirl#248]
As a new user this kept crashing R for me, I'd suggest list.files(recursive=TRUE, path='/tmp') or something less likely to involve ~3 TB of files :)

**Comment by WilCrofter** [comment]
Hi Dave,

You are probably following the swirl and swirl_courses issue pages, in which case apologies for this redundant forward.

Any ideas?

Cheers,
Bill

**Comment by lalala333** [comment]
I have tried to skip the question involving list.files by typing skip () but swirl won't let me skip it. My Mac keeps hanging and R crashes when I try list.files(recursive=TRUE)
so I tried your solution:

list.files(recursive=TRUE, path='/tmp') 

> list.files(recursive=TRUE, path='/tmp')
character(0)

| Give it another try. Or, type info() for more options.

| Type list.files(recursive = TRUE) to list all the files in
| your working directory recursively.

**Comment by WilCrofter** [comment]
I've temporarily commented out the troublesome question until we figure out something better. To get the new version, you must reinstall R Programming.
```
install_from_swirl("R Programming")
```
I do not think the new version will be mirrored at bitbucket.
