### ISSUE TITLE
Unable to load package 'car'

### ISSUE THREAD

**Issue by misskat** [swirldev/swirl#253]
In the Regression Model course, Lesson 10 on variance inflation factors, swirl() asks me if I want to load package 'car'. Typing either 1 or 2 (yes or no) produces the same error, below:

Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

**Comment by ncarchedi** [comment]
Please provide the output from 

```
library(swirl)
sessionInfo()
```

**Comment by misskat** [comment]
Here is some more info:

| Trying to install package ‘car’ now...
Warning in install.packages :
  cannot open: HTTP status was '404 Not Found'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/car_2.0-21.zip'
Warning in install.packages :
  download of package ‘car’ failed

| Could not install package ‘car’!
  |                                                                                                                                  |   0%
Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

> library(swirl)
> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] manipulate_0.98.1062 openintro_1.4        swirl_2.2.16        

loaded via a namespace (and not attached):
[1] digest_0.6.4   httr_0.5       RCurl_1.95-4.3 stringr_0.6.2  testthat_0.9.1 tools_3.1.1    yaml_2.1.13   
>

**Comment by ncarchedi** [comment]
Are you able to install the `car` package directly with `install.packages("car")`? If not, you may be behind a firewall or have some other connection issues.

**Comment by misskat** [comment]
No, I cannot install manually either. I guess I'll just skip this lesson for now. Thanks.

**Comment by ncarchedi** [comment]
Yea, not being able to install R packages is a bigger problem. Actually, now that I look at it, the link R was attempting to use for downloading the car package seems to be dead:

http://cran.rstudio.com/bin/windows/contrib/3.1/car_2.0-21.zip

Could you provide the following info?

```
getOption("repos")
```

**Comment by misskat** [comment]
CRAN                            CRANextra 
           "http://cran.rstudio.com" "http://www.stats.ox.ac.uk/pub/RWin" 
attr(,"RStudio")
[1] TRUE

**Comment by ncarchedi** [comment]
Interesting, R is trying to download an older version of car. The newest
version is available here:

http://cran.rstudio.com/bin/windows/contrib/3.1/car_2.0-22.zip

You can download the zip by clicking the link above, then running the
following (alter the file path according to where you download the file).

```
install.packages("~/Downloads/car_2.0-22.zip", repos = NULL)
```

Please let me know if that works.

**Comment by misskat** [comment]
It looks like that worked. Thanks!

**Comment by ncarchedi** [comment]
Great, good luck!

**Comment by MichaelVBronstein** [comment]
@ncarchedi thanks. Had the same problem and your solution worked!

**Comment by FranciscaMarinhoeSa** [comment]
Hi,

I'm having the same issue but this solution is not working for me. Could you please help me?

Thanks,
Francisca
