### ISSUE TITLE
How do you start the swirl lesson?

### ISSUE THREAD

**Issue by JimDG** [swirldev/swirl#254]
I have successfully installed swirl 
and successfully applied : install_from_swirl("R Programming")

I have read all of the help material and have not found anything that indicates how to start the first lesson of this course.

nxt() simply returns an empty prompt

Any suggestions?

**Comment by WilCrofter** [comment]
```
library(swirl)
swirl()
```
You should be presented with a sequence of menus: What shall I call you? Which course? Which lesson. Shout if you have trouble.

**Comment by JimDG** [comment]
many thanks! solved.
