### ISSUE TITLE
Swirl crashed during course teaching plotting

### ISSUE THREAD

**Issue by ghost** [swirldev/swirl#256]
Is there a way for me to use the Swirl course "Data_Visualization"?  This is my main reason for learning R, for the plotting ability but can't use the course.  I've already been through the following (Programming, Programming Alt, Getting_and_Cleaning_Data).

I get the following
=========================
| Would you like to continue with one of these lessons?

1: Data Analysis Data Visualization
2: R Programming Basic Building Blocks
3: No. Let me start something new.

Selection:
| Attemping to load lesson dependencies.
| Package ‘openintro’ loaded correctly!

| Here is a dot plot created using the variable 'price' from our 'cars'
| data set. As you may notice, the price is reported along the x-axis in
| $1000s, and each point above the axis represents the price of one of
| the 54 cars in our data set.

Error in plot.new() : figure margins too large

| Leaving swirl now. Type swirl() to resume.

=================================
Hopefully, something can be pointed out that I have forgotten.  so far all the courses have been great.

**Comment by reginaastri** [comment]
Someone else complained about this same problem in a different lesson (see the post by charles tippett on the regression course and plotting) and the recommendations were to make the plot window bigger. For instance, if you're running RStudio, adjust the size of the plot window by grabbing the left edge of it and pulling it leftward. I don't know if this is the problem but it's worth a try.
Hope this helps.

**Comment by glenwf** [comment]
During previous courses, when it said to look at the graph, the graph pops
up and you look at it.  This time when it was supposed to pop up and show
me something it crashed.  There was no window to size, the code just failed
to work and I don't know what the lesson code was running in the
background, so I don't know how to tweek it or fix it to allow it to
continue without crashing.

On Wed, Feb 4, 2015 at 3:18 PM, reginaastri <notifications@github.com>
wrote:

> Someone else complained about this same problem in a different lesson (see
> the post by charles tippett on the regression course and plotting) and the
> recommendations were to make the plot window bigger. For instance, if
> you're running RStudio, adjust the size of the plot window by grabbing the
> left edge of it and pulling it leftward. I don't know if this is the
> problem but it's worth a try.
> Hope this helps.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl/issues/256#issuecomment-72961563>.
>



-- 
Glen Forister
2319 Vernon St.
Roseville, CA  95678

**Comment by ctippett** [comment]
hi. i tried expanding the screen size and that did not help. 
I also moved to a larger 19" monitor and that did not help. 
any other suggestions? I hate to be unable to access the Regression course because of this. 
charles

**Comment by ctippett** [comment]
Hi. As you can see, i posted this back in May and since i could get no resolution, i just gave up on the Regression course. 
HOwever, having the same problem now with the Data Analysis / Central Tendency course. 
I would love to find an answer so i don't have to skip over this material.

**Comment by seankross** [comment]
@ctippett Are you using swirl in a console, in the R Gui, or in RStudio?

**Comment by ctippett** [comment]
Hi Sean. I found the solution on GitHub. 
THe problem is that the plot window needs to be resized to accomodate the graphic that swirl wants to drop in. 
thank you for following up with me. 
I love swirl.
I use it everyday.

PS: If you need to reach me live, please call me in my office (615) 849 3236 or on my cell (205)999 0052. 


Date: Wed, 21 Oct 2015 08:25:34 -0700

**Comment by seankross** [comment]
Good to hear.

**Comment by akinalan** [comment]
Would be great if the question had been answered completely
