### ISSUE TITLE
Win 7. 32bit - R 3.1.2 - Getting & Cleaning Data Tidying Data with tidyr - Problem on viewing dataset 'sat'

### ISSUE THREAD

**Issue by josiemariahlee** [swirldev/swirl#257]
I'm using Win 7 Pro SP1 32bit, R 3.1.2.
I have a problem viewing the dataset 'sat' in Getting & Cleaning Data Tidying Data with tidyr
I got a message saying:

Source: local data frame[6 x 20]
Error in nchar[values]: invalid multibyte string 2

I guess it may due to different data & time representations. I'm working with "Chinese (Simplified)_People's Republic of China.936" locale.

**Comment by ncarchedi** [comment]
You may want to reinstall the course, since we recently fixed a bug in that dataset that could be causing your issue: `install_from_swirl("Getting and Cleaning Data")`. Please let us know if it works.

**Comment by josiemariahlee** [comment]
Hi Nick,
Thank you for your response and sorry for the late reply. It is working now. Thank you! :)

**Comment by CourseProjectAY** [comment]
library(swirl)
install_from_swirl("Getting and Cleaning Data")
swirl()
This is still not working. I have been trying this since 2 days.

**Comment by seankross** [comment]
@CourseProjectAY try this:

1. Got o this page: https://github.com/swirldev/swirl_courses
2. Click "Download  Zip"
3. Run this code: `swirl::install_course_zip(file.choose(), multi = TRUE, which_course="Getting and Cleaning Data")`
4. Select the zip file you downloaded.

Let me know if that works.
