### ISSUE TITLE
Giving invocations of View() a pass

### ISSUE THREAD

**Issue by adaongithub** [swirldev/swirl#258]
Not sure if this in the spirit of your UI, but I get a complaint from Swirl if I do an inspection of a Data item in the Environment sub-window of RStudio in the middle of a Swirl session.  The inspection generates an invocation of View(\<data item\>) in the RS REPL which Swirl takes as a bum response from me.   E.g.,

>|==============                                                                                |  15%
>| The first step of working with data in dplyr is to load the data into what the package authors call
>| a 'data frame tbl' or 'tbl_df'. Use the following code to create a new tbl_df called cran:
>| 
>| cran <- tbl_df(mydf).
>
>__> View(cran)__
>
>| __One more time. You can do it! Or, type info() for more options.__
>
>| Type cran <- tbl_df(mydf) to create a new tbl_df called cran.

Could this sort of REPL function invocation as the result of RStudio GUI exploration be ignored by Swirl ?

Thanks,

Alec

**Comment by seankross** [comment]
If you want to explore your R environment or do anything outside of Swirl's regularly scheduled programming you can use the `play()` function to pause Swirl for a moment. To resume your Swirl session use the `nxt()` function.
