### ISSUE TITLE
Cannot successfully load swirl while it has been successfully downloaded.Please help!

### ISSUE THREAD

**Issue by chenchensun** [swirldev/swirl#259]
GO ALONG WITH THE GUIDANCE, BUT I GET  THE ERROR AS FOLLOWES,PLEASE HELP~~

The downloaded binary packages are in
	/var/folders/r2/vn070vss4hd0p2t2k4rzbjqh0000gn/T//Rtmptd0RUR/downloaded_packages

> library("swirl")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  不存在叫‘RCurl’这个名字的程辑包
错误: ‘swirl’程辑包或名字空间载入失败，

**Comment by seankross** [comment]
Can you paste the output from `sessionInfo()` here?

**Comment by chenchensun** [comment]
@seankross Sure, thank you very much!

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] tools_3.1.2

**Comment by ncarchedi** [comment]
@chenchensun swirl can't find the `RCurl` package, which it needs to operate. Try `install.packages("RCurl")`, then reload swirl with `library(swirl)`. Does that work?

If not, please give us `sessionInfo()` again, but this time, please make sure swirl is loaded first (`library(swirl)`).

**Comment by chenchensun** [comment]
@ncarchedi  thank you! Sorry that I reply late, so sad error occurs again. I go with your instructions and...

> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  不存在叫‘digest’这个名字的程辑包
错误: ‘swirl’程辑包或名字空间载入失败，
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] zh_CN.UTF-8/zh_CN.UTF-8/zh_CN.UTF-8/C/zh_CN.UTF-8/zh_CN.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] bitops_1.0-6   RCurl_1.95-4.5 tools_3.1.2

**Comment by maidamai0** [comment]
你安装一下缺失的包试试看：
install.packages("RCurl")
