### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by Muzammal-Naseer** [swirldev/swirl#264]
when I use install.packages("swirl") to install swirl does not give me all course option other than two. But when I tried it manually by usinginstall_course_zip("path/to/file/here/swirl_courses-master.zip", multi=TRUE, which_course="Course Name Here") then it shows me this problem 

"Error in unzip(path, list = TRUE) : 
  zip file 'D/My_Education/Swirl/swirl_courses-master.zip' cannot be opened".

I would be grateful if somebody can help to solve this.

Regards...Muzammal

**Comment by seankross** [comment]
Hi @Muzammal-Naseer,

Which course are you trying to install?

**Comment by Muzammal-Naseer** [comment]
I am trying to install "Data Analysis". But I tries others as well its showing me same problem.

**Comment by seankross** [comment]
Try:

```
install_from_swirl("Data Analysis")
```

**Comment by Muzammal-Naseer** [comment]
Thanks man....It took a lot of time but it worked :) thanks
