### ISSUE TITLE
Issues installing "R Programming" course

### ISSUE THREAD

**Issue by ccalix** [swirldev/swirl#265]
I'm trying to install the course "R Programming" but had some issues.
I'm working on a Windows 7 computer, using R Studio version 0.98.1102, R version 3.1.2.
Here is what I've done:

> library(swirl)
| Hi! Type swirl() when you are ready to begin.

> install_from_swirl("R Programming")
Error in unzip(path, list = TRUE) : 'exdir' does not exist

Then I try to install and run a course manually by downloading the zip file.

> install_course_zip("~/test-repo/swirl_courses-master.zip", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 'exdir' does not exist

Then I try to unzip it manually and use:

> install_course_directory("~/test-repo/swirl_courses-master", multi=TRUE, which_course="R Programming")
Error in install_course_directory("~/test-repo/swirl_courses-master",  : 
  unused arguments (multi = TRUE, which_course = "R Programming")

I've also tried:

> install_course_directory("~/test-repo/swirl_courses-master/R Programming")
| Course installation failed.
Warning message:
In file.copy(path, file.path(system.file(package = "swirl"), "Courses"),  :
  problem copying //dca/ccalix$\test-repo\swirl_courses-master\R Programming to C:\Program Files\R\R-3.1.2\library\swirl\Courses\R Programming: No such file or directory

Any help on my problem will be greatly appreciated!

**Comment by seankross** [comment]
Hi @ccalix, 

After unzipping `swirl_courses` try 
```
install_course_directory("~/test-repo/swirl_courses-master/R_Programming")
``` 
(notice the underscore).

**Comment by ccalix** [comment]
Thanks Seankross! Well spotted underscore, but I still can't install it :-(
Anyway, I feel I'm now one step closer! Here is what I've got:

> install_course_directory("~/test-repo/swirl_courses-master/R_Programming")
Error in list.files(path, recursive = TRUE) : reached elapsed time limit

Does it mean I need a faster computer? I've 4Gb RAM but my laptop is 5 years old...

**Comment by ccalix** [comment]
Right. I'm really keen on learning this thing and I've manually and individually installed each directory within R_Programming. It has now worked!!!
Thanks a lot Seankross!!!
Cheers.

**Comment by seankross** [comment]
Okay, please don't hesitate to reach out if you have any other problems.

**Comment by ilkinmirza** [comment]
Dear seankross  I also installed swirl sourse repostory manually . but while I want to get R programmin it gives me this message
Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Hi @ilkinmirza,

Did you download the zip file?

**Comment by Sameera-D** [comment]
I am getting error even after trying all the above steps:

install_course_directory("~/Downloads/swirl_courses-master/R_Programming")
| Course installation failed.

Warning message:
In file.copy(path, file.path(system.file(package = "swirl"), "Courses"),  :
  problem creating directory /home/billu/Downloads/swirl_courses-master/R_Programming: Permission denied

I even tried this too
 install_course_directory("~/test-repo/swirl_courses-master/R_Programming")

| Course installation failed.

Warning message:
In file.copy(path, file.path(system.file(package = "swirl"), "Courses"),  :
  problem creating directory /home/billu/test-repo/swirl_courses-master/R_Programming: Permission denied

**Comment by seankross** [comment]
Hi @Sameera-D,

Are you using swirl on a computer owned by your workplace or your school?

Sean

**Comment by Sameera-D** [comment]
Yes. And it has some proxy settings too.

**Comment by seankross** [comment]
Hi @Sameera-D,

Unfortunately there's no good fix for this right now if you don't have write permissions for where R is installed on your computer. This will be fixed later this month in the new version of swirl.

**Comment by jfieberg** [comment]
Hi Sean,

I teach an intro stat course at the University of Minnesota.  I've been developing some very simple swirl modules that I hoped to use as pre-lab computer exercises.  Unfortunately, I can't install them from github due to a lack of write permissions on the university computers.  Any chance you might have come up with a solution to this problem?  Thanks!

John

**Comment by seankross** [comment]
Hi @jfieberg,

This is absolutely possible! Your students will need to set up a directory where they do have write permissions, and then before they use swirl they need to run the following code:

```r
options(swirl_courses_dir = "new/dir/one", swirl_data_dir = "new/dir/two")
```

And they will need to run this every time they start swirl. One way they can ensure it's run every time is for them to put it in their `.Rprofile`. Sorry for the delayed response but let me know if you have any other questions!

**Comment by jfieberg** [comment]
Hi Sean,


Thanks for the response.  The good news is that I discovered that downloading and installing the latest version of swirl fixed the issues we were having.  The bad news is that the computers that we work on have a "frozen image" that everything reverts to every time the user logs off - so, this also has to be done every time.   Your suggestion sounds like it could offer another solution.


Really appreciate the quick and thoughtful response!


Best,


John


________________________________

**Comment by priyam2790** [comment]
I'm trying to install the course "R Programming" but had some issues.
I'm working on a Windows 10 computer, using R Studio version 1.1.383 , R version.
Here is what I've done:

library(swirl)
| Hi! Type swirl() when you are ready to begin.

> install_course("R Programming")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Connection timed out after 10000 milliseconds

Then I try to install and run a course manually by downloading the zip file.

> install_course("~/Downloads/swirl_courses-master", multi=TRUE, which_course="R_Programming")
Error in install_course("~/Downloads/swirl_courses-master.zip", multi = TRUE,  : 
  unused arguments (multi = TRUE, which_course = "R_Programming")

I've also tried:
> install_course_directory("~/Downloads/swirl_courses-master/R_Programming")

| Course installation failed.

Warning message:
In file.copy(path, swirl_courses_dir(), recursive = TRUE) :
  problem copying C:/Users/Priyam.Bhardwaj/Documents\Downloads\swirl_courses-master\R_Programming to C:\Users\Priyam.Bhardwaj\Documents\R\R-3.4.2\library\swirl\Courses\R_Programming: No such file or directory

Any help on my problem will be greatly appreciated!

**Comment by seankross** [comment]
@priyam2790 try the manual installation instructions here: http://swirlstats.com/scn/rprog.html

**Comment by BerkeleyMonkey** [comment]
Hi Sean, Im running into permission problem but it is my own personal Mac book pro. However, I am on the second account(have admin rights too). Rstudio was downloaded on the first account. Whats the fix on this? I read about the run as adminstrator on windows but no such thing in the mac...any advice?



-----------------------------------------------------
Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
  cannot open file '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/swirl/Courses/temp.zip': Permission denied
