### ISSUE TITLE
R Console Android, swirl cannot find internet, sh: 1: /usr/bin/firefox: not found

### ISSUE THREAD

**Issue by mloxton** [swirldev/swirl#267]
Running swirl under R Console for Android.
Swirl installs and executes,  but cannot load lessons.

>library ("swirl")
> swirl()

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did
| then. If you are new, call yourself something unique.

What shall I call you? mloxton

| To begin, you must install a course. I can install a course for you from the
| internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options
| and directions for installing courses yourself. (If you are not connected to
| the internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Don't install anything for me. I'll do it myself.

Selection: 1

| Sorry, but I'm unable to fetch 'R Programming: The basics of programming in
| R' right now. Are you sure you have an internet connection? If so, would you
| like to try again or visit the course repository for instructions on how to
| install a course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.

Selection: 2

| OK. I'm opening the swirl course respository in your browser.
The url to open is :
https://github.com/swirldev/swirl_courses

| Leaving swirl now. Type swirl() to resume.

sh: 1: /usr/bin/firefox: not found
>

**Comment by mloxton** [comment]
> install_from_swirl("R Programming")
Error in function (type, msg, asError = TRUE)  : 
  SSL certificate problem: unable to get local issuer certificate
>

**Comment by mloxton** [comment]
install_course_zip( "/mnt/Download/swirl_courses-master.zip", multi=TRUE, w
</Download/swirl_courses-master.zip", multi=TRUE, wh                         ich_course="R Programming
<ster.zip", multi=TRUE, which_course="R Programming:                          The basics of programmin
<ch_course="R Programming: The basics of programming                          in R")

> swirl ()

| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did
| then. If you are new, call yourself something unique.

What shall I call you? swirl ()

| Please don't use any quotes or other punctuation in your name.

What shall I call you? mloxton

| Please choose a course, or type 0 to exit swirl.

1: swirl courses-master
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

 1: Data Analysis
 2: ErrFind
 3: Exploratory Data Analysis
 4: Getting and Cleaning Data
 5: Mathematical Biostatistics Boot Camp
 6: Open Intro
 7: R Programming
 8: R Programming Alt
 9: Regression Models
10: Statistical Inference

Selection: 7

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

**Comment by mloxton** [comment]
R Console Premium

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: armv7l-unknown-linux-gnueabihf (32-bit)

**Comment by seankross** [comment]
Could you provide a Google Play Store link to the app you're using? I can't seem to find it.

**Comment by mloxton** [comment]
Hi Sean
https://play.google.com/store/apps/details?id=com.appsopensource.Rpremium

**Comment by mloxton** [comment]
Btw, I didn't have firefox installed before the errors,  but installed firefox and retried loading courses, with the same errors.
Have since uninstalled firefox
Uninstalled R Console and swirl
Reinstalled R Console and swirl
Same errors

**Comment by seankross** [comment]
The link you provided takes me to:
https://play.google.com/store/apps/details?id=not_found

**Comment by mloxton** [comment]
Odd.
I can see it in my apps and go to its play store page from my apps, but search doesn't find it anymore.
Maybe a temporary google play issue?

The app title is "R Console Premium" by Apps Embedded.
They also have a free version called "R Console Free"






Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by seankross** [comment]
To be honest with you, I don't think Swirl has ever been tested on Android. Is your tablet your primary computing device?

**Comment by mloxton** [comment]
Happily not, I can do this on a pc.
Using swirl on the tablet would be super convenient and pretty cool though!.

Sent from my Samsung Galaxy Tab®4

-------- Original message --------

**Comment by whitefishdontjump** [comment]
Think the app now requires android lollipop. Won't show in google play on kitkat or jelly bean
