### ISSUE TITLE
T is not recognized as TRUE

### ISSUE THREAD

**Issue by cielavenir** [swirldev/swirl#268]
When I put `recursive=T`, swirl complains and I need to type `TRUE`.

**Comment by seankross** [comment]
Swirl is correctly complaining because the author of that lesson is trying to enforce good style. In R you can do terrible things like: `T <- FALSE`, so typing the full `TRUE` guarantees you're passing the correct argument to the function.

**Comment by cameronbrown** [comment]
I just ran into this too.  I like your idea that swirl is just encouraging good style, but if so, it should make clearer to the user that it considers use of `T` improper and say explicitly why.  As is, it presents as a swirl mistake to ignore rather than a lesson to be learned.  If I had not read your comment, I would have started avoiding using `T` for `TRUE` in swirl, but gone ahead using `T` in other contexts.

```
| Create a directory in the current working directory called "testdir2" and a subdirectory for it
| called "testdir3", all in one command by usung dir.create() and file.path().

> dir.create(file.path("testdir2", "testdir3"), recursive = T)

| That's not exactly what I'm looking for. Try again. Or, type info() for more options.

| dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE) will do the trick. If you forgot the
| recursive argument, the command may have appeared to work, but it didn't create the nested directory.

> 
```

**Comment by cielavenir** [comment]
Right. The mess is buggy error message...

**Comment by blaiseli** [comment]
I encountered a related issue: Omitting the space in function arguments assignement (python-style) leads to misleading failure messages.

```
| Create a directory in the current working directory called "testdir2" and a
| subdirectory for it called "testdir3", all in one command by using
| dir.create() and file.path().

> dir.create(file.path("folder1", "folder2"), recursive=TRUE)

| Keep trying! Or, type info() for more options.

| dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE) will do the
| trick. If you forgot the recursive argument, the command may have appeared to
| work, but it didn't create the nested directory.

> dir.create(file.path("folder1", "folder2"), recursive = TRUE)
Warning message:
In dir.create(file.path("folder1", "folder2"), recursive = TRUE) :
  'folder1/folder2' already exists

| Try again. Getting it right on the first try is boring anyway! Or, type
| info() for more options.

| dir.create(file.path('testdir2', 'testdir3'), recursive = TRUE) will do the
| trick. If you forgot the recursive argument, the command may have appeared to
| work, but it didn't create the nested directory.

> 
```

**Comment by seankross** [comment]
@blaiseli is looks like you're using the incorrect folder names.

**Comment by blaiseli** [comment]
Indeed. Thanks for pointing the error.
I don't know why I ended up trying these directory names instead of what was asked.
