### ISSUE TITLE
Swirl error in library

### ISSUE THREAD

**Issue by Ghita88** [swirldev/swirl#269]
Hello I am absolutely new to all of this.  I am trying to download and run swirl and I successfully download it but when I type in library("swirl") i get the error message below.  Am I supposed to somehow acces the downloaded package that is in my temporary files in another manner besides the Library("swirl")? Thanks for the help! Ghita

 install.packages("swirl")
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/swirl_2.2.21.zip'
Content type 'application/zip' length 133042 bytes (129 Kb)
opened URL
downloaded 129 Kb

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ghita\AppData\Local\Temp\RtmpUd90E2\downloaded_packages
> library("swirl")
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘bitops’ not found: maybe not installed for this architecture?
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
Try:

`library(swirl)`

**Comment by Ghita88** [comment]
nope, but thank you for the suggestion!!! 
after executing install.packages("swirl")
i am able to type in library() and it opens everything in a separate screen above my console but then after that when I type library("swirl") or library(swirl) as you suggested I still get the same error message

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ghita\AppData\Local\Temp\RtmpUd90E2\downloaded_packages
 library()
> library(swirl)
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘bitops’ not found: maybe not installed for this architecture?
Error: package or namespace load failed for ‘swirl’

**Comment by ncarchedi** [comment]
install.packages("bitops")
library(swirl)

This will install the package that your error message says you are missing. If you get a similar message regarding another package, do the same.

**Comment by Ghita88** [comment]
I tried that and I still get the same error message....the install.packages("bitops") worked (it downloaded and unpacked it and put it in my temporary files) but I am still unable to access it (open and then run it) I receive the same error message as before.  I don't know enough about all of this but I feel like somehow it is not able to get it from my temporary files and I don't know why......this is the message I receive below. Thanks for the help!


install.packages("bitops")
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/bitops_1.0-6.zip'
Content type 'application/zip' length 36022 bytes (35 Kb)
opened URL
downloaded 35 Kb

package ‘bitops’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Ghita\AppData\Local\Temp\RtmpIfHegI\downloaded_packages
> library(swirl)
Error in library.dynam(lib, package, package.lib) : 
  DLL ‘RCurl’ not found: maybe not installed for this architecture?
Error: package or namespace load failed for ‘swirl’
>

**Comment by ncarchedi** [comment]
Same thing for the RCurl package now. install.packages("RCurl"). For
whatever reason, swirl's dependencies didn't install properly so you have
to do them one by one. The error messages will tell you which packages are
missing. What's your operating system?

**Comment by Ghita88** [comment]
now it just keeps sending my in circles and I no longer receive a warning that Rcurl is missing.........
I have a 64 bit operating system (Windows 7)
I don't really understand why it wont work.  I have been doing a course about R and through it I was able to install and do swirl.  I finished the course and now have not been able to load swirl since then.
I am going to a conference on Monday that is about Digitization in Science and maybe someone there can help me figure out whats going on.  Thank you for the suggestions!
Here is the message I receive now.  Also when I did receive the warning about R curl after I installed it I was told that Rcurl could not be run on my version of R (3.1.2)
install.packages("bitops")
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/bitops_1.0-6.zip'
Content type 'application/zip' length 36022 bytes (35 Kb)
opened URL
downloaded 35 Kb

package ‘bitops’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘bitops’

The downloaded binary packages are in
	C:\Users\Ghita\AppData\Local\Temp\Rtmpmai83C\downloaded_packages
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bitops’
Error: package or namespace load failed for ‘swirl’

**Comment by WilCrofter** [comment]
Remotely diagnosing a system problem like this is guesswork at best, but two of the diagnostics complain that a DLL can't be found. A DLL is a Windows binary which can be linked and loaded at runtime (Dynamically Loadable Library.) Both the bitops and RCurl DLL's should be installed when the packages were installed. Either they weren't included in the package or, for some reason, were not installed on R's search path.

Possibly, then, your system has a problem installing R packages which include binaries (DLL's.) If so, the problem could be any number of things, e.g., antivirus software preventing the DLL from being moved to a location where it can be loaded. You might try downloading the RCurl package as a zip file and using `install.packages` with the zip option. You could inspect the zip file to see if the DLL is included. After installation from the zip, you could inspect the installation directory to see if it was moved there. (Use `find.package` to find the location of the installed package.)

Good luck --Bill

**Comment by ncarchedi** [comment]
Are you on a work computer? If so, you might try this on a personal computer where you have full permissions.

**Comment by 30may1991** [comment]
At tutorial 9 , exactly at 98% even i got stuck. Swrl is not accepting any command. I would like to skip tat part and move forward. Kindly help. There was some kind of error in the problem before that but moved on. One with %p% while making binary operators. Now i am not able to simply type "I"%p
%"love"%p%"R!". Unable to fix

**Comment by 30may1991** [comment]
I figured it had error in previous question and still accepted it. Anyway i skipped the question with skip() command. In case if you find the trouble skip , however before that tryhttp://mathalope.co.uk/2015/03/08/swirl-r-programming-lesson-9-functions/
Most of the swirl docs are here for reference by swirl.
Thank oyu

**Comment by LMarte** [comment]
Thanks, ncarchedi, i was having the same issues with installing swirl. your advice worked.

**Comment by Sarah81** [comment]
Hello,

I am new too and going through the same issue. I tried everything i found in your forum but nothing work (I am using a private computer at home), getting the same error message.

Any advice?

thanl you


-----------------------------------------------------
> install.packages("swirl")
Installing package into ‘C:/Users/Sarah.T/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘bitops’, ‘RCurl’

trying URL 'http://stat.ethz.ch/CRAN/bin/windows/contrib/3.2/bitops_1.0-6.zip'
Content type 'application/zip' length 36015 bytes (35 KB)
downloaded 35 KB

trying URL 'http://stat.ethz.ch/CRAN/bin/windows/contrib/3.2/RCurl_1.95-4.7.zip'
Content type 'application/zip' length 2858472 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'http://stat.ethz.ch/CRAN/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132712 bytes (129 KB)
downloaded 129 KB

package ‘bitops’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘bitops’
package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘RCurl’
package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Sarah.T\AppData\Local\Temp\RtmpAhiKO1\downloaded_packages
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘magrittr’
Error: package or namespace load failed for ‘swirl’
failed for ‘swirl’

**Comment by seankross** [comment]
@Sarah81 Take a look at #325, #326, and #327. Let me know if any of those work for you.

**Comment by Sarah81** [comment]
thanks for your answer.

with #325 i got the same error
with #326 I got this for both TRUE and Source

*Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) : *
*  there is no package called 'magrittr'*
*ERROR: lazy loading failed for package 'swirl'*
** removing 'C:/Users/Sarah.T/Documents/R/win-library/3.2/swirl'*
** restoring previous 'C:/Users/Sarah.T/Documents/R/win-library/3.2/swirl'*

*The downloaded source packages are in*
*
‘C:\Users\Sarah.T\AppData\Local\Temp\RtmpGAnHok\downloaded_packages’*
*Warning messages:*
*1: running command '"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" CMD INSTALL -l
"C:\Users\Sarah.T\Documents\R\win-library\3.2"
C:\Users\Sarah.T\AppData\Local\Temp\RtmpGAnHok/downloaded_packages/swirl_2.2.21.tar.gz'
had status 1 *
*2: In install.packages("swirl", repos = "http://cran.rstudio.com/
<http://cran.rstudio.com/>",  :*
*  installation of package ‘swirl’ had non-zero exit status*

#327 I got this
*Downloading github repo swirldev/swirl@master*
*Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) : *
*  there is no package called ‘magrittr’*

Do you think that the problem can come from my antivirus? or any other
reason?

thank you very much for your help

Sarah

2015-07-09 21:13 GMT+02:00 Sean Kross <notifications@github.com>:

**Comment by Sarah81** [comment]
Hi,

I install R in my old PC then i use install.packages("swirl") link to a mirror, etc and swirl was install in 2minutes...
So something is blocking the process in my new computer....


Le 9 juil. 2015 à 21:13, Sean Kross <notifications@github.com> a écrit :

@Sarah81 Take a look at #325, #326, and #327. Let me know if any of those work for you.

**Comment by seankross** [comment]
Can you try installing magrittr and then try to install swirl? I doubt it has to do with your antivirus.

**Comment by Sarah81** [comment]
now I have these messages:
unable to access index for repository
package 'magrittr' is not available (for R version 3.2.1) ...

2015-07-11 0:11 GMT+02:00 Sean Kross <notifications@github.com>:

**Comment by Sarah81** [comment]
I am using the mirror  -->switzerland (ETHZ)

2015-07-11 16:42 GMT+02:00 Sarah Thurnheer <sarahthurnheer17@gmail.com>:

**Comment by Sarah81** [comment]
i reinstalled the R 3.2.1 and change the cran mirror and it worked
installing magrittr and swirl after

Thank you soooo much

Sarah

**Comment by shwetamrit** [comment]
I m also facing the same problem please help me.
package ‘swirl’ successfully unpacked and MD5 sums checked

**Comment by shwetamrit** [comment]
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bitops’
Error: package or namespace load failed for ‘swirl’
what i have to do then???

**Comment by seankross** [comment]
@shwetamrit try:

```r
install.packages("bitops")
library(swirl)
```

Let me know of that works.

**Comment by SQL-realname** [comment]
Hi Here is the **error** I got below. I appreciate your help!
> library("swirl")
Error: package or namespace load failed for ‘swirl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest/libs/digest.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest/libs/digest.so, 6): Symbol not found: ___cxa_uncaught_exceptions
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib


> library(swirl)
Error: package or namespace load failed for ‘swirl’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest/libs/digest.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.6/Resources/library/digest/libs/digest.so, 6): Symbol not found: ___cxa_uncaught_exceptions
  Referenced from: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib
  Expected in: /usr/lib/libc++abi.dylib
 in /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libc++.1.dylib

**Before that, I have done** 
> install.packages("swirl")
> install.packages("bitops")
> install.packages("R6")
> install.packages("evaluate")
> install.packages("swirl", dependencies=TRUE)

**This is what I have when I typed:**
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.6/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    RCurl_1.98-1.2 bitops_1.0-6
