### ISSUE TITLE
Error loading Swirl library

### ISSUE THREAD

**Issue by SSofia19** [swirldev/swirl#279]
Hello!  Would be grateful for any help.  I'm on Windows 7 Home Premium.  When I installed swirl and attempted library(swirl), it initially kept telling me I didn't have packages installed.  I installed them and got stuck here.  I fear user error may play a role. :)  Thank you in advance!

![image](https://cloud.githubusercontent.com/assets/10352475/6794403/aeded9f2-d1a7-11e4-9b9b-f4ec2b0ed8df.png)

**Comment by SSofia19** [comment]
So, since I can't sit idle, I did more research and realized it was a problem with the library path since one wasn't set.  So I set one!  And the package installed like it used to except I have a new problem when I call the library. 

Error : .onAttach failed in attachNamespace() for 'swirl', details:
  call: strwrap(str_c(..., sep = " "), width = getOption("width") - 2)
  error: cannot open file 'C:/Users/Sara Sofia/Documents/R/win-library/3.1/stringr/R/stringr.rdb': No such file or directory
Error: package or namespace load failed for ‘swirl’

Obviously, I should not be left alone to my own devices this long.  I promise I'll stop causing more problems.....for tonight...

![image](https://cloud.githubusercontent.com/assets/10352475/6794791/d7054f92-d1ac-11e4-963e-e0a1f02a0e77.png)

**Comment by ncarchedi** [comment]
Looks like some of swirls dependencies didn't install correctly. Try install.packages("swirl", dependencies = TRUE). If that doesn't work, you'll need to install the "stringr" R package and possibly others. The clues are in the error messages ;)
