### ISSUE TITLE
Can't run swirl("test"... from within a function

### ISSUE THREAD

**Issue by dgrtwo** [swirldev/swirl#280]
I'm working on an extension of swirl that requires entering swirl's "test" mode from within one of my functions. However, I've found that when `swirl("test", ...)` is used within a function, it shows very odd behavior: in particular, the first question is repeated.

Steps to reproduce:

    library(swirl)
    install_from_swirl("R Programming")

The following works just as expected, showing the 10th question in the "Basic Building Blocks" course, then exiting:

    swirl("test", test_course = "R Programming",
          test_lesson = "Basic Building Blocks",
          from = 10, to = 10.5)

However, if I wrap the exact same code in a function:

    func <- function() {
        swirl("test", test_course = "R Programming",
          test_lesson = "Basic Building Blocks",
          from = 10, to = 10.5)
    }
    func()

Now it repeats the question twice, where the response to the first question is entirely ignored:

    Completing the first part of the lesson for you...

      |                                                                      |   0%
      |=================                                                     |  24%
    | To view the contents of the variable x, just type x and press Enter. Try it
    | now.

    > x
    [1] 12

    Completing the first part of the lesson for you...

      |                                                                      |   0%
      |=================                                                     |  24%
    | To view the contents of the variable x, just type x and press Enter. Try it
    | now.

    > x
    [1] 12

    | Perseverance, that's the answer.

    | Lesson complete! Exiting swirl now...

Is there a way around this behavior?

**Comment by ncarchedi** [comment]
Hmm, this is related to the callback mechanism at swirl's core (see `?addTaskCallback`), but it's not immediately obvious to me why it's happening. I make a similar call to `swirl("test", ...)` in swirlify:

https://github.com/swirldev/swirlify/blob/166dcf450167ea064716e5ade9dd81332fa3b674/R/swirlify.R

**Comment by dgrtwo** [comment]
Your response led me to the solution: at [this line](https://github.com/swirldev/swirl/blob/master/R/swirl.R#L444) there is a special case for functions such as `swirl` and `swirlify`, that basically stops them from triggering on themselves when it sets up the list of variables that have changed:

      if(!uses_func("swirl")(e$expr)[[1]] &&
           !uses_func("swirlify")(e$expr)[[1]] &&
           !uses_func("testit")(e$expr)[[1]] &&
           !uses_func("nxt")(e$expr)[[1]] &&
           isTRUE(customTests$AUTO_DETECT_NEWVAR)) {
        e$delta <- mergeLists(safeEval(e$expr, e), e$delta)
      }

This is why `swirlify` worked and my function didn't. Since I am forking swirl in my application I can simply add the name of that function to the list of exceptions. Thanks!

**Comment by ncarchedi** [comment]
Ah, yes! It's been a while since I coded that. We actually just merged some code that hopefully provides the first somewhat useful swirl API. Do you mind sharing what the application is that you're working on?

**Comment by dgrtwo** [comment]
@ncarchedi We're calling it [Socratic Swirl](https://github.com/dimaoo7/socraticswirl) (hope that name's OK!). It lets R instructors give students Swirl exercises in class, and have the instructor watch their real-time progress in a dashboard. The student starts with something like:

    socratic_swirl("linear regression", instructor = "instructors name")

Then can take an exercise (when the instructor prompts) with

    exercise(1)
    exercise(2)

Here's a [demo of the dashboard](https://dgrtwo.shinyapps.io/socraticswirl/). We're still in the finishing touches stage but would love your thoughts or contributions!

(Of course everything is GPL-3 and free).
