### ISSUE TITLE
swirl name origin in documentation

### ISSUE THREAD

**Issue by apjanke** [swirldev/swirl#282]
Hi swirl folks, 

Minor request for background documentation: IIRC, `swirl`'s name is or comes from an acronym for "statistics with interactive R learning". But I didn't see that noted in the Readme or the swirlstats.com web page. Is that the case? There's no impact, but it would be interesting to have it noted somewhere for reference.

**Comment by ncarchedi** [comment]
You are correct, sir. It used to be on the website, but it must have gotten lost in the redesign a few months back. We should at least mention it on the FAQ page of swirlstats.com. Will keep this issue open until I have a chance to do so.

**Comment by apjanke** [comment]
Thanks!
