### ISSUE TITLE
Exits silently during lesson

### ISSUE THREAD

**Issue by msonnabaum** [swirldev/swirl#283]
During the Probability2 lesson of the Statistical Inference course, swirl exits without any error message after the same question. Here's a screenshot of the behavior:

![swirl_exit](https://cloud.githubusercontent.com/assets/49792/7101952/233f30a2-e036-11e4-8779-685ba425d735.png)

I've reproduced it in Rstudio and the R console. I've also upgraded R from 3.1.1 to 3.1.3 and swirl from 2.2.21 to 2.3.0, and the behavior remains the same.

Any ideas on how to debug this further?

**Comment by reginaastri** [comment]
Are you sure swirl is exiting? I don't see an error message. Try typing the area of the triangle after the command prompt.

**Comment by msonnabaum** [comment]
Ok, you're totally right, it's just waiting for a response.

What confused me here is that the prompt looks exactly like the normal R console prompt, so I thought I was outside of the swirl lesson. Also, if you press enter without giving an answer, it just shows the prompt again with no feedback.

**Comment by ncarchedi** [comment]
That's how swirl works. You are actually at the R prompt, not an imitation prompt. Swirl is just listening in the background for you to enter a response. Good luck!
