### ISSUE TITLE
Can't choose a lesson

### ISSUE THREAD

**Issue by mclark11** [swirldev/swirl#284]
Hi. I just downloaded Swirl in R Studio (0.98.1103) on my Windows 8 Computer and while I can run the program I can't choose a lesson.

> swirl()

| Welcome to swirl!

| Please sign in. If you've been here before,
| use the same name as you did then. If you are
| new, call yourself something unique.

What shall I call you? m

| Please choose a course, or type 0 to exit
| swirl.

1: swirldev-swirl courses-175c5ce
2: Take me to the swirl course repository!

Selection: 
Enter an item from the menu, or 0 to exit
Selection: 1

| Please choose a lesson, or type 0 to return
| to course menu.

1: R Programming

Selection: 1

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

How can I resolve this issue?

Thanks,
M

**Comment by seankross** [comment]
Try the following:

```
uninstall_all_courses()
install_from_swirl("R Programming")
swirl()
```

**Comment by mclark11** [comment]
Thanks Sean, this worked perfectly!
