### ISSUE TITLE
Unable to identify current timezone 'T'

### ISSUE THREAD

**Issue by JarqueBera** [swirldev/swirl#287]
Hello everyone,

I was dowloading a quiz. The package and the course (+ quizzes) had been successfully installed but it keeps giving me this :  

| Course installed successfully!

Warning messages:
1: In strptime(x, format, tz = tz) :
  unable to identify current timezone 'T':
please set environment variable 'TZ'
2: In strptime(x, format, tz = tz) : unknown timezone 'localtime'
3: In if (file.copy(dirs_to_copy, file.path(system.file(package = "swirl"),  :
  the condition has length > 1 and only the first element will be used 

I should not that I'm a beginner so plz excuse me if couldn't understand the warning msg.

Thx

**Comment by seankross** [comment]
What command are you using to install a course?

**Comment by JarqueBera** [comment]
Heya,

this what I wrote : 

install_course_github("dgrtwo", "RData", branch="quizzes", multi=TRUE)

and after starting the package I should be able to see the course menu, but I have the warning msg instead.

Thanx mate

**Comment by seankross** [comment]
If I were you I would download the zip file of the repository from [this](https://github.com/dgrtwo/RData/tree/quizzes) GitHub page and then run the following, with the path to the zip you downloaded:

```
uninstall_all_courses()
install_course_zip("path/to/zip/file", multi = TRUE, which_course = "Lesson_1._Variables_and_Data_Structures")
```

**Comment by JarqueBera** [comment]
Thank you so much for you reply and time :)

**Comment by seankross** [comment]
No problem! Let me know if you have any other issues.
