### ISSUE TITLE
Submit script

### ISSUE THREAD

**Issue by Euklidian-Space** [swirldev/swirl#290]
I am currently working on the "R programming functions" section on swirl.  When it asks me to use the submit() function it brings me to the menu for submitting my last programming assignment for the R class on coursera and it will not let me continue with the swirl lesson.

**Comment by seankross** [comment]
Are you using swirl in the R console, on the command line, or in RStudio?

**Comment by Euklidian-Space** [comment]
I am using it in Rstudio

**Comment by seankross** [comment]
When you're asked a question that requires you to submit a script in swirl, a new file should open up in the test editor window. Does this happen for you?

**Comment by Euklidian-Space** [comment]
Yes. A script named boringfunction.R opens up.

**Comment by seankross** [comment]
You're supposed to make modifications to that script, save it, and then
type submit() into the R console and hit enter. Is that process not
working?

**Comment by Jeroenvos** [comment]
I got the same problem, all the above works except typing submit()
This brings me to:

Press Enter to continue...
| Is the following information correct?

Course ID: rprog-0XX
Submission login (email): xx@gmail.com
Submission password: xxxxxx

1: Yes, go ahead!
2: No, I need to change something.

Selection: 
Enter an item from the menu, or 0 to exit
Selection: 

Et cetera.
Which is the submit script for the R programming course on coursera
source("http://d396qusza40orc.cloudfront.net/rprog%2Fscripts%2Fsubmitscript3.R")

**Comment by Jeroenvos** [comment]
Clearing the workspace however does the job 
rm(list=ls())

**Comment by ncarchedi** [comment]
Yea, unfortunately a different function by the same name is used to submit
programming assignments in the R Programming Coursera course. @Jeroen's
suggestion will solve your problem.

**Comment by Dean1944** [comment]
I think I just found the secret.  I'm working in "R-Studio", but I do most of my entry into the "Console" screen when working with Swirl.  I just, on a hunch, modified the script in the entry / editor screen (not Console), saved it, hi-lighted the modified script, and hit run.  Everything seemed to work OK.

I don't know why this has to be this difficult. 

gdw

**Comment by niokhor** [comment]
I don't known, I can't submit in R and R studio, this what the message.
Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.

| Not quite right, but keep trying.
What can I do please?
