### ISSUE TITLE
Swirl not loading courses

### ISSUE THREAD

**Issue by lapisdecor** [swirldev/swirl#292]
When running swirl I can only see this two courses, and at least the first one is not loading:
https://github.com/swirldev/swirl/blob/master/inst/Courses/suggested_courses.yaml
It tells me I have no internet connection.  But I have otherwise I wouldn't be writing this.
I also had to install RCurl from repositories (from Ubuntu terminal).

**Comment by seankross** [comment]
Perhaps this can help you:
https://github.com/swirldev/swirl_courses#install-and-run-a-course-automatically-from-swirl

**Comment by ncarchedi** [comment]
Yep, and if that doesn't work you may be behind a firewall at your office/school.

**Comment by lapisdecor** [comment]
Yes, I'm behind a firewall, what port do I need to open?

**Comment by lapisdecor** [comment]
This is not firewall related. I've disconnected the firewall, and it still doesn't works. Also, I had swirl working in a previous Ubuntu 14.04 installation.

**Comment by lapisdecor** [comment]
This might be happening because I tried to install swirl without installing RCurl first, since it did run gcc and may have configured some values. Since the installation didn't worked, I installed r-cran-rcurl ubuntu package, and reinstalled swirl which was very fast to install (It didn't make a many messages). Swirl did load and work after that, and it works if I do a manual install of the courses from ziped repository, but it's not working if I try the normal way. Since I might not be the only one with this problem, there should probably be a message on README.md telling ubuntu users they need to install the RCurl package before installing swirl because this might affect a lot of people. I tried the same procedure on another computer with the same OS and the same thing happend.

**Comment by seankross** [comment]
Have you tried installing a course manually yet? I meant to direct you to this link link earlier: https://github.com/swirldev/swirl_courses#install-and-run-a-course-manually

**Comment by lapisdecor** [comment]
Yes, as I previously said, I installed a course manually and it worked. I'm just puzzled to why can't I access courses the normal way. I'm even checking the code. It's strange that the only courses I see are the two in the inst/Courses directory of swirl repository.
