### ISSUE TITLE
issue installing swirl on mac r 3.1

### ISSUE THREAD

**Issue by timmo2003** [swirldev/swirl#293]
I'm unable to update r on my mac, and get the following error message when trying to use swirl..

R version 3.1.2 (2014-10-31) -- "Pumpkin Helmet"
Copyright (C) 2014 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin10.8.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library("swirl")
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/yaml/libs/yaml.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.1/Resources/library/yaml/libs/yaml.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.2/Resources/lib/libR.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.1/Resources/library/yaml/libs/yaml.so
  Reason: Incompatible library version: yaml.so requires version 3.2.0 or later, but libR.dylib provides version 3.1.0
Error: package or namespace load failed for ‘swirl’

Any help would be greatly appreciated.

Thanks

Andrew

**Comment by seankross** [comment]
Did you install swirl? If you're not sure, try:

```r
install.packages("swirl")
library(swirl)
```
