### ISSUE TITLE
Error in file(con, "r") : invalid 'description' argument when choosing course from library

### ISSUE THREAD

**Issue by Random-Primate** [swirldev/swirl#294]
I'm not able to run other courses from swirl such as Workspace and Files. 
Workflow:
(R installed)
1. ```install.packages("swirl")```
2. ```library("swirl")```
3. ``install_from_swirl("Workspace and Files")```
4. ```swirl()```
5. On the choose course selection I choose the number for Workspace and Files
6. I choose 1 which is lesson.yml
7. Results in:
```
Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.
```
And the traceback is:

```
> traceback()
15: file(con, "r")
14: readLines(input)
13: paste(readLines(input), collapse = "\n")
12: yaml.load(paste(readLines(input), collapse = "\n"), ...)
11: yaml.load_file(file)
10: parse_content.yaml(file, e)
9: parse_content.default(dataName, e)
8: parse_content(dataName, e)
7: loadLesson.default(e, courseU, lesson)
6: loadLesson(e, courseU, lesson)
5: mainMenu.default(e)
4: mainMenu(e)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)
```

Environment:
- OS X v10.10.3
- R v3.2.0
- swirl v2.2.1

Dependencies met based [this](https://github.com/swirldev/swirl/issues/255) thread.

Difference from other issues:
There are a couple of similar issues which refer to a custom module, or slightly different error messages from which I've tried re installing and removing packages but to no avail.

Any help really appreciated.

**Comment by shetaa** [comment]
I had a similar problem today (on windows 7). In my case the download on the course was interrupted  due to internet connection issues. The issue was fixed after I tried again and waited a bit longer. This might happen if the course is very large.

Maybe try downloading the zip for that class and try to load the zip file?

**Comment by seankross** [comment]
Try the following:

```r
install.packages("swirl")
library("swirl")
install_from_swirl("R Programming")
swirl()
```

Then navigate the menus and select Workspace and Files.

**Comment by Random-Primate** [comment]
Thanks for your help guys. What helped was re installing from Github.

```
install.packages("devtools")
devtools::install_github("swirldev/swirl")
```
