### ISSUE TITLE
R 3.1.3 Windows 7: Closed loop error in Functions - Resolved

### ISSUE THREAD

**Issue by NeilMcIvor** [swirldev/swirl#295]
In R Studio - Started exercise 9 - and entered Sys.Date()

Date is returned - then swirl loops back to asking my name. Can't break loop - even on restarting R Studio.

Any ideas?

**Comment by seankross** [comment]
Try reinstalling swirl. If this persists I can make a version of this lesson for you that doesn't include the `Sys.Date()` part.

**Comment by NeilMcIvor** [comment]
Thank you - that worked perfectly

**Comment by seankross** [comment]
No problem! Let us know if you have any other issues.

**Comment by NeilMcIvor** [comment]
Thanks - complete newbe to R - swirl is fantastic - just scratching my head on functions at present

**Comment by NeilMcIvor** [comment]
Happening again and no amount of uninstall and re install is helping now

**Comment by NeilMcIvor** [comment]
and is also now happening on lapply course after first input
