### ISSUE TITLE
R 3.1.3 Windows 7:loop error in Functions #295

### ISSUE THREAD

**Issue by NeilMcIvor** [swirldev/swirl#296]
Not sure how to re open an closed issue: 

In R Studio - Started exercise 9 - and entered Sys.Date()

Date is returned - then swirl loops back to asking my name. Can't break loop - even on restarting R Studio.

re installed after advice - and worked fine - next day:loop error happening again and no amount of uninstall and re install is helping now - and also on lapply course after first input.

I have tried uninstalling - closing down the RStudio session - re openeing and reinstalling - but keeps happening - I am at a loss!

**Comment by seankross** [comment]
What happens if you try to `skip()` a lesson?
