### ISSUE TITLE
evalute() still doesnt let me go to next question on Swirl + R3.2.0

### ISSUE THREAD

**Issue by ramssemya** [swirldev/swirl#298]
Swirl() doesnt let me go to next question on evaluate(). Below is what I tried for function within function question. It is working for me when I try this on R, but swirl doesn't let me go to next question. I also tried it after installing install_from_swirl("R Programming"), which installed successfully

evaluate <- function(func,dat){
	func(dat)
}

Thanks

**Comment by seankross** [comment]
Let me know if you've tried the following:

1. Exit R completely
2. Start R
3. `install.packages("swirl")`
4. `library(swirl)`
5. `install_from_swirl("R Programming")`
6. `swirl()`
7. And then navigate the menus / course to this question

**Comment by negin1986** [comment]
I know the problem! There is a mistake in this part of the software package I guess. I tried the following function a thousand times and Swirl said it was wrong.:
evaluate <- function(func, dat) {
func(dat)
}
You have to try this one instead: (I think it's an error in Swirl package, cause it is not logical):
evaluate <- function(func, dat) {
dat (func)
}

**Comment by seankross** [comment]
Hi @negin1986,
Can you show me an example where:
```
evaluate <- function(func, dat) {
  dat(func)
}
```
allows the user to move on with the lesson? It shouldn't be working that way.

**Comment by negin1986** [comment]
sorry this one works:

 evaluate <- function(func, dat){
   evaluate <- dat(func) 
 }
In the two following pictures, you will see that how running one function several times gives me three results. One says: Almost! Try again.  The other says: You got it right!
Another time, the same function gives me an error!

![untitled3](https://cloud.githubusercontent.com/assets/12476457/8241966/7e125fc4-1621-11e5-9e25-f7dc541e936b.png)

![untitled2](https://cloud.githubusercontent.com/assets/12476457/8241793/9fa2933a-1620-11e5-8875-f69d2977ad14.png)

![untitled3](https://cloud.githubusercontent.com/assets/12476457/8241826/c1d5756c-1620-11e5-8fd0-572f3d12987e.png)

And now about the function below:
evaluate <- function(func, dat){
   func(dat) 
 }

The picture shows that Swirl tells me:  Not quite right, but keep trying.
![untitled4](https://cloud.githubusercontent.com/assets/12476457/8242047/235ddaf8-1622-11e5-98a5-ec95b687bd7d.png)

**Comment by negin1986** [comment]
Also another screen shot:
![untitled6](https://cloud.githubusercontent.com/assets/12476457/8242321/d289074a-1623-11e5-965f-1cc6ea035e52.png)

**Comment by seankross** [comment]
Thanks @negin1986. This is interesting, but for the record you are not supposed to type the function into the console, when you start the question a text file should open, then you should edit that text file, save the file, and then type `submit()` into the console. Thanks for pointing this out though.

**Comment by negin1986** [comment]
Oh I thought after I edit that file and write the function, I should run the function in the console then write submit(). Thanks for saying that. And how should I save the script? By clicking on the save button up in the console?

**Comment by seankross** [comment]
> And how should I save the script?

Clicking the save button in the text editor or CTRL + S in the text editor should work.

**Comment by negin1986** [comment]
There is no save button in my text editor. There is a save button in R itself, but not specific for R editor.

**Comment by seankross** [comment]
What text editor are you using?

**Comment by aubreysworkcomputer** [comment]
I had this issue in the functions module as well.  Not only would this problem not let me move on despite being correct, it kept trying to return to it every time I return to swirl and skip() would not work to get out of it.  Glad to see I am not the only one.  Thanks!

**Comment by twmht** [comment]
I have the same issue too.

**Comment by prasadprakhar** [comment]
Hi, I had the same problem during Data Science Specialization and Advanced R Programming swirl assignment. The best way to get going with the next question is to modify the code as below, it worked for me 

evaluate <- function(sd, dat){

  sd(dat)
  
}

> evaluate(sd,c(1.4, 3.6, 7.9, 8.8))
[1] 3.514138

| You're the best!

As you notice I replaced func with sd. Kind of hard coding the function but it works to get you going with the remainder of the swirl course. Hope it helps.
