### ISSUE TITLE
unable to install swirl package.

### ISSUE THREAD

**Issue by Fareeha2** [swirldev/swirl#301]
Hi!! 
I am unable to intall swirl package and getting the following error. Can anybody please help me?
Thanks

> install.packages("swirl")
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/src/contrib
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib
Installing package into ‘C:/Users/Fareeha Sultan/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/src/contrib
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.2.0)
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/bin/windows/contrib/3.2
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.2

**Comment by seankross** [comment]
Are you using a proxy to connect to the internet?

**Comment by CVJOSHI876** [comment]
make sure your computer/laptop is connected to internet.

**Comment by Fareeha2** [comment]
Yes it is connected to internet and I'm not using any proxy etc. It's
connected directly.

**Comment by Fareeha2** [comment]
But I've solved my problem.
