### ISSUE TITLE
unable to install swirl 

### ISSUE THREAD

**Issue by nadavk87** [swirldev/swirl#302]
Hey!
for some reason I get this massage after trying to install swirl:
"there is no package called 'mgrittr'"

below is an image of the screen:
![image](https://cloud.githubusercontent.com/assets/12632759/7846750/318f893e-04c8-11e5-8421-cbba0e1ecf8e.png)

what can I do?

**Comment by ncarchedi** [comment]
install.packages("magrittr") then library(swirl) again. If you get the same message regarding another missing package, do the same. Hope this helps.

**Comment by nadavk87** [comment]
Thanks! Got it!
