### ISSUE TITLE
My code is correct but swirl is asking to attempt more.

### ISSUE THREAD

**Issue by sawankumar94** [swirldev/swirl#304]
I am stuck at Chapter 9 Function Swirl.My problem is that in order to calculate my_mean.I wrote
sum(my_vector)/length(my_vector).Its correct.But swirl is asking me to make more attempts.I have been trying this for two days.There was no such problems in the previous lessons from 1 to 8.Please help me out.This is delaying me .I want to learn more.

**Comment by reginaastri** [comment]
Are you putting your code in a correctly defined function? See 
https://gist.github.com/seankross/912fe3b9f19a91b0a7bd 
for the correct format.

**Comment by sawankumar94** [comment]
Again My code is correct for calculating "remainder" i wrote 
remainder<- function(num,divisor=2){
 num %% divisor
}  but swirl is saying to try for more.I think this is correct. This is really delaying for other lessons.

**Comment by seankross** [comment]
Can you include a screen shot of this issue? Thanks.

**Comment by f-e-charles** [comment]
I'm having the same issue. 
![screenshot 2015-08-05 22 02 36](https://cloud.githubusercontent.com/assets/4666026/9102215/bf4ebc96-3bbd-11e5-8d77-08ddfd27fe22.png)

**Comment by seankross** [comment]
@f-e-charles Did you save your script before entering `submit()`? Did you resume this lesson after quitting the lesson?

**Comment by f-e-charles** [comment]
I relaunched, saved the script and got it to work. Thanks!
