### ISSUE TITLE
I am putting my code in correctly defined function correctly. But swirl is still asking me to attempt more

### ISSUE THREAD

**Issue by sawankumar94** [swirldev/swirl#305]
I am stuck at Chapter 9 Function Swirl. My code is correct for calculating "remainder" i wrote 
remainder<- function(num,divisor=2){
num %% divisor
} but swirl is saying to try for more. The code is correct and i have put this in correctly defined function. 
Why this is happening  to the swirl.I have tried this for more than 15 times.This is delaying me for attempting new problems.Please help me out

**Comment by seankross** [comment]
Can you please post a screen shot of the problem you're having?

**Comment by sawankumar94** [comment]
Sir,
Here is the screen shot of problem.You can see that i am doing correct.But
Swirl is asking me to attempt more.

**Comment by ncarchedi** [comment]
I can't see a screen shot, but are you remembering to save the script before typing submit()?

**Comment by sawankumar94** [comment]
Yes, I always save first then source it,then submit().
Here is another screen shot.

**Comment by seankross** [comment]
I still can't see your screenshot. Please check this issue in Github to make sure your screenshot is appearing: https://github.com/swirldev/swirl/issues/305

**Comment by negin1986** [comment]
The same problem happened to me once but when I tried again it was fixed. Maybe it will be fixed it you write another function (wrong one) and run it and then write this correct function again. That helped me.

**Comment by GHarmata** [comment]
I am having the same issue in the tidyr lesson.  The script for the SAT example runs in R without any error messages and gives me the correct output, but the lesson keeps telling me that my script is wrong.  I have saved my script.

**Comment by jiangcsu** [comment]
i have the same question , now ,i deal with the question ,i forget to save .hope to help you
