### ISSUE TITLE
Error in unzip(path, list=TRUE)

### ISSUE THREAD

**Issue by js8384** [swirldev/swirl#306]
Hi
I could not load the course normally - see message as below

...
(| Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in R’ right now. Are you sure you have an
| internet connection? If so, would you like to try again or visit the course repository for instructions on how to install
| a course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.) 

...

I decided to laod them manually but i still get an error message  while i try to open the zipped file. 
Could you help me? 
Thanks

> library(swirl)
> install_course_zip("~/Downloads/swirl_courses-master.zip", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/sampieri.j/Documents/Downloads/swirl_courses-master.zip' cannot be opened
> library(swirl)
> install_course_zip("~/Downloads/swirl_courses-master", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/sampieri.j/Documents/Downloads/swirl_courses-master' cannot be opened
> install_course_zip("~/Downloads/swirl_courses-master.zip", multi=TRUE)
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/sampieri.j/Documents/Downloads/swirl_courses-master.zip' cannot be opened
> library(swirl)
> install_course_zip("~/Downloads/swirl_courses-master", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/sampieri.j/Documents/Downloads/swirl_courses-master' cannot be opened
> library(swirl)
> install_course_zip("~/Desktop/swirl_courses-master", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/sampieri.j/Documents/Desktop/swirl_courses-master' cannot be opened
> library(swirl)
> install_course_zip("C:/users/sampieri.j/Desktop/swirl_courses-master", multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/users/sampieri.j/Desktop/swirl_courses-master' cannot be opened

**Comment by seankross** [comment]
Where on your computer did you download the swirl courses zip file, and what is the name of the file you downloaded?

**Comment by js8384** [comment]
Hi,

I put in 2 places -

C:\Users\sampieri.j\Downloads\swirl_courses-master.zip

C:\Users\sampieri.j\Desktop\swirl_courses-master.zip

Regards

JS

**Comment by seankross** [comment]
Try:

```
library(swirl)
install_course_zip(file.path("~", "Downloads", "swirl_courses-master.zip"), multi=TRUE, which_course="R Programming")
```

**Comment by swchia** [comment]
Hi, I face the same issue as js8384, I tried the code above:

install_course_zip(file.path("~", "Downloads", "swirl_courses-master.zip"), multi=TRUE, which_course="R Programming")

the below error message is returned:
> install_course_zip(file.path("~", "Downloads", "swirl_courses-master.zip"), multi=TRUE, which_course="R Programming")
Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/Shao Wei/Documents/Downloads/swirl_courses-master.zip' cannot be opened

**Comment by seankross** [comment]
@swchia what is the full path to the zip file you downloaded?

**Comment by swchia** [comment]
Here's the full path:

'C:/Users/Shao Wei/Documents/Downloads/swirl_courses-master.zip'

**Comment by seankross** [comment]
@swchia Are you still not able to resolve this issue? Have you had access to a better internet connection?

**Comment by AZMomin** [comment]
I had the same problem until I realized it was looking in the wrong directory. 

.../Documents/Downloads/... usually isn't right (unless you actually made a Downloads folder?)

Some fixes:
**Recommended:** 1. Select the correct directory where the file was installed (or where you moved it to) using 'install_course_zip("path/to/file/swirl_courses-master.zip", multi=TRUE, which_course="R Programming")'  
2. Move  swirl_courses-master.zip to your working directory (type dir() to see your WD) then use
'install_course_zip(file.path("~", "swirl_courses-master.zip"), multi=TRUE, which_course="R Programming")'
3. change your working directory to where the swirl_courses-master.zip was downloaded and use 
'install_course_zip(file.path("~", "swirl_courses-master.zip"), multi=TRUE, which_course="R Programming")'

**Comment by Beginner2015** [comment]
![untitled](https://cloud.githubusercontent.com/assets/15017817/10344188/7a9bd3e6-6d3f-11e5-8be8-be9514c28fbe.png)

**Comment by seankross** [comment]
@Beginner2015 try:

```r
install_course_zip(file.choose(), multi=TRUE, which_course="R_Programming")
```

**Comment by jasondene** [comment]
I'm having a similar issue with Mac OS X

Error in unzip(path, list = TRUE) : 

I've used all the above suggestions but they don't work.   I'm confident that I'm pointing to the right directory. I think the issue is that there is no .zip extension and Mac already unzipped it.

So, when I tried this suggestion:
install_course_zip(file.choose(), multi=TRUE, which_course="R_Programming")
... I navigated to the file but was then led into the subfolder structure of the unzipped file.  Unsure of where to go from there.

**Comment by seankross** [comment]
Try `install_course_directory()`.

**Comment by jasondene** [comment]
Thank you @seankross that worked.. I received this message:

| Course installed successfully!

Now however, when I try to choose a lesson I get a new error (Error in file(con, "r") : invalid 'description' argument)

Here's what is on my screen:

| Please choose a course, or type 0 to exit swirl.

1: swirl courses-master
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

 1: Data Analysis
 2: ErrFind
 3: Exploratory Data Analysis
 4: Getting and Cleaning Data
 5: LICENSE
 6: Mathematical Biostatistics Boot Camp
 7: Open Intro
 8: R Programming
 9: R Programming Alt
10: README.md
11: Regression Models
12: Statistical Inference
13: Writing swirl Courses

Selection: 8

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

....  i get the same error with other lessons as well.  I'm tempted to uninstall/reinstall though not sure that would do much, since I did not do anything to modify the files I downloaded.

**Comment by seankross** [comment]
Try the following:

1. Run `uninstall_all_courses()`.
2. Then go one directory deeper when you're installing a course. For example if the path to the directory you selected before was `install_course_directory("/jason/Desktop/swirl_courses-master")` this time try `install_course_directory("/jason/Desktop/swirl_courses-master/R_Programming")`.

**Comment by jasondene** [comment]
Many thanks, @seankross!  I'm in...

**Comment by seankross** [comment]
:+1:

**Comment by sushkhatra1** [comment]
:) I had same problem, thanks @seankross

**Comment by Monnappa** [comment]
Excellent!..thanks @seankross

**Comment by shwetamrit** [comment]
hello @seankross 
1:when i am using ?tapply its showing error
Error in shell.exec(url) : 
  file association for 'http://127.0.0.1:24435/library/base/html/tapply.html' not available or invalid



2:here also the same 
I'm opening the swirl courses web page in your browser.
Error in shell.exec(url) : 
  file association for 'https://github.com/swirldev/swirl_courses' not available or invalid
plz help

**Comment by seankross** [comment]
Hi @shwetamrit 

Are you using R on the command line, with the RGui, or with RStudio?

**Comment by shwetamrit** [comment]
hello@Sean Kross
i m using RGui.

**Comment by seankross** [comment]
Hi @shwetamrit are you connecting to the internet through a proxy? The proxy may be interfering with your computer's ability to display local R documentation. You may need to disconnect from the internet while using swirl.

**Comment by shwetamrit** [comment]
hello @seankross ,thank u for your support now its working.

**Comment by seankross** [comment]
:+1:

**Comment by andgosa** [comment]
@jasondene  thanks for asking and @seankross thank you so much for solving the problem!!!!!! I'm so happy!!!! :dancers:

**Comment by beginneratanalytics** [comment]
hello @seankross  even after removing internet connection i am getting error
![screenshot 42](https://cloud.githubusercontent.com/assets/19633591/16143089/2277a76a-3488-11e6-94b2-1b383026e859.png)

**Comment by seankross** [comment]
Have you tried running RStudio in administrator mode?

**Comment by beginneratanalytics** [comment]
@seankross i tried running it in administrator mode but still there is no change

**Comment by seankross** [comment]
@beginneratanalytics Do you have proxy settings configured in your web browser?

**Comment by antonioarchangelo** [comment]
I had the same problem, but I realized that the zip file path was wrong. Thank you!

**Comment by Talhajawed** [comment]
I had similar problem and just getting this error again and again. Can someone help me to fix it??
![a](https://user-images.githubusercontent.com/12697769/41505974-b479166e-722d-11e8-85ce-e0c1a50a783b.png)

**Comment by HareshJashnani** [comment]
Hi Seankross

I am unable to install the packages due to below error, I have tried all the options mentioned above, however none worked so far. I am stuck with this for couple of days now and really need help to move on

Error in unzip(path, list = TRUE) : 
  zip file 'C:\Users\haresj\Documents\R\R-3.5.0\library\swirl\Courses\temp.zip' cannot be opened

Thanks in advance

**Comment by HareshJashnani** [comment]
Hi Seankross,

The issue standards resolved

Regards
Haresh

**Comment by HareshJashnani** [comment]
* Stands
