### ISSUE TITLE
How can install Statistical Inference exercise on swirl

### ISSUE THREAD

**Issue by sawankumar94** [swirldev/swirl#307]
I have recently joined "Statistical Inference" on Coursera. I have installed swirl on R.How can I install "Statistical Inference" on swirl for practice.

**Comment by seankross** [comment]
```
library(swirl)
install_from_swirl("Statistical Inference")
swirl()
```

**Comment by sawankumar94** [comment]
Once the Statistical Inference is opened ,I am unable to reinstall R
 programming  back to practice problem on it.


Sawan Kumar
Core Team Member
Student Alumni Relation Cell
Dean(Alumni & Corporate Relations)
IIT Bombay
Contact Number-9004780600

**Comment by seankross** [comment]
Are you having trouble getting out of the Statistical Inference course?

**Comment by martinyan** [comment]
HI there,
In my case, when I entered install_from_swirl("Statistical Inference") ...it takes forever and I never got my prompt back.  Is there anything I can do to find out whether R studio was stuck or is it just taking too long to download the package?

**Comment by seankross** [comment]
Hi @martinyan,

It's almost certain that the download was just taking too long. You should follow the instructions [here](https://github.com/swirldev/swirl_courses#install-and-run-a-course-manually) except you should use the command: 
```
install_course_zip(file.choose(), multi=TRUE, which_course="Statistical Inference")
``` 

after you download the zip file. Please let me know if that works.

**Comment by Nagateja** [comment]
The command works! Thanks a lot!
