### ISSUE TITLE
Swirl not loading

### ISSUE THREAD

**Issue by unnikrishnansivakumar** [swirldev/swirl#308]
> install.packages("swirl")
Installing package into ‘C:/Users/COMPUTER/Documents/R/win-library/3.1’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.1/swirl_2.2.21.zip'
Content type 'application/zip' length 132729 bytes (129 Kb)
opened URL
downloaded 129 Kb

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\COMPUTER\AppData\Local\Temp\RtmpeaFwCN\downloaded_packages
> library("swirl")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘crayon’
In addition: Warning message:
package ‘swirl’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
Try:
```
install.packages("swirl", dependencies = TRUE)
```

**Comment by foneguy4u** [comment]
I tried "install.packages("swirl", dependencies = TRUE)", when I execute cmd "library("swirl") I get the following error:
>library('swirl')
Error in library("swirl") : there is no package called ‘swirl’

**Comment by seankross** [comment]
@foneguy4u Take a look at #325, #326, and #327. Let me know if any of them helps.

**Comment by foneguy4u** [comment]
Sean,
I tried everything you suggested to no avail, below is the console output:
> install.packages("httr")
Installing package into ‘\\MI/DFS/Users/BSteele/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘jsonlite’, ‘curl’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/jsonlite_0.9.16.zip'
Content type 'application/zip' length 1009879 bytes (986 KB)
downloaded 986 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/curl_0.9.1.zip'
Content type 'application/zip' length 2240680 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/httr_1.0.0.zip'
Content type 'application/zip' length 382318 bytes (373 KB)
downloaded 373 KB

package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘\\MI\DFS\Users\BSteele\Documents\R\win-library\3.2\file28e41fce419\curl’ to ‘\\MI\DFS\Users\BSteele\Documents\R\win-library\3.2\curl’
package ‘httr’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘\\MI\DFS\Users\BSteele\Documents\R\win-library\3.2\file28e47cf1091\httr’ to ‘\\MI\DFS\Users\BSteele\Documents\R\win-library\3.2\httr’

The downloaded binary packages are in
        C:\Users\bsteele\AppData\Local\Temp\RtmpK8uNkG\downloaded_packages
> install.packages("swirl")
Installing package into ‘\\MI/DFS/Users/BSteele/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘curl’, ‘httr’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/curl_0.9.1.zip'
Content type 'application/zip' length 2240680 bytes (2.1 MB)
downloaded 2.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/httr_1.0.0.zip'
Content type 'application/zip' length 382318 bytes (373 KB)
downloaded 373 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132529 bytes (129 KB)
downloaded 129 KB

package ‘curl’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘httr’
package ‘swirl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  cannot remove prior installation of package ‘swirl’

The downloaded binary packages are in
        C:\Users\bsteele\AppData\Local\Temp\RtmpK8uNkG\downloaded_packages
> library("swirl")
Error in library("swirl") : there is no package called ‘swirl’


>

**Comment by seankross** [comment]
@foneguy4u Are you on your personal computer or a work computer?

**Comment by foneguy4u** [comment]
Work, but I have admin rights & if necessary a personal computer


________________________________

**Comment by seankross** [comment]
Try using this guide for installing packages on windows with admin privileges: http://www.magesblog.com/2012/04/installing-r-packages-without-admin.html

**Comment by sohelramjan** [comment]
Warning: namespace ‘swirl’ is not available and has been replaced
by .GlobalEnv when processing object ‘ok’
[Previously saved workspace restored]

I am getting this warning when I open my workspace and R is not supporting swirl and giving following message when I load library for swirl, please help!

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
@sohelramjan have you tried installing stringi on its own?
