### ISSUE TITLE
Error installing swirl

### ISSUE THREAD

**Issue by Raidlord** [swirldev/swirl#309]
Hi, I'm new using R and I'm trying to use it to help me out in a course I'm taking. 

My problem is that I cannot install the swirl package as the installation says. 

This is a screenshot of the console when im trying to use the install.packeges("swirl") command
![captura](https://cloud.githubusercontent.com/assets/12719802/7944754/47d8ea78-0932-11e5-8984-0b509a71893d.PNG)

**Comment by michalkahle** [comment]
Just fixed this problem by making C:\Program Files\R\R-3.2.0\library and subdirectories writable.
