### ISSUE TITLE
Swirl not installing in RStudio (2.13.1)

### ISSUE THREAD

**Issue by PerformanceGenetics** [swirldev/swirl#310]
> install.packages("swirl")
Warning in install.packages :
  package ‘swirl’ is not available (for R version 2.13.1)

**Comment by seankross** [comment]
You should download the latest version of R.

**Comment by PerformanceGenetics** [comment]
Thanks.

**Comment by Tushansu** [comment]
whenever i type swirl(), i get this
 swirl()
Error: could not find function "swirl" (this is when i already install swirl the last time)
Then i have to install it again. how can i install it for once and for all

**Comment by seankross** [comment]
@Tushansu try:
```
install.packages("swirl")
library(swirl)
swirl()
```
