### ISSUE TITLE
error while installing swirl

### ISSUE THREAD

**Issue by CVJOSHI876** [swirldev/swirl#312]
I was trying to install swirl package via rstudio.
Please find attached screen shot. It gave following error.

 cannot open compressed file 'stringi/DESCRIPTION', probable reason 'No such file or directory'.

Even though it is downloaded.

I tried again and run install.packages("swirl"). Everytime it download files with different size.

**Comment by seankross** [comment]
Try: `install.packages("swirl", dependencies = TRUE)`

**Comment by CVJOSHI876** [comment]
try installing packages through RStudio rather than from console. It worked
for me.

**Comment by seankross** [comment]
@CVJOSHI876 Did you solve your issue?

**Comment by maxlino** [comment]
Also I couldn't. In my case the following message appears:

> install.packages ("redemoinho", dependências = true)
Installing package into ‘C:/Users/Max/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘redemoinho’ is not available (for R version 3.2.1)

**Comment by seankross** [comment]
@maxlino what CRAN mirror are you using?

**Comment by rajeshgyawali** [comment]
I am using R version 3.2.3 on Windows 8.1 (32bit). After installing swirl,  When I used the following command    
 > library("swirl")     
And, I got the following message-

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’.

Would anybody help me ?

**Comment by seankross** [comment]
@rajeshgyawali 

What happens if you try `install.packages("stringi")`?

**Comment by rajeshgyawali** [comment]
Dear Sir,

Thank you for the help.
It worked.

**Comment by gustavoverasmorais** [comment]
install.packages("swirl", dependencies = TRUE) works for me. Thanks!
