### ISSUE TITLE
SWIRL UNABLE TO INSTALL

### ISSUE THREAD

**Issue by vaishnaveem** [swirldev/swirl#314]
Warning in install.packages :
  'lib = "C:/Program Files/R Programming/R/R-3.2.0/library"' is not writable
Error in install.packages : unable to install packages

kINDLY HELP

**Comment by seankross** [comment]
It looks like you don't have privileges to install swirl in that location. You can download swirl to another directory by using the `destdir` argument in `install.packages`. You will then need to specify `lib.loc` when loading swirl with `library`.
