### ISSUE TITLE
telegram() in Functions module

### ISSUE THREAD

**Issue by tbeatty23** [swirldev/swirl#316]
My telegram function is working properly (inserts "Start" at the beginning and "End" at the end), but Swirl thinks it's not correct. After many tries with different syntax, I seem to be stuck in an infinite loop. Swirl just keeps asking me to try again, rather than just ending and giving me the answer.

**Comment by seankross** [comment]
First make sure it's the same as this answer key: https://gist.github.com/seankross/912fe3b9f19a91b0a7bd

**Comment by tbeatty23** [comment]
Sean, thank you. I meant to say "Stop" in my description above instead of "End", but I had that right in my program. It looks like the problem is that I didn't have all CAPS. I had "Start" instead of "START" etc.

**Comment by seankross** [comment]
Let us know if you run into any other issues.
