### ISSUE TITLE
Error in shell. Access denied

### ISSUE THREAD

**Issue by powderfreak** [swirldev/swirl#317]
I've been working through the Basic Building Blocks section, when swirl prompts me to enter the newly command, " ?c ". When I do this, I get the error message:

Error in shell.exec(url) : 
  access to 'http://127.0.0.1:29912/library/base/html/c.html' denied

I can't move on and learn more until I can resolve this. Thanks for any help.

**Comment by seankross** [comment]
Does `skip()` work?

**Comment by powderfreak** [comment]
It doesn't. When I type skip(), I get this:


> skip()

| Entering the following correct answer for you...

> ?c
Error in shell.exec(url) : 
  access to 'http://127.0.0.1:29912/library/base/html/c.html' denied

| Leaving swirl now. Type swirl() to resume.

>

**Comment by seankross** [comment]
R is trying to open the manual page for the `c()` function. Are you using swirl through `ssh`?

**Comment by evilantal** [comment]
I'm getting this same error on this particular function.
It's because I'm behind a corporate firewall and can't connect to the url from R.

Is there a workaround without using the internet or by skipping the question somehow?

**Comment by seankross** [comment]
Try entering this command before you start up swirl:

```
options(help_type = "text")
```

**Comment by Jenny4** [comment]
Hi, I had the same issue. I entered what seankross suggested above before starting swirl and it resolved the issue, thanks!

**Comment by maurertrish** [comment]
Thank you @seankross! I just spent about 30 minutes looking for a solution and this was the only one that worked.

**Comment by millanforever** [comment]
thank you @seankross .. u great
