### ISSUE TITLE
Lesson 9

### ISSUE THREAD

**Issue by Papiwcio** [swirldev/swirl#318]
Hi, I am stuck on on boring_function. The function is correct, I checked, it is working well, however I still get an error message. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/9639007/8130028/926e3c34-110f-11e5-9c83-1040bdb13eba.png)

**Comment by seankross** [comment]
When you get to this question, a text editor should open up. Edit the program in that text editor, save the file, and then type `submit()` into the console.

**Comment by Papiwcio** [comment]
Thanks, got confused:) All good now
