### ISSUE TITLE
Another error installing swirl in RStudio

### ISSUE THREAD

**Issue by satiutni** [swirldev/swirl#319]
This is the output I receive after installing swirl:
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘crayon’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Program Files\R\R-3.2.0\library\file6181f9d44a9\jsonlite’ to ‘C:\Program Files\R\R-3.2.0\library\jsonlite’
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘bitops’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
Error in install.packages : missing value where TRUE/FALSE needed
> 
Does this mean 'jsonlite' is not correctly installed?
What, if anything, do I need to do about the final error regarding missing value?

**Comment by seankross** [comment]
Try: `install.packages("swirl", dependencies = TRUE)`
