### ISSUE TITLE
open intro overview of statistics

### ISSUE THREAD

**Issue by jrtheobald** [swirldev/swirl#324]
The documentations lists the overview of statistics as a course, and the content appears to download, but the course does not run in Rstudio when prompted to select an item from the menu.  It appears to be only a list of R scripts. 

I receive this error show at bottom:  

| Please choose a lesson, or type 0 to return to course menu.

 1: dependson.txt          2: initLesson.R           3: lesson.yaml            4: mod1 bargraph.R        5: mod1 bargraph add.R 
 6: mod1 bargraph add1.R   7: mod1 boxplot.R         8: mod1 boxplot add.R     9: mod1 dotplot.R        10: mod1 dotplot add.R  
11: mod1 dotplot add1.R   12: mod1 histogram.R      13: mod1 histogram add.R  14: mod1 leftskew.R       15: mod1 pop vs samp.R  
16: mod1 rightskew.R      17: mod1 scatter.R        18: mod1 stem.R           19: mod1 symmetric.R      

Selection: 2

Error in file(con, "r") : invalid 'description' argument

**Comment by seankross** [comment]
What command are you using to install the course?

**Comment by jrtheobald** [comment]
The one install from swirl as formatted in the documentation.  I just copied and pasted the command from github then put in the course name in parentheses.  It installed everything, but it did not run like the other courses.

**Comment by seankross** [comment]
Try the following:

```
library(swirl)
uninstall_all_courses()
install_from_swirl("Open Intro")
swirl()
```

**Comment by jrtheobald** [comment]
That worked. Thanks!

**Comment by seankross** [comment]
No problem! Let us know if you have any other issues.
