### ISSUE TITLE
Unable to Install Swril

### ISSUE THREAD

**Issue by chethanaraj** [swirldev/swirl#325]
> install.packages("swirl")
--- Please select a CRAN mirror for use in this session ---
Warning: unable to access index for repository http://ftp.iitm.ac.in/cran/src/contrib
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib
Warning: unable to access index for repository http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.2
Warning messages:
1: In open.connection(con, "r") :
  unable to connect to 'cran.r-project.org' on port 80.
2: package ‘swirl’ is not available (for R version 3.2.1) 

This is the error message that I am getting. Please help.

**Comment by robertncrampton** [comment]
I'm receiving the exact same error

**Comment by seankross** [comment]
Try the following:
```
install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
```

**Comment by chethanaraj** [comment]
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib
Warning: unable to access index for repository http://cran.rstudio.com/bin/windows/contrib/3.2
Warning message:
package ‘swirl’ is not available (for R version 3.2.1) 

Seems like this also not working.

**Comment by seankross** [comment]
See #326 and let me know if that works.

**Comment by chethanaraj** [comment]
sorry to say, even this is not working!
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib
Warning message:
package ‘swirl’ is not available (for R version 3.2.1)

**Comment by seankross** [comment]
Try choosing a CRAN mirror near you with:
```
chooseCRANmirror()
```
and then try:
```
install.packages("swirl")
```

**Comment by rajidutta** [comment]
Hi, As suggested I used the following : chooseCRANmirror() followed by install.packages("swirl"). 2 of the dependencies viz memoise and stringi were downloaded successfully. All other dependencies failed to download

also installing the dependencies ‘memoise’, ‘stringi’, ‘magrittr’, ‘crayon’, ‘jsonlite’, ‘mime’, ‘curl’, ‘R6’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’

trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/memoise_0.2.1.zip'
Content type 'application/zip' length 16871 bytes (16 KB)
downloaded 16 KB

trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/stringi_0.5-5.zip'
Content type 'application/zip' length 14261819 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/magrittr_1.5.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/magrittr_1.5.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘magrittr’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/crayon_1.3.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/crayon_1.3.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘crayon’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/jsonlite_0.9.16.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/jsonlite_0.9.16.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘jsonlite’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/mime_0.3.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/mime_0.3.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘mime’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/curl_0.9.1.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/curl_0.9.1.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘curl’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/R6_2.1.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/R6_2.1.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘R6’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/bitops_1.0-6.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/bitops_1.0-6.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘bitops’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/stringr_1.0.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/stringr_1.0.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘stringr’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/testthat_0.10.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/testthat_0.10.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘testthat’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/httr_1.0.0.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/httr_1.0.0.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘httr’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/yaml_2.1.13.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/yaml_2.1.13.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘yaml’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/RCurl_1.95-4.7.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/RCurl_1.95-4.7.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘RCurl’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/digest_0.6.8.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/digest_0.6.8.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘digest’ failed
trying URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://ftp.iitm.ac.in/cran/bin/windows/contrib/3.2/swirl_2.2.21.zip'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '401 Authorization Required'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘swirl’ failed
package ‘memoise’ successfully unpacked and MD5 sums checked
package ‘stringi’ successfully unpacked and MD5 sums checked

**Comment by rajidutta** [comment]
I retried and could successfully install swirl. Thanks for the posts.

**Comment by jinny20** [comment]
This is the error I keep getting while trying to install swirl. I referred and tried what was told in posts #325, #326. Please help


>install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
Installing package into ‘C:/Users/purbatripathy/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib
Warning: unable to access index for repository http://cran.rstudio.com/bin/windows/contrib/3.2
Warning message:
package ‘swirl’ is not available (for R version 3.2.1) 
> chooseCRANmirror()
Warning message:
In open.connection(con, "r") :
  unable to connect to 'cran.r-project.org' on port 80.
> chooseCRANmirror()
Warning message:
In open.connection(con, "r") :
  unable to connect to 'cran.r-project.org' on port 80.

**Comment by seankross** [comment]
@jinny20 what CRAN mirror are you using?

**Comment by hamk3010** [comment]
I had a problem while trying to install the swirl package.

install.packages("swirl")

once this command is executed you are required to choose a CRAN mirror. Problem that I faced was: I chose my CRAN mirror for USA(CA). As soon as I did that I got an error that the swirl package for

"R version 3.2.3 is not available"

In order to install the swirl package I had to change my CRAN mirror which can be done using

chooseCRANmirror()

once you execute this function you can choose a different CRAN mirror. I chose USA(TX) and then executed

install.packages("swirl")

and everything worked fine after.

Thanks @seankross

**Comment by bhaditya** [comment]
thanks @seankross ..choosing cran worked for me!

**Comment by njnlol** [comment]
Hey @seankross , I'm from India and I've been trying install swirl for over 12 hours now. I'm new to this so I might be making a stupid mistake. Here's what pops up when i try to install swirl-
Installing package into ‘C:/Users/User/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://cran.cnr.berkeley.edu/src/contrib:
  cannot open URL 'https://cran.cnr.berkeley.edu/src/contrib/PACKAGES'
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.cnr.berkeley.edu/bin/windows/contrib/3.4:
  cannot open URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.4/PACKAGES'
Warning: unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.4/PACKAGES'
Warning message:
package ‘swirl’ is not available (for R version 3.4.0)

**Comment by mabolivar** [comment]
@njnlol What R version are using to install swirl 32 or 64-bit? 
I had the same problem and I realized that I was using a 32-bit version. I switch to 64-bit version in RStudio and worked without any trouble.

**Comment by Yagyika** [comment]
Hi,

I am new to R. Can anyone help me out with the below error I am getting while loading Swril?

> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
Installing package into ‘C:/Users/welcome/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.5/swirl_2.4.3.zip'
Content type 'application/zip' length 344462 bytes (336 KB)
downloaded 336 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\welcome\AppData\Local\Temp\RtmpKgepko\downloaded_packages
> library(swril)
Error in library(swril) : there is no package called ‘swril’

I am currently using Windows 10, 64 Bit with R-3.5 64 bit version.

**Comment by GreenED14** [comment]
@Yagyika I think it is "swirl" and not "swril"
