### ISSUE TITLE
Loading Swirl into RStudio (R version 3.2.1

### ISSUE THREAD

**Issue by KAS58** [swirldev/swirl#326]
Hi there, 

I'm working on OS X Yosemite, 10.10.4, trying to install Swirl onto RStudio (following the directions from http://swirlstats.com/students.html).  When I try to install Swirl onto RStudio, I get the following response: 

![screen shot 2015-07-08 at 11 02 09 am](https://cloud.githubusercontent.com/assets/13239446/8573696/0d7599b2-2561-11e5-8d53-6d0bee019c93.png)

Please advise on what I can do.  Thanks!

**Comment by seankross** [comment]
Try:
```
install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
```
and if that doesn't work try:
```
install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")
```

**Comment by KAS58** [comment]
I followed the first line, and it worked!  Many thanks for your help!

**Comment by seankross** [comment]
Yay! Let us know if you have any other issues.

**Comment by trxtrbd** [comment]
I has same issue as KAS58.
I am on ubuntu 14.01
R 3.2.1
I used:

install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)

and if that doesn't work try:

install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")

but still the package did not  install:
got the following output:
Installing package into ‘/home/trxtr/R/x86_64-unknown-linux-gnu-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘curl’, ‘httr’, ‘RCurl’

trying URL 'http://cran.rstudio.com/src/contrib/curl_0.9.2.tar.gz'
Content type 'application/x-gzip' length 244688 bytes (238 KB)
==================================================
downloaded 238 KB

trying URL 'http://cran.rstudio.com/src/contrib/httr_1.0.0.tar.gz'
Content type 'application/x-gzip' length 245989 bytes (240 KB)
==================================================
downloaded 240 KB

trying URL 'http://cran.rstudio.com/src/contrib/RCurl_1.95-4.7.tar.gz'
Content type 'application/x-gzip' length 916897 bytes (895 KB)
==================================================
downloaded 895 KB

trying URL 'http://cran.rstudio.com/src/contrib/swirl_2.2.21.tar.gz'
Content type 'application/x-gzip' length 51037 bytes (49 KB)
==================================================
downloaded 49 KB

Warning in install.packages :
  system call failed: Cannot allocate memory
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status
Warning in install.packages :
  system call failed: Cannot allocate memory
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status
Warning in install.packages :
  system call failed: Cannot allocate memory
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
Warning in install.packages :
  system call failed: Cannot allocate memory
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp8G0Kpc/downloaded_packages’

Sorry: I am still a Newbie...
// trxtrbd

**Comment by DHARM013** [comment]
I am having problem in installing swirl package.
 install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
Installing package into ‘C:/Users/dharm/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib:
  cannot open URL 'http://cran.rstudio.com/src/contrib/PACKAGES'
Warning: unable to access index for repository http://cran.rstudio.com/bin/windows/contrib/3.3:
  cannot open URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/PACKAGES'
Warning message:
package ‘swirl’ is not available (for R version 3.3.1) 
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE, type="source")
Installing package into ‘C:/Users/dharm/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository http://cran.rstudio.com/src/contrib:
  cannot open URL 'http://cran.rstudio.com/src/contrib/PACKAGES'
Warning message:
package ‘swirl’ is not available (for R version 3.3.1) 

Please Help Me.
I am using windows 7 and R version 3.3.1

**Comment by DHARM013** [comment]
While Choosing cran mirror this error is appeared. Please let me know how to solve this problem.
chooseCRANmirror()
Warning: failed to download mirrors file (cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'); using local file 'C:/PROGRA~1/R/R-33~1.1/doc/CRAN_mirrors.csv'
Warning message:
In download.file(url, destfile = f, quiet = TRUE) :
  cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv': HTTP status was '407 Proxy Authentication Required'

**Comment by seankross** [comment]
@DHARM013 where are you located?

**Comment by DHARM013** [comment]
Thanks, but I got solution for my problem. I used a VPN software to install swirl package.

**Comment by GamerRaja1** [comment]
Help in installing Swirl package. Please find the log below

**
> install.packages("swirl")
Warning in install.packages :
  downloaded length 12288 != reported length 247122
Installing package into ‘C:/Users/Syanjeet/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.3.1)
Warning in install.packages :
  downloaded length 208896 != reported length 236681
> library("swirl")
Error in library("swirl") : there is no package called ‘swirl’
> install.packages("swirl")
Installing package into ‘C:/Users/Syanjeet/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.3.1)
> install.packages("swirl", repos="http://cran.rstudio.com/", dependencies=TRUE)
Installing package into ‘C:/Users/Syanjeet/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘magrittr’, ‘crayon’, ‘praise’, ‘R6’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’, ‘stringi’

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/magrittr_1.5.zip'
Content type 'application/zip' length 151029 bytes (147 KB)
downloaded 147 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/crayon_1.3.2.zip'
Content type 'application/zip' length 703777 bytes (687 KB)
downloaded 687 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/praise_1.0.0.zip'
Content type 'application/zip' length 17680 bytes (17 KB)
downloaded 17 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/R6_2.1.2.zip'
Content type 'application/zip' length 271203 bytes (264 KB)
downloaded 264 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/jsonlite_1.0.zip'
Content type 'application/zip' length 1095377 bytes (1.0 MB)
downloaded 1.0 MB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/mime_0.5.zip'
Content type 'application/zip' length 37477 bytes (36 KB)
downloaded 36 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/curl_1.1.zip'
Content type 'application/zip' length 4415171 bytes (4.2 MB)
downloaded 4.2 MB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/openssl_0.9.4.zip'
Content type 'application/zip' length 3001849 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/bitops_1.0-6.zip'
Content type 'application/zip' length 36372 bytes (35 KB)
downloaded 35 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/stringr_1.0.0.zip'
Content type 'application/zip' length 83294 bytes (81 KB)
downloaded 81 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/testthat_1.0.2.zip'
Content type 'application/zip' length 1030130 bytes (1005 KB)
downloaded 1005 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/httr_1.2.1.zip'
Content type 'application/zip' length 281236 bytes (274 KB)
downloaded 274 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/yaml_2.1.13.zip'
Content type 'application/zip' length 175733 bytes (171 KB)
downloaded 171 KB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2854329 bytes (2.7 MB)
downloaded 1.6 MB

Warning in install.packages :
  downloaded length 1626112 != reported length 2854329
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/digest_0.6.9.zip'
Content type 'application/zip' length 167355 bytes (163 KB)
downloaded 48 KB

Warning in install.packages :
  downloaded length 49152 != reported length 167355
trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/stringi_1.1.1.zip'
Content type 'application/zip' length 14258493 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'http://cran.rstudio.com/bin/windows/contrib/3.3/swirl_2.4.2.zip'
Content type 'application/zip' length 212426 bytes (207 KB)
downloaded 207 KB

package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘crayon’ successfully unpacked and MD5 sums checked
package ‘praise’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘bitops’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘yaml’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  error 1 in extracting from zip file
Warning in install.packages :
  cannot open compressed file 'RCurl/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection
**

**Comment by seankross** [comment]
@GamerRaja1 What's your geographic location?

**Comment by GamerRaja1** [comment]
Hi Sean!

Thanks for such real time update.

My Geographical location is in India and I was trying to install it in my Work-PC. this must be due to firewall settings. Because, I installed the same package successfully without any errors in my personal laptop at home.

Can you give me link to a zip package of swirl so that I can install the package manually using the install.packages('package.zip') on my Workplace PC as I am guessing the error is because files are not being downloaded through R.

Thanks in advance Sean for this immense help.

**Comment by seankross** [comment]
Hi @GamerRaja1,

When using `install.packages()` for bitops, stringi, and swirl, try using the argument: `repos = "http://ftp.iitm.ac.in/cran/"` and let me know of that helps.

Sean

**Comment by GamerRaja1** [comment]
Hey Sean! It worked like charm! Thanks a lot you genius! :)

**Comment by ramshankar29** [comment]
Hello,
I am based out of India. 
I almost tried all the options provided in the discussion forum. Changed the mirror and checked other options too. I am just wondering is it due to trying to install it from my office and the firewall is stopping however just wanted to make sure so posting only the relevant information below. please help. 
  
Warning in install.packages :
  cannot open URL 'https://rweb.crmda.ku.edu/cran/src/contrib/PACKAGES.gz': HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'https://bioconductor.org/packages/3.3/bioc/src/contrib/PACKAGES.gz': HTTP status was '407 Proxy Authentication Required
Warning in install.packages :
  unable to access index for repository https://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'https://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning in install.packages :
  cannot open URL 'https://R-Forge.R-project.org/src/contrib/PACKAGES.gz': HTTP status was '407 Proxy Authentication Required'
Warning in install.packages :
  cannot open URL 'https://R-Forge.R-project.org/src/contrib/PACKAGES': HTTP status was '407 Proxy Authentication Required'

**Comment by seankross** [comment]
@ramshankar29 Did you ever get this working from another internet connection?
