### ISSUE TITLE
Error with swirl

### ISSUE THREAD

**Issue by akshaynaik29** [swirldev/swirl#331]
After running installed.packages("swirl"), it displays the following error
Package LibPath Version Priority Depends Imports LinkingTo Suggests Enhances
     License License_is_FOSS License_restricts_use OS_type Archs MD5sum
     NeedsCompilation Built
>

**Comment by seankross** [comment]
Can you send a screenshot of this error?

**Comment by akshaynaik29** [comment]
![screenshot 368](https://cloud.githubusercontent.com/assets/12708236/9156505/10082fde-3efa-11e5-886b-e017fe484772.png)

**Comment by seankross** [comment]
Try the following:

```
install.packages("swirl")
library(swirl)
swirl()
```

**Comment by TimilehinEO** [comment]
Still did not install
![image](https://cloud.githubusercontent.com/assets/13628894/9588758/e9f0efc8-5021-11e5-80d8-7dc94a4bae2e.png)

**Comment by seankross** [comment]
You're using the function `installed.packages()` when you should be using the function `install.packages()`. Please see my comment above for the canonical method of installing swirl.

**Comment by TimilehinEO** [comment]
Thank You
