### ISSUE TITLE
Swirl is not working

### ISSUE THREAD

**Issue by ches0892** [swirldev/swirl#332]
Hi
I installed swirl but i received a warning message: 

| Hi! Type swirl() when you are ready to begin.
Warning message:
package ‘swirl’ was built under R version 3.1.3 

![image](https://cloud.githubusercontent.com/assets/11236874/9069412/afb7a136-3aae-11e5-86b7-f2e1866ea149.png)
But when i write 1, i does not goes to the next step. Any suggesstion?

**Comment by seankross** [comment]
What version of R do you have?

**Comment by ches0892** [comment]
I verified and have the latest version of R (3.1.3), because when i updated, i just had the option for updating for the beta version 3.2

**Comment by waynelu2015** [comment]
I have the same problem....nothing happened....!
Once I click ESC, it goest 1. try again 2.Send me to the course repository for manual installation.

I'm using win 8.......
Does anyone know what to do???  PLz

**Comment by seankross** [comment]
Try this:

Go to [this](https://github.com/swirldev/swirl_courses) page and download the zip file (download zip on the right). Then try:

```
library(swirl)
uninstall_all_courses()
install_course_zip("path/to/zip/file", multi = TRUE, which_course = "R Programming")
swirl()
```

**Comment by waynelu2015** [comment]
Thanks for helping me but still error.

> install_course_zip("~/Downloads/swirl_courses-master.zip", multi=TRUE,
which_course="R Programming")
Error in unzip(path, list = TRUE) :
  zip file 'C:/Users/YiLung/Documents/Downloads/swirl_courses-master.zip'
cannot be opened


Which I download the file to C:\Users\YiLung\Downloads  folder

**Comment by waynelu2015** [comment]
For additional info, I attach 2 screenshots.

Again, thanks for helping me!!

**Comment by seankross** [comment]
Try:

```r
install_course_zip("C:/Users/YiLung/Downloads/swirl_courses-master.zip", multi = TRUE, which_course = "R Programming")
```

**Comment by waynelu2015** [comment]
Thanks so much.

**Comment by seankross** [comment]
Is everything working now?

**Comment by waynelu2015** [comment]
yes, thanks so much.

But I dont know why I need to alter the path, since I used all default
option.
In addition, what is the default path for "~".

I keep thinking I had right path...

**Comment by seankross** [comment]
Whatever is the result of `normalizePath("~")` is equivalent to `"~"`.

**Comment by ches0892** [comment]
I've just solved the problem. I re-installed R and it is working. Actually. R is in the version 3.2.1 and not in the 3.1.3.  When i tried to update to the latest version since R, it just allowed me to update to the version 3.2.2 (beta version)

**Comment by seankross** [comment]
Wonderful! I'm closing this issue. Let me know if you have any other concerns.
