### ISSUE TITLE
Suggestion: Using other data set in swirl demo

### ISSUE THREAD

**Issue by hxd1011** [swirldev/swirl#335]
Hi, Everyone, first I would like to thank the efforts for making this awesome learning tool. I am an experienced R user but still learning a lot from it.

I reviewed the R programming course, *apply lessons. And I have suggestions about improving it. 

I think the flags data set may not be a very good one for demo, because many metrics may not make too much difference. For example, the "mean on flag color". 

I would suggest to use some data contain both discrete and continuous features. and the diamonds data in ggplot 2 is pretty good one.

**Comment by seankross** [comment]
Hi @hxd1011,

I see what you're saying, but this would require a significant re-write of the course. I would caution against the diamonds dataset. Swirl has users from all around the world, and variables like cut and clarity are not very relatable for [someone who has never seen a diamond before](https://youtu.be/nlcIKh6sBtc).

**Comment by hxd1011** [comment]
Thanks for the reply, and I agree with your point.
