### ISSUE TITLE
unable to install swirl

### ISSUE THREAD

**Issue by yu-wang** [swirldev/swirl#337]
I ran into the problem below, can anyone help me please?

* installing *source* package ‘curl’ ...
** package ‘curl’ successfully unpacked and MD5 sums checked
File curl.h not found. Make sure the curl development library is installed, e.g. libcurl4-openssl-dev (deb) or libcurl-devel (rpm).
ERROR: configuration failed for package ‘curl’
* removing ‘/home/yu/R/x86_64-pc-linux-gnu-library/3.0/curl’
Warning in install.packages :
  installation of package ‘curl’ had non-zero exit status
* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/home/yu/R/x86_64-pc-linux-gnu-library/3.0/RCurl’
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status
ERROR: dependency ‘curl’ is not available for package ‘httr’
* removing ‘/home/yu/R/x86_64-pc-linux-gnu-library/3.0/httr’
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies ‘testthat’, ‘httr’, ‘RCurl’ are not available for package ‘swirl’
* removing ‘/home/yu/R/x86_64-pc-linux-gnu-library/3.0/swirl’
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

**Comment by seankross** [comment]
Looks like you're using linux. Take a look at our installing swirl on linux
page: https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux

**Comment by yu-wang** [comment]
Thanks so much !! It works perfectly now !!:)

**Comment by xueping312** [comment]
R 3.1.2, Windows 10. I cannot install my swirl compleretly, can you help me? Thank you.
>install.packages("swirl")
also installing the dependency ‘RCurl’

试开URL’http://ftp.ctex.org/mirrors/CRAN/bin/windows/contrib/3.1/RCurl_1.95-4.7.zip'
Content type 'application/zip' length 2858866 bytes (2.7 Mb)
打开了URL
downloaded 2.5 Mb

试开URL’http://ftp.ctex.org/mirrors/CRAN/bin/windows/contrib/3.1/swirl_2.2.21.zip'
Content type 'application/zip' length 132216 bytes (129 Kb)
打开了URL
downloaded 129 Kb

错误于read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  无法打开链结
此外: 警告信息：
1: In download.file(url, destfile, method, mode = "wb", ...) :
  下载的长度2637952不等于报告的长度2858866
2: In unzip(zipname, exdir = dest) : 从zip文件中抽取1时出了错
3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  无法打开压缩文件'RCurl/DESCRIPTION'，可能是因为'No such file or directory'

**Comment by xueping312** [comment]
前一个问题，通过改变镜像解决了。

**Comment by seankross** [comment]
Try:

```r
install.packages("RCurl")
install.packages("swirl")
```

**Comment by shachisayata** [comment]
R 3.2.1, OS X 10.7.5, Cannot Install Swirl. It asks me to select a CRAN mirror as well, which one do I select?

![cran_mirro](https://cloud.githubusercontent.com/assets/15167300/10683060/0f5bf1f4-7903-11e5-82ca-9ddbbcce7242.jpg)
![swirl_error](https://cloud.githubusercontent.com/assets/15167300/10683059/0f59fe44-7903-11e5-8fa2-f048df69d637.jpg)

**Comment by seankross** [comment]
What is your geographic location?

**Comment by shachisayata** [comment]
Illinois

**Comment by seankross** [comment]
Try:

```r
install.packages("swirl", dependencies = TRUE, repos = "http://ftp.ussg.iu.edu/CRAN/")
```

**Comment by shachisayata** [comment]
still doesnt work

**Comment by shachisayata** [comment]
![swirl](https://cloud.githubusercontent.com/assets/15167300/10698195/6ce54696-7975-11e5-8d25-d75ecda8f64a.jpg)

**Comment by shachisayata** [comment]
![swirl1](https://cloud.githubusercontent.com/assets/15167300/10698243/abb681c8-7975-11e5-8e8a-14777674f576.jpg)

**Comment by seankross** [comment]
Can you download the latest version of R and then try this again?

**Comment by shr420** [comment]
install_from_swirl("R Programming") is taking a long time and its not showing any results

**Comment by seankross** [comment]
@shr420 see #387

**Comment by Takehashi** [comment]
I install swirl . > install.packages("swirl") 
Error : 
Warning: unable to access index for repository https://cran.cnr.berkeley.edu/src/contrib
Warning message:
package ‘swirl’ is not available (for R version 3.0.2)
.How can fix issue ?

**Comment by seankross** [comment]
@Takehashi You need to install the latest version of R.

**Comment by karrtikiyer** [comment]
On OSX 10.11.6 with R 3.3.1, I am get following error when I try to install swirl (install.packages("swirl")), seems to be some issue with RCurl, but unable to find a solution, please help.
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/Cellar/r/3.3.1_2/R.framework/Resources/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o RCurl.so base64.o curl.o curlInit.o curl_base64.o enums.o json.o memoryManagement.o myUTF8.o -lcurl -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm -F/usr/local/Cellar/r/3.3.1_2/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation
ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RCurl.so] Error 1
ERROR: compilation failed for package 'RCurl'
* removing '/Users/karrtik/Library/R/3.3/library/RCurl'

**Comment by seankross** [comment]
@karrtikiyer What happens when you try to install RCurl on its own with `install.packages("RCurl")`?

**Comment by igvbar** [comment]
Read Error message.
In my case it was:

> there is no package called ‘magrittr’ 

so:
`install.packages("magrittr")`

**Comment by terysetn** [comment]
Hi there,

I have a problem while trying to install swirl in R 3.4.3 in windows 10

The message reads:
Error in unzip(zipname, exdir = dest) : 
  cannot open file '\\CNAS.RU.NL/U758207/Documents/R/win-library/3.4/file28fc719

Anyone can help me on this?
Thank you!

**Comment by hebamuh68** [comment]
- I can't install swirl, i use latest version of R, and tried all solutions above and nothing worked!
- DISTRIB_ID=Ubuntu
- DISTRIB_RELEASE=20.04
- DISTRIB_CODENAME=focal

raised same error:

Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpiUr6wX/downloaded_packages’
