### ISSUE TITLE
My code is correct but swirl is asking to attempt more. #304

### ISSUE THREAD

**Issue by OdayaG** [swirldev/swirl#340]
I am stuck at Chapter 9 Function

My code is correct for calculating "remainder" i wrote "

remainder<- function(num,divisor=2){
num %% divisor
} 

but swirl is saying to try for more.I think this is correct.

i've already tried 20 times (perhaps i'm not saving the script correctly?)

help please??

thanks

**Comment by seankross** [comment]
Hi @OdayaG,

It looks like you're doing everything correctly. If you're still having trouble, I'd recommend exiting R and restarting the lesson. Make sure you have all open scripts closed. If this problem continues, you may have to remove and then re-install swirl.

**Comment by OdayaG** [comment]
hi Sean

thank you for the response. the problem is solved (apparently i didn't save
the script right)

thanks,
Odaya
