### ISSUE TITLE
unable to Install Swirl

### ISSUE THREAD

**Issue by TimilehinEO** [swirldev/swirl#341]
Trying to install swirl and its giving me a "Package LibPath Version Priority Depends Imports LinkingTo Suggests Enhances License
     License_is_FOSS License_restricts_use OS_type Archs MD5sum NeedsCompilation Built"
Snapshot is below 
Thanks 

![image](https://cloud.githubusercontent.com/assets/13628894/9588633/3e1693a6-5021-11e5-8f19-70f3cc296f81.png)

**Comment by moorejac** [comment]
Looks like you're using the function:**`installed.packages()`** which is used to [find (or retrieve) details of all packages installed in the specified libraries](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/installed.packages.html).

You need to use the function: **`install.packages()`**
|>`install.packages("swirl")`
