### ISSUE TITLE
Translate courses to other languages?

### ISSUE THREAD

**Issue by paternogbc** [swirldev/swirl#342]
Hi all,

thanks for developing such nice package! 

I wonder if you are thinking about translating swirl courses to other languages?

All the best,
Gustavo

**Comment by seankross** [comment]
Hi @paternogbc,

If you want to work on translating swirl, I suggest you start on individual courses: https://github.com/swirldev/swirl_courses

R Programming, Getting and Cleaning Data, Statistical Inference, and Exploratory Data Analysis are good places to start.

**Comment by paternogbc** [comment]
Hi @seankross ,

thanks for your reply. Yep.. I think this is the best. 
Could you please give me some guidelines because I am not so aware of the file structure.

1: Which files should I translate on each course folder?
2: Should I fork, make changes and then pull request?

Thanks in advance,
Gustavo Paterno

**Comment by seankross** [comment]
Translate the `lesson.yaml` files inside of each lesson directory. If I were you I would download our course repository as a zip, and then start your own repository with the translations.

**Comment by paternogbc** [comment]
Ok, thanks for that.

So the courses are independent of the source package, you think there is no problem with future releases of swirl in terms of consistance with the translated courses? The way swirl and the courses interact are stable over time?

Sorry to ask so many questions!

**Comment by seankross** [comment]
I certainly welcome these questions! Each folder in the swirl_courses repository is a course. Each course is completely independent. We will be adding new features to courses but they will forever be backwards compatible.

**Comment by paternogbc** [comment]
Ok that is great!

I will give a try on the course "R Programming" to see how it goes. 
Perhaps when I fully understand the struture of the courses and the functions used to create the lessons I can start developing new courses. 

thanks a lot!

**Comment by seankross** [comment]
Thank you!

**Comment by paternogbc** [comment]
Hi @seankross,

I have created a [repo](https://github.com/paternogbc/cursos_swirl-Br) to gather the brazilian community and start translating swirl courses to portuguese. We will start with the course __R Programming_Alt__, but the idea is to translate all swirl courses to portuguese.
 
I would like to ask permission to use the swirl logo to advertise this initiative. 
![](http://i.imgur.com/fNC9TLa.jpg)



Thanks in advance

**Comment by seankross** [comment]
This looks great! Do you mind if I write about this effort in a blog post?

**Comment by paternogbc** [comment]
Not at all!

cheers,
Gustavo

**Comment by paternogbc** [comment]
I have some questions on how to make the project more attractive to volunteers: how can we give credit to people engaged on translations? It is possible to add a Yaml field
Translator: xxx?

Any suggestion?

Thanks again!

**Comment by seankross** [comment]
Probably best to put it under author, so it would look like:

```
- Class: meta
  Course: R Programming
  Lesson: Logic
  Author: Sean Kross, Gustavo Paterno
  Type: Coursera
  Organization: swirlstats
  Version: 2.2.15
```

**Comment by paternogbc** [comment]
Great! I will also create a contributors page on the repo wiki. I think this is important to encourage people to colaborate. :smile: 

Cheers,

**Comment by paternogbc** [comment]
Hi @seankross,

At the moment I have one repository: [cursos_swirl-Br](https://github.com/paternogbc/cursos_swirl-Br) which will have different folders for each course translated (same structure from [swirl_courses](https://github.com/paternogbc/swirl_courses)). However, to install courses using `install_course_github` I need them to be independent repositories, correct? Thus:

    install_course_github("paternogbc/cursos_swirl-Br", "R_Programming_Alt") 

gives this error:

    Error in unzip(path, list = TRUE) : 
However, It would be great to keep all courses translated into a single repo. This would make a lot easier to organize all the volunteers, etc. Any advise on how to do that and ensure that installation from github could be used? 

Cheers

**Comment by seankross** [comment]
We're working on better ways to distribute courses right now. Currently there's no good solution for installing courses from a repository that contains multiple courses.

The best way this can be done now is for users to download the zip file for the repository, and then use `install_course_zip(file.choose(), multi = TRUE, which_course = "R_Programming_Alt")`.

**Comment by paternogbc** [comment]
no problem.
Thanks

**Comment by demidovakatya** [comment]
Hi Sean, do you know if these courses are being translated to Russian? And what is the best way to do it (should I make a repo with the same structure and start translating lesson by lesson)?

**Comment by seankross** [comment]
Hi @demidovakatya,

I do not believe anyone is currently translating swirl into Russian, though we would certainly appreciate your help! If I were you I would start with translating swirl's menus, you can find out more information about that here: https://github.com/swirldev/translations. As far as translating courses,
the best thing to do is to make a repository for each course, and then to translate each lesson. Here's a great example of how this has been done for a Spanish translation of R Programming: https://github.com/josersosa/Programando_en_R. Let me know if you have any other questions.

**Comment by demidovakatya** [comment]
@seankross I've [forked](https://github.com/demidovakatya/translations) this [repo](https://github.com/swirldev/translations) and going to add folders for Russian language. Would it work? :)

**Comment by seankross** [comment]
Yes, I would start with translating the `english.yaml` in the courses folder.

**Comment by demidovakatya** [comment]
Cool, thanks!

**Comment by demidovakatya** [comment]
On the other hand, I'm a little bit confused with the folders structure. Any advice or guidelines? :open_hands:

**Comment by seankross** [comment]
Hi @demidovakatya,

Here's a guide that should help you get started: https://github.com/swirldev/translations/wiki/Getting-Started

**Comment by demidovakatya** [comment]
@seankross awesome! Thanks for your time! :+1:
