### ISSUE TITLE
Adding limits to encouraging feedback ?

### ISSUE THREAD

**Issue by gomezismael** [swirldev/swirl#344]
Hello,
 
First of all, congratulations and a million thanks to all the developers and contributors to swirl. It's simply fantastic. The definitive tool to learn R. 

I just wanted to suggest to remove, at least partially, the encouraging messages (positive feedback) after a right answer. I admit the idea is nice in theory, but in practice it is relatively annoying, just a line you tend to skip. A simple "OK" without a line break (to focus directly on the following material) would work more fluently, IMHO. Maybe keeping the encouraging feedback for the very beginning then just "OKing" will be a nice balance; or make it become a user defined parameter, I don't know. Just a suggestion. 

Thank you again for such a wonderful tool !!
Best regards, 
Ismael

**Comment by ncarchedi** [comment]
More people seem to love it than hate it, so until that changes, we won't
change the default. However, you can set options(swirl_is_fun = FALSE) to
achieve the result you're looking for. Happy swirling, Nick

**Comment by gomezismael** [comment]
That's great ! Thank you so much for the quick response ! 
Best, 
Ismael
