### ISSUE TITLE
strptime parsing and locale in "R programming" module 14 "Dates and Times"

### ISSUE THREAD

**Issue by CHerSun** [swirldev/swirl#345]
Course "R programming" module 14 "Dates and Times"
It's suggested to parse string "October 17, 1986 08:24" with strptime function with format "%B %d, %Y %H:%M" and save that to t4 variable. Trying to do that sets t4 to list with 1 element NA on any non-english locale. Having found solution (by setting Sys.setlocale("LC_TIME","us")) I found t4 to be hard-locked to original value by swirl session. I was unable to remove t4 variable with rm function. And unable to progress further, as t4 had inappropriate value.
I suggest to modify course a bit to include saving original locale to variable, then switching locale to US or whichever is suitable to parsing. This will also highlight important date/time parsing issues to students.

Issue is similar to issue 201, but I propose different solution,

**Comment by seankross** [comment]
Hi @CHerSun,

We're working on a fix for this that will allow all locales to be compatible.

**Comment by CHerSun** [comment]
Thank you!
Still, introduction to locale could be awesome for beginners.
Should we close this issue?

**Comment by seankross** [comment]
Ooo, a lesson all about locale would be very interesting. I'm going to close this but that's a good idea for a course.
