### ISSUE TITLE
Missing package on Linux Mint 17.2 (libxml2-dev)

### ISSUE THREAD

**Issue by 3manuek** [swirldev/swirl#348]
I'm not sure if this goes here, but on the instructions on https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux , there is a missing package when executing the `apt-get install`. Should be:

```
apt-get install r-base-dev libxml2-dev
```
Also, before issue `install_from_swirl("Statistical Inference")` I ran:

```
options(download.file.method = "wininet")
```
More details [here](http://stackoverflow.com/questions/31293325/r-install-github-fails).

The library has the `xml2copy` command, used during the swirl installation.

**Comment by seankross** [comment]
I just added this to the docs, thanks.
