### ISSUE TITLE
Cannot Load "Swirl" R STUDIO Version 0.99.484 WINDOWS 

### ISSUE THREAD

**Issue by smyl4mi** [swirldev/swirl#349]
> install.packages("swirl")
Installing package into ‘C:/Users/Az Baako/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132236 bytes (129 KB)
downloaded 129 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Az Baako\AppData\Local\Temp\RtmpMnvq3o\downloaded_packages
 
> library(swirl)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’
> library("swirl")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’

I have tried so many solutions on the help page but is still not working.

**Comment by seankross** [comment]
Try:

```r
install.packages("stringi")
library(swirl)
swirl()
```

If that doesn't work, try:

```r
install.packages("swirl", dependencies = TRUE)
```

**Comment by smyl4mi** [comment]
Thank You seankross
install.packages("stringi") worked
