### ISSUE TITLE
swirl Explorartory Data Analysis and ggplot2 package

### ISSUE THREAD

**Issue by erisinis** [swirldev/swirl#350]
*** *Note: I am able to load the lesson after installing the munsell package independently, but the errors below still seem to warrant some attention. Also, just in case others have the same problem :)* ***

I have been trying to start the Exploratory Data Analysis course. When I select it, swirl asks to install ggplot2, which I already have installed - below is the result of running installed.packages():

![image](https://cloud.githubusercontent.com/assets/12780240/10182279/01b176dc-66e8-11e5-9fbf-6c7c1af33036.png)

Here is the error I get when I say "yes" to installing it (I tried before checking to see if I already had it):
![image](https://cloud.githubusercontent.com/assets/12780240/10182334/a101fa5e-66e8-11e5-960f-b4775c53b526.png)

And here is the error I get when I say "no" to installing it:
![image](https://cloud.githubusercontent.com/assets/12780240/10182354/dbbf40ac-66e8-11e5-8e25-2c266c21eac6.png)

**Comment by seankross** [comment]
Thanks for letting us know. Is everything working for you now though?

**Comment by erisinis** [comment]
Yes, thanks, installing the missing dependency allowed me to open and complete the lesson. Thanks for developing this tool btw, it's a very engaging and effective way to learn!

**Comment by seankross** [comment]
I'm happy you're enjoying it! Let me know if you have any other issues.
