### ISSUE TITLE
50% question at part 8 of Statistical Inference doesn't accept correct answer

### ISSUE THREAD

**Issue by gagin** [swirldev/swirl#351]
Here's what happens - it expects me to do 1-0.6 and doesn't accept correct answer

"  |=========================================================                                                         |  50%

| With the formula p'+/- qnorm(.975)*sqrt(p'(1-p')/100), use the p' and n values from above and the R construct
| p'+c(-1,1)... to handle the plus/minus portion of the formula. You should see bounds similar to the ones you just
| estimated.

> 0.6+c(-1,1)*qnorm(.975)*sqrt(0.6*(1-0.6)/100)
[1] 0.5039818 0.6960182

| Not quite right, but keep trying. Or, type info() for more options.

| Type .6 + c(-1,1)*qnorm(.975)*sqrt(.6*.4/100) at the command prompt.

> .6 + c(-1,1)*qnorm(.975)*sqrt(.6*.4/100)
[1] 0.5039818 0.6960182
| Your dedication is inspiring!

  |===========================================================                                                       |  51%"

**Comment by seankross** [comment]
Fixed in c5d3115f49ddbcc97791e698784d9e12c9f89a94
