### ISSUE TITLE
0 doesn't exit questions

### ISSUE THREAD

**Issue by gagin** [swirldev/swirl#355]
I'm trying to exit swirl, and it says "0 to exit", but doesn't really exit

![image](https://cloud.githubusercontent.com/assets/12004030/10229927/69be421c-682f-11e5-957e-8a34ec390645.png)

**Comment by seankross** [comment]
This has been fixed in the latest version of swirl, which is not yet on CRAN.

**Comment by benlindsay** [comment]
This just happened to me in 2018. Has this been fixed?
