### ISSUE TITLE
Regression Modeling, Multivariable Examples 3 at 86% no slop lines

### ISSUE THREAD

**Issue by joshmorel** [swirldev/swirl#356]
I'm running swirl in RStudio 0.98.1103 on R 3.1.3 64bit in Windows.

At 86% of Regression Modeling, Multivariable Examples 3 I am asked "which line has the steeper slope". There are no slope lines in the plot.

See Image
![image](https://cloud.githubusercontent.com/assets/10546720/10267703/c6a256f0-6a6c-11e5-80bc-7aad372f0afc.png)

**Comment by seankross** [comment]
What version of Windows are you using?

**Comment by guilucas2000** [comment]
I'm using Windows 10 at home, and windows 7 at work.

**Comment by seankross** [comment]
Does this error occur on both of your computers?

**Comment by guilucas2000** [comment]
I'm new using R, i don't know how to test this. I'm really sorry!

**Comment by seankross** [comment]
When this error occurred, were you using Windows 10 or Windows 7?

**Comment by kitjosh1050** [comment]
I was using Windows 7

**Comment by seankross** [comment]
In my test on Windows 7 the lines appear. Have you gone through this lesson since?
