### ISSUE TITLE
prettyNum error during swirl start

### ISSUE THREAD

**Issue by byblosjj** [swirldev/swirl#357]
Hi
I have a problem with starting swirl. At the very beginnig I got 
"Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  :
  8 arguments passed to .Internal(format) which requires 9"

> swirl()

>| Welcome to swirl!

>| Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself something
| unique.

>What shall I call you? John

>| Thanks, John. Let's cover a few quick housekeeping items before we begin our first lesson. First of all, you should know
| that when you see '...', that means you should press Enter when you are done reading and ready to continue.

>...  <-- That's your cue to press Enter to continue

>| Also, when you see 'ANSWER:', the R prompt (>), or when you are asked to select from a list, that means it's your turn
>| to enter a response, then press Enter to continue.

>Select 1, 2, or 3 and press Enter 
Error in prettyNum(.Internal(format(x, trim, digits, nsmall, width, 3L,  : 
  8 arguments passed to .Internal(format) which requires 9

>| Leaving swirl now. Type swirl() to resume.

Results of sessioninfo (Windows 10)

> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

>locale:
[1] LC_COLLATE=Polish_Poland.1250  LC_CTYPE=Polish_Poland.1250    LC_MONETARY=Polish_Poland.1250
[4] LC_NUMERIC=C                   LC_TIME=Polish_Poland.1250    

>attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

>other attached packages:
[1] swirl_2.2.21

>loaded via a namespace (and not attached):
 [1] httr_1.0.0      R6_2.1.1        magrittr_1.5    tools_3.2.0     RCurl_1.95-4.7  yaml_2.1.13     memoise_0.2.1  
 [8] crayon_1.3.1    stringi_0.5-5   stringr_1.0.0   digest_0.6.8    testthat_0.10.0 bitops_1.0-6

**Comment by seankross** [comment]
This might be a locale issue. Try:

```
Sys.setlocale(locale = "en_US.UTF-8")
library(swirl)
swirl()
```

**Comment by byblosjj** [comment]
Hi
This locale doesn't work on my machine

>Sys.setlocale(locale = 'en_US.UTF-8')
>[1] ""
>Warning message:
>In Sys.setlocale(locale = "en_US.UTF-8") :
  >OS reports request to set locale to "en_US.UTF-8" cannot be honored

I've set simple US locale

 >Sys.setlocale(locale = "US")
[1] "LC_COLLATE=English_United States.1252;LC_CTYPE=English_United States.1252;LC_MONETARY=English_United States.1252;LC_NUMERIC=C;LC_TIME=English_United States.1252"

I've still prettyNum error during swirl start

**Comment by seankross** [comment]
(I'm assuming you're in Poland)

Try:
```r
Sys.setlocale(locale = "pl_PL.UTF-8")
```

If that doesn't work, can you tell me what happens when you run the line of code below?
```r
select.list(c(1, 2, 3), title = "Pick an option", graphics = FALSE)
```

**Comment by byblosjj** [comment]
I'm from Poland :-)

Sys.setlocale(locale = "pl_PL.UTF-8") dosen't work.

**Comment by byblosjj** [comment]
I'm assuming that this something with R, not the Swirl. I've changed R version to 3.2.0 (64-bit) in global options and now Swirl works fine for me.

**Comment by seankross** [comment]
Oh okay great! This is an R issue and it's not something I've ever seen before. I'm glad you got it working. Do you mind if I close this issue?

**Comment by byblosjj** [comment]
Yes, thanks :)
