### ISSUE TITLE
Skip the directories which have prefix "." during installation of the course

### ISSUE THREAD

**Issue by wush978** [swirldev/swirl#358]
Dear maintainers,

I hope that the swirl does not copy the directory whose prefix is `.`, such as `.git` or `.svn`, to the course directory. Copying .git usually introduces lots of warning message and sometimes triggers an error during the installation. Moreover, I think a course name should not have prefix "." and a directory named with prefix `.` usually serves some purposes which is irrelevant to swirl. For example, `.git` and `.svn` are used by version control system, and we should not copy them to the course directory.

If you accept this feature request, I could send you a PR to resolve this. Please let me know whether you will accept this feature request or not.

Best,
Wush

**Comment by seankross** [comment]
Hi Wush,

The current version of swirl does copy files and directories with the `.` prefix, and we know this is a problem. Right now we're in the process of completely changing how swirl courses are shared. We're creating our own file type called `.swc` which packages a swirl course into a single file. We believe this will make sharing courses much easier. Using `.swc` files eliminates this issue of hidden files or folders getting into swirl courses that are distributed. This way swirl course authors will be able to use version control on their course but they will not distributed their `.git` or `.svn` histories with the courses. If you want a sneak peak at how this will work take a look at [this branch](https://github.com/swirldev/swirlify/tree/3.1) of swirlify. Specifically take a look at [pack.R](https://github.com/swirldev/swirlify/blob/3.1/R/pack.R).

Sean

**Comment by wush978** [comment]
I see. I'll take a look of them.
