### ISSUE TITLE
Not able to install swirl in R studio

### ISSUE THREAD

**Issue by DYLU1029** [swirldev/swirl#360]
> install.packages("swirl")
Warning in install.packages :
  InternetOpenUrl failed: 'The operation timed out'
Warning in install.packages :
  InternetOpenUrl failed: 'The operation timed out'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/src/contrib
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.2.2)
Warning in install.packages :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning in install.packages :
  InternetOpenUrl failed: 'The operation timed out'
Warning in install.packages :
  unable to access index for repository https://cran.rstudio.com/bin/windows/contrib/3.2
> > install.packages("swirl")
Error: unexpected '>' in ">"
> > library("swirl")
Error: unexpected '>' in ">"
> > swirl()
Error: unexpected '>' in ">"

**Comment by seankross** [comment]
Where are you geographically located?

**Comment by DYLU1029** [comment]
hi Seankross, It has been installed now. I am in China and after posted this I tried connecting with VPN and it worked out. Thanks.
