### ISSUE TITLE
Getting and Cleaning Data Activity 2: offer RStudio warning earlier

### ISSUE THREAD

**Issue by gitcub** [swirldev/swirl#361]
Hi swirl team, 
Thanks so much for the swirl courses - they are incredibly helpful! 

I just wanted to offer some feedback on the placement of the below warning, offered in Getting and Cleaning Data Course 2:
> Warning: The View() function may not work properly in every programming environment. We highly recommend the use of RStudio for the remainder of this lesson.

This warning doesn't occur until a student is 44% of the way through the lesson. 

When I tried to transfer my work from R to RStudio, none of the objects I had created in R were available in my RStudio environment and I had to start over. (I fully accept that this could be user error as I am new to R, but I also imagine that my general skill set is common with your target audience. I suspect I am not the only one who has had challenges here.)

I think it would be useful to students if you offered the warning upfront rather than surfacing the potential issue when the View() function is introduced. Perhaps you could slightly modify your message and offer it at the beginning of the lesson using something along the lines of:  
> Warning: This lesson uses functions that may not work properly in every programming environment.  We highly recommend the use of RStudio for the completion of this lesson.

I think this could save future learners the frustration of finishing half a lesson before being disrupted. 

Thank you again!
Rachel

**Comment by seankross** [comment]
Hi Rachel,

Thank you so much for this feedback. I completely agree with you and I will change this lesson so that the warning message is immediate. You didn't do anything wrong or make any errors, and you're absolutely right about being our exact target audience! Let me know if you have any other issues or suggestions.

Sean

**Comment by seankross** [comment]
Rachel I have a question: What happened when you tried to use `View()`?

**Comment by gitcub** [comment]
Awesome, thanks so much!

When I ran the lesson in R, I received the following error using the View() function:
>Error in check_for_XQuartz() : 
  X11 library is missing: install XQuartz from xquartz.macosforge.org

I'm running on a Mac with OS X Yosemite version 10.10.5 and R version 3.2.2.

**Comment by seankross** [comment]
Fixed in swirldev/swirl_courses@346d92c.
