### ISSUE TITLE
Simulation - replace=TRUE is correct while replace=T is not

### ISSUE THREAD

**Issue by clesiemo3** [swirldev/swirl#362]
When looking to assign the unfair coin flips scenario to the "flips" variable it considered replace=T to be incorrect while replace=TRUE to be correct. Is there something I'm missing or should swirl be a little more flexible on what is correct when T and TRUE are both valid syntax?

R console:

    > flips <- sample(c(0,1),100,replace=T,prob=c(0.3,0.7))
    
    | One more time. You can do it! Or, type info() for more options.
    
    | The following command will produce 100 flips of an unfair coin and assign the result: flips <- sample(c(0,1),
    | 100, replace = TRUE, prob = c(0.3, 0.7))
    
    > flips <- sample(c(0,1),100,replace=TRUE,prob=c(0.3,0.7))
    
    | You are really on a roll!

**Comment by seankross** [comment]
`TRUE` is better style than `T` so swirl encourages the use of `TRUE`.

**Comment by clesiemo3** [comment]
Good to know. Thanks for the quick reply!
