### ISSUE TITLE
Warning message for stringi when trying to install swirl

### ISSUE THREAD

**Issue by bundaaj** [swirldev/swirl#364]
I am on a Mac 10.7.5. When installing swirl I get the warning message:
"Warning in install.packages : 
Installation of package 'stringi' had non-zero exit status"

When I try to install strigi using install.packages("stringi") I receive the same warning message. 

Any thoughts?

**Comment by seankross** [comment]
Are there any other errors displayed? What version of R are you using?

**Comment by bundaaj** [comment]
I am using version 0.99.486. Attached are screen shots of RStudio.

Thank you,

Lexi

**Comment by seankross** [comment]
For some reason I can't see the attached image.

**Comment by bundaaj** [comment]
![screen shot 2015-11-02 at 12 09 50 pm](https://cloud.githubusercontent.com/assets/15217255/10889155/43b5ede8-815e-11e5-94df-2d5f507150f1.png)
![screen shot 2015-11-02 at 12 10 13 pm](https://cloud.githubusercontent.com/assets/15217255/10889156/43bf8768-815e-11e5-821f-225f6f1dd3ae.png)

**Comment by seankross** [comment]
What do you get as the result of `session_info()` ?

**Comment by bundaaj** [comment]
Here is the response I get:
Error: could not find function "session_info"

**Comment by seankross** [comment]
Once again for some reason I can't see the attachment.

**Comment by bundaaj** [comment]
![screen shot 2015-11-02 at 1 55 40 pm](https://cloud.githubusercontent.com/assets/15217255/10891041/b06b3186-8169-11e5-90ed-999b7e1571de.png)

**Comment by seankross** [comment]
Oh sorry my mistake, try:

```r
sessionInfo()
```

**Comment by bundaaj** [comment]
Okay, here's what I got:
![screen shot 2015-11-02 at 1 59 40 pm](https://cloud.githubusercontent.com/assets/15217255/10891155/516e0036-816a-11e5-9464-fb765019da14.png)

**Comment by seankross** [comment]
I hate to say this but it seems that the version of stringi that is required is not available for your operating system.

**Comment by bundaaj** [comment]
Thank you for your help. I will look into getting my OS upgraded and see if that fixes the problem. Will I need to un-install swirl prior to upgrading my OS?

**Comment by seankross** [comment]
When you upgrade your OS you should just reinstall swirl, no need to uninstall it.

**Comment by bundaaj** [comment]
Hi @seankross,
I updated my OS to El Capitan 10.11.1. I tried typing the command "install.packages("swirl") as well as install.packages("stringi") and received the same error messages as before. I also typed the command "sessionInfo()" and again received the same response as before. Any thoughts? See below.
![screen shot 2015-11-03 at 9 41 36 pm](https://cloud.githubusercontent.com/assets/15217255/10928134/d713b514-8273-11e5-857b-11a1aba9d06f.png)
![screen shot 2015-11-03 at 9 42 11 pm](https://cloud.githubusercontent.com/assets/15217255/10928135/d7156742-8273-11e5-8136-982022127fe1.png)

**Comment by seankross** [comment]
1. Download [this file](https://cran.r-project.org/bin/macosx/mavericks/contrib/3.2/stringi_1.0-1.tgz).
2. Run `install.packages(file.choose(), repos = NULL)` in your console and select the file you downloaded.

**Comment by bundaaj** [comment]
That worked! You have been very helpful, thank you very much!

**Comment by seankross** [comment]
Great! I'm sorry it was such a painful process.
