### ISSUE TITLE
Can not install swirl - no stringi package . R 3.2.1 Rstudio 0.99.386

### ISSUE THREAD

**Issue by ebastiano** [swirldev/swirl#365]
Hello I get the following problem while trying to install swirl. 
Need help please.

> library("swirl")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringi'
Error: package or namespace load failed for 'swirl'
> install.packages("stringi")

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  0.5-5  1.0-1             FALSE

installing the source package 'stringi'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  7 3557k    7  255k    0     0   332k      0  0:00:10 --:--:--  0:00:10  439k 21 3557k   21  751k    0     0   417k      0  0:00:08  0:00:01  0:00:07  465k 38 3557k   38 1359k    0     0   491k      0  0:00:07  0:00:02  0:00:05  526k 56 3557k   56 1999k    0     0   530k      0  0:00:06  0:00:03  0:00:03  558k 74 3557k   74 2655k    0     0   556k      0  0:00:06  0:00:04  0:00:02  579k 94 3557k   94 3359k    0     0   582k      0  0:00:06  0:00:05  0:00:01  620k100 3557k  100 3557k    0     0   589k      0  0:00:06  0:00:06 --:--:--  662k
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /Library/Frameworks/R.framework/Resources
checking for R... /Library/Frameworks/R.framework/Resources/bin/R
checking for R >= 3.1.0... yes
checking for cat... /bin/cat
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/private/var/folders/yV/yVGJIez+FtyMej8wQuondE+++TI/-Tmp-/Rtmpe0ueB3/R.INSTALL6296513b60c/stringi':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: configuration failed for package 'stringi'
* removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/stringi'
Warning in install.packages :
  installation of package 'stringi' had non-zero exit status

The downloaded source packages are in
	'/private/var/folders/yV/yVGJIez+FtyMej8wQuondE+++TI/-Tmp-/Rtmpqfno8E/downloaded_packages'
>

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by ebastiano** [comment]
Hi seankross. 
Thank you for picking up the subject :-)
the sessioninfo() result is below:
thanks! S.


R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.6.8 (Snow Leopard)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.1

**Comment by seankross** [comment]
Try the following:

```r
install.packages("stringi", type = "source")
```

**Comment by ebastiano** [comment]
Hi
looks like the result is the same (details below).
---------------
> install.packages("stringi", type = "source")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  2 3557k    2 81010    0     0  74525      0  0:00:48  0:00:01  0:00:47  112k 18 3557k   18  655k    0     0   319k      0  0:00:11  0:00:02  0:00:09  393k 41 3557k   41 1467k    0     0   481k      0  0:00:07  0:00:03  0:00:04  550k 66 3557k   66 2371k    0     0   585k      0  0:00:06  0:00:04  0:00:02  646k 90 3557k   90 3235k    0     0   640k      0  0:00:05  0:00:05 --:--:--  693k100 3557k  100 3557k    0     0   647k      0  0:00:05  0:00:05 --:--:--  789k
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
* installing *source* package 'stringi' ...
** package 'stringi' successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /Library/Frameworks/R.framework/Resources
checking for R... /Library/Frameworks/R.framework/Resources/bin/R
checking for R >= 3.1.0... yes
checking for cat... /bin/cat
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/private/var/folders/yV/yVGJIez+FtyMej8wQuondE+++TI/-Tmp-/RtmpV8sq1b/R.INSTALLdb179dc2cc/stringi':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: configuration failed for package 'stringi'
* removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/stringi'
Warning in install.packages :
  installation of package 'stringi' had non-zero exit status

The downloaded source packages are in
	'/private/var/folders/yV/yVGJIez+FtyMej8wQuondE+++TI/-Tmp-/RtmpB6tESg/downloaded_packages'

**Comment by seankross** [comment]
Hi @ebastiano,

I'm sorry to say this but your operating system is too old to support stringi. Perhaps you could build stringi from the source code if you installed Xcode, but it may make more sense to upgrade your OS or to use a different OS.

**Comment by ebastiano** [comment]
Hi Sean. Thank you for the advice. I will update to Mavericks and see if it helps.
Best regards
Sebastian

**Comment by ebastiano** [comment]
Hello again. I updated the MacOS to Mavericks, installed R 3.2.2. and tried to install swirl again. - it did not work  (Command line result below):
Any help would be very much appreciated.

Sebastian

> install.packages("swirl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 25  127k   25 32768    0     0  64967      0  0:00:02 --:--:--  0:00:02 64887100  127k  100  127k    0     0   155k      0 --:--:-- --:--:-- --:--:--  155k
tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/z8/_9_mngr13sz65_y_y77b9lmm0000gn/T//RtmpvmBKbZ/downloaded_packages
> library("swirl")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringi'
Error: package or namespace load failed for 'swirl'

**Comment by seankross** [comment]
Looks like this might a locale issue. What do you get as the result of `Sys.getlocale()`?

**Comment by seankross** [comment]
Also are you sure you upgraded to Mavericks or did you upgrade to El Capitan‎?

**Comment by ebastiano** [comment]
Hi Sean
Thank you for helping again. I updated to 10.9 Mavericks. I did install R 3.2.2 but did not reinstall Rstudio.
Here is the result of your question:
> Sys.getlocale()
[1] "C"

**Comment by seankross** [comment]
What do you get as the result of `"swirl" %in% installed.packages()[,1]`?

**Comment by ebastiano** [comment]
> "swirl" %in% installed.packages()[,1]
[1] TRUE

**Comment by seankross** [comment]
Have you tried `install.packages("stringi")` and then `install.packages("swirl")`?

**Comment by ebastiano** [comment]
> install.packages("stringi")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  1 12.1M    1  159k    0     0  83131      0  0:02:32  0:00:01  0:02:31 83113  3 12.1M    3  463k    0     0   155k      0  0:01:19  0:00:02  0:01:17  155k  6 12.1M    6  767k    0     0   191k      0  0:01:04  0:00:04  0:01:00  191k  7 12.1M    7  927k    0     0   194k      0  0:01:03  0:00:04  0:00:59  194k  9 12.1M    9 1199k    0     0   207k      0  0:00:59  0:00:05  0:00:54  253k 11 12.1M   11 1487k    0     0   216k      0  0:00:57  0:00:06  0:00:51  270k 13 12.1M   13 1711k    0     0   206k      0  0:00:59  0:00:08  0:00:51  236k 13 12.1M   13 1711k    0     0   184k      0  0:01:07  0:00:09  0:00:58  179k 13 12.1M   13 1727k    0     0   173k      0  0:01:11  0:00:09  0:01:02  154k 15 12.1M   15 1903k    0     0   177k      0  0:01:09  0:00:10  0:00:59  142k 17 12.1M   17 2191k    0     0   184k      0  0:01:07  0:00:11  0:00:56  140k 19 12.1M   19 2431k    0     0   191k      0  0:01:04  0:00:12  0:00:52  162k 23 12.1M   23 2895k    0     0   208k      0  0:00:59  0:00:13  0:00:46  255k 27 12.1M   27 3375k    0     0   229k      0  0:00:54  0:00:14  0:00:40  345k 31 12.1M   31 3919k    0     0   248k      0  0:00:49  0:00:15  0:00:34  397k 36 12.1M   36 4559k    0     0   268k      0  0:00:46  0:00:17  0:00:29  462k 39 12.1M   39 4927k    0     0   276k      0  0:00:44  0:00:17  0:00:27  487k 44 12.1M   44 5519k    0     0   295k      0  0:00:42  0:00:18  0:00:24  546k 48 12.1M   48 6031k    0     0   304k      0  0:00:40  0:00:19  0:00:21  524k 53 12.1M   53 6639k    0     0   317k      0  0:00:39  0:00:20  0:00:19  531k 58 12.1M   58 7215k    0     0   332k      0  0:00:37  0:00:21  0:00:16  565k 63 12.1M   63 7839k    0     0   345k      0  0:00:35  0:00:22  0:00:13  597k 66 12.1M   66 8287k    0     0   345k      0  0:00:35  0:00:23  0:00:12  525k 70 12.1M   70 8751k    0     0   352k      0  0:00:35  0:00:24  0:00:11  542k 76 12.1M   76 9471k    0     0   365k      0  0:00:33  0:00:25  0:00:08  568k 81 12.1M   81  9.8M    0     0   372k      0  0:00:33  0:00:27  0:00:06  536k 84 12.1M   84 10.2M    0     0   378k      0  0:00:32  0:00:27  0:00:05  527k 86 12.1M   86 10.4M    0     0   369k      0  0:00:33  0:00:28  0:00:05  484k 87 12.1M   87 10.5M    0     0   365k      0  0:00:33  0:00:29  0:00:04  426k 90 12.1M   90 10.9M    0     0   364k      0  0:00:34  0:00:30  0:00:04  353k 92 12.1M   92 11.2M    0     0   361k      0  0:00:34  0:00:31  0:00:03  296k 93 12.1M   93 11.3M    0     0   346k      0  0:00:35  0:00:33  0:00:02  192k 93 12.1M   93 11.3M    0     0   340k      0  0:00:36  0:00:33  0:00:03  173k 95 12.1M   95 11.6M    0     0   340k      0  0:00:36  0:00:34  0:00:02  199k 96 12.1M   96 11.7M    0     0   336k      0  0:00:36  0:00:35  0:00:01  163k 97 12.1M   97 11.8M    0     0   329k      0  0:00:37  0:00:36  0:00:01  130k100 12.1M  100 12.1M    0     0   332k      0  0:00:37  0:00:37 --:--:--  214k
tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/z8/_9_mngr13sz65_y_y77b9lmm0000gn/T//RtmpfC9xWe/downloaded_packages

**Comment by ebastiano** [comment]
> install.packages("swirl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0  0  130k    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0 24  130k   24 32768    0     0   8183      0  0:00:16  0:00:04  0:00:12  8183100  130k  100  130k    0     0  28452      0  0:00:04  0:00:04 --:--:-- 28453
tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/z8/_9_mngr13sz65_y_y77b9lmm0000gn/T//RtmpfC9xWe/downloaded_packages

**Comment by seankross** [comment]
Wow okay clearly the locale this the issue. Try this: `Sys.setlocale("LC_ALL","English")` and then try installing swirl.

**Comment by ebastiano** [comment]
> Sys.setlocale("LC_ALL","English")
[1] ""
Warning message:
In Sys.setlocale("LC_ALL", "English") :
  OS reports request to set locale to "English" cannot be honored

**Comment by seankross** [comment]
Where are you geographically located?

**Comment by ebastiano** [comment]
Sweden

**Comment by ebastiano** [comment]
The OS displays are in English

**Comment by seankross** [comment]
Try: `Sys.setlocale("sv_SE")`. And let me know if that can be "honored." :stuck_out_tongue_winking_eye:

**Comment by ebastiano** [comment]
Not really ;-)
> Sys.setlocale("sv_SE")
Error in Sys.setlocale("sv_SE") : invalid 'category' argument

**Comment by seankross** [comment]
What about: `Sys.setlocale("sv_SE.UTF-8")`?

**Comment by ebastiano** [comment]
> Sys.setlocale("sv_SE.UTF-8")
Error in Sys.setlocale("sv_SE.UTF-8") : invalid 'category' argument

**Comment by seankross** [comment]
Okay try this:

1. Download this: http://ftp.acc.umu.se/mirror/CRAN/bin/macosx/mavericks/contrib/3.2/stringi_1.0-1.tgz
2. Run `install.packages(file.choose(), repos=NULL)` in your console and select the file you downloaded.
3. Then try `install.packages("swirl")`.

**Comment by ebastiano** [comment]
Did not work well: (file was on desktop)
> install.packages(file.choose(), repos=NULL)
tar: Failed to set default locale

**Comment by ebastiano** [comment]
Could there be some remaining files from R 3.1 that the R 3.2 instal did not clean?

**Comment by seankross** [comment]
Okay time to take the gloves off. Try: 

```r
system("defaults write org.R-project.R force.LANG en_US.UTF-8")
```

I doubt this is a remaining files issue.

**Comment by ebastiano** [comment]
Just that line did not create a reply (There was no "stop" sign indicating ongoing process)
> system("defaults write org.R-project.R force.LANG en_US.UTF-8")
> install.packages("swirl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  130k  100  130k    0     0   121k      0  0:00:01  0:00:01 --:--:--  121k
tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/z8/_9_mngr13sz65_y_y77b9lmm0000gn/T//Rtmpc14Ovl/downloaded_packages

**Comment by ebastiano** [comment]
I really appreciate your help. I'm a true beginner trying to learn to use the Rstudio for statistics in biology. Waiting for suggestions...

**Comment by seankross** [comment]
Do you know your way around you computer's terminal? Even if you don't:

1. Press `command` + `spacebar`
2. Type: `terminal` and hit `enter`
3. Copy `defaults write org.R-project.R force.LANG en_US.UTF-8` and paste it into the terminal.
4. Hit enter and let me know what happens.

**Comment by ebastiano** [comment]
Not much: I got the same line that shows when I turn the terminal on: 
Sebastian-Lewandowskis-MacBook-2:~ sebastian$

**Comment by seankross** [comment]
Okay that's not bad! Now restart R completely and try: `install.packages("swirl")`.

**Comment by ebastiano** [comment]
I guess you meant the "RStudio". I do not have the R program on.
> install.packages("swirl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 84  130k   84  109k    0     0   174k      0 --:--:-- --:--:-- --:--:--  174k100  130k  100  130k    0     0   199k      0 --:--:-- --:--:-- --:--:--  199k

The downloaded binary packages are in
	/var/folders/z8/_9_mngr13sz65_y_y77b9lmm0000gn/T//Rtmpat8n10/downloaded_packages

**Comment by seankross** [comment]
So does `library(swirl);swirl()` work?

**Comment by ebastiano** [comment]
Something worked :-) :

library(swirl);swirl()

| Hi! Type swirl() when you are ready to begin.


| Welcome to swirl!

| Please sign in. If you've been here before, use the same name as you did then. If you are
| new, call yourself something unique.

What shall I call you?

**Comment by seankross** [comment]
Yay! Yeah you're in! Sorry this was such an arduous process!

**Comment by ebastiano** [comment]
THANK YOU! I wish I could do something in return. :-)

**Comment by seankross** [comment]
Are you a student? How did you find swirl?

**Comment by ebastiano** [comment]
I am a postdoc. I signed up for a R programming course on Coursera:
https://www.coursera.org/course/rprog
They asked to start using swirl.

**Comment by seankross** [comment]
Oh okay great! Enjoy the course! Whatever you're doing in your research is what you're doing in return!

**Comment by ebastiano** [comment]
Thank you. Have a great weekend :-) Cheers Sebastian

**Comment by rrdalmeida** [comment]
seankross, thank you so much for your help!

I had the same problem, but i didn't need to upgrade to mavericks. I followed your instructions and installed https://cran.r-project.org/bin/macosx/contrib/3.2/stringi_0.5-5.tgz, which seems to work fine with snow leopard.

**Comment by seankross** [comment]
@rrdalmeida sounds good! Let me know if there's anything I can help with.

**Comment by cdsjatin** [comment]
@seankross 
I had the same issue, thanks for the help. 👍

**Comment by LadyLazy-77** [comment]
@seankross Hi, I followed your suggestion and it worked!!! Thank you very much!!

**Comment by Poonu17** [comment]
I did face the same issue, I just uninstalled the Rstudio and reinstalled it again. Created a new directory. And while installing packages, It asked for a complied one, I selected for no, so it installed in the default path and no problem occured. It happened to me that installing the binary version created the problem locale issue
