### ISSUE TITLE
Unable to install swirl

### ISSUE THREAD

**Issue by tambekeffie** [swirldev/swirl#367]
I have tried multiple times to install swirl but failed. I am using windows. I am taking R programming now on Coursera. Please find my screen shot below:
![image](https://cloud.githubusercontent.com/assets/9359449/10988674/8a6552aa-840c-11e5-96f4-4a58debb4178.png)
The error says the library is not writable

**Comment by seankross** [comment]
Where are you geographically located? Also what do you get as the result of `sessionInfo()`?

**Comment by tambekeffie** [comment]
I am located in North Carolina, USA.  This is what I get when I enter sessionInfo():

![image](https://cloud.githubusercontent.com/assets/9359449/11014797/16de5d64-8514-11e5-8602-dd2c00fe39f5.png)

Thanks

**Comment by tambekeffie** [comment]
I live in North Caroina, USA . I get the message below when I enter sessionInfo():
sessionInfo()R version 3.2.2 (2015-08-14)Platform: i386-w64-mingw32/i386 (32-bit)Running under: Windows 8 x64 (build 9200)
locale:[1] LC_COLLATE=English_United States.1252 [2] LC_CTYPE=English_United States.1252   [3] LC_MONETARY=English_United States.1252[4] LC_NUMERIC=C                          [5] LC_TIME=English_United States.1252    
attached base packages:[1] stats     graphics  grDevices utils     datasets  methods   base     
loaded via a namespace (and not attached):[1] tools_3.2.2

Thanks

 


     On Friday, November 6, 2015 11:19 AM, Sean Kross <notifications@github.com> wrote:
   

 Where are you geographically located? Also what do you get as the result of sessionInfo()?—

**Comment by seankross** [comment]
Try the following:

```r
install.packages("swirl", repos = "http://archive.linux.duke.edu/cran/")
```

**Comment by tambekeffie** [comment]
Thanks, it worked. 


     On Monday, November 9, 2015 1:57 PM, Sean Kross <notifications@github.com> wrote:
   

 Try the following:install.packages("swirl", repos = "http://archive.linux.duke.edu/cran/")—

**Comment by seankross** [comment]
:+1:

**Comment by tambekeffie** [comment]
Hi Sean,I had an issue with the programming assignment. I saved my data in a folder called specdata. and extracted all the files from the folder. However, I have not been able to read the data into R. I was able to open 1 of the csv files and read it to R but was not able to read the entire folder (specdata) into R. Tried for 2 days but keep having the same error: cannot write, permission denied.I am the administrator of the computer and I have tried giving myself all kinds of privileges to be able to analyze the data in R to no avail. Please help.
Thanks

**Comment by seankross** [comment]
Hi @tambekeffie,

Which programming assignment are you trying to get the data for?

**Comment by tambekeffie** [comment]
r programming assignment 1. The air pollution data. The dead line for the assignment has passed because I could not resolve that problem.
Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 16, 2015 at 11:00 am, Sean Kross<notifications@github.com> wrote:   
Hi @tambekeffie,

Which programming assignment are you trying to get the data for?

**Comment by seankross** [comment]
Even though the deadline has passed do you still want help getting the data?

**Comment by tambekeffie** [comment]
Yes I do. I am planning on taking care of the assignment today after work if I can get access to the data. I will apply late days.
Thanks

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 16, 2015 at 11:14 am, Sean Kross<notifications@github.com> wrote:   
Even though the deadline has passed do you still want help getting the data?

**Comment by seankross** [comment]
What code were you using to read the data into R?

**Comment by tambekeffie** [comment]
read.csv.Is that what you are asking for?

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 16, 2015 at 11:30 am, Sean Kross<notifications@github.com> wrote:   
What code were you using to read the data into R?

**Comment by seankross** [comment]
How are you constructing the path to the csv files?

**Comment by tambekeffie** [comment]
read.csv ("paste path", header=TRUE)As I explained previously, when I do that on the folder which I named specdata, it gives me the permission denied error but I am able to read the CSV files independently. i.e I can read csv.001 or 002 etc but not the specdata contaiming all the csv files

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 16, 2015 at 11:54 am, Sean Kross<notifications@github.com> wrote:   How are you constructing the path to the csv files?

**Comment by seankross** [comment]
Try: `file.choose()` and select the CSV you're trying to read and make sure that the resulting string is the same as the string you're providing to `read.csv()`.

**Comment by tambekeffie** [comment]
Thanks,  will try that. I appreciate it.

Sent from Yahoo Mail on Android 
 
  On Mon, Nov 16, 2015 at 12:35 pm, Sean Kross<notifications@github.com> wrote:   
Try: file.choose() and select the CSV you're trying to read and make sure that the resulting string is the same as the string you're providing to read.csv().
