### ISSUE TITLE
Unable to install Swirl - OSX 10.11.1 in RStudio 3.2.1

### ISSUE THREAD

**Issue by lnross88** [swirldev/swirl#369]
I'm using OSx 10.11.1 and RStudio 3.2.1 and I am unable to install Swirl.  I used the command 

> install.packages("swirl", repos="http://cran.rstudio.com", dependences=TRUE)

Here's what I got in return:
> install.packages("swirl", repos="http://cran.rstudio.com", dependences=TRUE)
also installing the dependency ‘testthat’
  There is a binary version available but the source version is
  later:
         binary source needs_compilation
testthat 0.10.0 0.11.0              TRUE
Do you want to install from sources the package which needs compilation?
y/n: y
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (dependences = TRUE)
Warning in install.packages :
  download of package ‘swirl’ failed
installing the source package ‘testthat’

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (dependences = TRUE)
Warning in install.packages :
  download of package ‘testthat’ failed
> 

Thanks for any advice you can provide!

**Comment by seankross** [comment]
Try: 

```r
install.packages("testthat", source=TRUE)
```

**Comment by lnross88** [comment]
That didn't seem to solve the problem, here's what I got: 

> install.packages("swirl", repos="http://cran.rstudio.com", dependences=TRUE)
also installing the dependency ‘testthat’


  There is a binary version available but the source version is
  later:
         binary source needs_compilation
testthat 0.10.0 0.11.0              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (dependences = TRUE)
Warning in install.packages :
  download of package ‘swirl’ failed
installing the source package ‘testthat’

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (dependences = TRUE)
Warning in install.packages :
  download of package ‘testthat’ failed
> install.packages("testthat", source=TRUE)

  There is a binary version available but the source version is
  later:
         binary source needs_compilation
testthat 0.10.0 0.11.0              TRUE

Do you want to install from sources the package which needs compilation?
y/n: y
installing the source package ‘testthat’

Error in download.file(url, destfile, method, mode = "wb", ...) : 
  unused argument (source = TRUE)
Warning in install.packages :
  download of package ‘testthat’ failed

**Comment by seankross** [comment]
Try this:

1. Download [this](https://cran.r-project.org/bin/macosx/mavericks/contrib/3.2/testthat_0.11.0.tgz) file.
2. Run `install.packages(file.choose(), repos=NULL)` in your console and select the file you downloaded.
3. Then try `install.packages("swirl")`.

Please let me know whether or not that helps.

**Comment by lnross88** [comment]
I think it worked, this is what I got:
install.packages(file.choose(), repos=NULL)
> install.packages("swirl")
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100  127k  100  127k    0     0   109k      0  0:00:01  0:00:01 --:--:--  109k

The downloaded binary packages are in
	/var/folders/sb/0wjxmx5575x_pg4nj352j7d00000gn/T//RtmpsU9U1R/downloaded_packages
>

**Comment by seankross** [comment]
Try running:

```r
library(swirl)
swirl()
```

Then you'll be able to see if everything installed correctly.

**Comment by lnross88** [comment]
This is what I got, so it doesn't appear to have worked: 
> library(swirl)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’
> swirl()
Error: could not find function "swirl"
>

**Comment by seankross** [comment]
Now try this:

1. Download [this](https://cran.r-project.org/bin/macosx/mavericks/contrib/3.2/stringi_1.0-1.tgz) file.
2. Run `install.packages(file.choose(), repos=NULL)` in your console and select the file you downloaded.
3. Then try `library(swirl)`.

Again, please let me know whether or not that helps.

**Comment by bfujiyama** [comment]
Hello seankross, I am using Windows 7, 64 bit, R 3.2.2. I wonder if your solution applies to my system, as well.
I was able to install the package, but there were some errors moving files, which I did my best to correct after library(swirl) failed. I tried downloading your file and running the install line and selecting the file and received these errors:

> library(swirl)
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’
> install.packages(file.choose(),repos=NULL)
Installing package into ‘C:/Users/Fuji/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'

Please let me know if you have a solution or if I am posting in the wrong thread because I am using a different OS. I can include the install notes, if necessary. Thank you for your help

**Comment by seankross** [comment]
Hey, I'm glad everything got resolved! Let me know if you need further help.

**Comment by apetrides** [comment]
Hi 

I am having similiar problems.  What exactly was the solution here?  

I tried this from above and am continuing to get the error messages:
install.packages("swirl", repos="https://cran.revolutionanalytics.com/", dependencies=TRUE)
 There were problems installing RCurl and Crayon, so I used install.packages("RCurl") and "Crayon" and I could finally run Swirl.

**Comment by seankross** [comment]
Hi @apetrides,

I don't think that's a good `repos` argument to use. Where are you geographically located?

**Comment by karrtikiyer** [comment]
On OSX 10.11.6 with R 3.3.1, I am get following error when I try to install swirl (install.packages("swirl")), seems to be some issue with RCurl, but unable to find a solution, please help.
```
clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/usr/local/Cellar/r/3.3.1_2/R.framework/Resources/lib -L/usr/local/opt/gettext/lib -L/usr/local/opt/readline/lib -L/usr/local/opt/openssl/lib -L/usr/local/lib -o RCurl.so base64.o curl.o curlInit.o curl_base64.o enums.o json.o memoryManagement.o myUTF8.o -lcurl -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/lib -lxml2 -lz -lpthread -licucore -lm -F/usr/local/Cellar/r/3.3.1_2/R.framework/.. -framework R -lintl -Wl,-framework -Wl,CoreFoundation
ld: file not found: /usr/lib/system/libsystem_symptoms.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [RCurl.so] Error 1
ERROR: compilation failed for package 'RCurl'

    removing '/Users/karrtik/Library/R/3.3/library/RCurl'
```
