### ISSUE TITLE
I am not able to install Swirl

### ISSUE THREAD

**Issue by ncrnic** [swirldev/swirl#370]
1    2    3 
>  install.packages("swirl")
--- Please select a CRAN mirror for use in this session ---
Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/src/contrib
Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/bin/windows/contrib/3.2
Warning message:
package ‘swirl’ is not available (for R version 3.2.2)

This is What I get when I try to install it.  I am using R 64 bit

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by kavaliro** [comment]
> install.packages("swirl")
    Installing package into ‘C:/Users/gilmorej/Documents/R/win-library/3.2’
    (as ‘lib’ is unspecified)
    Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/src/contrib
    Warning: unable to access index for repository https://cran.cnr.Berkeley.edu/bin/windows/contrib/3.2
    Warning message:
    package ‘swirl’ is not available (for R version 3.2.2) 
    > sessionInfo()
    R version 3.2.2 (2015-08-14)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    Running under: Windows 8 x64 (build 9200)

    locale:
    [1] LC_COLLATE=English_United States.1252 
    [2] LC_CTYPE=English_United States.1252   
    [3] LC_MONETARY=English_United States.1252
    [4] LC_NUMERIC=C                          
    [5] LC_TIME=English_United States.1252    

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     

    loaded via a namespace (and not attached):
    [1] tools_3.2.2

**Comment by seankross** [comment]
Hi @kavaliro,

Try: `install.packages('swirl', dependencies=TRUE, repos='http://cran.rstudio.com/')`

**Comment by kavaliro** [comment]
That worked, thank you!

**Comment by seankross** [comment]
No problem. I'm going to close this issue. @ncrnic if you're still having issues let me know and I'll reopen this issue.
