### ISSUE TITLE
ggplot2 loading issues

### ISSUE THREAD

**Issue by teotubi** [swirldev/swirl#371]
Hi everyone, 
when I try to call library("ggplot2") I get this error 

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  object 'vI' not found
Error: package or namespace load failed for ‘ggplot2’

I checked libPaths(), they are ok - I rerun the code with the .lib.loc dependency but the result is the same.
I installed ggplot2 with the dependecies command but nothing changes.
I re-installed RStudio at the latest version with R 3.2.2 - always the same output.

Can you help me? I cannot even really understand what the problem is.

**Comment by seankross** [comment]
Try reinstalling ggplot2:

```r
install.packages("ggplot2", dependencies=TRUE)
```

**Comment by teotubi** [comment]
thanks for the answer,
however I already tried this.

As you can see from the error message, it does not claim the lack of any specific package ggplot2 is dependent on. However, I do not understand what the error means.

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by teotubi** [comment]
this is the sessionInfo() output

R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252   
[3] LC_MONETARY=Italian_Italy.1252 LC_NUMERIC=C                  
[5] LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] plyr_1.8.3   tools_3.2.2  gtable_0.1.2 Rcpp_0.12.2  grid_3.2.2   digest_0.6.8 proto_0.3-10


thank for the time you dedicate me

**Comment by seankross** [comment]
Try this and let me know if it helps:

```r
update.packages(checkBuilt=TRUE)
```
