### ISSUE TITLE
Can Swirl be installed on my system, or am I doing something wrong?

### ISSUE THREAD

**Issue by LargoTerranova** [swirldev/swirl#373]
Hello Guys,

I'm a student from Germany, and I was offered a Job if I would learn to program in R. After some research I figured the fastest way to approach this was by using Swirl. However, for some reason I cannot install it. I saw that there are a couple people around here who had the same Problem, so I followed the instructions which were already given. No success :( I use the following setup: 

Mac OSX 10.9.5
R: 3.2.1
RStudio: 0.99.489

I tried a couple of things and included the code below. Can anyone make something out of this? Is swirl even working with my OS Version???

I greatly appreciate any help and send you my best :)

Largo

After I type in:	install.packages("swirl")	I get the following message:
-------

Installing package into ‘/Users/Largo/Library/R/3.2/library’
(as ‘lib’ is unspecified)
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 47  127k   47 61645    0     0   383k      0 --:--:-- --:--:-- --:--:--  481k100  127k  100  127k    0     0   543k      0 --:--:-- --:--:-- --:--:--  630k

The downloaded binary packages are in
	/var/folders/kt/x9dd8qrx4mq3qvd6j2pxxll40000gp/T//Rtmp4SAZB7/downloaded_packages

Then I type:	library(swirl) and I get
------

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : there is no package called ‘stringi’ Error: package or namespace load failed for ‘swirl’

When I try to install stringy I type: install.packages("stringi") and I get
-------

Installing package into ‘/Users/Largo/Library/R/3.2/library’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
        binary source needs_compilation
stringi  0.5-5  1.0-1             FALSE

installing the source package ‘stringi’

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0 12 3557k   12  458k    0     0   450k      0  0:00:07  0:00:01  0:00:06  749k 37 3557k   37 1325k    0     0   656k      0  0:00:05  0:00:02  0:00:03  822k 61 3557k   61 2192k    0     0   726k      0  0:00:04  0:00:03  0:00:01  839k 86 3557k   86 3059k    0     0   761k      0  0:00:04  0:00:04 --:--:--  847k100 3557k  100 3557k    0     0   774k      0  0:00:04  0:00:04 --:--:--  850k
* installing *source* package ‘stringi’ ...
** package ‘stringi’ successfully unpacked and MD5 sums checked
checking for local ICUDT_DIR... icu55/data
checking for R_HOME... /Library/Frameworks/R.framework/Resources
checking for R... /Library/Frameworks/R.framework/Resources/bin/R
checking for R >= 3.1.0... yes
checking for cat... /bin/cat
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 151: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 152: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 153: make: command not found
/Library/Frameworks/R.framework/Resources/bin/config: line 269: make: command not found
checking for gcc... no
checking for cc... no
checking for cl.exe... no
configure: error: in `/private/var/folders/kt/x9dd8qrx4mq3qvd6j2pxxll40000gp/T/RtmpDiGd7O/R.INSTALL13c821bfa290/stringi':
configure: error: no acceptable C compiler found in $PATH
See `config.log' for more details
ERROR: configuration failed for package ‘stringi’
* removing ‘/Users/Largo/Library/R/3.2/library/stringi’
Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/kt/x9dd8qrx4mq3qvd6j2pxxll40000gp/T/Rtmp4SAZB7/downloaded_packages’

When I type in		sessionInfo()	I get:
---------

R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.8.5 (Mountain Lion)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.1    RCurl_1.95-4.7 digest_0.6.8   bitops_1.0-6

**Comment by seankross** [comment]
Try the following:

1. Download [this](https://cran.r-project.org/bin/macosx/mavericks/contrib/3.2/stringi_1.0-1.tgz) file.
2. Run `install.packages(file.choose(), repos = NULL)` and select the file you downloaded.
3. Then run `library(swirl);swirl()`

Please let me know if that works out.

**Comment by LargoTerranova** [comment]
Hey,

Thanks for the super fast answer :) I followed your instructions, and it did not work. I got the following replies:

install.packages(file.choose(), repos = NULL)
Installing package into ‘/Users/Largo/Library/R/3.2/library’
(as ‘lib’ is unspecified)
Error in install.packages : type == "both" cannot be used with 'repos = NULL'

> library(swirl);swirl()
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
That's unusual, try:

`install.packages(file.choose(), repos = NULL, type="binary")`

with the same instructions as I wrote before.

**Comment by LargoTerranova** [comment]
I tried with no success. A window pops up, I select the file I downloaded (string_1.0-1.tar) press enter and this happens:

> install.packages(file.choose(), repos = NULL, type="binary")
Installing package into ‘/Users/Largo/Library/R/3.2/library’
(as ‘lib’ is unspecified)
> library(swirl);swirl()
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so':
  dlopen(/Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so, 6): Symbol not found: ___exp10
  Referenced from: /Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so
Error: package or namespace load failed for ‘swirl’
>

**Comment by seankross** [comment]
What do you get as the result of `.libPaths()`?

**Comment by LargoTerranova** [comment]
I get the following:

[1] "/Users/Largo/Library/R/3.2/library"                            
[2] "/Library/Frameworks/R.framework/Versions/3.2/Resources/library"

**Comment by seankross** [comment]
Try:

`install.packages(file.choose(), repos = NULL, type="binary", lib = .libPaths()[2])`

**Comment by LargoTerranova** [comment]
The Program asks a question. How do I answer? Yes or No?

> install.packages(file.choose(), repos = NULL, type="binary", lib = .libPaths()[2])
Warning in install.packages :
  'lib = "/Library/Frameworks/R.framework/Versions/3.2/Resources/library"' is not writable

Would you like to use a personal library instead?  (y/n)

**Comment by seankross** [comment]
Intersting, try:

```r
install.packages(file.choose(), repos = NULL, type="binary", lib = .libPaths()[1])
```

Are you on a work computer?

**Comment by LargoTerranova** [comment]
No, its my personal Mac. I have full administration rights. But I'm using a standard user account for daily work. When I type in the above code, the file-select window pops up, I select the file, and then nothing happens. Just a new arrow appears...

**Comment by seankross** [comment]
Do you still get the same error after running `library(swirl)` ?

**Comment by LargoTerranova** [comment]
I still get an error, but it looks very different than before (post1):

Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so':
  dlopen(/Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so, 6): Symbol not found: ___exp10
  Referenced from: /Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/Largo/Library/R/3.2/library/stringi/libs/stringi.so
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
I was trying to avoid having you install make and gcc, but there doesn't appear to be a good way around it. Here's is a sane-looking guide for installing make and gcc on your Mac: http://stackoverflow.com/questions/10265742/how-to-install-make-and-gcc-on-a-mac

After installation you should restart and try `install.packages("stringi")`. Sorry this has been such a pain.

**Comment by LargoTerranova** [comment]
No Problem! I will try it and write how it worked out! Thanks for your help so far. I appreciate it!

**Comment by LargoTerranova** [comment]
Ok. I tried following the instructions, but as far as I can tell, it had no effect. I googled a bit, and someone suggested in another post to install the "apple command line interface", whatever that is. in order to make "make" work. I installed it from the apple developer homepage, and then typed

install.packages("stingi")

It took forever and i saw hundreds of millions of lines of code passing by, but after it was over, i tried:

install.packages("swirl")
library(swirl)

and now it looks like this:

> library(swirl)
| Hi! Type swirl() when you are ready to begin.
> swirl()
| Welcome to swirl!
| Please sign in. If you've been here before, use the same name as you did then. If
| you are new, call yourself something unique.
What shall I call you? 


I presume, I succeeded? I'm still suspicious though, since I have no clue what exactly I did there…!?

**Comment by seankross** [comment]
You did everything right! It looks like you're in! Let me know if you have other questions. I'm going to close this issue but you can still continue commenting on it and I'll respond.

**Comment by LargoTerranova** [comment]
Hey, so far it is working nicely! I can install packages and answer questions. Thanks for helping me. I appreciate it :) Peace
