### ISSUE TITLE
Swirl says my scripts are wrong, but they're not

### ISSUE THREAD

**Issue by JasperL93** [swirldev/swirl#374]
Hi, for the Coursera course "Getting and cleaning data", I'm currently
doing the Swirl assignment "Grouping and Chaining with dplyr".

Everything went okay, until I had to fill out the scripts.
Although I fill them out correctly and submit() them, I get the message they're wrong.
I had no other option than to use skip() and then I get the correct script, which is 
identical to the one I submitted but was said to be incorrect.
(the chain.r scripts)

Problem is if I skip more than once I don't get the grade for the assigment.

What should I do with this?

**Comment by seankross** [comment]
Are you sure you're saving your scripts before you `submit()` them?

**Comment by danielmedbar** [comment]
The exact same thing just happened to me, and i was saving the script before submitting it. I also had to skip this exercise.
Could it be that functions of some other libraries are masking the n() function of dplyr? I had a lot of them working in my current session.

**Comment by seankross** [comment]
@danielmedbar did you try restarting your r session and swirl?
