### ISSUE TITLE
Problem loading SWIRL

### ISSUE THREAD

**Issue by spikethescope** [swirldev/swirl#375]
OS: WIn 7, Problem loading package. During install all dependencies were installed too. RCurl also installed properly.
![swirlerror](https://cloud.githubusercontent.com/assets/15625936/11678555/16a61674-9e6f-11e5-8e0e-d9756af5b3ff.jpg)

**Comment by seankross** [comment]
What do you get as a result of `library(RCurl)` ?

**Comment by spikethescope** [comment]
Thanks Sean, I reinstalled RCurl and it works now.

**Comment by seankross** [comment]
Great, let me know if you run into any other issues.
