### ISSUE TITLE
Swirl to Ubuntu: doesn't go

### ISSUE THREAD

**Issue by Corsika** [swirldev/swirl#378]
I'm trying to install swirl (install.packages("swirl") via R (and RStudio as well), but all the time the same warning comes:

ERROR: dependency ‘testthat’ is not available for package ‘swirl’
* removing ‘/home/anastasia/R/x86_64-pc-linux-gnu-library/3.0/swirl’

Скачанные исходники пакетов находятся в
	‘/tmp/RtmpgXFFoE/downloaded_packages’
Предупреждение
In install.packages("swirl", dependencies = TRUE) :
  установка пакета ‘swirl’ имеет ненулевой статус выхода

How to eliminate this trouble?
Thank you in advance for your answer

**Comment by seankross** [comment]
Hi, what happens you try `install.packages("testthat")` ? Also what do you get as the result of `sessionInfo()` ?

**Comment by Corsika** [comment]
Hi, thank you for your interest in my trouble).
So, here below is the result of my next attemt to install swirl

> install.packages("swirl")
Installing package into ‘/home/anastasia/R/x86_64-pc-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
--- Please, choose the mirror CRAN for the session ---
Warning: dependency ‘testthat’ is not available                                        
trying URL 'http://cran.rstudio.com/src/contrib/swirl_2.2.21.tar.gz'                        
Content type 'application/x-gzip' length 51037 bytes (49 Kb)
opening URL
==================================================
downloaded 49 Kb

ERROR: dependency ‘testthat’ is not available for package ‘swirl’
* removing ‘/home/anastasia/R/x86_64-pc-linux-gnu-library/3.0/swirl’

Downloaded packages are in 
	‘/tmp/Rtmpgdhgie/downloaded_packages’
Warning
In install.packages("swirl") :
  package installation ‘swirl’ has non-zero exit status

**Comment by Corsika** [comment]
sessionInfo()
R version 3.0.2 (2013-09-25)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=ru_RU.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=ru_RU.UTF-8        LC_COLLATE=ru_RU.UTF-8    
 [5] LC_MONETARY=ru_RU.UTF-8    LC_MESSAGES=ru_RU.UTF-8   
 [7] LC_PAPER=ru_RU.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=ru_RU.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tcltk_3.0.2 tools_3.0.2

**Comment by seankross** [comment]
Try the following:

```r
install.packages("testthat", repos = "https://cran.gis-lab.info/")
```

**Comment by Corsika** [comment]
> install.packages("testthat", repos="https://cran.gis-lab.info/")
Installing package into ‘/home/anastasia/R/x86_64-pc-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
Warning: index  is not available for storage https://cran.gis-lab.info/src/contrib
Warning
package ‘testthat’ is not available (for R version 3.0.2)

**Comment by seankross** [comment]
It looks like you need to upgrade your version of R. You can find instructions for doing this here: http://stackoverflow.com/questions/10476713/how-to-upgrade-r-in-ubuntu

**Comment by Corsika** [comment]
Thank you for the hint)). Now all works!

**Comment by seankross** [comment]
Good to hear! Let me know if you have any other questions.

**Comment by Corsika** [comment]
OK! Thank you once more)!
