### ISSUE TITLE
Swirl not updating grade on assignment page

### ISSUE THREAD

**Issue by Daniellehiggins** [swirldev/swirl#379]
I'm trying to complete Week 4 Swirl Programming Assignment in R(rprog-035) and at the end of the course it asks me to submit my email address and submission token (in R). I assumed the submission token was the 'submission password' given at the top of the assignment page. After submitting the password, it said "You Got it" and continued into another course but when i checked the assignment page, no grade was updated. 

So i did the "Basic Building Blocks" course again and submitted the same password and still no updated grade on site. I even tried doing another course, same result, no update on grades site.

Kindly let me know what i did wrong. Deadline is tomorrow.

**Comment by skmamidi** [comment]
I am having the exact same issue as @Daniellehiggins, any help on the subject is appreciated!

**Comment by seankross** [comment]
You need to reinstall the course and complete the lesson again. Sorry about this. The courses were prematurely updated, but the changes have been reversed.

**Comment by skmamidi** [comment]
thank you for confirming @seankross 
I followed the manual instructions mentioned at this [link](https://class.coursera.org/rprog-035/forum/thread?thread_id=515), and that has helped.

I am able to submit the assignments again!
