### ISSUE TITLE
Unable to Install Swirl!

### ISSUE THREAD

**Issue by ShaliniSureshKumar** [swirldev/swirl#381]
I am using R-3.2.3 on Windows 10. I am getting errors while trying to install Swirl.
1a) The first error I got was same as issue #314 ,
Warning in install.packages :
'lib = "C:/Program Files/R Programming/R/R-3.2.0/library"' is not writable
Error in install.packages : unable to install packages 
Solution was not clear to me, so I reinstalled R into a folder location where I would have the rights to download(C folder)
1b)I got this error: It asked me to choose CRAN mirror, so I used 
install.packages("swirl", dependencies = TRUE, repos = "http://ftp.ussg.iu.edu/CRAN/")
Following which I got this message:
package ‘swirl’ successfully unpacked and MD5 sums checked

2)However when I use library(swirl), I get the following error: 
Error : .onLoad failed in loadNamespace() for 'crayon', details:
  call: loadNamespace(name)
  error: there is no package called ‘memoise’
Error: package or namespace load failed for ‘swirl’

I am unsure what the issue is. Please help!

**Comment by seankross** [comment]
Try restarting R, then try:

```r
install.packages("crayon", dependencies = TRUE, repos = "http://ftp.ussg.iu.edu/CRAN/")
library(swirl)
```

**Comment by ShaliniSureshKumar** [comment]
That worked! Thank you.
