### ISSUE TITLE
Dependency Error about digest()

### ISSUE THREAD

**Issue by hcheruku** [swirldev/swirl#385]
Hi Team:

I am new to R.
After installing R, when I did library("swirl"), I get error:
there is no package called ‘digest’ Error: package or namespace load failed for ‘swirl’

I tried installing digest by doing install.packages("digest")
I still get the same message.

~ Thanks

**Comment by seankross** [comment]
Try running `install.packages("swirl", dependencies = TRUE)`. When you ran `install.packages("digest")` did it install normally?

**Comment by hcheruku** [comment]
install.packages("swirl", dependencies = TRUE) worked!
Thank you

Yes, it installed fine. but not sure why I was getting that message. The digest folder was in R library too.

But yeah, its working now !

**Comment by seankross** [comment]
Good to hear!

**Comment by mattiapdo** [comment]
Thank you @seankross ! This worked also for me!
Could you explain why did you give that suggestion?
