### ISSUE TITLE
Problem in submitting swirl assignment

### ISSUE THREAD

**Issue by deepamgp** [swirldev/swirl#386]
After completing the first assignment and entering my credentials I received the following error message

Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL connect error
What should I do in this situation

**Comment by seankross** [comment]
Is there anything unusual about how you're accessing the internet? For example are you using a proxy to connect?

**Comment by deepamgp** [comment]
Yes, I am using a proxy

**Comment by seankross** [comment]
Did you resolve this problem in changing the settings you discussed in #387?

**Comment by deepamgp** [comment]
Sir the problem was not resolved.  Now it is showing, 
Error in curl::curl_fetch_memory(url, handle = handle) : 
  SSL peer certificate or SSH remote key was not OK

**Comment by seankross** [comment]
Hi @deepamgp,

Are you only able to connect to the internet through a proxy?

**Comment by deepamgp** [comment]
Yes sir. only through a proxy

**Comment by seankross** [comment]
Hi @deepamgp,

I'm working on a workaround right now to allow users to manually submit assignments. Sorry about this inconvenience.

**Comment by Loricrio** [comment]
I am also having trouble submitting. RStudio is still asking me for a Course ID when I thought I had read that we were no longer using a Course ID. I gave my email and my unique password.

**Comment by seankross** [comment]
Hi @Loricrio,

You may need to re-download the swirl course so that you have the latest version.

Sean

**Comment by manishareddy23** [comment]
hi sean,

Can you tell me how to submit it manually.
I am unable to submit it thru R-Studio as well. I get the same issue

**Comment by seankross** [comment]
Hi @manishareddy23,

Right now there is no way to submit manually, though we are working on a solution.

Sean

**Comment by sinbad20in** [comment]
I am unable to submit the assignment either. I have the latest version of swirl and there is no proxy on my system but still I get the error that it is unable to establish connection

**Comment by DanKHansen** [comment]
Hi, just completed the first swirl assignment (week 1) and as Loricrio mentioned, I had no assignment Token available for me ... using latest version of RStudio, R and swirl.

**Comment by sinbad20in** [comment]
Hi, I was running the latest version... but for some reason it worked when i reopened R studio and reinstalled the swirl package.
Thanks,

**Comment by DanKHansen** [comment]
Reinstalled everything, but I still haven't got any token for the excersize so I can't get credits:

![nyt bitmapbillede](https://cloud.githubusercontent.com/assets/16195962/12724350/d8367e6e-c90d-11e5-9404-e51435a72187.jpg)

**Comment by seankross** [comment]
@DanKHansen see: https://github.com/swirldev/swirl/wiki/Coursera-FAQ

**Comment by Anu7** [comment]
I can't submit my swirl assignments because there is no token given. I even checked the link provided by Sean Kross but still there are no tokens.

**Comment by seankross** [comment]
@Anu7 can you send me a screenshot of the token not showing up where it should? If there's an actual problem with Coursera I'll see that it's fixed. Send the screenshot to info@swirlstats.com too.

**Comment by DanKHansen** [comment]
Hi All. Well the issue is, that there ARE no tokens in week 1, as it is really not an assignment. The Toekns are there in Week 3 and 4, where the assignments are. And they corresponds to the menus in swirl as well. In week 1 it is merely an excersize of installing the swirl lessons, not actually doing the tasks. All tokens are available in assignments in week 3 and 4. Hope that clears up everything :-)

**Comment by cybersan** [comment]
Hi all,

Actually there is a token. Refer the screenshot. Follow the instruction at https://github.com/swirldev/swirl/wiki/Coursera-FAQ as given by @seankross 
![token](https://cloud.githubusercontent.com/assets/10301277/13033840/9f4bc5d0-d35f-11e5-98e3-466d93a1e1c1.png)

**Comment by rajamaniv** [comment]
I am also accessing through proxy and I am unable to submit my Swirl assignments :-(

**Comment by cybersan** [comment]
Hi Raja,

Send me the screenshot, see if i can assist you.
Thx

**Comment by rajamaniv** [comment]
Hi,

Please find attached the screen shot.

Thanks
Raja

**Comment by rajamaniv** [comment]
Hi,

I am able to submit from home laptop, the problem arises when I try to
submit from work laptop. Since, I use them interchangeably, it would be
great if I can submit from both of them.

Thanks
Raja

**Comment by dianaavram** [comment]
Hi,

Same problem like the other course participants. Since I'm able to use the time at work to do the course it would be nice to have a function that asks for the proxy settings.

Thnaks,
Diana

**Comment by seankross** [comment]
@dianaavram 

Try the following before using swirl:

```r
opts <- list(
  proxy         = "http://****",
  proxyusername = "****", 
  proxypassword = "*****", 
  proxyport     = ****
)

options(RCurlOptions = opts)
```

From: http://stackoverflow.com/questions/25120043/rcurl-default-proxy-settings

**Comment by dianaavram** [comment]
@seankross 

Thank you for the answer.
I've tried the following with  no success:

`opts <- list(
  proxy         = "IP_Adress",
  proxyport     = 8080
)

options(RCurlOptions = opts)`

There is no proxy username or password. I've managed to set that proxy for GitHub and works fine. I'll just do the homework and upload the result at home. 

Diana

**Comment by Pres83** [comment]
Dear @seankross ,

I 'm having similar issue,  already reported deepamgp

after completing the third swirl assignment of week 2, I entered my credentials I received the following error message

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't connect to server
Called from: curl::curl_fetch_memory(url, handle = handle)

I tried both on work pc  and home pc, same error.

Thanks in advance for your feedback

**Comment by dianaavram** [comment]
@Pres83 , I had no problems in submitting the assignments from home. I complete them at work, and just do the submission from home. 

Is it possible that you're firewall is blocking it ? In case you run on windows.

Good work guys in saving the completed assignment even without entering the credentials. Saved me a lot of time of not repeating the assignment.

Cheers,
Diana

**Comment by tiborban64** [comment]
+   submit()
Error in submit(.) : unused argument (.)
 I get this everytime I try to submit my titanic_1 answer. Why?
