### ISSUE TITLE
cant install swirl

### ISSUE THREAD

**Issue by Meer025** [swirldev/swirl#388]
I am having problem with installing swirl.

> install.packages("swirl")
Warning in install.packages("swirl") :
  'lib = "C:/Program Files/R/R-3.2.3/library"' is not writable
Error in install.packages("swirl") : unable to install packages

**Comment by seankross** [comment]
Are you using Windows 10? You may need to start R or RStudio (depending on which one you're using) in administrator mode.

**Comment by Meer025** [comment]
Yes I m using windows 10. Thanks for the reply. I will start as administrator mode

**Comment by shr420** [comment]
executed command install.packages("swirl")

downloaded swirl but when i call the library function- library("swirl"),it shows the following error

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :

there is no package called ‘bitops’

Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
@shr420 Try the following:

```r
install.packages("swirl")
library(swirl)
swirl()
```
Let me know if that works.

**Comment by shr420** [comment]
thanks for your quick reply..
actually bitops wasnt loaded so i typed install.packages("bitops") and then executed library(swirl) it started working

**Comment by seankross** [comment]
:+1:

**Comment by shr420** [comment]
can u tell me the best source online to learn R ?

**Comment by seankross** [comment]
Here is a list of a few: http://seankross.com/rbootcamp/resources.html

**Comment by Hz7990646** [comment]
i am unable to install swirl package:
install.packages("swirl")
Installing package into ‘/home/hassan/R/x86_64-pc-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.0.2)

**Comment by seankross** [comment]
Swirl is in fact not available for R version 3.0.2. You will need to
upgrade your version of R in order to use  Swirl.

**Comment by Hz7990646** [comment]
i have tried to update but unable to update
Plzz tell me the commands
I have used the normal commands to update

**Comment by abongwa** [comment]
anyone succeeded in install "swirl" or R studio R. 3.4.2?. Once I launch  command, I get a error message that says Swirl is not available (for R version 3.4.2) , wondering if there is a work around?

**Comment by seankross** [comment]
@abongwa see https://stackoverflow.com/questions/25721884/how-should-i-deal-with-package-xxx-is-not-available-for-r-version-x-y-z-wa

**Comment by abongwa** [comment]
I was able to resolve the issue, thanks for the response.
