### ISSUE TITLE
swirl // problems

### ISSUE THREAD

**Issue by urbarea** [swirldev/swirl#389]
When I try to load the swirl  package the following message appears:

> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘magrittr’’
Error: package or namespace load failed for ‘swirl’

Please, could anyone recommend me, how to solve the problem?

What is this package "magrittr" for?
Is it necessary to download it to use swirl?

**Comment by seankross** [comment]
Try the following:

```r
install.packages("swirl", dependencies = TRUE)
swirl()
```

**Comment by urbarea** [comment]
@seankross, thank you!!
still can not use the function "library(swirl)".
Now there is following message: 

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bitops’

I run "R" as administrator

**Comment by seankross** [comment]
Try:

```r
install.packages("bitops")
library(swirl)
swirl()
```

**Comment by urbarea** [comment]
Thank you, Sean!!
Yey. It helped in R-studio (not in R) also after installing packages("magrittr").

**Comment by seankross** [comment]
Good to know! Let me know if you have any other issues.

**Comment by Poojabatish** [comment]
you have to install magrittr package by using this code

> install.packages("magrittr")

i hope this will help you

**Comment by Shrayo** [comment]
Thanks you so much @seankross 
Was breaking my head over swirl install for 3 long days now! haha this was great help! 
It works fine with: 

install.packages("magrittr")
install.packages("bitops")
install.packages("swirl")
library(swirl)
swirl()

**Comment by tanviksh** [comment]
when I try to load the swirl package it shows the following error after library(swirl):
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘digest’

**Comment by tanviksh** [comment]
when I try to load the swirl package it shows the following error after library(swirl):

library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
there is no package called ‘digest’

can you help me to figure this out?
Thanks!

**Comment by tanviksh** [comment]
thanks!
