### ISSUE TITLE
Error in packageVersion("swirl")-Windows8.1

### ISSUE THREAD

**Issue by entheos37** [swirldev/swirl#390]
> library("swirl")
Error in library("swirl") : ‘swirl’이라고 불리는 패키지가 없습니다
> install.packages("swirl")
install.packages("swirl")에서 경고가 발생했습니다 : 
  'lib = "C:/Program Files/R/R-3.2.3/library"'는 기록이 가능하지 않습니다
--- 현재 세션에서 사용할 CRAN 미러를 선택해 주세요 ---
URL 'http://healthstat.snu.ac.kr/CRAN/bin/windows/contrib/3.2/swirl_2.2.21.zip'을 시도합니다
Content type 'application/zip' length 132098 bytes (129 KB)
downloaded 129 KB

패키지 ‘swirl’를 성공적으로 압축해제하였고 MD5 sums 이 확인되었습니다

다운로드된 바이너리 패키지들은 다음의 위치에 있습니다
        C:\Users\이누리\AppData\Local\Temp\RtmpSuL78i\downloaded_packages
> library("swirl")
Error in library("swirl") : ‘swirl’이라고 불리는 패키지가 없습니다
> swirl()
에러: 함수 "swirl"를 찾을 수 없습니다
> chooseCRANmirror()
> install.packages("swirl")
install.packages("swirl")에서 경고가 발생했습니다 : 
  'lib = "C:/Program Files/R/R-3.2.3/library"'는 기록이 가능하지 않습니다
URL 'http://cran.nexr.com/bin/windows/contrib/3.2/swirl_2.2.21.zip'을 시도합니다
Content type 'application/zip' length 132098 bytes (129 KB)
downloaded 129 KB

패키지 ‘swirl’를 성공적으로 압축해제하였고 MD5 sums 이 확인되었습니다

다운로드된 바이너리 패키지들은 다음의 위치에 있습니다
        C:\Users\이누리\AppData\Local\Temp\RtmpSuL78i\downloaded_packages
> packageVersion("swirl")
Error in packageVersion("swirl") : 패키지 ‘swirl’를 찾을 수 없습니다
> 

----------------------
Question:
I use Windows 8.1 and I also downloaded R Studio.
I set cranmirror in Seoul(my area) and downloaded the packages but 

Error said that they can not find "swirl" packages.
R checked the location of downloaded packages, but I don't know why "swirl" packages are not found on my Computer?

Thank you for reading this question:)

**Comment by seankross** [comment]
Hi @entheos37,

Are you using a school or work computer? You may not have permission to write files to certain parts of your computer in that case. If you're using a personal computer try starting RStudio in administrator mode. Let me know if that works.

**Comment by entheos37** [comment]
Thank you for your reply! It worked :)

**Comment by seankross** [comment]
Good to hear! Please get in touch if you have other questions.
