### ISSUE TITLE
Issue in Lattice_Plotting_System

### ISSUE THREAD

**Issue by kenegray** [swirldev/swirl#392]
I've been running Swirl for a few weeks now and I tried doing Lattice_Plotting_System but the menu system errors out with "Error in file(con, "r") : invalid 'description' argument" whenever if choose a module in it.

Rstudio:99.486
r: 
>platform       x86_64-w64-mingw32          
>arch           x86_64                      
>os             mingw32                     
>system         x86_64, mingw32             
>status                                     
>major          3                           
>minor          2.2                         
>year           2015                        
>month          08                          
>day            14                          
>svn rev        69053                       
>language       R                           
>version.string R version 3.2.2 (2015-08-14)
>nickname       Fire Safety    

Any help would be much appreciated.
| Please choose a lesson, or type 0 to return to course menu.

1: clearPlot.R
2: customTests.R
3: dependson.txt
4: initLesson.R
5: lesson
6: myLabels.R
7: plot1.R
8: plot2.R

Selection: 1

Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
You need to reinstall the course:

```r
library(swirl)
uninstall_all_courses()
install_from_swirl("Exploratory Data Analysis")
```

**Comment by kenegray** [comment]
wow I tried installing Lattice_Plotting_System not "Exploratory Data Analysis". that was probably my problem.
thanks!

**Comment by seankross** [comment]
No problem, let me know if you have any other issues.
