### ISSUE TITLE
Error in swirl Statistal Inference Hypothesis Testing

### ISSUE THREAD

**Issue by mjdata** [swirldev/swirl#393]
Hello, Swirl team: Would you please fix a problem in Statistical Inference Hypothesis Testing, thanks.

swirl stopped working in Statistal Inference Hypothesis testing with the following messages:

|Would you like to continue with one of these lessons?
1: Statistical Inference Hypothesis Testing
2: No. Let me start something new.
Selection: 1
| Attemping to load lesson dependencies...
| Package <U+617B>gplot2<U+FFFD> loaded correctly!

| Here's a plot to show what we mean. The shaded portion
| represents 5% of the area under the curve and those X values in
| it are those for which the probability that X>C is 5%.

Error in layer("area", mapping = aes(x = ifelse(x > qnorm(0.95, sd = 2),  : 
  unused argument (geom_params = list(fill = "red", alpha = 0.5))

| Leaving swirl now. Type swirl() to resume.

>

**Comment by mathsgrinds** [comment]
I'm having this problem too, I'm using version 3.2.2 on windows 10.

**Comment by hoony** [comment]
same problem on OS X 10.9

**Comment by hoony** [comment]
this issue is related to this discussion: https://www.coursera.org/learn/statistical-inference/programming/1KvcA/swirl-lesson-2-hypothesis-testing/discussions/ZjHTT7vuEeWSBRJpSArseQ

I solved it by installing ggplot2 1.0.1.
