### ISSUE TITLE
There doesn't exists the package named "stringi"

### ISSUE THREAD

**Issue by KasenLYU** [swirldev/swirl#395]
Coucou for help!

After installing swirl, when I enter "library(swirl)", an error comes like this "不存在叫‘stringi’这个名字的程辑包" which mean there exists no such a packge named 'stringi'. 
My OS is window10, and I've tried to RUN RStudio and Rx64 in administrator mode, the problem still cann't be solved.

PS. The installation is good, I think, according to the notice "
package ‘swirl’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\LUX\AppData\Local\Temp\RtmpCA1s4H\downloaded_packages"

**Comment by seankross** [comment]
Try `install.packages("stringi")` and then try `library(swirl)`. Let me know if that helps.

**Comment by KasenLYU** [comment]
Thank you very much! Your suggestion did work!

发自我的 iPhone

在 2016年1月19日，23:19，Sean Kross <notifications@github.com<mailto:notifications@github.com>> 写道：


Try install.packages("stringi") and then try library(swirl). Let me know if that helps.

―
