### ISSUE TITLE
Exploratory_Data_Analysis: Cannot finish lesson 9 and 10 on ggplot2 as qplot() does not know the parameter method 

### ISSUE THREAD

**Issue by tinaamazon** [swirldev/swirl#397]
In lesson 9, I'm supposed to enter the following as the first R command:
> qplot(displ, hwy, data=mpg, geom=c("point","smooth"), facets=.~drv, method="loess")

Error: Unknown parameters: method

So I tried to leave this question with skip(), but the following error message ocured and swirl stopped automatically:
Error: Unknown parameters: method
| Leaving swirl now. Type swirl() to resume.

?qplot does not mention a parameter method. Possibly swirl relies on an old version of ggplot2?

swirl: 2.2.21
ggplot2: 2.2.0
R: 2.0.0
OS: Windows 8

Is there a way to bypass this problem? Thanks in advance for an advice or a fix.

**Comment by seankross** [comment]
To bypass the problem for now, try following the instructions here: http://seankross.com/rbootcamp/hw2.html

Let me know if that works for you.

**Comment by tinaamazon** [comment]
Sean, your instructions perfectly worked for me except for Step 4: 
> install.packages(file.choose(), repos = NULL, type="source")
The interactive file picking caused freezing. So I copied the *.gz to my project directory in R Studio and addressed it directly:
> install.packages("ggplot2_1.0.1.tar.gz", repos = NULL, type="source")  

Everything is okay now and I'm able to continue with the swirl lessons on Exploratory Data Analysis.
Thank you very much for your advice.
