### ISSUE TITLE
error while loading swirl package

### ISSUE THREAD

**Issue by Poojabatish** [swirldev/swirl#398]
after installing swirl package successfully m getting error while loading swirl package
my coding is 
> install.packages("swirl")
Installing package into ‘C:/Users/SONY/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.2.21.zip'
Content type 'application/zip' length 132175 bytes (129 KB)
downloaded 129 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\SONY\AppData\Local\Temp\RtmpKURJBy\downloaded_packages
> packageVersion("swirl")
[1] ‘2.2.21’
> library(swirl)
Error : .onLoad failed in loadNamespace() for 'crayon', details:
  call: loadNamespace(name)
  error: there is no package called ‘memoise’
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
See #389
