### ISSUE TITLE
RStudio failing to submit completed assignments

### ISSUE THREAD

**Issue by Loricrio** [swirldev/swirl#399]
Receiving this feedback:
Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.

Question: Does the code have to be spaced perfectly? IE: remove whitespace?
It has failed now twice for two assignments and I don't know the code to return back to the submission question.

Thanks in advance for help!

**Comment by seankross** [comment]
There cannot be any whitespace. You can find more info here: https://github.com/swirldev/swirl/wiki/Coursera-FAQ Let me know if you're still having trouble submitting.

**Comment by Loricrio** [comment]
Thanks, will try. One submission worked so far.

**Comment by MariGeorge** [comment]
I received this feedback when I try to submit my first assignment in SWirl:
Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.

I enterered my email ID and assignment token.
I tried a second time and it says Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.
Question:  I dont know what I am doing wrong.  Thanks in Advance

**Comment by chaudharyankit23** [comment]
I am having the same issue, can't find any solution. Please help

**Comment by RSzucs** [comment]
I am having the same issue, can't find any solution
:(

**Comment by acharyaanupam17** [comment]
Having the same issue. Cannot find a solution to the problem. Grade submission failed. I have already tried generating a new token. I have also tried typing the whole thing. Please help.

**Comment by Anandreena** [comment]
facing same issue. tried multiple times. regenerated new code as well as restarted rstudio. still issue is there.

**Comment by englianhu** [comment]
https://github.com/swirldev/swirl/issues/665#issuecomment-435776124

**Comment by englianhu** [comment]
> facing same issue. tried multiple times. regenerated new code as well as restarted rstudio. still issue is there.

Same with me, I retook the test couple times but the issue is still there.
https://github.com/swirldev/swirl/issues/665#issuecomment-435776124

**Comment by alemayehuargawu** [comment]
The same issue for me. Cannot find a solution to the problem. Grade submission failed. I have already tried generating a new token. I have also tried typing the whole thing. Please help.
