### ISSUE TITLE
qplot does not recognize the 'method' arguement

### ISSUE THREAD

**Issue by rheplo** [swirldev/swirl#401]
When I try to input the correct function call of qplot in section 9 of Exploratory Data Analysis I receive this error:

Error: Unknown parameters: method

| Leaving swirl now. Type swirl() to resume.

**Comment by sloisellegd** [comment]
This issue is a duplicate of this:
https://github.com/swirldev/swirl_courses/issues/224

**Comment by seankross** [comment]
You can find work arounds in the issue above or you can try this: http://seankross.com/rbootcamp/hw2.html

Closing because this is a duplicate.
