### ISSUE TITLE
can not submit task to receive credit for "R programming "on Coursera.org

### ISSUE THREAD

**Issue by nihaoCC** [swirldev/swirl#409]
Thanks a lot.
My software environment：win10 64; R 3.2.3; swirl 2.2.21;
Problem：
---------------------------------------------------------------------------
Selection: 1
What is your email address? **
What is your assignment token? **
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)
| Leaving swirl now. Type swirl() to resume.
--------------------------------------------------------------------------------
I try to run Rstudio as administrator, however it does not work. 
----------------------------------------------------------------------------
Buy the way , I can not install course auto, I solve it by download the zip. I don't know why.
> install_from_swirl("R Programming")

Error in curl::curl_fetch_memory(url, handle = handle) : 

Failure when receiving data from the peer.

**Comment by nihaoCC** [comment]
I solved the prolem in mac os system (all software are the latest version ). However, I still do not know what happens in windows system. By the way, in mac os the "install_from_swirl("R Programming")" problem still exist.

**Comment by seankross** [comment]
I'm glad you were able to solve this issue. We're working on manual submission and improving course installation right now.

Sean

**Comment by Yun-Han** [comment]
I got the same problem. However, I don't have a Mac. @seankross
