### ISSUE TITLE
package ‘swirlify’ is not available (for R version 3.1.2)

### ISSUE THREAD

**Issue by daniellesent** [swirldev/swirl#410]
I'm trying to install the package swirlify using:

`install.packages("swirlify")`, but I get the following message:

Warning in install.packages :
  package ‘swirlify’ is not available (for R version 3.1.2)

> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] nl_NL.UTF-8/nl_NL.UTF-8/nl_NL.UTF-8/C/nl_NL.UTF-8/nl_NL.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.1.2

Help is very much appreciated!

**Comment by seankross** [comment]
Hi @daniellesent,

You need to update your version of R in order to install swirlify. Let me know if you need any help updating.

Sean

**Comment by daniellesent** [comment]
Oh dear, found indeed that to be the problem (but unfortunately not able to delete this issue). Sorry.

**Comment by seankross** [comment]
No problem, if you have any other issues please let me know.
