### ISSUE TITLE
Cannot advance past R Lesson 9 Functions

### ISSUE THREAD

**Issue by JanCombrink** [swirldev/swirl#412]
Hi
I am unable to get past boring_function in Lesson 9.  RStudio Console returns "Error: could not find function "submit""  when I enter submit(), after I have saved the "fixed" function in the editor.  The rest of the environment is empty - nothing else running.  I have restarted several times and still no luck.  I can also not skip or next.  Swirl seems to stop altogether the moment the exercise is displayed.  Screenshot is attached.

![l9 problem screenshot 2016-02-16 18 11 24](https://cloud.githubusercontent.com/assets/15798417/13082382/212f124e-d4d9-11e5-9d87-35b291898b2b.png)

R 3.2.3 RStudio Version 0.99.878  on Windows 10 and Swirl 2.2.21

Please help with alternatives.

Jan

**Comment by JanCombrink** [comment]
Hi

Sorry about the previous message, but just after I posted this the submit() worked.  I do not know why as nothing has changed as far as I am concerned.

Thanks for a great package.  I am learning so much and it suits my learning style 100%.

Jan

**Comment by seankross** [comment]
@JanCombrink good to hear, sorry you ran into this hiccup.
