### ISSUE TITLE
Can not access the courses in SWIRL

### ISSUE THREAD

**Issue by cgreen4ever** [swirldev/swirl#415]
Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in R’
| right now. Are you sure you have an internet connection? If so, would you like to
| try again or visit the course repository for instructions on how to install a
| course manually? Type 0 to exit.

I have the internet open but can not access the course.  I have to manually add them but it does not work.  Any advice?

**Comment by SolioMo** [comment]
I am having the exact same problem!
I can load swirl, but I can't load any of the swirl programs
I'm pretty much a tech novice, but here is everything that I could think of to try.  If I'm missing something, please let me know! 

Things I have already tried
uninstalled R and R studios, made sure I had the the latest version of both and reinstalled.
attempted to use the "install packages" from the tools menu bar
tried from 2 different internet connections (home and work)
used a VPN
downloaded the ZIP file twice and saved in different locations, tried from both locations
for one of the ZIP files I extracted everything previous to trying to load it, the other I did not.  neither worked
it says 'lib' is unspecified.  I am not entirely sure what that means, if it is a problem, or how to fix it


> install.packages("C:/Users/x/Downloads/swirl_courses-master (1).zip", repos = NULL, type = "win.binary")
Installing package into ‘C:/Users/x/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  cannot open compressed file 'swirl_courses-master (1)/DESCRIPTION', probable reason 'No such file or directory'
Error in install.packages : cannot open the connection

**Comment by thepule** [comment]
I was having ithe same issue, but I seem to have solved it using a different mirror for the download.
Following the code I used to install "Getting and cleaning data":

` install_from_swirl("Getting and Cleaning Data", mirror = "bitbucket")`

**Comment by SolioMo** [comment]
Hey, thanks for your help!  
I tried it, but unfortunately I then got this message:

> install_from_swirl("Getting and Cleaning Data", mirror = "bitbucket")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached

**Comment by SolioMo** [comment]
Hey, I tried the answer from https://github.com/swirldev/swirl/issues/387 and it worked for me.  :)

> install_course_zip(file.choose(), multi = TRUE, which_course = "R Programming")

| Course installed successfully!

**Comment by seankross** [comment]
@cgreen4ever I recommend the advice in #387

**Comment by jcbeck** [comment]
Running into this issue and have tried some of the suggestions here. All of the entries ended up with some form of 
-- Error: could not find function "install_from_swirl"
-- Error: could not find function "install_course_zip"
-- Error: could not find function "install_from_swirl"

Any help would be appreciated. Thanks.

**Comment by cgreen4ever** [comment]
I had to install both versions of JAVA (32bit and 64bit) and reinstall the packages for them to finally work.

**Comment by seankross** [comment]
@jcbeck did you enter `library(swirl)` before using those functions?

**Comment by seankross** [comment]
@cgreen4ever I'm glad it's working but Java shouldn't have anything to do with how R or swirl functions.

**Comment by jcbeck** [comment]
@seankross That was the mistake. Thanks.

**Comment by seankross** [comment]
Good to know, closing this issue.

**Comment by ChaiBapchya** [comment]
I am running into similar error.


```
> library(swirl)
| Hi! I see that you have some variables saved in your workspace. To keep things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

> install_from_swirl("Getting and Cleaning Data")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
> install_from_swirl("Getting and Cleaning Data", mirror = "bitbucket")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached
```

**Comment by seankross** [comment]
See #511
