### ISSUE TITLE
Problem loading swirl

### ISSUE THREAD

**Issue by martin800103** [swirldev/swirl#416]
Hi everybody,

I can install swirl and check my swirl version as 2.2.21.
When I load swirl.

I get this error message:
Error : .onLoad failed in loadNamespace() for 'crayon', details:
  call: `_digest`(c(list(), lapply(`_additional`, function(x) eval(x[[2L]], 
  error: object 'digest_impl' not found
Error: package or namespace load failed for ‘swirl’

How do I solve this problem and what other information I should provide to help you figure out my problem.

Thank you!

**Comment by seankross** [comment]
Try:

```r
install.packages("crayon")
library(swirl)
```

Let me know if that works for you.

**Comment by martin800103** [comment]
Hi Seankross!
Thank you!
I think I found the problem.
My R version is 3.13.
After I updated to 3.23, the swirl is working.
Thanks, again.

**Comment by agapanthusme** [comment]
Hi All,

I could install swirl. However, when I tried to Install the Getting and Cleaning Data course with the following code. 

install_from_swirl("Getting and Cleaning Data")

**Comment by seankross** [comment]
@agapanthusme try this: https://github.com/swirldev/swirl/issues/387#issuecomment-170266258
