### ISSUE TITLE
usability issue(s)

### ISSUE THREAD

**Issue by actraub** [swirldev/swirl#417]
Two usability issues and possible solutions:

**1. The "command" prompt and the "more" prompt are too similar. I made a mistake by typing on the more prompt (see image)**

- When on a more prompt, any key should advance me forward
- Use the name of the user at the prompt to make it more naturally identifiable by the user

**2. The r studio tooltip covers your instructions. While this seems like an Rstudio issue, remember that you use the command line differently when you are following instructions that exploring numbers.**

- Add another hard break before displaying the command prompt. Note: don't add one for the more prompt. This will further distinguishing the prompts-contributing to the solution for 1.

![image](https://cloud.githubusercontent.com/assets/1034301/13369878/fe08260a-dcc8-11e5-8454-2f20ed05558b.png)

**Comment by seankross** [comment]
Hi @actraub,

Thanks for these suggestions. Right now I can't think of how to implement making any keypress advance the text, but I'll think about it. The underlying mechanism is just `readline("...")`. As far as always adding a line after text, many of our users use swirl on the command line and I'm afraid that inserting extra lines would cause those users to have to scroll around in their terminal more often. You could always just push the text up by pressing `Enter` at the prompt.
