### ISSUE TITLE
I am using R 3.2.3 and cannot install the package swirl as it is not available for this version of R

### ISSUE THREAD

**Issue by lovelor** [swirldev/swirl#423]
> R.version.string
[1] "R version 3.2.3 (2015-12-10)"
> install.packages("swirl")
Installing package into ‘C:/Users/Lorraine/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning: unable to access index for repository https://mirrors.ebi.ac.uk/CRAN/src/contrib:
  cannot open URL 'https://mirrors.ebi.ac.uk/CRAN/src/contrib/PACKAGES'
Warning: unable to access index for repository https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.2:
  cannot open URL 'https://mirrors.ebi.ac.uk/CRAN/bin/windows/contrib/3.2/PACKAGES'
Warning message:
package ‘swirl’ is not available (for R version 3.2.3) 
**
Do I need to install an older version of R to use swirl? How far back? **

**Comment by lovelor** [comment]
I have got round this by using RStudio instead - it seems to be ok. Does anyone understand why this is? I'm obviously doing something wrong but it's not clear to me what.

**Comment by seankross** [comment]
I don't why it started working but if you have any other issues let me know!
