### ISSUE TITLE
installing swirl on GNURoot Debian (Android)

### ISSUE THREAD

**Issue by jackjt8** [swirldev/swirl#424]
So, I'm trying to install swirl on my Nexus 7 (2013) via GNURoot Debian. But I keep running into issues with installing swirl in R. Below I've put the order that I've been told to install packages along with some extras.

apt-get update
apt-get update
apt-mark hold perl-base
_--- Extras, not being found even after getting packages_
apt-get install libcurl4-openssl-dev
apt-get install libssl-dev
apt-get install curl
_--- Connect is lost halfway through so I use --fix-missing to try and resume r-base and r-cran*_
apt-get install r-base
apt-get install r-cran*
R
> install.packages("swirl")

During installing swirl, I get errors stating that libcurl4-openssl-dev & libssl-dev are missing or not configured. But I am unsure of how to correctly fix this issue.

Console log [swirlerror.txt](https://github.com/swirldev/swirl/files/161812/swirlerror.txt)

Note - I've tried my best to look at the Linux install guide, search the issues here and  to google this issue, but I am honestly a complete novice when it comes to Linux so it might be an easy fix.

**Comment by seankross** [comment]
Hi @jackjt8,

My suspicion is that this is a very deep issue that doesn't have to do with swirl or R. I suspect that libcurl4-openssl-dev and libssl-dev are not compatible with your phone's architecture. If you're serious about having Linus access on your phone I suggest you find a mobile ssh client. Sorry I can't be of more help.

Sean

**Comment by jackjt8** [comment]
Hi @seankross 

It's definitely a possibility. R works fine using this method. Both libcurl4-openssl-dev and libssl-dev have arm Architecture downloads available. Though only armel. I've been trying to find out what Android/the snapdragon processor is using but it could be armhf, hence possible incompatibly.

Hopefully someone might have some ideas about I could possible test the packages I have got installed to see if they are incompatible or just unconfigured as the error(s) suggested.

In the mean time, I will see if the app dev has any ideas.

Thanks Jack

**Comment by seankross** [comment]
I'm going to close this but if you think it is in fact a swirl issue feel free to re-open.
