### ISSUE TITLE
Getting "leaving swirl now" msg whenever I select any lesson

### ISSUE THREAD

**Issue by datascienceaccount** [swirldev/swirl#425]
I installed swirl a couple day ago and can load it fine. I enter my name (what I want to be called) and type "1" for R Programming and get taken to a list of 15 lessons. Whenever I type any value from 1-15, or the names of any of the courses, at the "choose a lesson" prompt, I see :

|                                                                                                                              | 0%$
##(the two pipe characters are far apart in the display, github wont maintain the spacing)
| Leaving swirl now. Type swirl() to resume.

Does anyone know whats causing this? If I type 0 the prompt takes me back to the main menu as it says it would, but I cannot select any of the lessons.

**Comment by seankross** [comment]
Can you send a screenshot?

**Comment by datascienceaccount** [comment]
Interestingly enough, I accidentally identified myself differently and got a full-length error message for the first time. (For some reason "Jon" doesn't get this error message, but "J" does. Jon was the name the admin used when they installed swirl the first time though, so...?)  

![swirl access failure screenshot](https://cloud.githubusercontent.com/assets/17504144/13680848/685be240-e6c8-11e5-9546-d53e6c9ccf8c.JPG)

**Comment by seankross** [comment]
Are you using a computer that belongs to your school or your employer?

**Comment by datascienceaccount** [comment]
It's a computer I don't have admin access on.

**Comment by seankross** [comment]
Try this an let me know if it works:

```r
remove.packages("swirl")
path <- file.path("~", "R", "swirl")
dir.create(path, recursive = TRUE)
install.packages("swirl", lib = path)
library(swirl)
```
