### ISSUE TITLE
Unable to install swirl package

### ISSUE THREAD

**Issue by shaggy2107** [swirldev/swirl#427]
I tried installing swirl package using,

**1)**
`install.packages("C:\\Users\\ADMIN\\Downloads\\swirl_2.2.21.tar.gz", repos = NULL, type="source")`

I got following error,

```
Installing package into ‘C:/Users/ADMIN/R/win-library/3.2’
(as ‘lib’ is unspecified)
ERROR: dependencies 'stringr', 'testthat', 'httr', 'yaml', 'RCurl', 'digest' are not available for package 'swirl'
* removing 'C:/Users/ADMIN/R/win-library/3.2/swirl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-32~1.4/bin/x64/R" CMD INSTALL -l "C:\Users\ADMIN\R\win-library\3.2" "C:/Users/ADMIN/Downloads/swirl_2.2.21.tar.gz"' had status 1
Warning in install.packages :
  installation of package ‘C:/Users/ADMIN/Downloads/swirl_2.2.21.tar.gz’ had non-zero exit status
```

**2)**
`install.packages("swirl")`

I got following error

```
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/src/contrib:
  cannot open URL 'http://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Installing package into ‘C:/Users/ADMIN/R/win-library/3.2’
(as ‘lib’ is unspecified)
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/src/contrib:
  cannot open URL 'http://cran.rstudio.com/src/contrib/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/src/contrib:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘swirl’ is not available (for R version 3.2.4)
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://cran.rstudio.com/bin/windows/contrib/3.2:
  cannot open URL 'http://cran.rstudio.com/bin/windows/contrib/3.2/PACKAGES'
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  InternetOpenUrl failed: ''
Warning in install.packages :
  unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.2:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.2/PACKAGES'
```

Here is my environment info,

```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.4
```

**Comment by seankross** [comment]
This SO question may be relevant: http://stackoverflow.com/questions/25599943/unable-to-install-packages-in-latest-version-of-rstudio-and-r-version-3-1-1

Let me know if that works.

**Comment by ankitgoel000** [comment]
install.packages("swirl")
Installing package into ‘C:/Users/Ankit/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘stringi’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’
Packages which are only available in source form, and may need compilation of
C/C++/Fortran: ‘stringi’ ‘jsonlite’ ‘mime’ ‘curl’ ‘openssl’ ‘bitops’ ‘testthat’
‘yaml’ ‘RCurl’ ‘digest’
These will not be installed
installing the source packages ‘stringr’, ‘httr’, ‘swirl’

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.1.0.tar.gz'
Content type 'application/x-gzip' length 63174 bytes (61 KB)
downloaded 61 KB

trying URL 'https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz'
Content type 'application/x-gzip' length 133398 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/src/contrib/swirl_2.4.2.tar.gz'
Content type 'application/x-gzip' length 98565 bytes (96 KB)
downloaded 96 KB

ERROR: dependency 'stringi' is not available for package 'stringr'

removing 'C:/Users/Ankit/Documents/R/win-library/3.3/stringr' Warning in install.packages : running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Ankit\Documents\R\win-library\3.3" C:\Users\Ankit\AppData\Local\Temp\Rtmpeeg39e/downloaded_packages/stringr_1.1.0.tar.gz' had status 1 Warning in install.packages : installation of package ‘stringr’ had non-zero exit status ERROR: dependencies 'jsonlite', 'mime', 'curl', 'openssl' are not available for package 'httr'
removing 'C:/Users/Ankit/Documents/R/win-library/3.3/httr' Warning in install.packages : running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Ankit\Documents\R\win-library\3.3" C:\Users\Ankit\AppData\Local\Temp\Rtmpeeg39e/downloaded_packages/httr_1.2.1.tar.gz' had status 1 Warning in install.packages : installation of package ‘httr’ had non-zero exit status ERROR: dependencies 'stringr', 'testthat', 'httr', 'yaml', 'RCurl', 'digest' are not available for package 'swirl'
removing 'C:/Users/Ankit/Documents/R/win-library/3.3/swirl' Warning in install.packages : running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\Ankit\Documents\R\win-library\3.3" C:\Users\Ankit\AppData\Local\Temp\Rtmpeeg39e/downloaded_packages/swirl_2.4.2.tar.gz' had status 1 Warning in install.packages : installation of package ‘swirl’ had non-zero exit status
The downloaded source packages are in
‘C:\Users\Ankit\AppData\Local\Temp\Rtmpeeg39e\downloaded_packages’

**Comment by seankross** [comment]
Have you tried installing stringi on its own?

**Comment by ankitgoel000** [comment]
The issue is resolved now sir. I have installed all the requirements independently. 
Thanks for support.
