### ISSUE TITLE
Similar code not getting read in SWIRL and asking for repetitive try

### ISSUE THREAD

**Issue by gitagowda** [swirldev/swirl#430]
paste(1:3, c("X", "Y", "Z"), sep=" ")
[1] "1 X" "2 Y" "3 Z"

| Not quite right, but keep trying. Or, type info() for more options.

| Use paste(1:3, c("X", "Y", "Z"), sep = "") to see what happens when we join
| two vectors of equal length using paste().

I couldn't fine the difference between my submission and SWIRL's suggestion. Am I missing something? Please let me know.

**Comment by seankross** [comment]
Looks like the `sep` arguments are different.

**Comment by gitagowda** [comment]
OOPS!! Yeah, I missed it every time. Got it right now. Sorry for the hurried issue.
