### ISSUE TITLE
Stuck after welcome message

### ISSUE THREAD

**Issue by dwitibasu** [swirldev/swirl#431]
hi,

i am trying to load swirl R package, and trying to install the 1st course "R_Programming". however after the welcome message it is giving me 3 options as follows, but nothing is happening when I am typing the number and pressing enter:

To begin, you must install a course. I can install a course for you from the
| internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options and
| directions for installing courses yourself. (If you are not connected to the
| internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Don't install anything for me. I'll do it myself.

after this message i am typing the number and pressing enter but nothing is happening. I am very new to swirl kindly suggest anyone how do I troubleshoot this.

Thanks

**Comment by seankross** [comment]
It's probably taking a long time for the course to install. Try installing the course with [this](https://github.com/swirldev/swirl/issues/387#issuecomment-170266258) method instead.
