### ISSUE TITLE
Error in swirl functions module modifying function

### ISSUE THREAD

**Issue by jasonbutt** [swirldev/swirl#436]
Hi, working through the function module (#9) in swirl for the Lesson 2 assignment. I'm at 14% where I am asked to modify a function to return X after continuing. When I continue I receive the following Error:

> Error in editor(file = file, title = title):
>        argument "name" is missing, with no default

I'm then dumped out of Swirl. No file to edit. Not able to proceed.

Tried running RSutdio as Administrator and get the same response.

Using Rstudio (Ver. 0.99.891) on Windows 10 with R 3.2.4.

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by jasonbutt** [comment]
Perfect! Thanks for pointing me to that thread.
