### ISSUE TITLE
swirl Lesson 5: GGPlot2 Extras - Wrong Instructions (Corrections required?)

### ISSUE THREAD

**Issue by edgetrader** [swirldev/swirl#437]
**At 48%, instructions given as follows:**

| We'll rerun the plot you just did (carat,price,data=diamonds and color=cut) but add two more
| parameters. The first is the argument geom set equal to the concatenation of the 2 strings, "point"
| and "smooth". The second is the argument method set equal to the string "lm". Try this now.

> qplot(carat, price, data=diamonds, color=cut, geom=c('point', 'smooth'), method='lm')
Error: Unknown parameters: method
> qplot(carat, price, data=diamonds, color=cut, geom=c('point', 'smooth'))

| Give it another try. Or, type info() for more options.

| Type qplot(carat,price,data=diamonds, color=cut) + geom_smooth(method="lm") at the command prompt.

**At 50%, instruction given as follows:**

| Finally, let's rerun that plot you just did (carat,price,data=diamonds, color=cut, geom
| =c("point","smooth"),method="lm") but add one (just one) more argument. The new argument is facets
| and it should be set equal to the formula .~cut. Recall that the facets argument indicates we want a
| multi-panel plot. The symbol to the left of the tilde indicates rows (in this case just one) and the
| symbol to the right of the tilde indicates columns (in this five, the number of cuts). Try this now.

> qplot(carat, price, data=diamonds, color=cut, geom=c('point', 'smooth'), method='lm', facets = .~cut)
Error: Unknown parameters: method

**Comment by seankross** [comment]
Thanks, I'll correct this.

**Comment by Drfourkay** [comment]
Still, it appears in the old order.
