### ISSUE TITLE
Exploratory Data Analysis - 13:Dimenstion Reduction.  Cannot proceed beyond 7%

### ISSUE THREAD

**Issue by edgetrader** [swirldev/swirl#438]
| Let's add a pattern to the data. We've put some R code in the file addPatt.R for you. Run the command myedit with the single
| argument "addPatt.R" (make sure to use the quotation marks) to see the code. You might have to click your cursor in the console
| after you do this to keep from accidentally changing the file.

**> myedit("addPatt.R")

 Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default **

> myedit
function(fname){
   #fxfer(fname)
   #file.edit(fname)
   mypath <- pathtofile(fname)
   file.edit(mypath)
}
<environment: 0x000000001315b9c8>

| Keep trying! Or, type info() for more options.

| Type myedit("addPatt.R") at the command prompt.

**> myedit("addPatt.R")

 Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default **
>

**Comment by edgetrader** [comment]
Need to 

source("initLesson.R") 

to continue

**Comment by tianyuanxie** [comment]
Same thing happens to me. But it can work in R.

**Comment by seankross** [comment]
See #434

**Comment by rajeevamatya** [comment]
Hi Sean, 

myedit("addPatt.R") works but 

source("addPatt.R", local=TRUE) does not work for me. 

Gives the following message:

Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'addPatt.R': No such file or directory

Any idea?
