### ISSUE TITLE
Practical R Exercises in swirl: Assignment2-Functions: Script to be modified is not appearing

### ISSUE THREAD

**Issue by BeginWithR** [swirldev/swirl#439]
RStudio
Error
The last R expression to be evaluated in a function will become the return value of
| that function. We want this function to take one argument, x, and return x without
| modifying it. Delete the pound sign so that x is returned without any modification.
| Make sure to save your script before you type submit().

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.
![problem](https://cloud.githubusercontent.com/assets/18076986/14155746/a3b8786c-f6e0-11e5-82f6-28c7c08e8c3f.JPG)

**Comment by seankross** [comment]
See #434

**Comment by Navia2000** [comment]
can you please send me the assignment (functions)
its urgent
