### ISSUE TITLE
R-Programming. Lesson:Functions

### ISSUE THREAD

**Issue by firemindfields** [swirldev/swirl#440]
Currently working through the Functions Lesson in R Programming. When it's time to load a script i see the following message. I can't seem to proceed from here. I only hit enter once after the message "...so be sure to read them!"

> mean(c(2,4,5))
[1] 3.666667

| Keep up the great work!

  |===========                                                                                                     |  10%

| Functions usually take arguments which are variables that the function operates on. For example, the mean() function
| takes a vector as an argument, like in the case of mean(c(2,6,8)). The mean() function then adds up all of the numbers
| in the vector and divides that sum by the length of the vector.

...

  |==============                                                                                                  |  12%

| In the following question you will be asked to modify a script that will appear as soon as you move on from this
| question. When you have finished modifying the script, save your changes to the script and type submit() and the script
| will be evaluated. There will be some comments in the script that opens up, so be sure to read them!

...

  |================                                                                                                |  14%

| The last R expression to be evaluated in a function will become the return value of that function. We want this
| function to take one argument, x, and return x without modifying it. Delete the pound sign so that x is returned
| without any modification. Make sure to save your script before you type submit().

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by jiayingxoxo** [comment]
Me too! Looks like the file for the assignment is missing, or the link is broken...?

**Comment by seankross** [comment]
See #434
