### ISSUE TITLE
R Programming: Lesson 9 - Functions

### ISSUE THREAD

**Issue by brokawq** [swirldev/swirl#442]
**I'm getting the following error near the beginning of R Programming - Lesson 9:**

_______________________________________________________________________________
| In the following question you will be asked to modify a script that will appear as soon as you move on from this
| question. When you have finished modifying the script, save your changes to the script and type submit() and the script
| will be evaluated. There will be some comments in the script that opens up, so be sure to read them!

...

  |================                                                                                                |  14%

| The last R expression to be evaluated in a function will become the return value of that function. We want this
| function to take one argument, x, and return x without modifying it. Delete the pound sign so that x is returned
| without any modification. Make sure to save your script before you type submit().

**Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default**

| Leaving swirl now. Type swirl() to resume.
_______________________________________________________________________________

**I've received the error multiple times and I've tried re-installing swirl.**

**Here is the Session Info (using windows 10)**
_______________________________________________________________________________
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.0

loaded via a namespace (and not attached):
 [1] httr_1.1.0      magrittr_1.5    R6_2.1.2        tools_3.2.4     RCurl_1.95-4.8  curl_0.9.6      yaml_2.1.13    
 [8] memoise_1.0.0   crayon_1.3.1    stringi_1.0-1   stringr_1.0.0   digest_0.6.9    testthat_0.11.0 bitops_1.0-6

**Comment by seankross** [comment]
See #434

**Comment by brokawq** [comment]
Using instructions in #434: "Before you start swirl in RStudio, try entering options(editor = "internal")." fixes the issue!

Thank you
