### ISSUE TITLE
Exploratory Data Analysis Case Study Lesson is stuck on a code

### ISSUE THREAD

**Issue by pragyakalia** [swirldev/swirl#444]
Swirl is stuck on the below code. It is asking me to type the same code as I have typed and it is still suggesting to type the same. With skip( ) too, it is not moving ahead.
Unable to move ahead in this assignment....

"...Now it's clearer what information each column of pm0 holds. The measurements of
| particulate matter (pm25) are in the column named Sample.Value. Assign this component of
| pm0 to the variable x0. Use the m$n notation.

> x0 <- pm0$Sample.Value

| You're close...I can feel it! Try it again. Or, type info() for more options.

| Type x0 <- pm0$Sample.Value at the command prompt.

> skip()

| Entering the following correct answer for you...

> x0 <- pm0$Sample.Value

| Give it another try. Or, type info() for more options.

| Type x0 <- pm0$Sample.Value at the command prompt.

> x0 <- pm0$Sample.Value

| That's not the answer I was looking for, but try again. Or, type info() for more options.

| Type x0 <- pm0$Sample.Value at the command prompt.

> x0 <- pm0$Sample.Value

| Almost! Try again. Or, type info() for more options.

| Type x0 <- pm0$Sample.Value at the command prompt.

**Comment by seankross** [comment]
This is unusual behavior. Have you tried uninstalling and then reinstalling swirl?

**Comment by pragyakalia** [comment]
Hi, yes, I did uninstall & reinstall the latest version of R but was still getting the same error. Finally, I decided to run the same on RStudio after updating the version then restarting my mac and it somehow worked for the lesson on swirl.
However, I am still struggling with R on fixing one warning as below and tried following help instructions but to no results. : 
During startup - Warning messages:
1: Setting LC_CTYPE failed, using "C" 
2: Setting LC_COLLATE failed, using "C" 
3: Setting LC_TIME failed, using "C" 
4: Setting LC_MESSAGES failed, using "C" 
5: Setting LC_MONETARY failed, using "C" 
[R.app GUI 1.67 (7152) x86_64-apple-darwin13.4.0]

WARNING: You're using a non-UTF8 locale, therefore only ASCII characters will work.
Please read R for Mac OS X FAQ (see Help) section 9 and adjust your system preferences accordingly.
[Workspace restored from /Users/pragyakalia/.RData]
[History restored from /Users/pragyakalia/.Rapp.history]

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by pragyakalia** [comment]
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

**Comment by seankross** [comment]
@pragyakalia Did you ever get this working?

**Comment by pragyakalia** [comment]
Nope. Still struggling with R. Could manage my project work on R Studio instead.

**Comment by seankross** [comment]
Does it work in RStudio?

**Comment by pragyakalia** [comment]
Yes, it does.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Sean Kross <notifications@github.com> Date: 20/04/2016  21:14  (GMT+05:30) To: swirldev/swirl <swirl@noreply.github.com> Cc: Pragya Kalia <pragyaskalia@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [swirldev/swirl] Exploratory Data Analysis Case Study Lesson is stuck on a code (#444) 
Does it work in RStudio?

**Comment by seankross** [comment]
Is there anything else I can help you with?

**Comment by pragyakalia** [comment]
Thanks a lot for proactively following up. Whats the issue with my R. Is it
possible for you to suggest actions to fix the same. I get same error in R
studio but I could do my project. Don't know whether the same will work as
i advance in my learning.

On Wed, Apr 20, 2016 at 9:29 PM, Sean Kross <notifications@github.com>
wrote:

> Is there anything else I can help you with?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/swirldev/swirl/issues/444#issuecomment-212489552>
>



-- 
Warm Regards
Pragya

**Comment by seankross** [comment]
Just make sure you have the latest version of R and RStudio. Also you might want to look at the language options on your Mac under System Preferences.

**Comment by pragyakalia** [comment]
Did all of that Sean.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Sean Kross <notifications@github.com> Date: 20/04/2016  22:13  (GMT+05:30) To: swirldev/swirl <swirl@noreply.github.com> Cc: Pragya Kalia <pragyaskalia@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [swirldev/swirl] Exploratory Data Analysis Case Study Lesson is stuck on a code (#444) 
Just make sure you have the latest version of R and RStudio. Also you might want to look at the language options on your Mac under System Preferences.

**Comment by seankross** [comment]
What errors are you getting now?
