### ISSUE TITLE
Error in file(con, "r") : invalid 'description' argument

### ISSUE THREAD

**Issue by jfoelst1** [swirldev/swirl#447]
Hi, I'm trying to load the "Basic_Building_Blocks" course onto RStudio, but I'm getting this error message when prompted to choose a lesson:

_Error in file(con, "r") : invalid 'description' argument

| Leaving swirl now. Type swirl() to resume._

I've uninstalled and reinstalled swirl, but to no avail. I have Windows 7, 32-bit.

Here's my traceback: 

> traceback()
15: file(con, "r")
14: readLines(input)
13: paste(readLines(input), collapse = "\n")
12: yaml.load(paste(readLines(input), collapse = "\n"), ...)
11: yaml.load_file(file)
10: parse_content.yaml(file, e)
9: parse_content.default(dataName, e)
8: parse_content(dataName, e)
7: loadLesson.default(e, courseU, lesson)
6: loadLesson(e, courseU, lesson)
5: mainMenu.default(e)
4: mainMenu(e)
3: resume.default(e, ...)
2: resume(e, ...)
1: (function (expr, val, ok, vis, data = e) 
   {
       e$expr <- expr
       e$val <- val
       e$ok <- ok
       e$vis <- vis
       return(resume(e, ...))
   })(quote(swirl()), NULL, TRUE, FALSE)

Any help would be appreciated, thanks!

**Comment by seankross** [comment]
Try the following:

```r
uninstall_all_courses()
install_course("R Programming")
swirl()
```

**Comment by jfoelst1** [comment]
Thanks @seankross, but I'm getting the same error message.

**Comment by seankross** [comment]
Can you send a screenshot?

**Comment by jfoelst1** [comment]
Here you go!
![swirl - error](https://cloud.githubusercontent.com/assets/13824908/14362729/b78dcb50-fcb5-11e5-8680-f7564177d57c.jpg)

**Comment by seankross** [comment]
So after you run this code:

```r
library(swirl)

uninstall_all_courses()
install_course("R Programming")
swirl()
```

select `R Programming` and then select `Basic Building Blocks`.

**Comment by jfoelst1** [comment]
That did the trick; thanks for your support @seankross!
