### ISSUE TITLE
Packages are not available with R v. 3.2.4 Revised

### ISSUE THREAD

**Issue by Saviopham** [swirldev/swirl#448]
Hi,

I upgraded my R to version 3.2.4 Revised on Windows and I can't seem to install the Swirl packages for learning.  The one on my mac still works.  Please help.

Savio

**Comment by seankross** [comment]
What error are you seeing when you try to install a swirl course?

**Comment by dsabrinad94** [comment]
I encountered the same problem when installing swirl. it says unable to access http://lib.stat.cmu.edu/R/CRAN/src/contrib/PACKAGES

**Comment by seankross** [comment]
Try: `install.packages("swirl", repos = "https://cran.rstudio.com/")` and let me know if that works.
