### ISSUE TITLE
Automated R scripts not opening in console

### ISSUE THREAD

**Issue by MBJR1986** [swirldev/swirl#449]
I am trying to complete the Grouping and Chaining module in the dplyr lesson, but I am unable to find the R script the lesson says it has opened. Nothing has opened, so there is nothing for me to edit. I am using R Studio, most recent version of R. I have noticed something similar occurring in the functions module in R Programming course. Any help would be greatly appreciated. Script is attached below.

`| 
That's exactly what you'll get if you use summarize() to apply mean(size) to the grouped data in by_package. Give it
| a shot.

> summarize(by_package, mean(size))
Source: local data frame [6,023 x 2]

       package mean(size)
         (chr)      (dbl)
1           A3   62194.96
2          abc 4826665.00
3     abcdeFBA  455979.87
4  ABCExtremes   22904.33
5     ABCoptim   17807.25
6        ABCp2   30473.33
7     abctools 2589394.00
8          abd  453631.24
9         abf2   35692.62
10       abind   32938.88
..         ...        ...

| You are quite good my friend!

  |=============================                                                                                |  27%

| Instead of returning a single value, summarize() now returns the mean size for EACH package in our dataset.

...

  |===============================                                                                              |  29%

| Let's take it a step further. I just opened an R script for you that contains a partially constructed call to
| summarize(). Follow the instructions in the script comments.
| 
| When you are ready to move on, save the script and type submit(), or type reset() to reset the script to its
| original state.

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.
````

**Comment by seankross** [comment]
See #434

**Comment by MBJR1986** [comment]
Thanks Sean. I just referenced you in a another similar thread with a screenshot.

**Comment by MBJR1986** [comment]
Solution works, @seankross. Thanks for the quick help!

**Comment by akaEmma** [comment]
Wait, what? What solution worked?
