### ISSUE TITLE
Error in Hierarchical clustering lesson 

### ISSUE THREAD

**Issue by Moocprojects** [swirldev/swirl#450]
Hi, 
I am trying to complete a lesson "Hierarchical clustering" in the swirl course "Exploratory data analysis"

**I am getting the below error and attached is the screen shot.**
Trying to install package ‘ggplot2’ now...
package ‘ggplot2’ successfully unpacked and MD5 sums checked
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’

| Could not install package ‘ggplot2’!
  |                                                                                        |   0%
Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.
 
**I tried below two steps :** 
1)  I tried re- installing the swirl package and also the course.
 2) When i manually install ggplot2 and Rcpp packages it says installed,  but it says unable to install ggplot2 when i choose the lesson hierarchical clustering.

Appreciate your advice on this as i got stuck and unable to move forward. 

![screenshot](https://cloud.githubusercontent.com/assets/16925844/14482523/9e5b4dd8-00f2-11e6-87f4-bd0b17b2c574.png)

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by Moocprojects** [comment]
**Please find the below : **
sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.0

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning messages:
1: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'RCurl' is missing or broken
2: In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'curl' is missing or broken

**Comment by seankross** [comment]
You should upgrade to the newest version of R, and then try starting this course in swirl.

**Comment by Moocprojects** [comment]
Thank you i have updated the R version and also uninstalled ggplot2 package and installed them again. Its working fine now.
