### ISSUE TITLE
More intelligent checks for the right answers

### ISSUE THREAD

**Issue by vitkarpov** [swirldev/swirl#451]
Hi!

I'd like to notice the case that I run into. For instance, I need to simulate rolling four six-sided dice. I can write:

```
sample(1:6, 4, replace = T)
```

but it's not right. Because it's not strictly equals to expected result `sample(1:6, 4, replace = TRUE)`. But it's the same.

Maybe the checker should be a little bit more intelligent?

**Comment by seankross** [comment]
Hi @vitkarpov,

Swirl has the ability to check the validity of multiple answers, however this is up to the author of a swirl lesson. In the case of `T` versus `TRUE`, `TRUE` is preferred because it's better stylistically. Try the following in your R console to see what I mean:

```r
T <- FALSE
F <- TRUE
T
F
TRUE <- FALSE
FALSE <- TRUE
```

**Comment by vitkarpov** [comment]
Yep, now I see the difference. `T` could be redefined and then it breaks all the things in my case. Thank you!
