### ISSUE TITLE
error all courses after installing courses-master.zip

### ISSUE THREAD

**Issue by melrose** [swirldev/swirl#452]
After successfully installing with 'install_course_zip("C:/R/workDirs/SwirlStats/cources-master.zip", multi=TRUE, which_course="01_DataScientistToolbox")' I'm getting a 'Error in file(con, "r") : invalid 'description' argument' when running any of the classes. I'd like to take these classes.

**Comment by seankross** [comment]
Hi @melrose,

The Data Scientist's Toolbox does have a corresponding swirl course. Perhaps you meant to install a different course?
