### ISSUE TITLE
Error in library("swirl") : there is no package called ‘swirl’

### ISSUE THREAD

**Issue by TeshomeBalkew** [swirldev/swirl#454]
> library("swirl")
Error in library("swirl") : there is no package called ‘swirl’

**Comment by seankross** [comment]
Have you tried `install.packages("swirl")`?

**Comment by TeshomeBalkew** [comment]
I tried to install swirl after installing it when I write  library("swirl") it says Error in library("swirl") : there is no package called ‘swirl’.

**Comment by TeshomeBalkew** [comment]
yes

**Comment by seankross** [comment]
What do you get as the result of `"swirl" %in% installed.packages()`?

**Comment by TeshomeBalkew** [comment]
FALSE

**Comment by seankross** [comment]
What do you see after running `install.packages("swirl")`?

**Comment by TeshomeBalkew** [comment]
The following
%%%%%%%%%%%%%%%%
Installing package into ‘C:/Users/teshomebalkew/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)

  There is a binary version available but the source version is later:
      binary source needs_compilation
swirl  2.4.0  2.4.1             FALSE

installing the source package ‘swirl’

trying URL 'https://cran.cnr.berkeley.edu/src/contrib/swirl_2.4.1.tar.gz'
Content type 'application/x-gzip' length 98264 bytes (95 KB)
downloaded 95 KB

* installing *source* package 'swirl' ...
** package 'swirl' successfully unpacked and MD5 sums checked
** R
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'stringi'
ERROR: lazy loading failed for package 'swirl'
* removing 'C:/Users/teshomebalkew/Documents/R/win-library/3.2/swirl'

The downloaded source packages are in
        ‘C:\Users\teshomebalkew\AppData\Local\Temp\RtmpuWlJ0R\downloaded_packages’
Warning messages:
1: running command '"C:/PROGRA~1/R/R-32~1.4RE/bin/x64/R" CMD INSTALL -l "C:\Users\teshomebalkew\Documents\R\win-library\3.2" C:\Users\TESHOM~1\AppData\Local\Temp\RtmpuWlJ0R/downloaded_packages/swirl_2.4.1.tar.gz' had status 1 
2: In install.packages("swirl") :
  installation of package ‘swirl’ had non-zero exit status

**Comment by seankross** [comment]
What do you get as a result of `sessionInfo()`?

**Comment by TeshomeBalkew** [comment]
The following
%%%%%%%%%%%%%%%%
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8.1 x64 (build 9600)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.4

**Comment by seankross** [comment]
Have you tried restarting R and then trying to install swirl again? Also are you using a computer for work or school?

**Comment by TeshomeBalkew** [comment]
I didn't restart R which I will do it right away. Yes I use the computer for school.

**Comment by seankross** [comment]
Do you personally own this computer or does the computer belong to the school?

**Comment by TeshomeBalkew** [comment]
It is my personal labtop.

**Comment by TeshomeBalkew** [comment]
Thanks for the help. I have to go.

**Comment by seankross** [comment]
Let me know if you get it working.

**Comment by ahmesa02** [comment]
I had noticed this with the package "party"..
I tried the following and it never occurred again.

if(!require(party))
{
    install.packages("party", repos= "https://cran.ma.imperial.ac.uk/")
}

You might have to mention the repo for the package.
