### ISSUE TITLE
no credit for using swirl - R programming in coursera

### ISSUE THREAD

**Issue by aindira1** [swirldev/swirl#455]
I have been using swirl to learn R programming. But when I try to get credit in the Coursera class,  I get this error message after entering my assignment token.  

Do you know how to adjust for this?

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

Thanks in advance.

**Comment by seankross** [comment]
Hi @aindira1,

Can you try using a different internet connection?

**Comment by aindira1** [comment]
Thank you, I did that just a few hours back from a different machine and it
worked! Regards, Indira
