### ISSUE TITLE
Installing Swirl - Ubuntu 14.04, R3.0.2, R Studio 0.99.893 - install.packages("swirl") fails

### ISSUE THREAD

**Issue by hossedar** [swirldev/swirl#456]
install.packages("swirl")
produces the message in R Studio:

installing *source* package ‘swirl’ ...
package ‘swirl’ successfully unpacked and MD5 sums checked
R
inst
preparing package for lazy loading
Error : object ‘compare’ is not exported by 'namespace:testthat'
ERROR: lazy loading failed for package ‘swirl’
removing ‘/home/dhoss/R/x86_64-pc-linux-gnu-library/3.0/swirl’**

I've already installed testthat via the terminal and the version is '0.7.1'.

Thanks

**Comment by seankross** [comment]
You need to install the newest version of testthat. You can do this with `install.packages("testthat")`.

**Comment by hossedar** [comment]
Thanks for your response. 
I have tried that, but in RStudio I get:
Warning in install.packages :
  package ‘testthat’ is not available (for R version 3.0.2)

This is a well-documented problem so I have installed testthat directly via terminal (sudo apt-get install r-cran-testthat) - this tells me that I already have the newest version of testthat.

**Comment by seankross** [comment]
Can you update your version of R?

**Comment by hossedar** [comment]
Thanks very much for your help, I have updated R to v 3.2.5 then the swirl package install proceeds as normal from the R Studio consol.
For those looking to update R in Ubuntu 14.04, I found the following useful:
http://askubuntu.com/questions/431380/how-to-install-upgrade-r-base-to-3-02
