### ISSUE TITLE
Error when I type swirl(): Swirl Package v 2.4.0 R v 3.2.4 Revised Windows 7

### ISSUE THREAD

**Issue by supsauch** [swirldev/swirl#457]
![image](https://cloud.githubusercontent.com/assets/17270746/14718002/6123b4c4-07f4-11e6-99f0-8078e0a3a71b.png)

I have installed the package: library(swirl)
I have also cleared my workspace using rm(list=ls())

**Comment by seankross** [comment]
Please update swirl to version 2.4.1 with `install.packages("swirl")`.

**Comment by supsauch** [comment]
Thanks for the reply. I tried an alternative approach given in the previous issue raised: https://github.com/swirldev/swirl/issues/457

I used install.packages("testthat") and it worked.
