### ISSUE TITLE
1: R Programming Alt: 16% into lesson. Error in swirlExpectation

### ISSUE THREAD

**Issue by dswain661** [swirldev/swirl#458]
| What do you think tf will look like?

1: a vector of 4 logical values
2: a single logical value

Selection: 1
Error in swirlExpectation(condition(object)) : 
  could not find function "is_equivalent_to"

| Leaving swirl now. Type swirl() to resume.

No matter what selection is made, error above is shown.

**Comment by seankross** [comment]
R Programming Alt is no longer maintained. However you might solve this problem by making sure you have the latest version of R, swirl, and testthat.

**Comment by dswain661** [comment]
Thanks for the info, I believe I am all up to date, R version 3.2.5 (2016-04-14) and Swirl 2.4.1

I see that R Programming is very similar, I'll just use that. Thanks.
