### ISSUE TITLE
Error in loading lesson

### ISSUE THREAD

**Issue by RobertReynolds77** [swirldev/swirl#460]
When I try to load lesson 10 in Regression models it asks if I want to install the package "car". No matter if I say yes or no it ends like this:

| Trying to install package ‘car’ now...
package ‘car’ successfully unpacked and MD5 sums checked
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘lme4’

| Could not install package ‘car’!
  |                                                                                     |   0%
Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Try `install.packages("car")` and then try running the lesson.

**Comment by RobertReynolds77** [comment]
Definitely tried that. Car is installed. The program still asks to install it. When I say no to the install I still get: 

Error in seq.default(0, 1, length = nrow(e$les)) : 
argument 'length.out' must be of length 1

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Have you tried installing lme4?

**Comment by RobertReynolds77** [comment]
No, is that a package? The point is largely moot now since I have managed to get things going on another computer and will finish the lessons there.

**Comment by seankross** [comment]
It is a package. Sorry for this inconvenience.
