### ISSUE TITLE
Exploratory Data Analysis - Lattice Plotting System: myedit("plot1.R") fails

### ISSUE THREAD

**Issue by parate** [swirldev/swirl#462]
Just upgraded to R3.2.5, maybe that's got something do do with it?

When running myedit("plot1.R") at 54% of the lesson "Lattice Plotting System" in the Exploratory Data Analysis course, I get:
`Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default `

**Comment by seankross** [comment]
See #434

**Comment by parate** [comment]
Thanks, works :)

**Comment by lxyea** [comment]
Hi, seankross, I got the same error as parate. but I don't understand your recommendation: "You are receiving this because you are subscribed to this thread. 
 Reply to this email directly or view it on GitHub"
What thread, reply to which email? which github... please kindly let me know.

**Comment by lxyea** [comment]
Hi #434 works, which is using:
options(editor = "internal")

Thanks!
