### ISSUE TITLE
Error in library(swirl)

### ISSUE THREAD

**Issue by vivagwb** [swirldev/swirl#463]
The OS is win10-64. the below error will occur when I load swirl. 
Wish your answer!
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  不存在叫‘bitops’这个名字的程辑包
Error: ‘swirl’程辑包或名字空间载入失败，

**Comment by seankross** [comment]
Try: 

```r
install.packages("bitops")
install.packages("swirl", dependencies = TRUE)
library(swirl)
swirl()
```

**Comment by vivagwb** [comment]
thank you ! the suggest is work
