### ISSUE TITLE
Regression Models Least Squares Estimation not loading

### ISSUE THREAD

**Issue by jrtheobald** [swirldev/swirl#464]
This is what I get upon selecting lesson 3:
`Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.`

Lessons 1 and 4 load and run fine.

**Comment by seankross** [comment]
See #434

**Comment by jrtheobald** [comment]
I tried what was suggested in #434 (`options(editor = 'internal')`), which worked except that now all scripts show up as separate boxes outside of RStudio as if I was working directly from R.  I restarted the R session in RStudio and now I get the same error as previously except now with any lesson, whereas before it was only the least squares estimation.

**Comment by jrtheobald** [comment]
function (name, file, title) 
{
    if (is.null(name) || is.function(name)) {
        if (is.null(name)) {
            if (!is.null(file) && nzchar(file)) 
                targetFile <- file
            else targetFile <- scratchFile
        }
        else {
            functionSrc <- .rs.deparseFunction(name, TRUE, FALSE)
            targetFile <- scratchFile
            writeLines(functionSrc, targetFile)
        }
        if (.Call("rs_editFile", targetFile)) {
            newFunc <- try(eval.parent(parse(targetFile)), silent = TRUE)
            if (inherits(newFunc, "try-error")) {
                stop(newFunc, "You can attempt to correct the error using ", 
                  title, " = edit()")
            }
            return(newFunc)
        }
        else {
            stop("Error occurred while editing function '", name, 
                "'")
        }
    }
    else edit(name, file, title, editor = defaultEditor)
}
<environment: 0x000000000b043490>

**Comment by seankross** [comment]
Hi @jrtheobald,

> which worked except that now all scripts show up as separate boxes outside of RStudio...

This is the "correct" behavior for now. In the next version of swirl scripts will open in new tabs in RStudio. Sorry for the inconvenience.
