### ISSUE TITLE
Issues with loading in Swirl - Functions

### ISSUE THREAD

**Issue by B5rnard** [swirldev/swirl#465]
Hi!
I'm having problems to load and submit my exercises on Swirl, specifically in the functions section, below is what I'm getting. Appreciate the help.

| The last R expression to be evaluated in a function will become the return value of that function. We want 
| this function to take one argument, x, and return x without modifying it. Delete the pound sign so that x is
| returned without any modification. Make sure to save your script before you type submit().

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
See #434
