### ISSUE TITLE
Problem when submitting my assignment

### ISSUE THREAD

**Issue by Yun-Han** [swirldev/swirl#466]
Every time I submit my assignment to Coursera. It occurs an error as follow.

Selection: 1
What is your email address? xxxx
What is your assignment token? pxDhbMlUDPxEh0mT
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

I run it in two different machines. But it doesn't work. Also, I tried your solution in #387 but failed.
Both R and Swirl are the latest version. 
Thanks!

**Comment by seankross** [comment]
Hi @Yun-Han,

Have you tried using a different internet connection to submit?

**Comment by NadyaKochetova** [comment]
Hi, I have same issue as Yun-Han,  Im getting "Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached" and unable to get credit for my swirl exercise. 
I have also had problems with  install_from_swirl("R Programming") command getting "Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached " error
I only managed to get swirl working by manually installing the entire course. 

PC: Windows 7 SP1 
64 bit
R Studio:  0.99/896
R - 3.3.0 -win

Thanks

**Comment by seankross** [comment]
See #475
