### ISSUE TITLE
Problem with installing "Getting and Cleaning Data" from the swirl courses

### ISSUE THREAD

**Issue by JahlaJazz** [swirldev/swirl#467]
I am experiencing some problems with installing the dependencies for "Getting and Cleaning Data". Has anyone else experienced this issue? Please help!

## Here is the message that I received:
**| Attempting to load lesson dependencies...
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’
**
## Following are the steps that lead to this response:
Step1 : library(swirl)
Step2: install_course_zip( path, multi = TRUE )    ## install all courses need for Data Science courses
## Received the following warning
Warning message:
In if (file.copy(dirs_to_copy, swirl_courses_dir(), recursive = TRUE)) { :
  the condition has length > 1 and only the first element will be used
Step3: swirl()
Step4:  Selected option 1 :  Getting and Cleaning Data
Step5: Selected option 1: Manipulating Data with dplyr
Step6: selected option 1 for the following
| This lesson requires the ‘dplyr’ package. Would you like me to install it for you now?
1: Yes
2: No
Selection: 1
## Received the following response:
| Trying to install package ‘dplyr’ now...
--- Please select a CRAN mirror for use in this session ---
also installing the dependencies ‘Rcpp’, ‘BH’

Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 1458176 != reported length 3225053
2: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 417792 != reported length 15529294
3: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
4: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'Rcpp/DESCRIPTION', probable reason 'No such file or directory'

Thanks in advance for any assistance

**Comment by JahlaJazz** [comment]
Sorry, but I overlooked including the sessioninfo. Here it is and hopefully it will provide more insight
 sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 10586)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.1

loaded via a namespace (and not attached):
Error in x[["Version"]] : subscript out of bounds
In addition: Warning message:
In FUN(X[[i]], ...) :
  DESCRIPTION file of package 'bitops' is missing or broken

**Comment by seankross** [comment]
Can you try installing Rcpp and dplyr before you start the course?

**Comment by JahlaJazz** [comment]
Hi SeanKross,
I tried to install Rcpp and received a message that the temporary installation could not be moved"
 
package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\Andre\Documents\R\win-library\3.2\file19704aa530e0\Rcpp’ to ‘C:\Users\Andre\Documents\R\win-library\3.2\Rcpp’

Following are the exact results
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
install.packages("Rcpp")
Installing package into ‘C:/Users/Andre/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) : 
  cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'
In addition: Warning message:
In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl failed: 'The operation timed out'
trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3224912 bytes (3.1 MB)
downloaded 3.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\Andre\Documents\R\win-library\3.2\file19704aa530e0\Rcpp’ to ‘C:\Users\Andre\Documents\R\win-library\3.2\Rcpp’

Thanks in advance for you help

**Comment by seankross** [comment]
Are you on a computer owned by your school or workplace?

**Comment by JahlaJazz** [comment]
I am on my personal laptop
