### ISSUE TITLE
Having problems with loading "Getting and Cleaning Data"

### ISSUE THREAD

**Issue by JahlaJazz** [swirldev/swirl#468]
This is a continuation of my last submission which I closed by accident. It was suggested that I install Rcpp and then dplyr. I tried to install Rcpp on my personal laptop but was told that the temp folder could not be moved. The following information follows
1. response for installing Rcpp
2. response for installing dplyr
3. session info

Thanks in advance for your help.
 

###  install.packages("Rcpp")
Installing package into ‘C:/Users/Andre/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Error in download.file(url, destfile = f, quiet = TRUE) : 
  cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'
In addition: Warning message:
In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl failed: 'The operation timed out'
trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3224912 bytes (3.1 MB)
downloaded 3.1 MB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\Andre\Documents\R\win-library\3.2\file19704aa530e0\Rcpp’ to ‘C:\Users\Andre\Documents\R\win-library\3.2\Rcpp’

The downloaded binary packages are in
        C:\Users\Andre\AppData\Local\Temp\RtmpywPe4y\downloaded_packages

### I also tried to install dplyr and following is the response

install.packages("dplyr")
Installing package into ‘C:/Users/Andre/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘Rcpp’, ‘BH’

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3224912 bytes (3.1 MB)
downloaded 3.1 MB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/BH_1.60.0-1.zip'
Content type 'application/zip' length 15233291 bytes (14.5 MB)
downloaded 6.1 MB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/dplyr_0.4.3.zip'
Content type 'application/zip' length 2548881 bytes (2.4 MB)
downloaded 524 KB

package ‘Rcpp’ successfully unpacked and MD5 sums checked
Warning: unable to move temporary installation ‘C:\Users\Andre\Documents\R\win-library\3.2\file197030b17add\Rcpp’ to ‘C:\Users\Andre\Documents\R\win-library\3.2\Rcpp’
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 6418432 != reported length 15233291
2: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 536576 != reported length 2548881
3: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
4: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'
> install.packages("dplyr")
Installing package into ‘C:/Users/Andre/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
also installing the dependencies ‘Rcpp’, ‘BH’

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/Rcpp_0.12.4.zip'
Content type 'application/zip' length 3224912 bytes (3.1 MB)
downloaded 2.2 MB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/BH_1.60.0-1.zip'
Content type 'application/zip' length 15233291 bytes (14.5 MB)
downloaded 284 KB

trying URL 'https://cran.revolutionanalytics.com/bin/windows/contrib/3.2/dplyr_0.4.3.zip'
Content type 'application/zip' length 2548881 bytes (2.4 MB)
downloaded 1.7 MB

Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 2273280 != reported length 3224912
2: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 290816 != reported length 15233291
3: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 1732608 != reported length 2548881
4: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
5: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'Rcpp/DESCRIPTION', probable reason 'No such file or directory'

## Here is the sessioninfo
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 10586)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.4

**Comment by JahlaJazz** [comment]
I think the prior submission, before the accidential close, was #467

**Comment by seankross** [comment]
Are you using a reliable internet connection? Can you change connections somehow?

**Comment by JahlaJazz** [comment]
I am using a wireless internet connection in my home. How can I change it and what are the options? Thanks for your help

**Comment by seankross** [comment]
First, make sure you have the latest version of R installed. It appears that you don't currently.

**Comment by JahlaJazz** [comment]
Okay, thanks for that advise. Just a few follow up questions
1. how do I un-install the current version ( to eliminate conflicts) ?
2. Where do I find the most current version and what is the version number?
Thanks for your help

**Comment by JahlaJazz** [comment]
The version that I current have ( according to sessionInfo ) is 3.2.4 revised (2016-03-16)
sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 10586)

**Comment by seankross** [comment]
The current version is 3.3.0. You can download R from here:
https://cran.r-project.org Installing a new version of R will completely
uninstall the old version.

**Comment by JahlaJazz** [comment]
Thank you SeanKross! I will follow your advise and get back to your shortly.
Thanks again!

**Comment by JahlaJazz** [comment]
Hello SeanKross,
I followed your suggestion and installed the current version of R ( 3.3.0 ). Everything seems to have been completed successfully. But, I am experiencing a problem whenever I try to access "Getting and Cleaning Data" from swirl. Following is a summary of the 1. steps taken, 2. the results received and 3. the sessionInfo ( Thanks for your help and patience )

## The Issue : Trying to get into "Getting and Clean Data" and selected option 2 for the installation of the dplyr package ( installed it earlier ) , but the selection of 2 is given a length greater than 1 and kicks be out of swirl.

## Steps taken
1. library(swirl)  => swirl() => specified user name => selected option 1 to continue
2. selected "4. Getting and Cleaning Data" from the swirl menu
3. selected "1: Manipulating Data with dplyr" and yes for the installing of the dplyr package : following is the system response . ( step4 is below this section )
 --------------------------------------------------------------------------------------------------------------------------------     
 Attempting to load lesson dependencies...

| This lesson requires the ‘dplyr’ package. Would you like me to install it for you now?

1: Yes
2: No

Selection: 1

| Trying to install package ‘dplyr’ now...
also installing the dependencies ‘assertthat’, ‘Rcpp’, ‘lazyeval’, ‘DBI’, ‘BH’

package ‘assertthat’ successfully unpacked and MD5 sums checked
package ‘Rcpp’ successfully unpacked and MD5 sums checked
package ‘lazyeval’ successfully unpacked and MD5 sums checked
package ‘DBI’ successfully unpacked and MD5 sums checked
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  cannot open the connection
In addition: Warning messages:
1: In download.file(url, destfile, method, mode = "wb", ...) :
  downloaded length 3371008 != reported length 15529281
2: In unzip(zipname, exdir = dest) : error 1 in extracting from zip file
3: In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'BH/DESCRIPTION', probable reason 'No such file or directory'
-----------------------------------------------------------------------------------------------------------------------------------------
4. initial swirl() again , along with step 2 and 3 above, but this time I answer no to the installation of dplyr.( selected option 2). Following are the result

| This lesson requires the ‘dplyr’ package. Would you like me to install it for you now?

1: Yes
2: No

Selection: 2       
    |   0%Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1
| Leaving swirl now. Type swirl() to resume.
_________________________________________________________________________________
## I selected 2 and was kicked out. Tried to get back into "Getting and Cleaning Data" several times but to no avail. 
__________________________________________________________________________________
## Here is the sessionInfo
R version 3.3.0 (2016-05-03)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 10 x64 (build 10586)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.1

loaded via a namespace (and not attached):
 [1] httr_1.1.0     magrittr_1.5   R6_2.1.2       tools_3.3.0    RCurl_1.95-4.8 yaml_2.1.13    memoise_1.0.0  crayon_1.3.1   stringi_1.0-1  stringr_1.0.0  digest_0.6.9   testthat_1.0.2
[13] bitops_1.0-6

**Comment by JahlaJazz** [comment]
I was able to resolve this issue by downloading each of the dependencies for dplyr locally, unzipping each and then install dplyr package. Thanks

**Comment by Watcher06** [comment]
Hi, I am having the same problem, can you tell me how you downloaded each of the dependencies locally
