### ISSUE TITLE
Problem in Matrix Section

### ISSUE THREAD

**Issue by allen-y** [swirldev/swirl#469]
At a certain point it just doesn't let me through and the error message is as follows.

```
Error in eval(expr, envir, enclos) : 
  could not find function "calculates_same_value"

| Leaving swirl now. Type swirl() to resume.
```

I have tried restarting the section or skip(), but neither worked. 

Here are the snapshots.
------
<img width="534" alt="screen shot 2016-05-11 at 16 36 46" src="https://cloud.githubusercontent.com/assets/18265392/15175095/5ff75f9e-1797-11e6-9b28-d578c841de67.png">
------
<img width="536" alt="screen shot 2016-05-11 at 16 36 58" src="https://cloud.githubusercontent.com/assets/18265392/15175097/640ef2ea-1797-11e6-9ca0-40bb878a78d7.png">

Could you please help me on this? Thanks in advance!

**Comment by seankross** [comment]
Try reinstalling swirl, it's possible you have an older version.

**Comment by ChrisBoomhower** [comment]
Sean, I am seeing the same error at the 44% mark for this module and can confirm I have version 2.4.1 installed. I'm working on this with a number of other students at the same time and we are all having the same problem. We're also experiencing an error during Module 3 of the R Programming Alt course with the following:

**| What do you think tf will look like?

1: a single logical value
2: a vector of 4 logical values

Selection: 2
Error in swirlExpectation(condition(object)) : 
  could not find function "is_equivalent_to"

| Leaving swirl now. Type swirl() to resume.**

Any help you can offer would be extremely appreciated. Thanks :)

**Comment by jdquick** [comment]
I ran into the same issues as above. I tried using versions 3.3 and 3.2.2 of R. My sessionInfo is identical to ChrisBoomhower's. We appreciate any help you can provide.

**Comment by seankross** [comment]
Hi,

I didn't realize that you were using R Programming Alt. Unfortunately R Programming Alt is no longer supported.

**Comment by jdquick** [comment]
OK, thank you very much for your help.

**Comment by allen-y** [comment]
I've tried reinstall the latest version of both R and swirl. The problem is solved. Thank you very much, Sean!
