### ISSUE TITLE
Token for completing the practical R excercise in "Getting and Cleaning Data"

### ISSUE THREAD

**Issue by JahlaJazz** [swirldev/swirl#471]
I am unable to locate the token required to receive credit for the R exercise in "Getting and Cleaning Data". Can anyone help with this? Thanks

**Comment by seankross** [comment]
See: https://github.com/swirldev/swirl/wiki/Coursera-FAQ

**Comment by JahlaJazz** [comment]
The above link has been review and the instruction have been followed, but to no avail.
Specifically, from the course content page the swirl assignment was selected, but there is not token on the right hand side. Follow is what I am seeing: ( following is the entire page )



During this course we'll be using the swirl software package for R in order to illustrate some key concepts. The swirl package turns the R console into an interactive learning environment. Using swirl will also give you the opportunity to get and clean data just like a data scientist would. In this programming assignment, you'll have the opportunity to practice some key concepts from this course.

0. Install R
•swirl requires R 3.0.2 or later. If you have an older version of R, please update before going any further. If you're not sure what version of R you have, type R.version.string at the R prompt. You can download the latest version of R from https://www.r-project.org/.
•Optional but highly recommended: Install RStudio. You can download the latest version of RStudio at https://www.rstudio.com/products/rstudio/.


1. Install swirl

Since swirl is an R package, you can easily install it by entering a single command from the R console:
install.packages("swirl")

If you've installed swirl in the past make sure you have version 2.2.21 or later. You can check this with:
packageVersion("swirl")


2. Load swirl

Every time you want to use swirl, you need to first load the package. From the R console:
library(swirl)


3. Install the Getting and Cleaning Data course

swirl offers a variety of interactive courses, but for our purposes, you want the one called Getting and Cleaning Data. Type the following from the R prompt to install this course:
install_from_swirl("Getting and Cleaning Data")


4. Start swirl and complete the lessons

Type the following from the R console to start swirl:
swirl()

Then, follow the menus and select the Getting and Cleaning Data course when given the option.

If you need help...

Visit the Frequently Asked Questions (FAQ) page to see if you can answer your own question immediately.

Search the Discussion Forums this course.

If you still can't find an answer to your question, then create a new thread under the swirl Programming Assignment sub-forum and provide the following information:
•A descriptive title
•Any input/output from the console (copy & paste) or a screenshot
•The output from sessionInfo()

Good luck and have fun!

For more information on swirl, visit swirlstats.com
















**Comment by kblocksom** [comment]
I am encountering the same issue. I don't see any assignment token on the page at all.

**Comment by seankross** [comment]
If you're both sure you're looking at the correct page you you still don't see you assignment token I recommend posting in the course forums or getting in contact with Coursera. I don't have any control over how Coursera makes these token available to their users. Sorry about that.

**Comment by gopalbhatta** [comment]
I am encountering the same issue. I just completed the exercise but there is no token in the right side. Anyone had a luck in locating the token?

**Comment by ShahinMo** [comment]
I have the same problem! there is no token!

**Comment by wfresch** [comment]
Same here

**Comment by wfresch** [comment]
You can find the token in Week 3 of the "Getting and Cleaning Data" course.  Week 3 contains tokens for "Manipulating Data with dplyr", "Grouping and Chaining with dplyr", and "Tidying Data with tidyr".

**Comment by raydot** [comment]
Guys, Swirl has nothing to do with Coursera.  This is a question for Coursera, not Swirl.

**Comment by Az4x4** [comment]
Seems like you just need to hit "next" in the top right

**Comment by berghout-chris** [comment]
Hi Guys. I was able to figure this out after some tinkering. At the course home page under the specific calendar week corresponding to the practice exercises you need a token for, select the "practice exercises" button. This will have the time remaining and circular figure associated with it. Your browser will then be directed to a Coursera page which generates the token code you need to enter into your r-console in  Swirl for extra credit.

Hope that helps!

**Comment by alexim2018** [comment]
SOLVED! Ok berghout-chris got me so tantalizingly close to the answer for finding the token but some sleuthing was still needed, hopefully these details will help. The course is [R Programming](https://www.coursera.org/learn/r-programming) at Coursera. Enroll and audit the course unless you want to trial/pay (audit link is small print at bottom of "7 Day Trial"). In the course under Overview, click on the week with the calendar icon next to it (in my case Week 1). Scroll down the page to "Practical R Exercises in swirl" then you will see the list of exercises that correspond to those you are working through in RStudio. Click the exercise you have completed and on the right side you will see "How to Submit" and there you will find the token that needs to be copied and pasted for swirl in RStudio to receive your credit.

**Comment by lidanyang237** [comment]
Hi, teacher!
I just finished the ' Basic Building Blocks' course in 'R Programming' using RStudio, but I don't know the assignment token. What should I do?

**Comment by Himerand** [comment]
I just finished the ' Basic Building Blocks' course in 'R Programming' using swirl,, but I don't know the assignment token. What should I do?

**Comment by dominick1984** [comment]
> SOLVED! Ok berghout-chris got me so tantalizingly close to the answer for finding the token but some sleuthing was still needed, hopefully these details will help. The course is [R Programming](https://www.coursera.org/learn/r-programming) at Coursera. Enroll and audit the course unless you want to trial/pay (audit link is small print at bottom of "7 Day Trial"). In the course under Overview, click on the week with the calendar icon next to it (in my case Week 1). Scroll down the page to "Practical R Exercises in swirl" then you will see the list of exercises that correspond to those you are working through in RStudio. Click the exercise you have completed and on the right side you will see "How to Submit" and there you will find the token that needs to be copied and pasted for swirl in RStudio to receive your credit.

thanks!

**Comment by jnl815** [comment]
> > SOLVED! Ok berghout-chris got me so tantalizingly close to the answer for finding the token but some sleuthing was still needed, hopefully these details will help. The course is [R Programming](https://www.coursera.org/learn/r-programming) at Coursera. Enroll and audit the course unless you want to trial/pay (audit link is small print at bottom of "7 Day Trial"). In the course under Overview, click on the week with the calendar icon next to it (in my case Week 1). Scroll down the page to "Practical R Exercises in swirl" then you will see the list of exercises that correspond to those you are working through in RStudio. Click the exercise you have completed and on the right side you will see "How to Submit" and there you will find the token that needs to be copied and pasted for swirl in RStudio to receive your credit.
> 
> thanks!

I was expecting to receive a certification through my email, but I guess not.. But this def worked after some hassle. Thank you so much!

**Comment by poisonivyr1** [comment]
> SOLVED! Ok berghout-chris got me so tantalizingly close to the answer for finding the token but some sleuthing was still needed, hopefully these details will help. The course is [R Programming](https://www.coursera.org/learn/r-programming) at Coursera. Enroll and audit the course unless you want to trial/pay (audit link is small print at bottom of "7 Day Trial"). In the course under Overview, click on the week with the calendar icon next to it (in my case Week 1). Scroll down the page to "Practical R Exercises in swirl" then you will see the list of exercises that correspond to those you are working through in RStudio. Click the exercise you have completed and on the right side you will see "How to Submit" and there you will find the token that needs to be copied and pasted for swirl in RStudio to receive your credit.

Solved my concern!! Thank you sooooo MUCH!!!!
