### ISSUE TITLE
Error in installation of swirl

### ISSUE THREAD

**Issue by SwarnenduSengupta** [swirldev/swirl#473]
Hey. I am getting an error which is this
Warning messages:
1: In install.packages("swirl", dependencies = TRUE) :
  installation of package ‘openssl’ had non-zero exit status
2: In install.packages("swirl", dependencies = TRUE) :
  installation of package ‘httr’ had non-zero exit status
3: In install.packages("swirl", dependencies = TRUE) :
  installation of package ‘swirl’ had non-zero exit status

After this
 > library("swirl")
Error in library("swirl") : there is no package called ‘swirl’

Please help me out.

**Comment by SwarnenduSengupta** [comment]
Try to install the packages separately.

**Comment by seankross** [comment]
Hi @SwarnenduSengupta,

What do you get as the result of `sessionInfo()`?

**Comment by stynejohn** [comment]
Hi @SwarnenduSengupta 

I am also facing the same issue. How to install the packages separately ?
