### ISSUE TITLE
Error in installation of R programming in swirl

### ISSUE THREAD

**Issue by qingaidexin** [swirldev/swirl#474]
The right step is : 
1.library(swirl)
2.install_from_swirl("R Programming")
3.swirl()
but my error in the second step：
1.library(swirl)
2.install_from_swirl("R Programming")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)
the R programming is not properly installed。
please help me

**Comment by qingaidexin** [comment]
install_course("R Programming")  就ok了

**Comment by seankross** [comment]
Hi @qingaidexin, 

Did `install_course("R Programming")` work for you? It seems there's something wrong with your internet connection otherwise.
