### ISSUE TITLE
Error in curl::curl_fetch_memory

### ISSUE THREAD

**Issue by seankross** [swirldev/swirl#475]
The following error is usually the result of your internet connection.

```
Error in curl::curl_fetch_memory(url, handle = handle) : 
Problem with the SSL CA cert (path? access rights?)
```

Try connecting to the internet through a different connection, and then submitting again.

**Comment by sugarcane29** [comment]
I've tried different modules, uninstalling/installing R and Swirl, using swirl via R-Studio, running R as an administrator, adding R to my firewall exceptions, but none has worked.

Also, I've tried using different internet connections. On my other system it works fine, even though both are Windows 10.

**Comment by chenyizhe** [comment]
I also has the same problem
I found the solution from the web(http://blog.csdn.net/wangishero/article/details/50859670)
somethine should be set before you enter the swirl, type as :

library(RCurl)
library(httr)
set_config( config( ssl_verifypeer = 0L ) )
library(swirl)
swirl()

**Comment by evayuezhang** [comment]
This instruction fixed my problem!
