### ISSUE TITLE
Need Method to Reset Data

### ISSUE THREAD

**Issue by Shumakriss** [swirldev/swirl#476]
I was in a swirl lesson and accidentally clobbered the data swirl setup for me. It would be good to be able to reset the data. Sample scenario below:

| Now it's clearer what information each column of pm0 holds. The measurements of particulate matter (pm25) are in the column named Sample.Value. Assign this
| component of pm0 to the variable x0. Use the m$n notation.

> pm0 <- pm0$Sample.Value

| Not exactly. Give it another go. Or, type info() for more options.

| Type x0 <- pm0$Sample.Value at the command prompt.

> x0 <- pm0$Sample.Value
Error in pm0$Sample.Value : $ operator is invalid for atomic vectors
> help()
> ?
+ 
+ )
Error: unexpected ')' in:
"
)"
> head(pm0)
[1]     NA     NA     NA  8.841 14.920  3.878

**Comment by seankross** [comment]
If you exit swirl and then pick up where you left off it should restore the data.

**Comment by Shumakriss** [comment]
Hi Sean, 

Thanks for the quick response. I tried that but unfortunately it seems not every change was applied to the data to match the step that I was on. I needed to run through the course again from the beginning. I don't have a copy of that part of the output though.
