### ISSUE TITLE
Swirl crashed at 53% in 'Lesson 2: Residuals' in 'Regression Models" course

### ISSUE THREAD

**Issue by rawgit** [swirldev/swirl#477]
It crashed in the lesson and is crashing straight away on resumption. It's even crashing straight away, having crashing once, with the same error on another lesson 'Least Squares Estimation'. Please resolve it ASAP because it is holding the submission of assignments. The error message is given below.

| Would you like to continue with one of these lessons?

1: Regression Models Residuals
2: No. Let me start something new.

Selection: 1

| Now we'll show you some R code which generates the left and right sides of
| this equation.  Take a moment to look it over. We've formed two 6-long
| vectors of variations, one for the slope and one for the intercept. Then
| we have two "for" loops to generate the two sides of the equation.

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367
