### ISSUE TITLE
Lesson 15 Case Study in Exploratory Data Analysis Missing Dependency

### ISSUE THREAD

**Issue by Shumakriss** [swirldev/swirl#478]
I just switched computers and found that the case study module for EDA was missing the "fields" dependency.

**Comment by seankross** [comment]
Are you experiencing an issue with swirl?

**Comment by Shumakriss** [comment]
Hi thanks for the consideration but I resolved it on my own by installing the fields package. I just wanted to track the issue in case someone else runs into it and doesn't know what to do.
