### ISSUE TITLE
 Error: correctName %in% names(delta) isn't true.

### ISSUE THREAD

**Issue by NaomiRadke** [swirldev/swirl#479]
In the 'R Programming Matrices and Data Frames' course I received the following error message and got kicked out of swirl:
 Error: correctName %in% names(delta) isn't true.
What's the problem?
I am using Windows
![unbenannt](https://cloud.githubusercontent.com/assets/19567229/15532514/7786af42-2260-11e6-9306-f10be1222a3c.PNG)

**Comment by seankross** [comment]
I'm having trouble reproducing this error. Does the problem persist if you restart the lesson?

**Comment by debdey** [comment]
Yes, I am also facing the same
