### ISSUE TITLE
Installation error of "Statistical Inference"

### ISSUE THREAD

**Issue by DonsonYeh** [swirldev/swirl#480]
Dears,

Environment: R Version 3.2.3 "Wooden Christmas-Tree"

> library(swirl)
Warning message:
package ‘swirl’ was built under R version 3.2.5 

> install_from_swirl("Statistical Inference")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Couldn't resolve host name

I am not sure if it's a good idea to uninstall the old R version and install the latest one can solve it. Please advise. Thanks.

Faithfully,
Donson

**Comment by seankross** [comment]
Try: `install_course("Statistical Inference")`

**Comment by DonsonYeh** [comment]
Hi Sean,

It works. I had installed it completely. Thank you.

Donson
