### ISSUE TITLE
Unable to get Coursera Credit

### ISSUE THREAD

**Issue by sugarcane29** [swirldev/swirl#486]
Hi,
Everytime I try to get Coursera credit for completing the Swirl assignments, I get the following error after entering the token id:
_**Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)**_

I've tried different modules, uninstalling/installing R and Swirl, using swirl via R-Studio, running R as an administrator, adding R to my firewall exceptions, but none has worked.

On another system, I use R-Portable, and over there, I don't get any issue.

Please help.

Thanks.

**Comment by sugarcane29** [comment]
Also, I've tried using different internet connections. On my other system it works fine, even though both are Windows 10.

**Comment by seankross** [comment]
Does your other system use a different internet connection? Have you tried using R-Portable on your current system?

**Comment by sugarcane29** [comment]
Hi Sean,
No. My other system used the same internet connection. I  didn't try with R-portable on my system, but will try that and let you know.

Are there any more details that you would about my system, that can help you debug?

**Comment by seankross** [comment]
Unfortunately these kinds of errors are specific to each individual's system and internet connection so they're difficult to debug. The best chance you have at debugging it is to find the code for submitting a particular lesson GitHub, look in `customTests.R`, and then try to execute the submission code yourself. I'm sorry I can't be more helpful.

**Comment by hemamali** [comment]
@sugarcane29 
Did you find a fix or a workaround for this issue? I get the same error message. My OS is windows 10. 

Thanks in advance,

**Comment by sugarcane29** [comment]
Nope. Didn't find anything. I am using another computer for getting credit.

On Sat, Jul 09, 2016 at 2:24 PM, hemamali < notifications@github.com [notifications@github.com] > wrote:
@sugarcane29 [https://github.com/sugarcane29]
Did you find a fix or a workaround for this issue? I get the same error message. My OS is windows 10.

Thanks in advance,

**Comment by zhengxinyanhhh** [comment]
Mine is like this....Do I need to reinstall a curl package?
| Would you like to receive credit for completing this course on
| Coursera.org?

1: No
2: Yes

Selection: 2
What is your email address? xxxxxxxxxx@qq.com
What is your assignment token? zxxxxx
Error in loadNamespace(name) : there is no package called ‘curl’

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
@zhengxinyanhhh Leave the lesson, then try: `install.packages("curl")`. You may need to restart R, but then try to get credit.

**Comment by PrathyushaVasanth** [comment]
Hi, I am problem while I am trying to get the credit. Can you please help me with this

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to www.coursera.org port 443: Timed out

Please help me out

**Comment by MadraghRua** [comment]
Folks I had this problem and corrected it as follows:
library(bitops)
library(RCurl)
library(httr)
set_config(config(ssl_verifypeer=0L))
library(swirl)
swirl()

The problem in my case was due to ssl connection errors. This set of commands allows the R language to ignore these errors and continue sending data. Look here for some more detail:
https://stackoverflow.com/questions/36997896/ignore-ssl-errors-in-r-httr-connection

**Comment by BethCalub** [comment]
Hi, I'm trying to start with my swirl Programming Exercise on Data Cleaning and I'm getting this error while installing

install_from_swirl("Getting and Cleaning Data")

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to github.com port 80: Timed out

Please help. Thanks

**Comment by seankross** [comment]
@BethCalub see: http://swirlstats.com/scn/getclean.html

**Comment by davidrajdgl** [comment]
Hi guys, 
This is a late reply, but still need to post it because it will help someone who will search (like me) in future. 

There may many machine depended errors when you cant submit your swirl assignment. One of the common is when you are with proxy settings. 
This can be solved by running the following code:

```
library(httr)
set_config(
  use_proxy(url="172.16.19.11", port=80)
)

```
Replace your proxy setup with url and port. 

Hope this helps.

**Comment by haqueSanaul** [comment]
@davidrajdgl - thanks lot, it helps !!!
