### ISSUE TITLE
Swirl exits when internal call for a script fails

### ISSUE THREAD

**Issue by SeanCrotty** [swirldev/swirl#487]
I'm working through the Getting and Cleaning Data: Grouping and Chaining with dplyr lesson and get the same error at this point. It appears that when the lesson tries to bring up the pre-written script, it fails and then automatically forces swirl to quit. I've restarted the computer and R-Studio, but get the same error. Any advice would be appreciated. 

![swirl_error1](https://cloud.githubusercontent.com/assets/11299033/15760923/2b28e90e-28db-11e6-8378-8a7fedd290d5.JPG)

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by SeanCrotty** [comment]
wonderful! Thanks Sean! My apologies for posting this to twitter first - I've got the protocol down now.

**Comment by seankross** [comment]
No problem. It doesn't matter where you post it, as long as you ask once in one place.
