### ISSUE TITLE
"Unexpected symbol" error in InitLesson.R

### ISSUE THREAD

**Issue by jrtheobald** [swirldev/swirl#489]
Upon attempt of loading Multivar examples 3 in the course regression models I receive the following error:

```
Error in source(initFile, local = TRUE) : 
  C:/Users/xxxxxxx/Documents/R/win-library/3.2/swirl/Courses/Regression_Models/MultiVar_Examples3/initLesson.R:16:1: unexpected symbol
15:                          
16: hunger
    ^
```

The packages 'datasets', 'stats', and 'graphics' load correctly prior to the error, then swirl closes.
This is the script in the file referenced in the error:
```
# For compatibility with 2.2.21
.get_course_path <- function(){
  tryCatch(swirl:::swirl_courses_dir(),
           error = function(c) {file.path(find.package("swirl"),"Courses")}
  )
}

# Put initialization code in this file. The variables you create
# here will show up in the user's workspace when he or she begins
# the lesson.

file.copy(from=file.path(file.path(.get_course_path(),
	"Regression_Models","MultiVar_Examples3","hunger.csv"),
          to="hunger.csv")
                         
hunger <-read.csv(file.path(.get_course_path(),
	"Regression_Models","MultiVar_Examples3","hunger.csv"))
```

I cannot find any unexpected symbol.

Thanks,
James T.

**Comment by seankross** [comment]
Does this happen in any other lessons? Also are you sure you have the latest version of R installed?

**Comment by jrtheobald** [comment]
No.  There are mistakes in the script.  I was able to correct them, and afterward the lesson worked fine.

**Comment by seankross** [comment]
What mistakes did you correct?

**Comment by stefansimik** [comment]
Confirming same problem here - no solution found yet...

**Comment by stefansimik** [comment]
Temporary help is:

1. to comment out the part of the code below
2. and copy the hunger.csv file manually
```
file.copy(from=file.path(file.path(.get_course_path(),
	"Regression_Models","MultiVar_Examples3","hunger.csv"),
          to="hunger.csv")
```

**Comment by jrtheobald** [comment]
There are 7 parentheses. I added an extra closing parenthesis which threw are error indicating that the "to" argument was missing. I noticed two "file.path" commands, so deleted one which resolved the problem.

**Comment by seankross** [comment]
This should be fixed if you install the regression models course using:

```r
install_course("Regression Models")
```

**Comment by simon19891101** [comment]
As @seankross said, reinstalling the course solves the problem.

**Comment by jrtheobald** [comment]
This is an old issue, and I think it has already been closed.

Thanks
