### ISSUE TITLE
Add RStudio Error to Wiki of common errors: Error in editor(file = file, title = title) :    argument "name" is missing, with no default

### ISSUE THREAD

**Issue by Fabi1080Coursera** [swirldev/swirl#492]
When using swirl in RStudio, a very common error is:

```
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
```

The solution, or workaround for this is to run this first:

`options(editor = "internal")`

Can you insert a "RStudio Check" that sets this option automatically? 
Also this should be added to the wiki. I can't edit it somehow.

**Comment by seankross** [comment]
This bug will be fixed in the next version of swirl, so I don't think it's necessary to add it to the wiki.
