### ISSUE TITLE
Can't load Swirl packages?

### ISSUE THREAD

**Issue by Juoko** [swirldev/swirl#493]
Problem: After installation of Swirl, can't use >library("swirl") to access swirl package. Recieve this error:

> 
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘magrittr’
> Error: package or namespace load failed for ‘swirl’

Picture of problem: http://i.imgur.com/TfGnsOB.png

Solutions I've tried:

1) Initially swirl installed to a temp folder; I moved all the zips into RStudio > R > Packages, but it didn't seem to help

2) I unzipped the Swirl .zip and attempted to access that from the library() function instead, but it didn't work.

After each change that I made, I tried restarting RStudio just in case that would help. I have been poking around the help pages on RStudio to figure out the solution on my own, but I think my nonexistent understanding of R is holding me back from making progress with the help pages.

I also tried to open bitops (which is one of the packages) but nothing happened when I tried - not even an error. Not sure why but maybe it will help us figure it out.

**Comment by Juoko** [comment]
I should add that I am using the latest versions of R and Rstudio for Windows 7 on 64 bit

**Comment by seankross** [comment]
Do you own the computer you're using?

**Comment by Juoko** [comment]
Yeah, I'm also the only user account. It's not for sale though :p

**Comment by seankross** [comment]
Hahaha. Have you tried using `install.packages("swirl", dependencies = TRUE)` to install swirl?

**Comment by Juoko** [comment]
I haven't. I just did and it installed everything again. I have a file in My Documents with all the packages,  I personally made a file in RStudio have all the packages, and I have a temp folder with the zips for all the packages.

Should I add them all to the library folder in R?

**Comment by seankross** [comment]
I'm a little confused, is there a reason you're manually managing the location of where R packages are installed?

**Comment by Juoko** [comment]
The temp folder of zips was made by the installation. The reason I made a file in RStudio was because I didn't know if it was appropriate for the packages to only be in My Documents (The installation put the packages there, and it's where RStudio seems to be trying to call them from). I haven't made any other changes to the R or RStudio directories post-installation.

**Comment by seankross** [comment]
So after running `install.packages("swirl", dependencies = TRUE)` does swirl work?

**Comment by Juoko** [comment]
No, this is in regular R now, in case it helps to see it from its point of view as well: http://i.imgur.com/E4bbsj0.png

After I installed swirl, I used the "packages" menu to load swirl, but all that happened was this error.

**Comment by seankross** [comment]
So what happens when you enter `library(swirl)`?

**Comment by Juoko** [comment]
I get this error:
http://i.imgur.com/OXvLqCE.png

This picture was taken in regular R, though I got the basically same error message in RStudio (you can see there is a slight difference, I quoted the RStudio error message in the original post, it's in the faded words).

**Comment by seankross** [comment]
What happens if you install magrittr and then try running swirl?

**Comment by Juoko** [comment]
It worked, thank you very much. I didn't even think to look for 'magrittr' in the list of packages. Sorry for the stupid "issue" ;D
