### ISSUE TITLE
Error in downloading swirl

### ISSUE THREAD

**Issue by DevendraJaiswal** [swirldev/swirl#494]
Error : object ‘compare’ is not exported by 'namespace:testthat'
i am getting this error and I have tried installing the "evaluate" package as well but I am getting the same error over and over again.
I have an R version of 3.0.2 and I am trying to install it on Ubuntu 14.04

Thanks for your help.

**Comment by seankross** [comment]
You should install the latest version of R, and also be sure that you've installed the latest version of testthat.

**Comment by DevendraJaiswal** [comment]
@seankross 
thanks..yeah it was because of that only..it installed like a charm on R 3.3.0
