### ISSUE TITLE
installation issuee

### ISSUE THREAD

**Issue by meenaravi** [swirldev/swirl#495]
unable to install dplyr package. argument "leength.out" must be of lenggth one
warning: unable to move temporary installation

**Comment by seankross** [comment]
Have you tried `install.packages("dplyr")` ?

**Comment by JeanUTHSC** [comment]
I'm having the same issue three years after this question being reported...and have tried install.packages("dplyr") but not help me:

| Could not install package ‘dplyr’!
  |                                                                                                                                           |   0%Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1
