### ISSUE TITLE
install_course() fails to connect to internet while install_from_swirl() works fine

### ISSUE THREAD

**Issue by kennethd** [swirldev/swirl#496]
RStudio 0.99.896 & r-base 3.3.0-1wily0 on Ubuntu "xenial", as well as Rstudio 0.99.902 & r-base 3.3.0-1~jessiecran on Debian "jessie".  no proxies or firewall involved. install.packages() also works fine.  CRAN mirror is "Global (CDN) - RStudio"

> install_course("Data Analysis")
Downloading: 5.3 kB     

| It looks like your internet connection is not working. Go to http://swirlstats.com/scn/ and download the
| .swc file that corresponds to the course you wish to install. After downloading the .swc run
| install_course() and choose the file you downloaded.
Error in install_course("Data Analysis") : 
  Could not connect to course file.
> install_from_swirl("Data Analysis")
  |=================================================================================================| 100%

| Course installed successfully!

> install_course("Mathematical Biostatistics Boot Camp")
Downloading: 5.3 kB     

| It looks like your internet connection is not working. Go to http://swirlstats.com/scn/ and download the
| .swc file that corresponds to the course you wish to install. After downloading the .swc run
| install_course() and choose the file you downloaded.
Error in install_course("Mathematical Biostatistics Boot Camp") : 
  Could not connect to course file.
> install_from_swirl("Mathematical Biostatistics Boot Camp")
  |=================================================================================================| 100%

| Course installed successfully!

**Comment by seankross** [comment]
The Data Analysis and Mathematical Biostatistics Boot Camp courses are no longer officially supported, and that's why they can't be installed with `install_course()`.
