### ISSUE TITLE
Swirl installed but could not load

### ISSUE THREAD

**Issue by SUMIT0206** [swirldev/swirl#499]
Swirl installed but could no load it
shoeing error
> local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)})
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘R6’
In addition: Warning message:
package ‘swirl’ was built under R version 3.3.1 
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
What happens after running this:

```r
install.packages("swirl", dependencies = TRUE)
library(swirl)
swirl()
```

**Comment by SUMIT0206** [comment]
> install.packages("swirl", dependencies = TRUE)
Installing package into ‘C:/Users/Admin/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL '
https://cloud.r-project.org/bin/windows/contrib/3.3/swirl_2.4.2.zip'
Content type 'application/zip' length 212528 bytes (207 KB)
downloaded 207 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Admin\AppData\Local\Temp\RtmpGChOEt\downloaded_packages
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :
  there is no package called ‘R6’
In addition: Warning message:
package ‘swirl’ was built under R version 3.3.1
Error: package or namespace load failed for ‘swirl’
> swirl()
Error: could not find function "swirl"
>

**Comment by SUMIT0206** [comment]
GOT  THIS 
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘R6’
In addition: Warning message:
package ‘swirl’ was built under R version 3.3.1 
Error: package or namespace load failed for ‘swirl’
> swirl()
Error: could not find function "swirl"
>

**Comment by seankross** [comment]
What do you get as the result of `R.version.string`?

**Comment by SUMIT0206** [comment]
[1] "R version 3.3.0 (2016-05-03

**Comment by SUMIT0206** [comment]
DONE
thanks seankross

**Comment by brust8** [comment]
How did you resolve this issue?

**Comment by MikeInfo2015** [comment]
I am having a problem loading swirl.  i can install it fine but the library("swirl")  command is causing problems.  It is strange as swirl has worked in the past. I reinstalled with dependencies+True and  I also can find.package("swirl") as well.
This is my error below after library("swirl")
_Error : object ‘compare’ is not exported by 'namespace:testthat'
In addition: Warning message:
package ‘swirl’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘swirl’_

**Comment by seankross** [comment]
@MikeInfo2015 You need to install the latest version of testthat and swirl.

**Comment by sangeethavelu83** [comment]
when i try 'load package' i got ths message "local({pkg <- select.list(sort(.packages(all.available = TRUE)),graphics=TRUE)
+ if(nchar(pkg)) library(pkg, character.only=TRUE)}) ",why i am i getting this?

**Comment by aanupkumar08** [comment]
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):  there is no package called ‘R6’
