### ISSUE TITLE
unit test: correct answer should pass associated answer tests

### ISSUE THREAD

**Issue by WilCrofter** [swirldev/swirl#50]
Gina's idea, though I'm posting it.

If skip() is invoked, swirl acts for the user using a module's CorrectAnswer column. The  correct answer is then subjected to tests, just as the user's answer would have been. If the correct answer fails to pass its own tests, e.g., because of a typo, the question will be impossible to skip.

Unit tests could insure that a module's correct answers pass their associated tests.

**Comment by ChihChengLiang** [comment]
Thinking the same. I'm developing a package to test a course, so automatic testing and CI would be possible for instructors. Here's my repo: https://github.com/ChihChengLiang/swirlitest, forks are welcomed!

The package can run through all the cmd_questions, unit testing is not yet achieved at the moment. However, it can still help to teaching assistants to scan bugs of a course quickly on different OS environments.

I'm working on testing the official courses, the package may be proved useful when it can test all official courses

**Comment by ncarchedi** [comment]
Very cool!! @seankross, you should take a look. Could be
possibly incorporated into swirlify/swirlools once it matures.

**Comment by seankross** [comment]
@ChihChengLiang this is great! Please keep us up to date with your developments on this project. I'd be very interested in folding this into [swirlify](https://github.com/swirldev/swirlify).

**Comment by ChihChengLiang** [comment]
Thanks @ncarchedi  and @seankross ! Looks like I'm on the right track. Will keep you updated, and also please let me know what's the most wanted feature if any.

**Comment by seankross** [comment]
@ChihChengLiang is this code/ these features incorporated into swirldev/swirlify#15?

**Comment by ChihChengLiang** [comment]
Exactly! all codes and features are included in https://github.com/swirldev/swirlify/pull/15

**Comment by seankross** [comment]
In that case can I close this issue?

**Comment by ChihChengLiang** [comment]
Sure, feel free to do it. Sorry for not referring the PR to this issue before.
