### ISSUE TITLE
Regression Models Lesson 12: Binary Outcomes Error

### ISSUE THREAD

**Issue by zer0won** [swirldev/swirl#501]
I get the following error during this lesson one or two prompts after creating the model:

`Error in xy.coords(x, y) : 'x' and 'y' lengths differ`

The error appears right after the following prompt:

`| The probabilities estimated by logistic regression using glm() are represented by the black curve. It is
| more reasonable than our crude estimate in several respects: It increases smoothly with score, it
| estimates that 15 points give the Ravens a 50% chance of winning, that 28 points give them an 80% chance,
| and that 55 points make a win very likely (98%) but not absolutely certain.`

`Error in xy.coords(x, y) : 'x' and 'y' lengths differ`

`| Leaving swirl now. Type swirl() to resume.`

I've tried uninstalling and reinstalling the swirl package and the individual course, but I've had no luck resolving this, I get the error every time. I'm using R version 3.3 and RStudio 0.99.902. Any ideas?

**Comment by seankross** [comment]
Hi @zer0won,

I'm having trouble reproducing this error. Are you sure your global environment is empty before you start this lesson?
