### ISSUE TITLE
Confusing error when downloading jpeg package

### ISSUE THREAD

**Issue by dsdesrosiers** [swirldev/swirl#502]
Trying to run swirl for Stat Inference class > Variance module.

Was told I needed jpeg package...said yes to download... output thread is below.

Exited swirl and was able to get jpeg package outside of swirl environment. Resuming swirl was successful.

Some confusion in error message. Perhaps by the time you get get to this course users are savvy enough to plug thru a workaround but the error message below was pretty confusing initially. 

Thanks and thanks for the swirl package.

Danielle
=============================

| Trying to install package ‘jpeg’ now...
--- Please select a CRAN mirror for use in this session ---
Warning: failed to download mirrors file (cannot open URL 'https://cran.r-project.org/CRAN_mirrors.csv'); using local file 'C:/PROGRA~1/R/R-33~1.0/doc/CRAN_mirrors.csv'
Warning: unable to access index for repository https://cran.mtu.edu/src/contrib:
  cannot open URL 'https://cran.mtu.edu/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.mtu.edu/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.mtu.edu/bin/windows/contrib/3.3/PACKAGES'

| Could not install package ‘jpeg’!

  |                                                                            
  |                                                                      |   0%Error in seq.default(0, 1, length = nrow(e$les)) : 
  argument 'length.out' must be of length 1
In addition: Warning messages:
1: In download.file(url, destfile = f, quiet = TRUE) :
  InternetOpenUrl failed: ''
2: package ‘jpeg’ is not available (for R version 3.3.0) 

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Did you ever get this working?

**Comment by dsdesrosiers** [comment]
Sean -

I'm sorry I missed this earlier. I installed the dev version of swirl from github. 

Danielle
