### ISSUE TITLE
Error message in swirl; course Statistical Inference: Asymptotics

### ISSUE THREAD

**Issue by jcwalmsley** [swirldev/swirl#505]
| Would you like to continue with one of these lessons?

1: Statistical Inference Asymptotics

2: No. Let me start something new.

Selection: 1

| Attemping to load lesson dependencies...

| Package ‘ggplot2’ loaded correctly!

at this point in the exercise;

| We know from the CLT that for large n, the sample mean is normal with mean mu and standard

| deviation sigma/sqrt(n). We also know that 95% of the area under a normal curve is within

| two standard deviations of the mean. This figure, a standard normal with mu=0 and sigma=1,

| illustrates this point; the entire shaded portion depicts the area within 2 standard

| deviations of the mean and the darker portion shows the 68% of the area within 1 standard

| deviation.

==============

Error: geom_ribbon requires the following missing aesthetics: ymax

| Leaving swirl now. Type swirl() to resume.

==============

> sessionInfo()
R version 3.1.1 (2014-07-10)
Platform: x86_64-apple-darwin10.8.0 (64-bit)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gtable_0.1.2    survival_2.38-1 ggplot2_1.0.1   swirl_2.2.21   

loaded via a namespace (and not attached):
 [1] bitops_1.0-6     colorspace_1.2-6 digest_0.6.8     httr_0.6.1       labeling_0.3    
 [6] magrittr_1.5     MASS_7.3-40      munsell_0.4.2    plyr_1.8.2       proto_0.3-10    
[11] Rcpp_0.11.6      RCurl_1.95-4.6   reshape2_1.4.1   scales_0.2.4     splines_3.1.1   
[16] stringi_0.4-1    stringr_1.0.0    testthat_0.9.1   tools_3.1.1      yaml_2.1.13  

===================
I am getting this message which ends the session and prevents me from continuing or resuming or skipping to the next section. I haven't found a way to solve this yet so any assistance would be appreciated.

Thanks

**Comment by seankross** [comment]
You should update swirl and ggplot2, then let me know if you are still having this issue.

**Comment by jcwalmsley** [comment]
Hi Sean,

Thanks, it seems to be working now.  I appreciate your help.

James
