### ISSUE TITLE
error in Practice Programming Assignment: swirl Lesson 1: Lattice Plotting System

### ISSUE THREAD

**Issue by maheshwickramarachchi** [swirldev/swirl#506]
Hi,
I get this error  after completing 54% of the lesson. Could someone please tell me how should I proceed....:(

| Again, the values match the plot. That's reassuring. We've copied
| some code from the slides for you. To see it, type
| myedit("plot1.R"). This will open your editor and display the R
| code in it.

> myedit("plot1.R")
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
Called from: editor(file = file, title = title)
Browse[1]> 

**I tried to skip the step by typing skip(). but still it doesn't  allow me to move forward and the same error appears again and again.**

> myedit("plot1.R")
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
Called from: editor(file = file, title = title)
Browse[1]> c
> skip()
Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default
Called from: editor(file = file, title = title)
Browse[1]> Q

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
See https://github.com/swirldev/swirl/issues/434#issuecomment-201907367
