### ISSUE TITLE
Unable to find the code for Swirl mean() function

### ISSUE THREAD

**Issue by money3030** [swirldev/swirl#508]
# You're free to implement the function my_mean however you want, as long as it
# returns the average of all of the numbers in `my_vector`.
#
# Hint #1: sum() returns the sum of a vector.
# 	Ex: sum(c(1, 2, 3)) evaluates to 6
#
# Hint #2: length() returns the size of a vector.
# 	Ex: length(c(1, 2, 3)) evaluates to 3
#
# Hint #3: The mean of all the numbers in a vector is equal to the sum of all of
#		   the numbers in the vector divided by the size of the vector.
#
# Note for those of you feeling super clever: Please do not use the mean()
# function while writing this function. We're trying to teach you something 
# here!
#
# Be sure to save this script and type submit() in the console after you make 
# your changes.

my_mean <- function(my_vector) {
  # Write your code here!
  # Remember: the last expression evaluated will be returned! 
}
I get below prompt.

my_vector <- sum(c(1,2,3))/length(c(1,2,3))
> my_vector
[1] 2
> submit()

| Sourcing your script...

| One more time. You can do it!

| Use the sum() function to find the sum of all the numbers in the vector. Use the length() function to find the size of the
| vector.

**Comment by seankross** [comment]
You need to edit the file that opens up, save the file, and then enter `submit()` into the R console.

**Comment by money3030** [comment]
Didn't get the answer....plz check below.

> options(editor = "internal")
> library(swirl)

| Hi! Type swirl() when you are ready to begin.

Warning message:
package ‘swirl’ was built under R version 3.2.5 
> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself
| something unique.

What shall I call you? Maneesh Gupta

| Would you like to continue with one of these lessons?

1: R Programming Functions
2: No. Let me start something new.

Selection: 1



| Make sure to save your script before you type submit().

> my_vector <- sum(c(1,2,3))/length(c(1,2,3))
> my_vector
[1] 2
> submit()

| Sourcing your script...


| Keep trying!

| Use the sum() function to find the sum of all the numbers in the vector. Use the length() function to find the size of the
| vector.

**Comment by seankross** [comment]
> Didn't get the answer....plz check below.

Could you please clarify what question you're asking?

**Comment by money3030** [comment]
#319.

**Comment by seankross** [comment]
It seems that you're trying to define the function in the R console. Instead you should define the function inside of the script that opens up in the text editor, save that script, and then enter `submit()` into the R console. If that doesn't work please let me know.

**Comment by money3030** [comment]
I saved the below code in the file that opens up. Then I saved it. but getting again the same error.

my_mean <- function(my_vector) {
  sum(c(1,2,3))/length(c(1,2,3))
  }

error is..

> submit()

| Sourcing your script...


| That's not exactly what I'm looking for. Try again.

| Use the sum() function to find the sum of all the numbers in the vector. Use the length() function to find the size of the
| vector.
Please help.

**Comment by seankross** [comment]
Your function will only find the mean of `c(1, 2, 3)`. Think about how can you write the function so it will find the mean of any numeric vector.

**Comment by money3030** [comment]
I tried...but not getting solution>>>>>

**Comment by seankross** [comment]
See https://gist.github.com/seankross/912fe3b9f19a91b0a7bd

**Comment by shashankajit14** [comment]
I saved the below code in script file:

my_mean <- function(my_vector) {
   sum1 = sum(my_vector)
   length1 = length(my_vector)
   mean1 = sum1/length1
   my_vector
}
 The error:
Use the sum() function to find the sum of all the numbers in the vector. Use the length() function to find the
| size of the vector.

Can you please Help

**Comment by kumarpraveen091** [comment]
my_mean <- function(my_vector) {
  sum(my_vector)/length(my_vector)
}
submit()

**Comment by DubovinaDj** [comment]
mathalope.co.uk/2015/03/08/swirl-r-programming-lesson-9-functions/
