### ISSUE TITLE
error - Exploratory data analysis, 11 - hierachical cluster analysis

### ISSUE THREAD

**Issue by maheshwickramarachchi** [swirldev/swirl#510]
Hi,
In swirl lesson under Exploratory data analysis, 11 - cluster analysis i get this error. Could please tell me a way to get this sorted. 

Error in xy.coords(x, y, xlabel, ylabel, log) : 
  'x' and 'y' lengths differ
In addition: Warning message:
In dist(mt) : NAs introduced by coercion

| Leaving swirl now. Type swirl() to resume.

Thanks.

**Comment by maheshwickramarachchi** [comment]
...

  |==================                                              |  27%

| Run the R command dist with the argument dataFrame to compute the
| distances between all pairs of these points. By default dist uses
| Euclidean distance as its metric, but other metrics such as Manhattan,
| are available. Just use the default.
I reinstalled swirl and tried the solutions given in https://github.com/swirldev/swirl/issues/384 
but still the error exists. Please help me :(
warning messages from top-level task callback 'mini'
Warning message:
In dist(mt) : NAs introduced by coercion

**Comment by seankross** [comment]
Were you able to get this lesson to work?
