### ISSUE TITLE
Better way of including Courses in Swirl

### ISSUE THREAD

**Issue by ChaiBapchya** [swirldev/swirl#511]
Given that there are a considerable amount of issues raised revolving around the "install_from_swirl()" method. 
I myself stuck at Timeout reached error from curl::curl_fetch_memory(url, handle = handle)
A foolproof and simpler way of doing it would be better.

**Comment by seankross** [comment]
You can find instructions for manually installing a course here: http://swirlstats.com/scn/getclean.html
