### ISSUE TITLE
error -Exploratory data analysis, 11 - hierarchical cluster analysis 

### ISSUE THREAD

**Issue by maheshwickramarachchi** [swirldev/swirl#512]
hi,

I get this error after i completed  79% of the lesson. could you please tell me what should i do. i would be much grateful if any one could give me a solution asap since i have to submit my coursera assignment tonight.    

| We've subsetted some vehicle data from mtcars, the Motor Trend Car
| Road Tests which is part of the package datasets. The data is in
| the matrix mt and contains 6 factors of 11 cars. Run heatmap now
| with mt as its only argument.

> skip()
Error in heatmap(mt) : 'x' must be a numeric matrix

thanks!

**Comment by seankross** [comment]
I'm having trouble reproducing this error. Are you sure you created `heatmap` in a previous step? Did you try restarting the lesson?

**Comment by egruhn** [comment]
I am getting the same error when applying heatmap(mt) in lesson 11.

| We've subsetted some vehicle data from mtcars, the Motor Trend Car Road Tests which
| is part of the package datasets. The data is in the matrix mt and contains 6 factors
| of 11 cars. Run heatmap now with mt as its only argument.

> heatmap(mt)
Error in heatmap(mt) : 'x' must be a numeric matrix

I have restarted the lesson 4 times now in both R and R Studio
