### ISSUE TITLE
Mean function gives an error 

### ISSUE THREAD

**Issue by Nastya93** [swirldev/swirl#514]
1.R programming
2. sapply&tapply
3. Problem: **Mean function gives an error, while I just paste given formulae**. 
``| If you take the arithmetic mean of a bunch of 0s and 1s, you get the proportion of 1s. Use tapply(flags$animate, flags$landmass, mean) to apply the mean function to
| the 'animate' variable separately for each of the six landmass groups, thus giving us the proportion of flags containing an animate image WITHIN each landmass
| group.

> tapply(flags$animate,flags$landmass,mean)
Error in 1:ncol(m) : argument of length 0

Problem definetely lies in mean, because replacing mean() with sum() gives expected result
`> play()

| Entering play mode. Experiment as you please, then type nxt() when you are ready to resume the lesson.

> tapply(flags$animate, flags$landmass, sum)
 1  2  3  4  5  6 
13  3  4  7  6  6 
> 
`
> 
4. Windows
5. `R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7600)

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] swirl_2.4.2

loaded via a namespace (and not attached):
 [1] httr_1.2.1     magrittr_1.5   R6_2.1.2       tools_3.3.1    RCurl_1.95-4.8 yaml_2.1.13    crayon_1.3.2   stringi_1.1.1  stringr_1.0.0  digest_0.6.9  
[11] testthat_1.0.2 bitops_1.0-6  
`

**Comment by seankross** [comment]
I suggest restarting this course, I can't reproduce the error. The code: `tapply(flags$animate, flags$landmass, mean)` should print:

```
        1         2         3         4         5         6 
0.4193548 0.1764706 0.1142857 0.1346154 0.1538462 0.3000000 
```
