### ISSUE TITLE
can't fetch any of the four courses....

### ISSUE THREAD

**Issue by zhengxinyanhhh** [swirldev/swirl#518]
i am getting to learn R by using swirl, but somehow it goes like this..I don't know what am I supposed to do ..
 
| To begin, you must install a course. I can install a course for you from the
| internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options and
| directions for installing courses yourself. (If you are not connected to the
| internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
5: Don't install anything for me. I'll do it myself.

Selection: 1

| Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in R’
| right now. Are you sure you have an internet connection? If so, would you like to
| try again or visit the course repository for instructions on how to install a
| course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.

**Comment by seankross** [comment]
You can find manual installation instructions here: http://swirlstats.com/scn/rprog.html
