### ISSUE TITLE
Unable to install "R Programming"

### ISSUE THREAD

**Issue by eravis** [swirldev/swirl#520]
Hello,

While trying to install "R Programming", I've got the following error message using a Mac:

> install_from_swirl("R Programming")

Error in loadNamespace(name) : there is no package called ‘curl’

I found the below alternative manual install on GitHub (after downloading the zip file) but it does not work either:

> install_course_zip("~/Downloads/swirl_courses-master.zip", multi=TRUE, which_course="R Programming")

Error in unzip(path, list = TRUE)

Regards,

Emmanuel.

**Comment by seankross** [comment]
Try:

```r
install.packages("curl")
install_course("R Programming")
```

or see the manual install instructions here:

http://swirlstats.com/scn/rprog.html

**Comment by eravis** [comment]
It works.
Thanks.

**Comment by ApoorvaBans** [comment]
It worked for me too! Thank you!
