### ISSUE TITLE
swirl installation issue

### ISSUE THREAD

**Issue by wlaa21** [swirldev/swirl#521]
I read through the recent issues with people experiencing similar problems with installing/opening swirl, but I haven't found a solution yet.  I am using Windows and this is what I get after running sessionInfo()

R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1

**--This is what I get after running install.packages("swirl")**

Installing package into ‘C:/Users/aubre/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘stringi’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’

Packages which are only available in source form, and may need
  compilation of C/C++/Fortran: ‘stringi’ ‘jsonlite’ ‘mime’
  ‘curl’ ‘openssl’ ‘bitops’ ‘testthat’ ‘yaml’ ‘RCurl’ ‘digest’
  These will not be installed
installing the source packages ‘stringr’, ‘httr’, ‘swirl’

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.0.0.tar.gz'
Content type 'application/x-gzip' length 34880 bytes (34 KB)
downloaded 34 KB

trying URL 'https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz'
Content type 'application/x-gzip' length 133398 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/src/contrib/swirl_2.4.2.tar.gz'
Content type 'application/x-gzip' length 98565 bytes (96 KB)
downloaded 96 KB

ERROR: dependency 'stringi' is not available for package 'stringr'
* removing 'C:/Users/aubre/Documents/R/win-library/3.3/stringr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\aubre\Documents\R\win-library\3.3" C:\Users\aubre\AppData\Local\Temp\RtmpqGxQJV/downloaded_packages/stringr_1.0.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘stringr’ had non-zero exit status
ERROR: dependencies 'jsonlite', 'mime', 'curl', 'openssl' are not available for package 'httr'
* removing 'C:/Users/aubre/Documents/R/win-library/3.3/httr'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\aubre\Documents\R\win-library\3.3" C:\Users\aubre\AppData\Local\Temp\RtmpqGxQJV/downloaded_packages/httr_1.2.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies 'stringr', 'testthat', 'httr', 'yaml', 'RCurl', 'digest' are not available for package 'swirl'
* removing 'C:/Users/aubre/Documents/R/win-library/3.3/swirl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\aubre\Documents\R\win-library\3.3" C:\Users\aubre\AppData\Local\Temp\RtmpqGxQJV/downloaded_packages/swirl_2.4.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\aubre\AppData\Local\Temp\RtmpqGxQJV\downloaded_packages’

**--And then this is what I get after running library(swirl)**

Error in library(swirl) : there is no package called ‘swirl’

Thanks in advance for your help!

**Comment by seankross** [comment]
What happens if you try `install.packages("stringi")`?

**Comment by wlaa21** [comment]
> install.packages("stringi")
Installing package into ‘C:/Users/aubre/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need
  compilation of C/C++/Fortran: ‘stringi’
  These will not be installed

But, I was able to install stringi and swirl using a different cran mirror:
> install.packages('swirl',repo='http://nbcgib.uesc.br/mirrors/cran')

**Comment by seankross** [comment]
What happens when you try to load swirl now?

**Comment by wlaa21** [comment]
It works now after using the different cran mirror.  Thank you!
