### ISSUE TITLE
R Programming >9.Functions >~91% Creating 'I love R!' using the %p% operator

### ISSUE THREAD

**Issue by rbnphlp** [swirldev/swirl#525]
Hi ,
Aplogies if this has been reported before.
Just thought I might let you know of the issue with the above assignemtn.
Swirl instucts at 91% completions of the above course to do the following:

> You made your own binary operator! Let's test it out. Paste together the strings:
> | 'I', 'love', 'R!' using your new binary operator.

Then  swirl outputs the follwoing as the right answer:

> Entering the following correct answer for you...
> > > 'I' %p% 'love' %p% 'R!'
> > [1] "I love R!"
> > 
> > | You are doing so well!

i.e the question intially should read

> Paste together the strings:
>  "I love R!" using your new binary operator.

**Comment by seankross** [comment]
The question asks the user to paste together three separate strings: `"I"`, `"love"`, and `"R!"`. I think that your suggestion is more confusing compared to what's already written.

**Comment by rbnphlp** [comment]
fair enough .I did not read swirl's suggestion properly
