### ISSUE TITLE
Error: in loading swirl with function library(swirl) ;Windows OS; R version 3.3.1; package version of swirl 2.4.2

### ISSUE THREAD

**Issue by pooh5** [swirldev/swirl#530]
Cannot load swirl in step 2

**Comment by seankross** [comment]
What happens when you run:

```r
install.packages("swirl")
library(swirl)
```

**Comment by pooh5** [comment]
When I run install.packages("swirl"), it asks me to select CRAN mirror. I did not know which one to select, so i selected the first one; it loads some package. But when I run library(swirl) it shows an error.


> install.packages("swirl")
Installing package into ‘C:/Users/Lenovo/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cloud.r-project.org/bin/windows/contrib/3.3/swirl_2.4.2.zip'
Content type 'application/zip' length 211781 bytes (206 KB)
downloaded 206 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\Lenovo\AppData\Local\Temp\RtmpY18nox\downloaded_packages
> library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘magrittr’
In addition: Warning message:
package ‘swirl’ was built under R version 3.3.1 
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
Where are you geographically located?

**Comment by pooh5** [comment]
India

**Comment by afabafa** [comment]
Similar things, happend to me,  when I tried to install swirl:

> install.packages("swirl")
Installing package into ‘C:/Users/abiiiii/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.4.2.zip'
Content type 'application/zip' length 212118 bytes (207 KB)
downloaded 207 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\abiiiii\AppData\Local\Temp\RtmpcjhSg7\downloaded_packages

> library("swirl")
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
In addition: Warning message:
package ‘swirl’ was built under R version 3.2.5 
Error: package or namespace load failed for ‘swirl’

**Comment by seankross** [comment]
Whenever you see:

> there is no package called ‘some package’

Try installing that package individually. Let me know if that helps.
