### ISSUE TITLE
Default swirl_data_dir should reside in $HOME

### ISSUE THREAD

**Issue by dgoerger** [swirldev/swirl#534]
Hello!

I'm working to package swirl for Fedora, and our users have hit the issue described in #400, requiring runtime export of something akin to

```
swirl_options(swirl_data_dir = "~/.swirl")
```

Is it possible to set the default to somewhere in $HOME? Or, absent that, is there some way to export this as an R environment variable so that we can set this globally for all our students?

**Comment by seankross** [comment]
Hi @dgoerger,

Have you read [this document](https://stat.ethz.ch/R-manual/R-devel/library/base/html/Startup.html)? It has some details about where you would want to put some R code that would set the appropriate swirl options.

**Comment by dgoerger** [comment]
I hadn't! This works to save to the per-user `~/.swirl`:

```
$ cat /usr/lib64/R/etc/Rprofile.site 
# workaround for https://github.com/swirldev/swirl/issues/534
setHook(packageEvent("swirl", "onLoad"),
  swirl::swirl_options(swirl_data_dir = ".swirl"))
```

While that works well for our particular shared computing environment (because we manage the whole system anyway), it doesn't help for automated installation from the package manager---namely, the R-swirl package can't own the sitewide R config file.

If we want to apply a Fedora-specific patch before compiling the RPM, am I correct in guessing that we should just need to change `R/options.R` line 11:

```
file.path(find.package("swirl"), "user_data")
```

to something more suitable?

Thanks for your help!

**Comment by seankross** [comment]
You're correct. You might also want to change:
https://github.com/swirldev/swirl/blob/master/R/options.R#L22

**Comment by dgoerger** [comment]
Thanks! It works perfectly. We're actually installing swirl_courses system-wide, too, so that all courses are automatically available to all students.

Pre-built packages and the SRPM are [here](https://copr.fedorainfracloud.org/coprs/dgoerger/yale-zoo/package/R-swirl/).

Thanks again!

**Comment by seankross** [comment]
Good to hear! Let me know if you have any other questions.
