### ISSUE TITLE
Guys can anyone tell me why this is showing?

### ISSUE THREAD

**Issue by jatinsehgal15** [swirldev/swirl#535]
install.packages("swirl")
Warning: unable to access index for repository https://cran.cnr.berkeley.edu/src/contrib:
  cannot open URL 'https://cran.cnr.berkeley.edu/src/contrib/PACKAGES'
Warning: unable to access index for repository https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3:
  cannot open URL 'https://cran.cnr.berkeley.edu/bin/windows/contrib/3.3/PACKAGES'
Warning message:
package ‘swirl’ is not available (for R version 3.3.1)

**Comment by seankross** [comment]
Looks like R is having trouble finding swirl on CRAN. What's your geographic location?

**Comment by jatinsehgal15** [comment]
I live in New Delhi, India

**Comment by seankross** [comment]
Try the following: `install.packages("swirl", repos = "http://ftp.iitm.ac.in/cran/")`

**Comment by jatinsehgal15** [comment]
Hi Sean, can you explain that to me? How's it different from the earlier
one?

**Comment by seankross** [comment]
You may have an easier time connecting to a server that hosts R packages that is geographically closer to you.

**Comment by jatinsehgal15** [comment]
I'll try this out and tell you how it pans out. Thanks Sean.
