### ISSUE TITLE
R 3.3.1 Win - Swirl - Installing Error

### ISSUE THREAD

**Issue by KazaokaMari** [swirldev/swirl#537]
```
> install.packages("swirl")
also installing the dependencies ‘stringi’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’

Packages which are only available in source form, and
  may need compilation of C/C++/Fortran: ‘stringi’
  ‘jsonlite’ ‘mime’ ‘curl’ ‘openssl’ ‘bitops’
  ‘testthat’ ‘yaml’ ‘RCurl’ ‘digest’
  These will not be installed
installing the source packages ‘stringr’, ‘httr’, ‘swirl’

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.1.0.tar.gz'
Content type 'application/x-gzip' length 63174 bytes (61 KB)
downloaded 61 KB

trying URL 'https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz'
Content type 'application/x-gzip' length 133398 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/src/contrib/swirl_2.4.2.tar.gz'
Content type 'application/x-gzip' length 98565 bytes (96 KB)
downloaded 96 KB

ERROR: dependency 'stringi' is not available for package 'stringr'
* removing 'D:/R/R-3.3.1/library/stringr'
Warning in install.packages :
  running command '"D:/R/R-3.3.1/bin/x64/R" CMD INSTALL -l "D:\R\R-3.3.1\library" `C:\Users\lenovo\AppData\Local\Temp\RtmpkD1fx0/downloaded_packages/stringr_1.1.0.tar.gz'` had status 1
Warning in install.packages :
  installation of package ‘stringr’ had non-zero exit status
ERROR: dependencies 'jsonlite', 'mime', 'curl', 'openssl' are not available for package 'httr'
* removing 'D:/R/R-3.3.1/library/httr'
Warning in install.packages :
  running command '"D:/R/R-3.3.1/bin/x64/R" CMD INSTALL -l "D:\R\R-3.3.1\library" C:\Users\lenovo\AppData\Local\Temp\RtmpkD1fx0/downloaded_packages/httr_1.2.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies 'stringr', 'testthat', 'httr', 'yaml', 'RCurl', 'digest' are not available for package 'swirl'
* removing 'D:/R/R-3.3.1/library/swirl'
Warning in install.packages :
  running command '"D:/R/R-3.3.1/bin/x64/R" CMD INSTALL -l "D:\R\R-3.3.1\library" C:\Users\lenovo\AppData\Local\Temp\RtmpkD1fx0/downloaded_packages/swirl_2.4.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\lenovo\AppData\Local\Temp\RtmpkD1fx0\downloaded_packages’
```
Here the sessioninfo()
```
> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Chinese (Simplified)_China.936 
[2] LC_CTYPE=Chinese (Simplified)_China.936   
[3] LC_MONETARY=Chinese (Simplified)_China.936
[4] LC_NUMERIC=C                              
[5] LC_TIME=Chinese (Simplified)_China.936    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1
```
THANK YOU FOR YOUR READING AND HELP

**Comment by seankross** [comment]
Try installing stringi on its own: `install.packages("stringi")`

**Comment by huahuahuahua** [comment]
> install.packages("RCurl")
Installing package into ‘C:/Users/hua/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘RCurl’
Do you want to attempt to install these from sources?
y/n: y
installing the source package ‘RCurl’

trying URL 'https://cran.rstudio.com/src/contrib/RCurl_1.95-4.8.tar.gz'
Content type 'application/x-gzip' length 916934 bytes (895 KB)
downloaded 895 KB

* installing *source* package 'RCurl' ...
** package 'RCurl' successfully unpacked and MD5 sums checked
** libs

*** arch - i386
c:/Rtools/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.1/include" -DNDEBUG -I/include -DHAVE_LIBIDN_FIELD=1 -DHAVE_CURLOPT_URL=1 -DHAVE_CURLINFO_EFFECTIVE_URL=1 -DHAVE_CURLINFO_RESPONSE_CODE=1 -DHAVE_CURLINFO_TOTAL_TIME=1 -DHAVE_CURLINFO_NAMELOOKUP_TIME=1 -DHAVE_CURLINFO_CONNECT_TIME=1 -DHAVE_CURLINFO_PRETRANSFER_TIME=1 -DHAVE_CURLINFO_SIZE_UPLOAD=1 -DHAVE_CURLINFO_SIZE_DOWNLOAD=1 -DHAVE_CURLINFO_SPEED_DOWNLOAD=1 -DHAVE_CURLINFO_SPEED_UPLOAD=1 -DHAVE_CURLINFO_HEADER_SIZE=1 -DHAVE_CURLINFO_REQUEST_SIZE=1 -DHAVE_CURLINFO_SSL_VERIFYRESULT=1 -DHAVE_CURLINFO_FILETIME=1 -DHAVE_CURLINFO_CONTENT_LENGTH_DOWNLOAD=1 -DHAVE_CURLINFO_CONTENT_LENGTH_UPLOAD=1 -DHAVE_CURLINFO_STARTTRANSFER_TIME=1 -DHAVE_CURLINFO_CONTENT_TYPE=1 -DHAVE_CURLINFO_REDIRECT_TIME=1 -DHAVE_CURLINFO_REDIRECT_COUNT=1 -DHAVE_CURLINFO_PRIVATE=1 -DHAVE_CURLINFO_HTTP_CONNECTCODE=1 -DHAVE_CURLINFO_HTTPAUTH_AVAIL=1 -DHAVE_CURLINFO_PROXYAUTH_AVAIL=1 -DHAVE_CURLINFO_OS_ERRNO=1 -DHAVE_CURLINFO_NUM_CONNECTS=1 -DHAVE_CURLINFO_SSL_ENGINES=1 -DHAVE_CURLINFO_COOKIELIST=1 -DHAVE_CURLINFO_LASTSOCKET=1 -DHAVE_CURLINFO_FTP_ENTRY_PATH=1 -DHAVE_CURLINFO_REDIRECT_URL=1 -DHAVE_CURLINFO_PRIMARY_IP=1 -DHAVE_CURLINFO_APPCONNECT_TIME=1 -DHAVE_CURLINFO_CERTINFO=1 -DHAVE_CURLINFO_CONDITION_UNMET=1 -DHAVE_CURLOPT_KEYPASSWD=1 -DHAVE_CURLOPT_DIRLISTONLY=1 -DHAVE_CURLOPT_APPEND=1 -DHAVE_CURLOPT_KRBLEVEL=1 -DHAVE_CURLOPT_USE_SSL=1 -DHAVE_CURLOPT_TIMEOUT_MS=1 -DHAVE_CURLOPT_CONNECTTIMEOUT_MS=1 -DHAVE_CURLOPT_HTTP_TRANSFER_DECODING=1 -DHAVE_CURLOPT_HTTP_CONTENT_DECODING=1 -DHAVE_CURLOPT_NEW_FILE_PERMS=1 -DHAVE_CURLOPT_NEW_DIRECTORY_PERMS=1 -DHAVE_CURLOPT_POSTREDIR=1 -DHAVE_CURLOPT_OPENSOCKETFUNCTION=1 -DHAVE_CURLOPT_OPENSOCKETDATA=1 -DHAVE_CURLOPT_COPYPOSTFIELDS=1 -DHAVE_CURLOPT_PROXY_TRANSFER_MODE=1 -DHAVE_CURLOPT_SEEKFUNCTION=1 -DHAVE_CURLOPT_SEEKDATA=1 -DHAVE_CURLOPT_CRLFILE=1 -DHAVE_CURLOPT_ISSUERCERT=1 -DHAVE_CURLOPT_ADDRESS_SCOPE=1 -DHAVE_CURLOPT_CERTINFO=1 -DHAVE_CURLOPT_USERNAME=1 -DHAVE_CURLOPT_PASSWORD=1 -DHAVE_CURLOPT_PROXYUSERNAME=1 -DHAVE_CURLOPT_PROXYPASSWORD=1 -DHAVE_CURLOPT_SSH_HOST_PUBLIC_KEY_MD5=1 -DHAVE_CURLOPT_NOPROXY=1 -DHAVE_CURLOPT_TFTP_BLKSIZE=1 -DHAVE_CURLOPT_SOCKS5_GSSAPI_SERVICE=1 -DHAVE_CURLOPT_SOCKS5_GSSAPI_NEC=1 -DHAVE_CURLOPT_PROTOCOLS=1 -DHAVE_CURLOPT_REDIR_PROTOCOLS=1 -DHAVE_CURLOPT_SSH_AUTH_TYPES=1 -DHAVE_CURLOPT_SSH_PUBLIC_KEYFILE=1 -DHAVE_CURLOPT_SSH_PRIVATE_KEYFILE=1 -DHAVE_CURLOPT_FTP_SSL_CCC=1 -DHAVE_CURLOPT_COOKIELIST=1 -DHAVE_CURLOPT_IGNORE_CONTENT_LENGTH=1 -DHAVE_CURLOPT_FTP_SKIP_PASV_IP=1 -DHAVE_CURLOPT_FTP_FILEMETHOD=1 -DHAVE_CURLOPT_LOCALPORT=1 -DHAVE_CURLOPT_LOCALPORTRANGE=1 -DHAVE_CURLOPT_CONNECT_ONLY=1 -DHAVE_CURLOPT_CONV_FROM_NETWORK_FUNCTION=1 -DHAVE_CURLOPT_CONV_TO_NETWORK_FUNCTION=1 -DHAVE_CURLOPT_CONV_FROM_UTF8_FUNCTION=1 -DHAVE_CURLOPT_MAX_SEND_SPEED_LARGE=1 -DHAVE_CURLOPT_MAX_RECV_SPEED_LARGE=1 -DHAVE_CURLOPT_FTP_ALTERNATIVE_TO_USER=1 -DHAVE_CURLOPT_SOCKOPTFUNCTION=1 -DHAVE_CURLOPT_SOCKOPTDATA=1 -DHAVE_CURLOPT_SSL_SESSIONID_CACHE=1 -DHAVE_CURLOPT_WRITEDATA=1 -DCURL_STATICLIB    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c base64.c -o base64.o
In file included from base64.c:1:0:
Rcurl.h:4:23: fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
make: *** [base64.o] Error 1
Warning: running command 'make -f "Makevars.win" -f "C:/PROGRA~1/R/R-33~1.1/etc/i386/Makeconf" -f "C:/PROGRA~1/R/R-33~1.1/share/make/winshlib.mk" SHLIB="RCurl.dll" OBJECTS="base64.o curl.o curlInit.o curl_base64.o enums.o json.o memoryManagement.o myUTF8.o"' had status 2
ERROR: compilation failed for package 'RCurl'
* removing 'C:/Users/hua/Documents/R/win-library/3.3/RCurl'
Warning in install.packages :
  running command '"C:/PROGRA~1/R/R-33~1.1/bin/x64/R" CMD INSTALL -l "C:\Users\hua\Documents\R\win-library\3.3" C:\Users\hua\AppData\Local\Temp\Rtmpe4zlmk/downloaded_packages/RCurl_1.95-4.8.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\hua\AppData\Local\Temp\Rtmpe4zlmk\downloaded_packages’
>

**Comment by KazaokaMari** [comment]
@seankross 
```
> install.packages("stringi")
Package which is only available in source form, and may need compilation of
  C/C++/Fortran: ‘stringi’
  These will not be installed
```

**Comment by KazaokaMari** [comment]
@huahuahuahua I AM IN YOUR SAME BOAT NOW. HAVE YOU FOUND THE SOLUTION?

**Comment by AndrewAA** [comment]
there are the same Errors as KazaokaMari ones:
`> install.packages("swirl")
also installing the dependencies ‘stringi’, ‘magrittr’, ‘crayon’, ‘praise’, ‘R6’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’

Packages which are only available in source form, and may need compilation of
  C/C++/Fortran: ‘stringi’ ‘jsonlite’ ‘mime’ ‘curl’ ‘openssl’ ‘bitops’ ‘testthat’ ‘yaml’
  ‘RCurl’ ‘digest’
  These will not be installed
installing the source packages ‘magrittr’, ‘crayon’, ‘praise’, ‘R6’, ‘stringr’, ‘httr’, ‘swirl’

trying URL 'https://cran.rstudio.com/src/contrib/magrittr_1.5.tar.gz'
Content type 'application/x-gzip' length 200504 bytes (195 KB)
downloaded 195 KB

trying URL 'https://cran.rstudio.com/src/contrib/crayon_1.3.2.tar.gz'
Content type 'application/x-gzip' length 656168 bytes (640 KB)
downloaded 640 KB

trying URL 'https://cran.rstudio.com/src/contrib/praise_1.0.0.tar.gz'
Content type 'application/x-gzip' length 6100 bytes
downloaded 6100 bytes

trying URL 'https://cran.rstudio.com/src/contrib/R6_2.1.3.tar.gz'
Content type 'application/x-gzip' length 202251 bytes (197 KB)
downloaded 197 KB

trying URL 'https://cran.rstudio.com/src/contrib/stringr_1.1.0.tar.gz'
Content type 'application/x-gzip' length 63174 bytes (61 KB)
downloaded 61 KB

trying URL 'https://cran.rstudio.com/src/contrib/httr_1.2.1.tar.gz'
Content type 'application/x-gzip' length 133398 bytes (130 KB)
downloaded 130 KB

trying URL 'https://cran.rstudio.com/src/contrib/swirl_2.4.2.tar.gz'
Content type 'application/x-gzip' length 98565 bytes (96 KB)
downloaded 96 KB

* installing *source* package 'magrittr' ...
** пакет 'magrittr' удачно распакован, MD5 sums проверены
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (magrittr)
* installing *source* package 'crayon' ...
** пакет 'crayon' удачно распакован, MD5 sums проверены
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (crayon)
* installing *source* package 'praise' ...
** пакет 'praise' удачно распакован, MD5 sums проверены
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (praise)
* installing *source* package 'R6' ...
** пакет 'R6' удачно распакован, MD5 sums проверены
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (R6)
ERROR: dependency 'stringi' is not available for package 'stringr'
* removing 'D:/R-1/R-3.3.1/library/stringr'
Warning in install.packages :
  running command '"D:/R-1/R-33~1.1/bin/i386/R" CMD INSTALL -l "D:\R-1\R-3.3.1\library" C:\TEMP\Rtmpw7e7wd/downloaded_packages/stringr_1.1.0.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘stringr’ had non-zero exit status
ERROR: dependencies 'jsonlite', 'mime', 'curl', 'openssl' are not available for package 'httr'
* removing 'D:/R-1/R-3.3.1/library/httr'
Warning in install.packages :
  running command '"D:/R-1/R-33~1.1/bin/i386/R" CMD INSTALL -l "D:\R-1\R-3.3.1\library" C:\TEMP\Rtmpw7e7wd/downloaded_packages/httr_1.2.1.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘httr’ had non-zero exit status
ERROR: dependencies 'stringr', 'testthat', 'httr', 'yaml', 'RCurl', 'digest' are not available for package 'swirl'
* removing 'D:/R-1/R-3.3.1/library/swirl'
Warning in install.packages :
  running command '"D:/R-1/R-33~1.1/bin/i386/R" CMD INSTALL -l "D:\R-1\R-3.3.1\library" C:\TEMP\Rtmpw7e7wd/downloaded_packages/swirl_2.4.2.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘C:\Temp\Rtmpw7e7wd\downloaded_packages’`

and for 
`> install.packages("stringi")
Package which is only available in source form, and may need compilation of C/C++/Fortran:
  ‘stringi’
  These will not be installed`

my sys info:
`> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251
[4] LC_NUMERIC=C                    LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.3.1`

Is there the solution?
A lot of Thanks!

**Comment by seankross** [comment]
Do you have Rtools installed? https://cran.r-project.org/bin/windows/Rtools/

**Comment by AndrewAA** [comment]
seankross

A lot of Thanks!
 I try, and 
```
> library(swirl)

| Hi! Type swirl() when you are ready to begin.

> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you
| did then. If you are new, call yourself something unique.
```

swirl was installed.
