### ISSUE TITLE
Issue with Lesson 8

### ISSUE THREAD

**Issue by garybtw** [swirldev/swirl#540]
Hello,

I ran into a weird issue in lesson 8: logic. When checking to see which integers are greater than 7 the program returned 4 and 6 which isn't right. I am using the program to learn R so it is possible that I might have missed something. Thank you for creating this package and let me know if you need anything from me. Below is the text from the console.:

`For the next few questions, we're going to need to create a vector of
| integers called ints. Create this vector by typing: ints <- sample(10)

> 
> ints <- sample(10)

| You got it!

  |======================================================             |  81%

| Now simply display the contents of ints.

> 
> ints
 [1]  6  3  2  9  4 10  5  1  7  8

| Excellent job!

  |=======================================================            |  83%

| The vector `ints` is a random sampling of integers from 1 to 10 without
| replacement. Let's say we wanted to ask some logical questions about
| contents of ints. If we type ints > 5, we will get a logical vector
| corresponding to whether each element of ints is greater than 5. Try
| typing: ints > 5

> ints > 5
 [1]  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE FALSE  TRUE  TRUE

| All that practice is paying off!

  |=========================================================          |  85%

| We can use the resulting logical vector to ask other questions about ints.
| The which() function takes a logical vector as an argument and returns the
| indices of the vector that are TRUE. For example which(c(TRUE, FALSE,
| TRUE)) would return the vector c(1, 3).

...

  |==========================================================         |  87%

| Use the which() function to find the indices of ints that are greater than
| 7.

> which (ints > 7)
[1]  4  6 10

| All that practice is paying off!
`

**Comment by seankross** [comment]
Hi @garybtw,

`which()` returns the index of values of the vector `c(6, 3, 2, 9, 4, 10, 5, 1, 7, 8)` that are greater than 7. As you can see the fourth, sixth, and tenth values are greater than 7, so `which (ints > 7)` returns `4 6 10`.

**Comment by garybtw** [comment]
Got it! Thanks for chiming in @seankross
