### ISSUE TITLE
Swirl installation issues with Microsoft R 3.3.1, OSX 10.11.5

### ISSUE THREAD

**Issue by shivendra90** [swirldev/swirl#541]
Hello,

Today I updated R to the latest R 3.3.1 released by revolution analytics. Till now swirl was functioning fine until the update that I believe removed all the existing files prompting me to try reinstalling it, but while doing so I got a really long list of warning messages and errors when R tries to unpack the content and install the associated packages. I'm pasting some of the screens here showing some of these alerts and errors.

![error_1](https://cloud.githubusercontent.com/assets/9760865/18808884/dcc6539a-828b-11e6-9a53-f897c575ced3.png)
![error_3](https://cloud.githubusercontent.com/assets/9760865/18808905/98e14300-828c-11e6-8c27-6833d1088482.png)
![error_2](https://cloud.githubusercontent.com/assets/9760865/18808906/99623fc8-828c-11e6-9683-d84d3554e044.png)

Used is Microsoft R open 3.3.1 on OSX 10.11.5. Will look forward to a fix since I've pending courses.

Regards,
Shivendra

**Comment by seankross** [comment]
Can you use the CRAN version of R?

**Comment by shivendra90** [comment]
Haven't tested it. I personally use MRAn because of its multi-threading feature and that is a big requirement at least since I have large datasets and computations are double the speed than the CRAN.

**Comment by seankross** [comment]
Hey @shivendra90,

I have never tested swirl with Microsoft R so I'm not sure how it will behave. Did you ever get this working?

**Comment by shivendra90** [comment]
@seankross 

Before the current version, swirl used to function absolutely fine with no errors or warnings. Have been using for over an year with Microsoft R. Such messages are new to me.

**Comment by seankross** [comment]
Can you send your error again? Fo some reason the screenshots aren't loading.

**Comment by shivendra90** [comment]
@seankross 

Sure, heres one more capture that pretty much included all of the errors.


![error](https://cloud.githubusercontent.com/assets/9760865/19552581/074bea84-96ce-11e6-9f8e-1cc5ccdfced2.jpg)

This is very urgent since I have to finish Coursera chapters.

**Comment by seankross** [comment]
Ack I still can't see the error. If you're still having issues I highly recommend you use CRAN R.
