### ISSUE TITLE
Problem installing swirl for R version 3.3.1 on Windows 10 Home

### ISSUE THREAD

**Issue by plectrumpryce** [swirldev/swirl#542]
When I type the command   library("swirl")   I get the following error message:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’

Not sure what's wrong, any suggestions?

**Comment by seankross** [comment]
See #537

**Comment by plectrumpryce** [comment]
Thanks, that seems to have fixed it! :)
