### ISSUE TITLE
Warning when using install_course_github() with multi = TRUE

### ISSUE THREAD

**Issue by jonmcalder** [swirldev/swirl#545]
Though it still works fine to install multiple courses from a repo in this way, the below warning seems to have been around for a long time, and stems from the use of the non-vectorized `if()` on `file.copy(...)` (which returns a vector) within `install_course_zip()`.

```
Warning message:
In if (file.copy(dirs_to_copy, swirl_courses_dir(), recursive = TRUE)) { :
  the condition has length > 1 and only the first element will be used
```

**Comment by seankross** [comment]
Users shouldn't use the `multi = TRUE` argument, really it's for internal use only. I'll make a note to update this in the documentation.

**Comment by jonmcalder** [comment]
Ok good to know. Just to confirm - would you advise against having multiple swirl courses in one repo? (I just assumed it was ok based on the [swirldev/swirl_courses](https://github.com/swirldev/swirl_courses) repo)

**Comment by seankross** [comment]
Yes absolutely, swirl_courses is still around because several things depend on it, I wish I could close it. Each course should be its own repo.

**Comment by jonmcalder** [comment]
Ok cool - thanks. Still early days for me - so I will split mine out into separate repos then 👍

**Comment by seankross** [comment]
@jonmcalder if you have any questions don't hesitate to contact me.
