### ISSUE TITLE
Can't get the Coursera credit, having problem in submission

### ISSUE THREAD

**Issue by hopeyesh** [swirldev/swirl#546]
Hi! Sean.

Recently while I was submitting the assignment to Coursera by R.

I've already tried to install the clean data in the R. See the code below.

> > library(swirl)
> > install_from_swirl("Getting and Cleaning Data", mirror = "bitbucket")
> > Downloading: 9.8 MB  
> > | Course installed successfully!

But problem exists showing i'm timed out. See the code below 

> Error in curl::curl_fetch_memory(url, handle = handle) : 
>   Timeout was reached
> 
> | Leaving swirl now. Type swirl() to resume.

I've already tried several internet connection both by proxy or not proxy, but still found the "timeout" problem existed.

Using R studio, the latest swirl package
System: OS X EI Capitan 10.11.6

**Comment by seankross** [comment]
Hi @hopeyesh,

Can you install the course using `install_course("Getting and Cleaning Data")`?

**Comment by hopeyesh** [comment]
Hi @seankross 
Thank you for the reply.

Yes, I can.
I accidentally entered the regression course when i tried the swirl. I wanted to quit this part and entered the first basic part, so I searched in your GitHub and found `install_course("Getting and Cleaning Data") `could solve this problem.
Quite sure I've used this.

**Comment by hopeyesh** [comment]
Hi @seankross 

I tried this code again in R. It showed that:

> install_course("Getting and Cleaning Data")
  |=======================================================================================| 100%

>  /Library/Frameworks/R.framework/Versions/3.3/Resources/library/swirl/Courses/Getting_and_Cleaning_Data already exists.
> Are you sure you want to overwrite it? [Y/n] 
> 
> 1: Y
> 2: n

Used this before.

**Comment by seankross** [comment]
@hopeyesh so are things working?

**Comment by hopeyesh** [comment]
Sorry, it doesn't.

**Comment by hopeyesh** [comment]
@seankross Sorry, it doesn't.

**Comment by seankross** [comment]
@hopeyesh What issue are you currently having?

**Comment by hopeyesh** [comment]
@seankross still can not submit, the timeout problem still exists.

**Comment by seankross** [comment]
Can you try using a different internet connection?

**Comment by hopeyesh** [comment]
Already tried with wifi of mine, my neighbor, and the public wifi in Starbucks, none of them works

**Comment by seankross** [comment]
Can you copy and paste the error you're receiving?

**Comment by seankross** [comment]
Also what's your geographic location?

**Comment by mariamgeorgeblr** [comment]
Im unable to submit my assignment because my token is not being accepted!
