### ISSUE TITLE
Problem Downloading and Running Swirl

### ISSUE THREAD

**Issue by acarroll05** [swirldev/swirl#550]
Hi,

I'm new to Swirl (and R), and am coming across the following error when I attempt to install the swirl package (R version 3.3.1, on a Mac):

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/var/folders/cx/5vgfvpnn7b51jvv_q93jwpwh0000gn/T/RtmpD8GtgC/R.INSTALL2a5d706aa967/stringi':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘stringi’
removing ‘/Library/Frameworks/R.framework/Versions/3.3/Resources/library/stringi’
Warning in install.packages :
  installation of package ‘stringi’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/cx/5vgfvpnn7b51jvv_q93jwpwh0000gn/T/RtmpzusZOu/downloaded_packages’

Afterwards, when I try to open swirl:

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
Error: package or namespace load failed for ‘swirl’

Any suggestions? I've tried installing the stringi package separately, which also doesn't work. Any help is appreciated!

**Comment by seankross** [comment]
You need to do the following:

1. Download [this](https://cran.r-project.org/bin/macosx/mavericks/contrib/3.3/stringi_1.1.1.tgz) file.
2. Run `install.packages(file.choose(), repos = NULL, type = "mac.binary.mavericks")`
3. Select the file you just downloaded.

Let me know if that works for you.

**Comment by acarroll05** [comment]
Hi Sean,

That worked! Thank you so much! What does that download do?

**Comment by bdods** [comment]
I also had a similar problem:

I am using R version 3.3.1 and running on mac OS X 10.11.6

I have tried to install swirl, but it is asking me to install "stringi.so" which is not available for the R version I am using. This is the error that comes up:

> install.packages("swirl")
trying URL 'https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.3/swirl_2.4.2.tgz'
Content type 'application/x-gzip' length 210316 bytes (205 KB)
==================================================
downloaded 205 KB

tar: Failed to set default locale

The downloaded binary packages are in
	/var/folders/tj/k19s946x0vx6k12x7zbz_np00000gn/T//RtmpXAZUaX/downloaded_packages
> library("swirl")
Error in library.dynam(lib, package, package.lib) : 
  shared object 'stringi.so' not found
Error: package or namespace load failed for 'swirl'
> install.packages("stringi.so")
Warning in install.packages :
  package 'stringi.so' is not available (for R version 3.3.1)

I would be grateful for any help provided, I am new to R.  

Thanks, 
Binal.

**Comment by divincno** [comment]
Hi Sean,

I have having the same problem and wanted to try your solution of downloading the file you mentioned. However, when I click on it, it says the file is outdated. Could you re-upload it so I can give this solution a try?

Thanks,

Nicole

**Comment by seankross** [comment]
@divincno @bdods I just updated the link above. Let me know if that works.

**Comment by divincno** [comment]
Hi again,

I downloaded the file, and got this error:
Error in install.packages : file ‘/Users/nicoledivincenzo/Documents/stringi_1.1.1.tar.gz’ is not an OS X binary package

I tried again to install and then run swirl and got the following:
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘stringr’
In addition: Warning message:
package ‘swirl’ was built under R version 3.2.5 
Error: package or namespace load failed for ‘swirl’

Did I do something wrong?

Nicole

**Comment by seankross** [comment]
@divincno sorry I made a mistake, the link should be correct now.

**Comment by bdods** [comment]
That worked, thanks Sean. 

Binal

**Comment by Malarija** [comment]
great seankross, thanks a lot!!!!!!

**Comment by Jumanah-y** [comment]
Hi,

I have the same problem. Can you please upload the file again. I get error 404 unfound when I use the link.
 
Thank you
