### ISSUE TITLE
Variance course gives: Error in file(con, "r") : invalid 'description' argument

### ISSUE THREAD

**Issue by NKCoe** [swirldev/swirl#551]
When running the Variance course I get an error:

`Error in file(con, "r") : invalid 'description' argument`

I've tried uninstalling all courses and reinstalling 'Variance' and uninstalling and reinstalling Swirl without any success.

`uninstall_all_courses()`
`install_from_swirl("Variance")`

still leads to 

`Error in file(con, "r") : invalid 'description' argument`

The 'R Programming' course works without problems.

**Comment by seankross** [comment]
Try: `install_course("Statistical Inference")`
