### ISSUE TITLE
Open write permissions for the Wiki

### ISSUE THREAD

**Issue by kbsali** [swirldev/swirl#552]
Hi,

I would like to submit changes to the Linux install page (https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux) but its access is restricted...
Anyway we could fix this?
(found this page giving instructions on changing this : https://help.github.com/articles/changing-access-permissions-for-wikis/)

Thanks

**Comment by seankross** [comment]
Hi @kbsali,

If you leave them here I'll add them. Thanks.

**Comment by kbsali** [comment]
Here is the patch : 
```
diff --git a/Installing-swirl-on-Linux.md b/Installing-swirl-on-Linux.md
index 7f0fed5..a4e3dee 100644
--- a/Installing-swirl-on-Linux.md
+++ b/Installing-swirl-on-Linux.md
@@ -1,4 +1,4 @@
-swirl and its dependencies require R version 3.1.0 or later as well as a recent version of libcurl. This page is our attempt to collect any information that might be helpful to Linux users wanting to install swirl.
+`swirl` and its dependencies require `R version 3.1.0` or later as well as a recent version of `libcurl`. This page is our attempt to collect any information that might be helpful to Linux users wanting to install `swirl`.
 
 ***
 
@@ -6,33 +6,26 @@ swirl and its dependencies require R version 3.1.0 or later as well as a recent
 
 These instructions have been successfully tested on:
 - Ubuntu 12.04 LTS (Precise Pangolin)
+- Ubuntu 16.04 LTS (Xenial)
 - Linux Mint 16 (Petra)
 
 #### 1. Install the most recent version of R. If you have R installed already, go to #2.
 
 Official source: http://cran.r-project.org/bin/linux/ubuntu/README
 
-**IMPORTANT: In the first line below, `precise/` should be replaced with the version of Ubuntu you are using. Other examples: `trusty/`, `saucy/`, `quantal/`, `lucid/`. If you're not sure which version you have, type `cat /etc/*release` at the command line.**
-
 ```
-$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list'
+$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/" >> /etc/apt/sources.list.d/cran.list'
 $ sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
 $ sudo apt-get update
 $ sudo apt-get install r-base-dev
 ```
-**NOTE**
-
-Most modern Linux distros recommend you not edit `/etc/apt/sources.list` directly and rather place any additions you want to outlive a package update in the `/etc/apt/sources.list.d` directory. With that in mind a best-practices alternative to the command above would be:
-```
-$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list.d/cran.list'
-```
 Note also that using either of these instructions on a more modern distribution (e.g. Ubuntu 14.10, and probably 14.04) breaks the install, since the package at that source depends on libtiff4, but this has been removed (superseded by libtiff5). Happily, users can (and should) skip that step entirely, since a compatible package (R 3.1.1) is already included in that distribution.
 
 PS. Thanks [Charl](https://github.com/charl) and [joegodbehere](https://github.com/joegodbehere)
 
 #### 2. Confirm that you have R version 3.1.0 or later. If not, return to #1.
 
-```
+```bash
 $ R --version
 ```
 
@@ -42,7 +35,7 @@ Download from http://www.rstudio.com/ide/download/desktop.
 
 #### 4. Install libcurl.
 
-This is [required](http://www.omegahat.org/RCurl/FAQ.html) for the RCurl package, which swirl uses to download courses from the internet.
+This is [required](http://www.omegahat.org/RCurl/FAQ.html) for the RCurl package, which `swirl` uses to download courses from the internet.
 
 ```
 $ sudo apt-get install libcurl4-openssl-dev
@@ -54,7 +47,7 @@ If you're installing on Linux Mint 17:
 $ sudo apt-get install libcurl4-openssl-dev r-base-dev libxml2-dev
 ```
 
-#### 5. From R or RStudio, install and run swirl.
+#### 5. From R or RStudio, install and run `swirl`.
 
 ```
 > install.packages("swirl")
@@ -62,25 +55,25 @@ $ sudo apt-get install libcurl4-openssl-dev r-base-dev libxml2-dev
 > swirl()
 ```
 
-**NOTE: If you upgrading from an earlier version of R, you may need to do `install.packages("codetools")` before installing swirl.**
+**NOTE: If you upgrading from an earlier version of R, you may need to do `install.packages("codetools")` before installing `swirl`.**
 
 ***
 
 ### Other Resources
 
-- Often, the most challenging part of getting swirl to work on Linux is getting a recent version of R. We've found [this blog post](http://www.jason-french.com/blog/2013/03/11/installing-r-in-linux/) to be a helpful resource for installing up-to-date versions of R on a variety of Linux platforms.
+- Often, the most challenging part of getting `swirl` to work on Linux is getting a recent version of `R`. We've found [this blog post](http://www.jason-french.com/blog/2013/03/11/installing-r-in-linux/) to be a helpful resource for installing up-to-date versions of R on a variety of Linux platforms.
 
-- Official R FAQ: [Are there Unix-like binaries for R?](http://cran.r-project.org/doc/FAQ/R-FAQ.html#Are-there-Unix_002dlike-binaries-for-R_003f)
+- Official `R` FAQ: [Are there Unix-like binaries for R?](http://cran.r-project.org/doc/FAQ/R-FAQ.html#Are-there-Unix_002dlike-binaries-for-R_003f)
 
-- Official R installation docs for various Linux distributions:
+- Official `R` installation docs for various Linux distributions:
   - Debian: http://cran.r-project.org/bin/linux/debian/
   - openSUSE: http://cran.r-project.org/bin/linux/suse/README.html
   - Ubuntu: http://cran.r-project.org/bin/linux/ubuntu/README.html
 
-- Official R Installation and Administration manual on building R from source: [Installing R under Unix-alikes](http://cran.r-project.org/doc/manuals/R-admin.html#Installing-R-under-Unix_002dalikes).
+- Official `R` Installation and Administration manual on building R from source: [Installing R under Unix-alikes](http://cran.r-project.org/doc/manuals/R-admin.html#Installing-R-under-Unix_002dalikes).
 
-- Download page for curl and libcurl: http://curl.haxx.se/download.html
+- Download page for `curl` and `libcurl`: http://curl.haxx.se/download.html
 
 ***
 
-Fix for graphics not working on Ubuntu: https://gist.github.com/papas8105/2cbd941dceb1678918ea
\ No newline at end of file
+Fix for graphics not working on Ubuntu: https://gist.github.com/papas8105/2cbd941dceb1678918ea
```

**Comment by kbsali** [comment]
it does not show well as it is interpreting the markdown of the patch itself... :-1:

**Comment by seankross** [comment]
Yeah could you just copy and paste the markdown?

**Comment by kbsali** [comment]
done, but the issue remains, you cannot get the raw version! I'll create a gist...

**Comment by kbsali** [comment]
here is it : https://gist.githubusercontent.com/kbsali/77acfc687141b9d02594c579da5bc6e1/raw/007b30c9649e2de43501395ab810615d05dff4f8/Installing-swirl-on-Linux.md

**Comment by kbsali** [comment]
@seankross seen the gist?

**Comment by seankross** [comment]
How do you know the following will work on all platforms?:

```
$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -cs)/" >> /etc/apt/sources.list.d/cran.list'
```

Why did you remove the note about editing `/etc/apt/sources.list`?

**Comment by kbsali** [comment]
What do you mean by "all platforms"?
This is for *ubuntu* only, as the previous instructions were.

**Comment by seankross** [comment]
By all platforms I meant all versions of Ubuntu.

**Comment by kbsali** [comment]
yes, that will indeed work on every version of Ubuntu

**Comment by seankross** [comment]
Okay great!

**Comment by kbsali** [comment]
any chance my changes could be published?
Or even better, I reckon you should consider moving those wiki pages to the repository itself!

**Comment by seankross** [comment]
Hi @kbsali,

Sorry for the radio silence on this. Would you mind just letting me know what specific lines or phrases in the wiki page that you would like to change and why? The reason I'm so protective of these pages is that they're used my many folks in the Coursera classes that use swirl.  I haven't heard any recent concerns from those students so I'm reluctant to fix something that doesn't appear to be broken.

Sean
