### ISSUE TITLE
Swirl download problem on windows .....HELP

### ISSUE THREAD

**Issue by Actudata77** [swirldev/swirl#553]
Im running Windows 7 , and R 3.3.1.
I'm Trying to fulfill my Coursera R Programming course requirements . In RStudio, I'm trying to download the swirl package .
install.packages("swirl") IS GOOD
packageVersion("swirl") IS GOOD ; it says 2.4.2
Now to load swirl using library(swirl), I get this message:
>library(swirl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘RCurl’
Error: package or namespace load failed for ‘swirl’

I will greatly appreciate any help please.

**Comment by seankross** [comment]
What happens if you try to install RCurl on its own?

**Comment by Actudata77** [comment]
I did just that and it worked very fine . Thanks so much .
