### ISSUE TITLE
Can't get coursera credit: Error in curl::curl_fetch_memory(url, handle = handle) : Peer certificate cannot be authenticated with given CA certificates

### ISSUE THREAD

**Issue by EdnaSantos** [swirldev/swirl#554]

**Comment by seankross** [comment]
Which course are you taking?

**Comment by EdnaSantos** [comment]
R Programming.

Swirl Lesson 1: Basic Building Blocks and now it happened the same with Lesson 2.

**Comment by seankross** [comment]
Can you try using a different internet connection?

**Comment by EdnaSantos** [comment]
No, I'm at work we have the same LAN line.

**Comment by seankross** [comment]
You workplace's firewall is likely blocking the connection, so there isn't much you can do unless you can use a different connection. Sorry about that.

**Comment by EdnaSantos** [comment]
Ohhh... Ok, but I can finish the courses and then later in another connection in my house get the credits?

**Comment by seankross** [comment]
You can as long as you load your saved progress. In other words, don't finish the lesson completely, then when you're in your house you can finish the lesson.

**Comment by EdnaSantos** [comment]
Ok. Thanks!

**Comment by seankross** [comment]
If you have any issues at home let me know here.
