### ISSUE TITLE
Confused on course instructions: swirl setup and submission of assignments

### ISSUE THREAD

**Issue by EdwardKoonce** [swirldev/swirl#555]
I installed swirl and received no error messages. Then I proceeded to test whether I could submit assignments. Here is the interaction:
Selection: 2
What is your email address? ted75077@earthlink.net
What is your assignment token? 2
Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.

What is the assignment token?? I could never find it next to the lesson. I suspect that this answer caused the failure. Is it possible to show a screen print of the correct page and show where to find the assignment token??

Under FAQ I read that manual submission is not accepted by coursera now. Then how do I submit assignments?? The instructions on the swirl setup page say,

"At the end of every swirl lesson you will be presented with a choice to submit the completion of your assignment to Coursera or for swirl to generate a code. If you're unable to connect to Coursera in Setting Up Swirl then you should always choose to generate a code. You can use this code as an answer to the quiz question that corresponds with the swirl lesson."

Please provide explicit answers. Thanks.

**Comment by seankross** [comment]
Hi @EdwardKoonce,

What course are you enrolled in on Coursera?

**Comment by EdwardKoonce** [comment]
I am in the course which begins on Monday, 17 October. According to the email which welcomes me to the course, I may begin early. Is this true??

In addition to the above questions, is there a simpler way of asking questions rather than going to the FAQ page and then finding the Github sign in ??

Finally, I am reading the material in the coursera webpages for this course. Is this material duplicated in swirl??

**Comment by EdwardKoonce** [comment]
Hello Sean,I am enrolled in the first course of Mastering Software Development in R, The R Environment. It begins on Monday, 17 October, but according to the email which I received, I may begin early.EdwardPS I received this email two days after I posted the question on GitHub.-----Original Message-----

**Comment by seankross** [comment]
Hi @EdwardKoonce,

Have you tried to submit since the course launched?

**Comment by EdwardKoonce** [comment]
Hello Sean,

Thanks for the response. 
First, a procedural question. Where is the real discussion forum, which will be used in this session?? On GitHub through the FAQ link? or in the Coursera Discussion Form (Weeks 1-5)??

Now my answer. No. I have not yet tried to submit. As of this morning, the webpages for this session beginning on October 17 still show that I have two options. I did find where I may receive a "token". Please tell me how to submit the swirl lessons results. I described my situation in the first post.

thanks

**Comment by seankross** [comment]
You can read about finding you submission token here: https://github.com/swirldev/swirl/wiki/Coursera-FAQ#how-do-i-find-my-submission-token

The "real" discussion forum for the course is on Coursera, these issues are just a way for folks to ask for help with swirl.

**Comment by DavidEboh** [comment]
I am taking the R programming class and it asks for a submission token, however it is nowhere to be found. I found a link that says it should be on the right of the course homepage, however there is nothing to be found

**Comment by seankross** [comment]
Hi @DavidEboh,

Exactly which course are you taking and which lesson are you trying to submit for?

**Comment by CONFIDENCESKT** [comment]
Hi there,

       I have just completed my first lesson with the swirl in R (BUILDING BASIC BLOCKS). I was asked to supply the assignment token, but I don't know how to get it.

**Comment by abdullahnasir1** [comment]
I am trouble getting the credit "Practice Programming Assignment: swirl Lesson 1: Logic"
The error I am getting on R Studio is as follows,

Error in loadNamespace(name) : there is no package called ‘curl’

| Leaving swirl now. Type swirl() to resume.

Although I completed my previous practice sessions and received the credit as well. I dont know why this time I am getting this issue. I tried installing different packages as suggested by different forums with the same problem. Can somebody tell me what is the problem here or what am I doing wrong?

**Comment by agwoayiti** [comment]
Does anybody can please tell me how to get the codes for setting up swirl, basic building blocks , sequences of numbers?

**Comment by NiceXT** [comment]
So where is the assignment token?

**Comment by dbramm** [comment]
@NiceXT @agwoayiti I had a hard time finding it too because it's not clear from the GitHub FAQ explanation.

(1) Open up the Coursera class you have signed up for.
(2) Look at the left side bar showing the course contents.
(3) Scroll down to the assignments and select the assignment you are working on
(4) Once you have opened the assignment in the main window, scroll down past the Coursera Sandbox.
(5) You will see on the bottom-right side a box that says "How to submit".
(6) The assignment token is in large print there. Copy and paste it into R.

**Comment by pranav-gilda** [comment]
> @NiceXT @agwoayiti I had a hard time finding it too because it's not clear from the GitHub FAQ explanation.
> 
> (1) Open up the Coursera class you have signed up for.
> (2) Look at the left side bar showing the course contents.
> (3) Scroll down to the assignments and select the assignment you are working on
> (4) Once you have opened the assignment in the main window, scroll down past the Coursera Sandbox.
> (5) You will see on the bottom-right side a box that says "How to submit".
> (6) The assignment token is in large print there. Copy and paste it into R.

I still don't get this

**Comment by NiharikaMagapu** [comment]
I am not getting token option on screen
![Screenshot 2023-03-25 103022](https://user-images.githubusercontent.com/95355246/227697263-7febaff4-740b-4abe-96cc-5568841cb8aa.png)

**Comment by SwindellL** [comment]
I just audited the class and went to the first assignment. That got me the token.

![image](https://github.com/swirldev/swirl/assets/108591466/938ac253-9a80-4e23-9bae-9fc5499b6014)

**Comment by FareedAhmed0606** [comment]
https://www.coursera.org/learn/r-programming/peer/tNy8H/programming-assignment-2-lexical-scoping/review/n8zdT2wvEe6aBxJU3eqBrQ

Please review my peer assignment
