### ISSUE TITLE
trouble installing swirl "unable to move temporary installation"

### ISSUE THREAD

**Issue by AmyDighe** [swirldev/swirl#556]
Hello! Having trouble running swirl for the first time. It says there is no package called 'swirl'. Is it something to do with the warning that it was unable to move temporary file installation to another folder? Anyone else had a similar issue?
Thanks

> install.packages ("swirl")
> Installing package into ‘C:/Users/Amy/Documents/R/win-library/3.2’
> (as ‘lib’ is unspecified)
> also installing the dependencies ‘stringi’, ‘magrittr’, ‘crayon’, ‘praise’, ‘R6’, ‘jsonlite’, ‘mime’, ‘curl’, ‘openssl’, ‘bitops’, ‘stringr’, ‘testthat’, ‘httr’, ‘yaml’, ‘RCurl’, ‘digest’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/stringi_1.1.2.zip'
Content type 'application/zip' length 14229497 bytes (13.6 MB)
downloaded 13.6 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/magrittr_1.5.zip'
Content type 'application/zip' length 149904 bytes (146 KB)
downloaded 146 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/crayon_1.3.2.zip'
Content type 'application/zip' length 703903 bytes (687 KB)
downloaded 687 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/praise_1.0.0.zip'
Content type 'application/zip' length 17688 bytes (17 KB)
downloaded 17 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/R6_2.2.0.zip'
Content type 'application/zip' length 197087 bytes (192 KB)
downloaded 192 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/jsonlite_1.1.zip'
Content type 'application/zip' length 1148816 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/mime_0.5.zip'
Content type 'application/zip' length 37439 bytes (36 KB)
downloaded 36 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/curl_2.1.zip'
Content type 'application/zip' length 4678034 bytes (4.5 MB)
downloaded 4.5 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/openssl_0.9.4.zip'
Content type 'application/zip' length 3010365 bytes (2.9 MB)
downloaded 2.9 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/bitops_1.0-6.zip'
Content type 'application/zip' length 36046 bytes (35 KB)
downloaded 35 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/stringr_1.1.0.zip'
Content type 'application/zip' length 119538 bytes (116 KB)
downloaded 116 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/testthat_1.0.2.zip'
Content type 'application/zip' length 1019138 bytes (995 KB)
downloaded 995 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/httr_1.2.1.zip'
Content type 'application/zip' length 281227 bytes (274 KB)
downloaded 274 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/yaml_2.1.13.zip'
Content type 'application/zip' length 180094 bytes (175 KB)
downloaded 175 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2860199 bytes (2.7 MB)
downloaded 2.7 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/digest_0.6.10.zip'
Content type 'application/zip' length 172494 bytes (168 KB)
downloaded 168 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/swirl_2.4.2.zip'
Content type 'application/zip' length 212117 bytes (207 KB)
downloaded 207 KB

package ‘stringi’ successfully unpacked and MD5 sums checked
package ‘magrittr’ successfully unpacked and MD5 sums checked
package ‘crayon’ successfully unpacked and MD5 sums checked
package ‘praise’ successfully unpacked and MD5 sums checked
package ‘R6’ successfully unpacked and MD5 sums checked
package ‘jsonlite’ successfully unpacked and MD5 sums checked
package ‘mime’ successfully unpacked and MD5 sums checked
package ‘curl’ successfully unpacked and MD5 sums checked
package ‘openssl’ successfully unpacked and MD5 sums checked
package ‘bitops’ successfully unpacked and MD5 sums checked
package ‘stringr’ successfully unpacked and MD5 sums checked
package ‘testthat’ successfully unpacked and MD5 sums checked
package ‘httr’ successfully unpacked and MD5 sums checked
package ‘yaml’ successfully unpacked and MD5 sums checked
package ‘RCurl’ successfully unpacked and MD5 sums checked
package ‘digest’ successfully unpacked and MD5 sums checked
package ‘swirl’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Users\Amy\Documents\R\win-library\3.2\filed502657188\swirl’ to ‘C:\Users\Amy\Documents\R\win-library\3.2\swirl’

The downloaded binary packages are in
    C:\Users\Amy\AppData\Local\Temp\RtmpCyHKE5\downloaded_packages

> library("swirl")
> Error in library("swirl") : there is no package called ‘swirl’

**Comment by seankross** [comment]
Are you using a computer for work or school? If so, you might not have permission to install programs on your computer.
