### ISSUE TITLE
Swirl Assignment #9

### ISSUE THREAD

**Issue by Tati86** [swirldev/swirl#557]
I'm having an issue with assignment 9 in swirl
![function assignment](https://cloud.githubusercontent.com/assets/22914596/19482072/f4fcd6c4-951d-11e6-9a17-c6d56751dab2.JPG)

anyone can help?

**Comment by seankross** [comment]
What version of  swirl do you have? You can find out with `packageVersion("swirl")`. You should also see https://github.com/swirldev/swirl/issues/434#issuecomment-201907367

**Comment by Tati86** [comment]
Thank you!
I have the version 2.4.0

**Comment by seankross** [comment]
If you upgrade swirl this error should go away: `install.packages("swirl")`.

**Comment by Tati86** [comment]
It worked thanks a lot!
