### ISSUE TITLE
have problem in submission

### ISSUE THREAD

**Issue by EricKing19** [swirldev/swirl#558]
Hi @seankross 
When I submitting the assignment to Coursera by R, there are some error. See the code below:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Problem with the SSL CA cert (path? access rights?)

I would appreciate it very much if can help me slove it.

**Comment by seankross** [comment]
Hi @EricKing19,

Can you use a different internet connection to submit?

**Comment by EricKing19** [comment]
Hi @seankross 

I had used other internet connection twice, but it did not work.

**Comment by seankross** [comment]
@EricKing19 What Coursera course are you having trouble with?

**Comment by AbhayGoyal** [comment]
Hi sir, I too am facing the same situation. What is to be done?

**Comment by ericmelo85** [comment]
Hi sir, 

Me too I'm facing the same issue. Is there any solution for this since changing internet connection doesn't solve the issue 

kr

**Comment by seankross** [comment]
Hi @AbhayGoyal and @ericmelo85,

Which Coursera courses are each of you taking?

**Comment by EricKing19** [comment]
Hi @seankross, 
I have finished this courses, so it did not trouble me. Thanks

**Comment by ericmelo85** [comment]
Hi @seankross  I'm doing R programming course

kr

**Comment by AbhayGoyal** [comment]
@seankross I am doing the course by John Hopkins University

**Comment by seankross** [comment]
@ericmelo85 @AbhayGoyal exactly what error do you see?

**Comment by ericmelo85** [comment]
Hi @seankross bellow the error while trying to submit

Error in curl::curl_fetch_memory(url, handle = handle) :
Problem with the SSL CA cert (path? access rights?)

kr

**Comment by seankross** [comment]
@ericmelo85 try this tip: https://github.com/hadley/devtools/issues/1079#issuecomment-182390147

cc: @AbhayGoyal

**Comment by AbhayGoyal** [comment]
@seankross Thank you very much. It helped me a lot. Thank u once again.
