### ISSUE TITLE
Swirl stopped working

### ISSUE THREAD

**Issue by bethgifford** [swirldev/swirl#560]
I was in the middle of a lesson "Exploratory Data Analysis Casestudy" when it stopped.  I tried to sign in again and get this:

> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself something unique.

What shall I call you? Beth

| Would you like to continue with one of these lessons?

1: Exploratory Data Analysis CaseStudy
2: No. Let me start something new.

Selection: 1
Error in eval(expr, envir, enclos) : object 'State.Code' not found

| Leaving swirl now. Type swirl() to resume.

I am using mac OX X El Capitan Version 10.11.6 & Rstudio Version 0.99.903; I have also tried running it in R and restarting my computer.

**Comment by seankross** [comment]
The Data Analysis course is no longer supported. Sorry about that :(
