### ISSUE TITLE
Can't open the course!

### ISSUE THREAD

**Issue by StephanieDong9584** [swirldev/swirl#563]
Hello! I use Mac and successfully installed swirl, however after I chose a course, the bug shows as follows:
Error in file(con, "r") : invalid 'description' argument

Could anyone help me solve the problem? 
Thanks in advance!

**Comment by elinw** [comment]
If you look through the issues or google your error message you'll see this a lot. It seems like uninstalling and then reinstalling usually solves it.

**Comment by seankross** [comment]
I'd say the same thing as @elinw. If that doesn't work for you let me know.
