### ISSUE TITLE
Problems loading swirl, R 3.3.1

### ISSUE THREAD

**Issue by shivendra90** [swirldev/swirl#571]
While running the command, library(swirl) or equivalent, I get the following long error message, prompting R to shut down. Meaning, that I'm totally unable to load the package from library. This is the result I get:

![error](https://cloud.githubusercontent.com/assets/9760865/20648583/464c3f24-b4d1-11e6-9808-5a5ee1483d26.jpg)

In the end, R lets me choose 4 options, none of them really making the package to function. They simply abort an R session. I can 'stop' the session and retry opening the package, but the second time the console simply freezes and I'm forced to quit. In RStudio, the app simply crashes trying to load the package. Retried and re-downloaded the package several times but none of it has worked so far. Eagerly and urgently looking for a solution. This is on CRAN R, MacOS 10.12 (Sierra)

**Comment by seankross** [comment]
HI @shivendra90,

Can you copy the error message here?

**Comment by shivendra90** [comment]
@seankross 

This is the message I get after library(swirl):

`*** caught segfault ***
address 0x18, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(package, lib.loc)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(expr, error = function(e) {    call <- conditionCall(e)    if (!is.null(call)) {        if (identical(call[[1L]], quote(doTryCatch)))             call <- sys.call(-4L)        dcall <- deparse(call)[1L]        prefix <- paste("Error in", dcall, ": ")        LONG <- 75L        msg <- conditionMessage(e)        sm <- strsplit(msg, "\n")[[1L]]        w <- 14L + nchar(dcall, type = "w") + nchar(sm[1L], type = "w")        if (is.na(w))             w <- 14L + nchar(dcall, type = "b") + nchar(sm[1L],                 type = "b")        if (w > LONG)             prefix <- paste0(prefix, "\n  ")    }    else prefix <- "Error : "    msg <- paste0(prefix, conditionMessage(e), "\n")    .Internal(seterrmessage(msg[1L]))    if (!silent && identical(getOption("show.error.messages"),         TRUE)) {        cat(msg, file = stderr())        .Internal(printDeferredWarnings())    }    invisible(structure(msg, class = "try-error", condition = e))})
11: try({    attr(package, "LibPath") <- which.lib.loc    ns <- loadNamespace(package, lib.loc)    env <- attachNamespace(ns, pos = pos, deps)})
12: library(swirl)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace`

**Comment by shivendra90** [comment]
Eagerly awaiting a solution. I have courses to finish.

**Comment by seankross** [comment]
What do you get as the result of `sessionInfo()`?

**Comment by shivendra90** [comment]
Unfortunately, clean re-install of R 3.3.1 did not fix the issue. Strangely though, the MRAN version did not have any problems while installing swirl but it had issues similar to my earlier post for other packages so I had to completely remove it too. As of now, the newest version R 3.3.2 has successfully unpacked the package and its been working as it should. Might respond again if a course gives similar errors.
