### ISSUE TITLE
Trouble with submitting a function 

### ISSUE THREAD

**Issue by nskabiri** [swirldev/swirl#574]
I am having issues with module 9 of the swirl lesson. I am unable to submit my functions. I have tried shutting down RStudio and opening it back up again, but the problem persists. Attached is a screen shot of the error that I receive. 
<img width="1201" alt="screen shot 2016-12-07 at 10 48 01 am" src="https://cloud.githubusercontent.com/assets/14840135/20974564/b7ef1f20-bc6a-11e6-966e-cc8cc5832fc6.png">

**Comment by seankross** [comment]
1. Restart R and restart the lesson.
2. Edit `my_mean.R`
3. Save `my_mean.R`
4. Enter `submit()` into the R console.

Let me know if that works for you.

**Comment by nskabiri** [comment]
I restarted R, and restarted the lesson, but now the issue persists with the previous exercise. 
Again, attached is the screenshot. 
<img width="1243" alt="screen shot 2016-12-07 at 2 40 42 pm" src="https://cloud.githubusercontent.com/assets/14840135/20983566/f5222ac0-bc8a-11e6-9496-03743a943a79.png">

**Comment by seankross** [comment]
It looks like you didn't edit `boring_function.R` in order to make it work. After editing  `boring_function.R` save the file and then enter `submit()` into the R console.

**Comment by nskabiri** [comment]
Sean, 

I didn't realize that changes had to be made directly in the editor window. 

Thank you !
