### ISSUE TITLE
Error installing swirl: missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by jjlugus** [swirldev/swirl#576]
I am trying to install swirl through RStudio (I also downloaded/installed R) and get this error message:

Error in install.packages : missing value where TRUE/FALSE needed
> 

I also get the same error when I try to install swirl in R.  Any help/suggestions?

**Comment by seankross** [comment]
What happens when you enter: `install.packages("swirl")` into the R console?

**Comment by jjlugus** [comment]
I get the same error message as in RStudio

**Comment by seankross** [comment]
Try:

```
options(repos=c(CRAN="https://cran.rstudio.com/"))
install.packages("swirl")
```

**Comment by jjlugus** [comment]
Now I get a different error:
Warning in install.packages :
  cannot open file '\\(server, machine and uer nameand info)$\DATA\R\R-3.3.2\library\file30f0cda28/stringi/MD5': Permission denied
Error in install.packages : cannot open the connection

**Comment by seankross** [comment]
Are you using a computer that is owned by work or school?

**Comment by jjlugus** [comment]
Yes, it is my work machine.  I previously had put R, RStudio, and swirl on my last computer but just had to upgrade my computer recently.

**Comment by seankross** [comment]
You should talk to you IT department about permissions on your computer so that you can install R packages and swirl courses in the future.

**Comment by jjlugus** [comment]
Will do, thanks.

**Comment by seankross** [comment]
If you're still having trouble installing after making sure you have the correct permissions, don't hesitate to get in touch. I should have asked this but does this happen when you're trying to install other packages?

**Comment by jjlugus** [comment]
Just tried to install ggplot2 and got the same error:

Error in install.packages : cannot open the connection

Clearly I need to talk to my IT folks.
