### ISSUE TITLE
Exercise 9 Function issue

### ISSUE THREAD

**Issue by kobaliya** [swirldev/swirl#583]
Hi, my response to 

| Now try using evaluate() along with an anonymous
| function to return the last element of the vector c(8,
| 4, 0). Your anonymous function should only take one
| argument which should be a variable `x`.

is the following: evaluate(function(x){x[length(x)]}, c(8, 4, 0))

I am given the following error: Error in evaluate(function(x) { : unused argument (c(8, 4, 0))

Any help is appreciated!

**Comment by seankross** [comment]
Hi @kobaliya,

What did you write for your evaluate function?

**Comment by kobaliya** [comment]
Hi, Sean,

I have the following:

| Now try using evaluate() along with an anonymous
| function to return the last element of the vector c(8,
| 4, 0). Your anonymous function should only take one
| argument which should be a variable `x`.
> evaluate(function(x){x[length(x)]}, c(8,4,0))Error in evaluate(function(x) { : unused argument (c(8, 4, 0))

>

Thanks,
Yelena

**Comment by kobaliya** [comment]
This is where I returned to swirl after exiting it. I am not sure if that
makes a difference.

Best,
Yelena

**Comment by seankross** [comment]
How did you write the evaluate function?

**Comment by kobaliya** [comment]
evaluate <- function(func, dat){
        func(dat)
}

**Comment by seankross** [comment]
I hate to say it but you may need to start this lesson over. Sorry.

**Comment by kobaliya** [comment]
How can I do that?

Thanks!

**Comment by seankross** [comment]
Hi @kobaliya,

After entering `swirl()` into the R console, enter your user name, then indicate that you want to start a new course, and choose the Functions lesson from R Programming.

**Comment by kobaliya** [comment]
That was simple. Thank you!
