### ISSUE TITLE
bitops error on install

### ISSUE THREAD

**Issue by 53peterp** [swirldev/swirl#585]
hi 
I'm having a  problem installing swirl. This is the message I am getting in the R studio console window. All the other  packages installed OK.

package ‘bitops’ successfully unpacked and MD5 sums checked
Warning in install.packages :
  unable to move temporary installation ‘C:\Users\Peter.Peter-PC\R\win-library\3.3\file1b2063ea3697\bitops’ to ‘C:\Users\Peter.Peter-PC\R\win-library\3.3\bitops’

> library("swirl")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘bitops’
Error: package or namespace load failed for ‘swirl’

can anybody give me a suggested fix for this?

I assume that the file called bitops didn't get moved to the  install directory because of some permissions error(why that would happen though when all the other files installed I don't know). Would it be possible to move file to the install directory  manually then run a command to unpack this file only?

**Comment by gmisiuly** [comment]
Whats the resolution to this issue? I have exactly the same problem.

**Comment by seankross** [comment]
@gmisiuly have you tried installing bitops on your own?
