### ISSUE TITLE
swirl is not able to load 'ggplot2'

### ISSUE THREAD

**Issue by mahimanarain** [swirldev/swirl#586]
I am getting the following error
"Attempting to load lesson dependencies...

| Package ‘jpeg’ loaded correctly!

Error in library(ggplot2) : there is no package called ‘ggplot2’

| Leaving swirl now. Type swirl() to resume."

**Comment by seankross** [comment]
Have you tried installing ggplot2?

**Comment by mahimanarain** [comment]
Hi, I have installed ggplot2. Error is now resolved. Thanks
