### ISSUE TITLE
Display the number of steps and total steps in progress bar

### ISSUE THREAD

**Issue by wush978** [swirldev/swirl#589]
Dear swirldev team,

This is just a suggestion. 

In my experience, sometimes the users are willing to know the real current step instead of the percentage of the total step. This is useful when they want's to report issues to the course developer when they want to locate the issued step in the yaml file.

On my forked branch, I resolve this issue via: https://github.com/wush978/swirl/pull/9/files

Thanks for your contribution of swirl.

Best,
Wush

**Comment by seankross** [comment]
Hi @wush978,

This is a good idea. I'll incorporate into the next version of swirl. Thanks again for your continued interest and contributions.

Sean
