### ISSUE TITLE
R 3.2.1 with swirl 2.4.2

### ISSUE THREAD

**Issue by XoliloX** [swirldev/swirl#593]
Hi all,

Trying to follow a coursera lesson on R here. I can't get swirl to be successfully installed and tried a lof of stuff already. It seems that swirl 2.4.2 is not working with R 3.2.1 but I can't have a newer version of R due to my "old mac OS" (10.8). I actually would like to avoid upgrading my computer unless someone can tell me ; yes, you have no choice. Here below are my info :

sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.8.5 (Mountain Lion)

locale:
[1] fr_BE.UTF-8/fr_BE.UTF-8/fr_BE.UTF-8/C/fr_BE.UTF-8/fr_BE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_1.2.1     R6_2.2.0       tools_3.2.1    RCurl_1.95-4.8 digest_0.6.10  bitops_1.0-6  

And each time I try to install swirl (that can be seen in "packages") I have this error  :

Error in loadNamespace (j <- i [[1L]], c (lib.loc, .libPaths ()), versionCheck = vI [[j]]):
   No package named 'stringr' is found
In addition: Warning message:
The 'swirl' package has been compiled with version R 3.2.5
Error: loading the package or namespace failed for 'swirl'

And of course I can't get stringr to be successfully installed either...

Any help is welcomed !!!!

Thanks a lot in advance !!!

D.

**Comment by seankross** [comment]
Have you tried installing stringr on its own?

**Comment by XoliloX** [comment]
Hi Sean !

Thanks for you reply. Yes and it did not worked. Here's the output (translated from french) :

> Install.packages ("stringr")
also installing the dependency ‘stringi’

  Binary versions are available but the versions of the sources are more recent:
        Binary source needs_compilation
Stringi 1.1.1 1.1.2 FALSE
Stringr 1.0.0 1.2.0 FALSE

Installing the source packages 'stringi', 'stringr'

  % Total% Received% Xferd
                                 Dload Upload Total Spent Left Speed
  0 0 0 0 0 0 0 0 0: -: - -: -: - -: -: - 0100 3559k 100 3559k 0 0 6419k 0 -: -: - - : -: - -: -: - 6653k
  % Total% Received% Xferd
                                 Dload Upload Total Spent Left Speed
  0 0 0 0 0 0 0 0 -: -: - -: -: - -: -: - 0100 94095 100 94095 0 0 580k 0 -: -: - - : -: - -: -: - 665k
* Installing * source * package 'stringi' ...
** package 'stringi' properly decompressed and MD5 checked
Checking for local ICUDT_DIR ... icu55 / data
Checking for R_HOME ... /Library/Frameworks/R.framework/Resources
Checking for R ... /Library/Frameworks/R.framework/Resources/bin/R
Checking for R> = 3.1.0 ... yes
Checking for cat ... / bin / cat

then this line x100 times /Library/Frameworks/R.framework/Resources/bin/config: line 150: make: command not found

and then

Checking for gcc ... no
Checking for cc ... no
Checking for cl.exe ... no
Configure: error: in `/private/var/folders/yt/6hnp_9qd2ws7xz8933z1lk_h0000gn/T/RtmpHzNKGT/R.INSTALLd20c5319c32f/stringi ':
Configure: error: no acceptable C compiler found in $ PATH
See `config.log 'for more details
ERROR: configuration failed for package 'stringi'
* Removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/stringi'
Warning in install.packages:
   Installation of package 'stringi' had non-zero exit status
ERROR: dependency 'stringi' is not available for package 'stringr'
* Removing '/Library/Frameworks/R.framework/Versions/3.2/Resources/library/stringr'
Warning in install.packages:
   Installation of package 'stringr' had non-zero exit status

The downloaded source packages are in
'/ Private / var / folders / yt / 6hnp_9qd2ws7xz8933z1lk_h0000gn / T / RtmpwXbsru / downloaded_packages'

What do you think ?
Thanks,
D.

**Comment by seankross** [comment]
Try:

```
install.packages("stringi", type = "mac.binary")
```

And let me know if that works.

**Comment by XoliloX** [comment]
Hi Sean,

I could successfully load stringi, stringr and swirl ! Thank you so much. Now, I still have a token issue but I'll try to solve it before posting. Thanks a thousand times !!!!!

**Comment by seankross** [comment]
No problem, if you're having any issues don't hesitate to ask!
