### ISSUE TITLE
install_from_swirl("Getting and Cleaning data") is not loading in R

### ISSUE THREAD

**Issue by varamihir** [swirldev/swirl#595]
First I loaded swirl package in R. After that I tried to install_from_swirl("Getting and Cleaning data") but didn't load. I want to do some practice on getting and cleaning data. Please let me know if there is any way to fix this problem.

**Comment by seankross** [comment]
Try:

```r
install_course("Getting and Cleaning Data")
```

**Comment by varamihir** [comment]
Thanks that worked!

Thanks,
Arti

**Comment by MariGeorge** [comment]
I tried install_course("Getting and Cleaning Data") . It does not work either. Any suggestions.  Thanks Jean

**Comment by seankross** [comment]
@MariGeorge What error do you get when you try to install that course?
