### ISSUE TITLE
"Generate code" option not available

### ISSUE THREAD

**Issue by XoliloX** [swirldev/swirl#596]
Hi all, 

Trying to get credit for coursera here but the token from is not working properly.
I have the following :

Would you like to receive credit for completing this course on Coursera.org?
1: Yes
2: No
Selection: 1
What is your email address? xxxx@gmail.com
What is your assignment token? xxxx
Grade submission failed.
Press ESC if you want to exit this lesson and you
want to try to submit your grade at a later time.

It seems that I should be able to have the "generate code" option but it's not there. Any idea how to settle this ?

Thanks so much in advance !!!
D.

sessionInfo()
R version 3.2.1 (2015-06-18)
Platform: x86_64-apple-darwin10.8.0 (64-bit)
Running under: OS X 10.8.5 (Mountain Lion)
locale:
[1] fr_BE.UTF-8/fr_BE.UTF-8/fr_BE.UTF-8/C/fr_BE.UTF-8/fr_BE.UTF-8
attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] swirl_2.4.2
loaded via a namespace (and not attached):
 [1] httr_1.2.1     magrittr_1.5   R6_2.2.0       tools_3.2.1    RCurl_1.95-4.8 curl_1.2       yaml_2.1.13   
 [8] crayon_1.3.2   stringi_1.1.1  stringr_1.0.0  digest_0.6.10  testthat_1.0.2 bitops_1.0-6

**Comment by seankross** [comment]
What course is this for?

**Comment by XoliloX** [comment]
This one : https://www.coursera.org/learn/r-programming-environment/

**Comment by seankross** [comment]
How did you install this course?

**Comment by XoliloX** [comment]
install_course("The R Programming Environment")

**Comment by XoliloX** [comment]
(and actually "setting up swirl" as lesson 1 is missing)

**Comment by seankross** [comment]
What lesson did you just complete?

**Comment by XoliloX** [comment]
Basic Building Blocks

**Comment by seankross** [comment]
I recommend you reinstall the course.

**Comment by XoliloX** [comment]
Thanks !
