### ISSUE TITLE
There is no ASSIGNMENT TOKEN for Getting and cleaning data?

### ISSUE THREAD

**Issue by varamihir** [swirldev/swirl#598]
I couldn't see the token for getting and cleaning data and for dplyr  practices in Swirl. Please confirm if it is not there.

**Comment by tahoemate** [comment]
See the swirl section for Week3 - there are 3 tokens there.

**Comment by varamihir** [comment]
Thank you so much for your response. Ok I got it.

Thanks,
Arti
