### ISSUE TITLE
Can't start lessons without internet connection !

### ISSUE THREAD

**Issue by xnguefack** [swirldev/swirl#600]
Hi dear,

I have a serious request concerning offline lessons, previously I was able to start a lessons while being offline, I didn't need to be connected to internet to start a lesson...I have updated my swirl package and I can't start a lesson without my google account authentication...I am leaving in Bamenda (Cameroon) and actually I don't have internet connection, our internet connection have being shutdown all over the region, I am thus oblige to travel to have access to everything related to internet...then when I am back home I can't continue my lessons nor start a new lesson...PLEASE is there a mean for me to start my lessons without internet connection?

Thanks in advance

**Comment by seankross** [comment]
If you're installing swirl with `install.packages("swirl")` then you shouldn't need any kind of authentication.

**Comment by xnguefack** [comment]
Thank you Sean, the problem is solve, before receiving your answer I have just reinstall by intuition  through install.packages("swirl") and everything has return to normal !!!!

**Comment by seankross** [comment]
Have you ever installed swirl from another source?

**Comment by xnguefack** [comment]
I think the last time I install was from

**Comment by seankross** [comment]
Can you remember what other source you used? If somebody else is distributing swirl I'd be very interested to know.

**Comment by xnguefack** [comment]
Thanks for your reaction sean... I can'be sure but it was another distribution but I thing I install a lesson from Data Science And R  and this cause me trouble...now I'm hesitating to reinstall it

**Comment by seankross** [comment]
Do they have a website? Can you post the link here?

**Comment by xnguefack** [comment]
yup...here is the site http://datascienceandr.org/

**Comment by seankross** [comment]
Thank you.
