### ISSUE TITLE
Issue with answer of Lesson 8 - Logic

### ISSUE THREAD

**Issue by CotrimJR** [swirldev/swirl#601]
**I had to select a wrong answer to continue the lesson.**

It keeps saying that the answer is wrong until I select 3, that is incorrect. The correct answer should be 2.

Here is what happened:
-------------------------------------------------
**Which of the following evaluates to FALSE?** | **Result**
------------ | -------------
**1:** xor(identical(xor, 'xor'), 7 == 7.0) |TRUE
**2:** xor(4 >= 9, 8 != 8.0) | FALSE
**3:** xor(!isTRUE(TRUE), 6 > -1) | TRUE
**4:** xor(!!TRUE, !!FALSE) | TRUE

Selection: **3**

| That's correct!

**Comment by seankross** [comment]
Thanks for letting me know, I can't reproduce this error on my machine but I'll look into it.
