### ISSUE TITLE
Unknown TZ UTC

### ISSUE THREAD

**Issue by jonmpowell** [swirldev/swirl#603]
When completing an introductory task, I get the following message and can't move on. Any help you be great...

| Lastly, we want the values in the class column to simply be 1, 2, ..., 5 and not class1, class2, ..., class5. We can use the parse_number()
| function from readr to accomplish this. To see how it works, try parse_number("class5").

> parse_number("class5")
Error: Unknown TZ UTC
>

**Comment by seankross** [comment]
Thanks for letting us know. What's your geographic location?

**Comment by jonmpowell** [comment]
Manchester, UK
So I've tried setting as Europe/London etc. etc. 

    On Tuesday, 21 March 2017, 13:44, Sean Kross <notifications@github.com> wrote:
 

 Thanks for letting us know. What's your geographic location?—

**Comment by seankross** [comment]
Does this problem persist after restarting R?

**Comment by jonmpowell** [comment]
Yes....just tried it again with the same error.
thanks 

    On Tuesday, 21 March 2017, 14:31, Sean Kross <notifications@github.com> wrote:
 

 Does this problem persist after restarting R?—

**Comment by seankross** [comment]
What course and lesson is this happening in?

**Comment by jonmpowell** [comment]
hi, this is in the 'parse_number("class5")' task in getting and cleaning data (lesson 3, from memory, sorry I'm on my mobile)thanks
Jon
 

    On Tuesday, 21 March 2017, 14:38, Sean Kross <notifications@github.com> wrote:
 

 What course and lesson is this happening in?—

**Comment by seankross** [comment]
I'm sorry but even after trying to change my timezone I can't reproduce this error. Are you sure all of the involved packages are up to date? Have you tried clearing your workspace and then restarting the lesson?

**Comment by jonmpowell** [comment]
Hi Sean,
Thanks very much for looking into this for me, it seems to be a larger problem (for me) in that I can't use any readr functions at all, which is a bit frustrating but...
Anyway thanks for your help
Best
Jon 

    On Friday, 31 March 2017, 17:17, Sean Kross <notifications@github.com> wrote:
 

 I'm sorry but even after trying to change my timezone I can't reproduce this error. Are you sure all of the involved packages are up to date? Have you tried clearing your workspace and then restarting the lesson?—

**Comment by jonmpowell** [comment]
sorry for filling your inbox but...
I'm also reassured that the issue isn't just me...timezone error reading csv
Thanks again for looking into this for me, what excellent support!
  
|  
|  
|  
|   |    |

  |

  |
|  
|   |  
timezone error reading csv
 After googling for a couple of hours I have not found a solution to this problem. Basically when I run read_csv(...  |   |

  |

  |

 
 

    On Wednesday, 5 April 2017, 10:44, Jonathan Powell <jonmpowell@ymail.com> wrote:
 

 Hi Sean,
Thanks very much for looking into this for me, it seems to be a larger problem (for me) in that I can't use any readr functions at all, which is a bit frustrating but...
Anyway thanks for your help
Best
Jon 

    On Friday, 31 March 2017, 17:17, Sean Kross <notifications@github.com> wrote:
 

 I'm sorry but even after trying to change my timezone I can't reproduce this error. Are you sure all of the involved packages are up to date? Have you tried clearing your workspace and then restarting the lesson?—

**Comment by seankross** [comment]
@jonmpowell, no problem, make sure that the proper issue is filed over at readr: https://github.com/tidyverse/readr (somebody else probably already opened the issue).
