### ISSUE TITLE
where do i start?

### ISSUE THREAD

**Issue by afriedman412** [swirldev/swirl#604]
i installed swirl but i can't figure out what to do next

‘R Programming: The basics of programming in R' won't load and i don't understand how to install it from github

how do i get started?

**Comment by afriedman412** [comment]
the error im getting is "| Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in
| R’ right now. Are you sure you have an internet connection? If so, would you
| like to try again or visit the course repository for instructions on how to
| install a course manually? Type 0 to exit."

**Comment by seankross** [comment]
You can install it manually, directions here: http://swirlstats.com/scn/rprog.html
