### ISSUE TITLE
Issues with installing: install_from_swirl("R Programming")

### ISSUE THREAD

**Issue by boshrakargar** [swirldev/swirl#617]
I have problem while I want to install R Programming

> install_from_swirl("R Programming")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failure when receiving data from the peer

**Comment by sathur90** [comment]
Same thing happened for me too.

**Comment by seankross** [comment]
See installation instructions here: http://swirlstats.com/scn/rprog.html
