### ISSUE TITLE
Swirl not accepting skip() input

### ISSUE THREAD

**Issue by Kiserian** [swirldev/swirl#624]
Hello. 

I'm currently mentoring JHU "The R Programming Environment" in Coursera. Recently an issue started to appear, where in certain part of an Swirl Lesson (Lesson 12-Titanic parts 3 and 4) cannot be skipped nor the solutions introduced are approved. Reset() function does not work either, and copying and pasting the solution provided by skip() does not work either. The bug is present across plataforms (OS) and R versions.

So far we (me and the learners) have tried: 
- Restarting R.
- Reinstalling course and Swirl.
- Reinstalling course and Swirl after deleting ALL binaries (course data, and associated files).
- Some learners tried to downgrade R without any luck. 

I tried to replicate the bug but without any success, I can still use skip() and reset().

Some tech specs associated with the learners having the issue:

- Windows 10, R 3.4.0, RStudio 1.0.143, x86_64-w64-mingw32/x64 (64-bit), ALSO in R 3.3.1 and RStudio 1.0.136
- Windows 10 64 bit, 32 GB Ram, OS build 14363.1198, RStudio ver 1.0.136, R ver 3.33, Swirl ver 2.4.3

- Mac OS X Sierra (x64), 16 GB RAM, Swirl version 2.4.3 in R v3.4.0 and RStudio v1.0.143.

- Mac OS X Sierra (x64), 16 GB RAM, Swirl version 2.4.3 in R version 3.3.2 and RStudio v1.0.14

- Windows 10 x64 with 8 gB RAM R version 3.4.0 (2017-04-21) x86_64-w64-mingw32/x64 (64-bit) . Swirl 2.4.3 RStudio 1.0.143

- Mac OS X Sierra (x64) 10.12.3, 8 GB RAM, R version 3.4.0, RStudio Version 1.0.143, Swirl 2.4.3

- Windows 7 (x64), 16 GB RAM, R version 3.4.0, RStudio Version 1.0.143, Swirl version 2.4.3

- Windows 10 Enterprise x64, R 3.3.2 Assuming RStudio 1.0.136 and Swirl v 2.4.3 (soon updated)

Soon I'll attach an image of the output given. 
Any information, will be highly appreciated. 
Thank you!

EDIT: Forgot to add my techspecs. In my build, the issue is NOT present.
- Windows 7 x64, 8Gb RAM. R 3.3.1 RStudio 1.0.136 Swirl 2.4.2. 
I also uninstalled swirl and the course and updated to Swirl 2.4.3 and reinstalled the course. The issue was not present.

**Comment by seankross** [comment]
Hi @Kiserian,

I just tried the course and I think I encountered the same error. I updated the course with a fix. Students will need to do the following in order to ensure they have a working version of the course:

```
install.packages(c("dplyr", "tidyr", "swirl"))
library(swirl)
install_course("The R Programming Environment")
swirl()
```

If the course is still not working after this fix please let me know.

**Comment by ridenourranchcompany** [comment]
Hi,
 I am doing an R course that uses Swirl.  I am in chapter 12 of the R Programming Environment - Data Manipulation.  I am stuck on the final problem about the Titanic Survivors.  I began with code from the previous question, which creates the first data frame. 

    titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) 
       mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                      include.lowest = TRUE,
                      labels = c("Under 15", "15 to 50",
                                 "Over 50")))
       head (titanic_4)

     

    # After the previous question, you should have transformed the `titanic`
    # data to look like this:
    #
    ##   Survived Pclass   Age     Sex      agecat
    ##          0      3    22    male    15 to 50
    ##          1      1    38  female    15 to 50
    ##          1      3    26  female    15 to 50
    ##          1      1    35  female    15 to 50
    ##          0      3    35    male    15 to 50
    ##          0      1    54    male     Over 50
    #
    # Add one or more `dplyr` or `tidyr` functions to the pipe chain in 
    # the code at the bottom of the script to change the `titanic` 
    # dataset. The first six lines of the final `titanic_4` dataset 
    # should look like the following example, with the number of
    # passengers, number of survivors, and percent survival stratified
    # by passenger class, age category, and sex. Be sure to use the 
    # same column names as shown in the example output. 
    #
    ## Pclass   agecat    Sex      N     survivors   perc_survived
    ## <int>   <fctr>    <chr>   <int>     <int>         <dbl>
    ##   1    Under 15  female     2         1        50.000000
    ##   1    Under 15    male     3         3       100.000000
    ##   1    15 to 50  female    70        68        97.142857
    ##   1    15 to 50    male    72        32        44.444444
    ##   1    Over 50   female    13        13       100.000000
    ##   1    Over 50     male    26         5        19.230769

To solve this problem, I created this code:

  

    titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) %>%
      mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
   

                           include.lowest = TRUE,
                              labels = c("Under 15", "15 to 50",
                                         "Over 50"))) %>%
          group_by(Pclass,agecat,Sex) %>%
          summarize(N=n(), survivors = sum(Survived))%>%
          mutate(perc_survived = sprintf("%.6f", 
          ((survivors/N)*100.000000)))
    
      head(titanic_4)

Which gives this output:

    # A tibble: 6 x 6
    # Groups:   Pclass, agecat [3]
      Pclass   agecat    Sex     N survivors perc_survived
       <int>   <fctr>  <chr> <int>     <int>         <chr>
    1      1 Under 15 female     2         1     50.000000
    2      1 Under 15   male     3         3    100.000000
    3      1 15 to 50 female    70        68     97.142857
    4      1 15 to 50   male    72        32     44.444444
    5      1  Over 50 female    13        13    100.000000
    6      1  Over 50   male    26         5     19.230769

The above output is wrong because the last column (perc_survived) is a character <chr> instead of a <dbl>.

To solve this, I tell R to change the type to numeric with the as.numeric function.


      titanic_4 <- titanic %>% 
      select(Survived, Pclass, Age, Sex) %>%
      filter(!is.na(Age)) %>%
      mutate(agecat = cut(Age, breaks = c(0, 14.99, 50, 150), 
                          include.lowest = TRUE,
                          labels = c("Under 15", "15 to 50",
                                     "Over 50"))) %>%
      group_by(Pclass,agecat,Sex) %>%
      summarize(N=n(), survivors = sum(Survived))%>%
      mutate(perc_survived = sprintf("%.6f", (perc_survived = as.numeric 
      ((survivors/N)*100.000000))))  
       head(titanic_4)


which creates this output:

    # A tibble: 6 x 6
    # Groups:   Pclass, agecat [3]
      Pclass   agecat    Sex     N survivors perc_survived
       <int>   <fctr>  <chr> <int>     <int>         <dbl>
    1      1 Under 15 female     2         1      50.00000
    2      1 Under 15   male     3         3     100.00000
    3      1 15 to 50 female    70        68      97.14286
    4      1 15 to 50   male    72        32      44.44444
    5      1  Over 50 female    13        13     100.00000
    6      1  Over 50   male    26         5      19.23077

 The new problem is that the output is rounded to 5 digits after the decimal place instead of 6 digits.  I have tried every combination I can find, but have not been able to tell r to keep 6 decimals when it converts from character to numeric.

I'm stuck and need some guidance from a generous person.  Thank you,  Andrew

**Comment by VrunBert** [comment]
@seankross 
could you please try to `submit() `Titanic Step 4 on `dplyr `0.8.0 as the last time you looked at this it might have been version 0.7.0?  
[https://cran.r-project.org/src/contrib/Archive/dplyr/](url)

Here is my build:

```
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     
other attached packages:
[1] faraway_1.0.7  titanic_0.1.0  tidyr_0.8.3    dplyr_0.8.0    swirl_2.4.3    usethis_1.4.0 
[7] devtools_2.0.1
```
`submit()` with the 'correct' code produces 'keep trying' with the following error:

```
warning messages from top-level task callback 'mini'
Warning messages:
1: Detecting old grouped_df format, replacing `vars` attribute by `groups` 
2: Detecting old grouped_df format, replacing `vars` attribute by `groups` 

```
i tried to uninstall `dplyr `0.8.0 and install 0.7.0 as someone suggested in Discussions but getting a bunch of namespace errors after numerous attempts.  It's possible a lot of people may have the same issue having downloading the newest March release

**Comment by VaibhaviNirajPathak** [comment]
I am even facing the same Warning message after ample number of tries.

**Comment by VaibhaviNirajPathak** [comment]
@seankross , Hi, could you solve your problem? as I am getting the same error and unable to submit after spending two days on this.

**Comment by jasonrims** [comment]
Same error on this course. Can someone help?

**Comment by brightandsparkly** [comment]
Same problem, swirl does not even accept its own model solution as correct

**Comment by Abssingh** [comment]
> @seankross , Hi, could you solve your problem? as I am getting the same error and unable to submit after spending two days on this.
Hi, did you succeeded in submitting the code, cause I'm stuck at this from past 2 days but nothing works.

**Comment by karnika01** [comment]
@seankross Please respond sir,i joined Github for this problem and for getting a solution for this. I had tried doing the same process as you had mentioned and applying ungroup() at the end as suggested by few as well, but the problem persists. Please respond as soon as possible sir.
Thank you
![Screenshot (43)](https://user-images.githubusercontent.com/67234638/85229569-0b448780-b408-11ea-9634-63676f13aa55.png)
this is what it looks like.
