### ISSUE TITLE
Trouble installing swirl

### ISSUE THREAD

**Issue by priyabhatter** [swirldev/swirl#628]
Hello,

I just set up R and I'm trying to install swirl.
I keep getting the following error : 

Error: package or namespace load failed for ‘swirl’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’

I'm new to R and programming, so any help fixing this would be awesome! Thanks!

**Comment by davidmeza1** [comment]
The error is telling you the 'stringi' package is not installed and needed.
Run, install.packages("stringi") to install it, then retry installing swirl.

**Comment by priyabhatter** [comment]
This worked! Thanks!
