### ISSUE TITLE
Unable to restart swirl! When I run library(swirl) I get the following error message: Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env): cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory

### ISSUE THREAD

**Issue by sowmyavp** [swirldev/swirl#629]
**Hi,
I started working on swirl to finish course 2 (R Programming) on coursera. I installed Swirl and finished practice programming lesson 1. When I got back to it the next day i realized the laptop battery had died and all the running applications including R were closed. Then on I have never been able to get on swirl again. As I restarted R my previous wokspace had no history.

So, I tried reinstalling swirl and received this message:**
install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpoHAwa1\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
 cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory
In addition: Warning message:
package ‘swirl’ was built under R version 3.4.1 

**Then, I downloaded latest version of R (3.4.1). Reinstalled swirl in this version and when I run library (swirl) I go an error message. Also tried an additional step, still no expected result.**

> install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
 DLL ‘bitops’ not found: maybe not installed for this architecture?
> install.packages("stringi")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/stringi_1.1.5.zip'
Content type 'application/zip' length 14289534 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
 DLL ‘bitops’ not found: maybe not installed for this architecture?

**For the above error message I tried a couple of more steps:**
> install.packages("bitops")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/bitops_1.0-6.zip'
Content type 'application/zip' length 37218 bytes (36 KB)
downloaded 36 KB

package ‘bitops’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
 DLL ‘RCurl’ not found: maybe not installed for this architecture?
> install.packages("RCurl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2871018 bytes (2.7 MB)
downloaded 2.7 MB

package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘RCurl’

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘RCurl’
> install.packages("RCurl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2871018 bytes (2.7 MB)
downloaded 2.7 MB

package ‘RCurl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
 cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory
> install.packages("swirl", dependencies=TRUE)
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages
> library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
 cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory

**Please, help me with this issue. I have no idea what else I can try. Library (swirl) just doesn't seem to work!

Thanks you.**

**Comment by llshine** [comment]
R version 3.4.1
you can install,please try








在2017年08月3日 05:01，sowmyavp<notifications@github.com> 写道：

**Hi,
I started working on swirl to finish course 2 (R Programming) on coursera. I installed Swirl and finished practice programming lesson 1. When I got back to it the next day i realized the laptop battery had died and all the running applications including R were closed. Then on I have never been able to get on swirl again. As I restarted R my previous wokspace had no history.

So, I tried reinstalling swirl and received this message:**
install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpoHAwa1\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory
In addition: Warning message:
package ‘swirl’ was built under R version 3.4.1

Then, I downloaded latest version of R (3.4.1). Reinstalled swirl in this version and when I run library (swirl) I go an error message. Also tried an additional step, still no expected result.

install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
DLL ‘bitops’ not found: maybe not installed for this architecture?
install.packages("stringi")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/stringi_1.1.5.zip'
Content type 'application/zip' length 14289534 bytes (13.6 MB)
downloaded 13.6 MB

package ‘stringi’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

install.packages("swirl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
DLL ‘bitops’ not found: maybe not installed for this architecture?

For the above error message I tried a couple of more steps:

install.packages("bitops")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/bitops_1.0-6.zip'
Content type 'application/zip' length 37218 bytes (36 KB)
downloaded 36 KB

package ‘bitops’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
DLL ‘RCurl’ not found: maybe not installed for this architecture?
install.packages("RCurl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2871018 bytes (2.7 MB)
downloaded 2.7 MB

package ‘RCurl’ successfully unpacked and MD5 sums checked
Warning: cannot remove prior installation of package ‘RCurl’

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
there is no package called ‘RCurl’
install.packages("RCurl")
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/RCurl_1.95-4.8.zip'
Content type 'application/zip' length 2871018 bytes (2.7 MB)
downloaded 2.7 MB

package ‘RCurl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory
install.packages("swirl", dependencies=TRUE)
Installing package into ‘C:/Users/prassanth/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.mtu.edu/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236488 bytes (230 KB)
downloaded 230 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\prassanth\AppData\Local\Temp\RtmpgP2PJS\downloaded_packages

library(swirl)
Error: package or namespace load failed for ‘swirl’ in get(Info[i, 1], envir = env):
cannot open file 'C:/Users/prassanth/Documents/R/win-library/3.4/crayon/R/crayon.rdb': No such file or directory

**Please, help me with this issue. I have no idea what else I can try. Library (swirl) just doesn't seem to work!

Thanks you.**

**Comment by sowmyavp** [comment]
Hi llshine,

Thank you for your response. I have tried that already. It is giving me a series of different errors as mentioned in my primary post.

**Comment by llshine** [comment]
Sorry to hear about that. Or maybe you can try to install R version 3.3.1 again. Swirl maybe needs old environment to work. Good luck!








在2017年08月4日 03:42，sowmyavp<notifications@github.com> 写道：

Hi llshine,

Thank you for your response. I have tried that already. It is giving me a series of different errors as mentioned in my primary post.

**Comment by sowmyavp** [comment]
IT WORKS!! Thank you so much :)
