### ISSUE TITLE
Swirl Error: Subject 1, Lesson 4

### ISSUE THREAD

**Issue by zanewolf** [swirldev/swirl#633]
![swirlerror](https://user-images.githubusercontent.com/30910417/29189862-0fdb76a6-7de6-11e7-98ea-1a2c771798a2.PNG)

Just chugging along and the program decides that there must be a second correct answer it's not telling me about. Skip() isn't working. Thoughts?

**Comment by andwil47** [comment]
The same thing happened to me on a different task.  I exited swirl and R initially, but that didnt resolve the issue.  after exiting all again in frustration, I did not return to the program for several hours.  Once i returned, it worked perfectly fine!  Not sure what spontaneously resolved it, but think the program just got stuck in a loop?  Maybe try exiting everything and reloading?

**Comment by ebzheng** [comment]
I also had this - after some playing around with the module and digging in the source code, I can speculate about what happened and offer some solutions:

This question is unique in the module in that it checks the length of the vector produced (here, `my_name`, which should be length 4). If for some reason the user manages to mangle `my_char` and change its length from 3, then the given answer `my_name <- c(my_char, "name")` will not yield a vector of length 4 and will be rejected.

For someone who's stuck, you can get past this with the following command:
`my_name <- c("My", "name", "is", "Swirl")`

For others like @andwil47 who are stuck on other tasks, restarting the module can work. While `restart()` doesn't seem implemented at the moment (Sept 14, 2017), you can do so by going back to the main menu with `main()` and then specifying "Something new". From there, navigate back to the module. Unfortunately, prior progress in that module will be lost.

**Comment by seankross** [comment]
@ebzheng, thanks for solving this one, your proposal for fixing this issue is the best one so far.
