### ISSUE TITLE
Swirl not updated yet! Couldn't find contains() in "purrr" package.

### ISSUE THREAD

**Issue by RominR** [swirldev/swirl#634]
There's a problem in the following course:
Mastering Software Development in R
Course 2: Advance R Programming.
Week 2: Quiz Portion.

OS: macOS Sierra 10.12.6
R Version: 3.4.1
Swirl Version: 2.4.3

One of the quiz questions (in the completion of 69% of the total quiz) in the above mentioned swirl course still asks to answer the question regarding contains() which we cannot find in purrr package anymore. I am not able to proceed further. Every time, I try to solve the problem, I stuck there by getting an error saying:

Error in contains(random_ints, 45) : could not find function "contains"
Could anyone please help me proceed this question?

**Comment by Nirajpaija** [comment]
same problem happened to me. if you solve this plz let me know

**Comment by seankross** [comment]
This should now be fixed if you reinstall the course.

**Comment by Nirajpaija** [comment]
Thank you, i do it before fixed....

**Comment by HemdaLevy** [comment]
I've just bumped into the same problem. I didn't want to lose all the previous swirl work so I just defined a function like this:
> has_element <- function(x,y){contains(x,y)}
and then used it as swirl expected it:
> has_element(random_ints, 45)
and passed ... :)
