### ISSUE TITLE
installing swirl library in r studio 

### ISSUE THREAD

**Issue by T59** [swirldev/swirl#635]
I am having trouble accessing the courses in Swirl for R programming. Package installed but library could not. Any useful suggestions, please.

**Comment by ShreyasFadnavis** [comment]
I am facing the exact same problem!

**Comment by badavids** [comment]
Same problem here. Followed the instructions to install the library and looks like everything went fine. Went to do a tutorial and get the following error message when trying to start swirl:

> library("swirl")
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]): there is no package called ‘RCurl’

**Comment by jacaissie** [comment]
Same here. I was using it yesterday for the R Programming course and now it's not loading.

Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘stringi’
In addition: Warning message:
package ‘swirl’ was built under R version 3.2.5 
Error: package or namespace load failed for ‘swirl’

**Comment by exeterstudent2017** [comment]
I have the same issue, opened it for the first time today and it won't load on my R studio. I am using an OSX 10.8.5. Would appreciate some help!

Put this into the R script:
install.packages('swirl')

library('swirl')
install_course_github("kosukeimai", "qss-swirl")

And this is the response:

Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/mv/y1f8ry7d4z96vd875rc6qr0c0000gn/T/Rtmpp15Hb4/downloaded_packages’
> libaray(swirl)
Error: could not find function "libaray"

Thank you!

**Comment by seankross** [comment]
If you get a message like "there is no package called [name of package]" try installing that package on it's own. Also if you need to manually install the R Programming course you can find instructions
for doing so here: http://swirlstats.com/scn/rprog.html
