### ISSUE TITLE
Problem for downloading swirl to windows 10

### ISSUE THREAD

**Issue by busragurler** [swirldev/swirl#645]
I just want to learn R language. But even I couldnt open Swirl. :/
> install.packages("swirl")
Warning in install.packages :
  'lib = "C:/Program Files/R/R-3.4.2/library"' is not writable
Warning in install.packages :
  cannot create dir 'C:\Users\Bü?ra', reason 'Invalid argument'
Error in install.packages : unable to create ‘C:/Users/Bü?ra/Documents/R/win-library/3.4’
> library("swirl")
Error in library("swirl") : there is no package called ‘swirl’
> > swirl()
Error: unexpected '>' in ">"
>

**Comment by seankross** [comment]
Are you using a computer from your school or workplace?

**Comment by busragurler** [comment]
No, its my own computer

**Comment by seankross** [comment]
Can you try running R or RStudio as an administrator?

**Comment by busragurler** [comment]
I tried on R studio but I dont know if Im an administrotar. Can you tell that how can I check it

**Comment by seankross** [comment]
Right-click RStudio, then click “run as administrator”

**Comment by busragurler** [comment]
Well, it was funny but worked. Thank you!

**Comment by AndreaHuggett** [comment]
Thanks this helped me too! Swirl is installed on my Windows 10 machine

**Comment by AndreaHuggett** [comment]
Solved it - don't worry!! Just ran Rstudio as an administrator
