### ISSUE TITLE
Error while installing Swirl package

### ISSUE THREAD

**Issue by aneeketdalvi** [swirldev/swirl#646]
I am trying to install Swirl package for interactive learning. Following are the steps I tried and the error response:

> install.packages("swirl")
Installing package into ‘C:/Users/anki/Documents/R/win-library/3.4’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.4/swirl_2.4.3.zip'
Content type 'application/zip' length 236815 bytes (231 KB)
downloaded 231 KB

package ‘swirl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\anki\AppData\Local\Temp\Rtmpaelt6a\downloaded_packages

> library("swirl")
Error: package or namespace load failed for ‘swirl’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘crayon’

Please, advise.

**Comment by anhaag** [comment]
I have this same problem

**Comment by seankross** [comment]
Try installing the crayon package on its own.
