### ISSUE TITLE
Not able to load swirl but i assume it is installed

### ISSUE THREAD

**Issue by Madangithub** [swirldev/swirl#649]
The downloaded binary packages are in
	/var/folders/ts/syx225mj4fb7ky5_tsxn08vc0000gn/T//Rtmp0GcptQ/downloaded_packages
#This is what i get after
install.packages("swirl")
#but when i proceed for 
library("swirl")
#i get
Error: package or namespace load failed for ‘swirl’ in library.dynam(lib, package, package.lib):
 shared object ‘stringi.so’ not found
#help

**Comment by Phonl** [comment]
I have downloaded swirl several times, troubleshooting by changes various things in my environment, recreating my working directory, etc. I am prompted that swirl is installed, but then cannot load package. 

package ‘swirl’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\Jerry\AppData\Local\Temp\RtmpAFUbJC\downloaded_packages

> package_version(swirl)
Error in package_version(swirl) : object 'swirl' not found
> package_version("swirl")
Error: invalid version specification ‘swirl’

> library(swirl)
Error: package or namespace load failed for ‘swirl’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’

> library("swirl")
Error: package or namespace load failed for ‘swirl’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘stringi’

> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)
Matrix products: default
locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                 
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] httr_1.3.1     compiler_3.4.2 R6_2.2.2       tools_3.4.2    RCurl_1.95-4.8
[6] digest_0.6.12  bitops_1.0-6

**Comment by seankross** [comment]
Have you tried installing stringi on its own?

**Comment by Phonl** [comment]
Thank you! Independently installing stringi first seems to have solved the problem.

**Comment by Shirlei1975** [comment]
I'm trying to install library(tidyverse) and I'm having this error, someone knows how to solve it?
Error: package or namespace load failed for ‘tidyverse’ in library.dynam(lib, package, package.lib):
 DLL ‘stringi’ not found: maybe not installed for this architecture?

**Comment by akkesarilab** [comment]
i faced exactly same error - 

> library(tidyverse)
Error: package or namespace load failed for ‘tidyverse’ in library.dynam(lib, package, package.lib):
 DLL ‘stringi’ not found: maybe not installed for this architecture?

i installed stringi , but did not resolve the issue , can someone please guide
