### ISSUE TITLE
Swirl Install Error, MacOSX, "Unable to load shared object"

### ISSUE THREAD

**Issue by colinastewart** [swirldev/swirl#655]
**Mac OSX 10.12.6 (Sierra)
Rstudio 1.0.153
R version 3.4.2**

I had a bunch of errors trying to install.packages('swirl'), where it had an issue with 'testthat'.  However, I followed the advice [here](https://github.com/swirldev/swirl/issues/550), and basically manually downloaded 'testthat' from the CRAN website & installed it.  I think it went ok, but now when I try to install Swirl, it says:

> Error in dyn.load(file, DLLpath = DLLpath, ...) : 
>   unable to load shared object '/anaconda3/lib/R/library/stringi/libs/stringi.so':
>   dlopen(/anaconda3/lib/R/library/stringi/libs/stringi.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libc++.1.dylib
>   Referenced from: /anaconda3/lib/R/library/stringi/libs/stringi.so
>   Reason: image not found
> ERROR: lazy loading failed for package ‘swirl’
> * removing ‘/anaconda3/lib/R/library/swirl’ 

I feel like I've tried everything- all the advice online says to install different packages, but I think I have all the ones they name (see below).  Any advice would be greatly appreciated!

**Here's a list of my installed.packages():**

             OS_type MD5sum NeedsCompilation Built  
assertthat   NA      NA     "no"             "3.4.2"
backports    NA      NA     "yes"            "3.4.2"
base         NA      NA     NA               "3.4.2"
base64enc    NA      NA     "yes"            "3.4.2"
BH           NA      NA     "no"             "3.4.2"
bindr        NA      NA     "no"             "3.4.2"
bindrcpp     NA      NA     "yes"            "3.4.2"
bitops       NA      NA     "yes"            "3.4.2"
boot         NA      NA     "no"             "3.4.2"
broom        NA      NA     "no"             "3.4.2"
callr        NA      NA     "no"             "3.4.2"
caret        NA      NA     "yes"            "3.4.2"
caTools      NA      NA     "yes"            "3.4.2"
cellranger   NA      NA     "no"             "3.4.2"
class        NA      NA     "yes"            "3.4.2"
cli          NA      NA     "no"             "3.4.2"
cluster      NA      NA     "yes"            "3.4.2"
codetools    NA      NA     "no"             "3.4.2"
colorspace   NA      NA     "yes"            "3.4.2"
compiler     NA      NA     NA               "3.4.2"
crayon       NA      NA     "no"             "3.4.2"
curl         NA      NA     "yes"            "3.4.2"
CVST         NA      NA     "no"             "3.4.2"
data.table   NA      NA     "yes"            "3.4.2"
datasets     NA      NA     NA               "3.4.2"
DBI          NA      NA     "no"             "3.4.2"
ddalpha      NA      NA     "yes"            "3.4.2"
DEoptimR     NA      NA     "no"             "3.4.2"
dichromat    NA      NA     NA               "3.4.2"
digest       NA      NA     "yes"            "3.4.2"
dimRed       NA      NA     "yes"            "3.4.2"
dplyr        NA      NA     "yes"            "3.4.2"
DRR          NA      NA     "no"             "3.4.2"
evaluate     NA      NA     "no"             "3.4.2"
forcats      NA      NA     "no"             "3.4.2"
foreach      NA      NA     "no"             "3.4.2"
foreign      NA      NA     "yes"            "3.4.2"
formatR      NA      NA     "no"             "3.4.2"
ggplot2      NA      NA     "no"             "3.4.2"
gistr        NA      NA     "no"             "3.4.2"
glmnet       NA      NA     "yes"            "3.4.2"
glue         NA      NA     "yes"            "3.4.2"
gower        NA      NA     "yes"            "3.4.2"
graphics     NA      NA     "yes"            "3.4.2"
grDevices    NA      NA     "yes"            "3.4.2"
grid         NA      NA     "yes"            "3.4.2"
gtable       NA      NA     "no"             "3.4.2"
haven        NA      NA     "yes"            "3.4.2"
hexbin       NA      NA     "yes"            "3.4.2"
highr        NA      NA     "no"             "3.4.2"
hms          NA      NA     "no"             "3.4.2"
htmltools    NA      NA     "yes"            "3.4.2"
htmlwidgets  NA      NA     "no"             "3.4.2"
httpuv       NA      NA     "yes"            "3.4.2"
httr         NA      NA     "no"             "3.4.2"
ipred        NA      NA     "yes"            "3.4.2"
IRdisplay    NA      NA     "no"             "3.4.2"
IRkernel     NA      NA     NA               "3.4.2"
iterators    NA      NA     "no"             "3.4.2"
jsonlite     NA      NA     "yes"            "3.4.2"
kernlab      NA      NA     "yes"            "3.4.2"
KernSmooth   NA      NA     "yes"            "3.4.2"
knitr        NA      NA     "no"             "3.4.2"
labeling     NA      NA     "no"             "3.4.2"
lattice      NA      NA     "yes"            "3.4.2"
lava         NA      NA     "no"             "3.4.2"
lazyeval     NA      NA     "yes"            "3.4.2"
lubridate    NA      NA     "yes"            "3.4.2"
magrittr     NA      NA     "no"             "3.4.2"
maps         NA      NA     "yes"            "3.4.2"
markdown     NA      NA     "yes"            "3.4.2"
MASS         NA      NA     "yes"            "3.4.2"
Matrix       NA      NA     "yes"            "3.4.2"
memoise      NA      NA     "no"             "3.4.2"
methods      NA      NA     "yes"            "3.4.2"
mgcv         NA      NA     "yes"            "3.4.2"
mime         NA      NA     "yes"            "3.4.2"
mnormt       NA      NA     "yes"            "3.4.2"
ModelMetrics NA      NA     "yes"            "3.4.2"
modelr       NA      NA     "no"             "3.4.2"
munsell      NA      NA     "no"             "3.4.2"
nlme         NA      NA     "yes"            "3.4.2"
nnet         NA      NA     "yes"            "3.4.2"
numDeriv     NA      NA     "no"             "3.4.2"
openssl      NA      NA     "yes"            "3.4.2"
packrat      NA      NA     "no"             "3.4.2"
parallel     NA      NA     "yes"            "3.4.2"
pbdZMQ       NA      NA     "yes"            "3.4.2"
pkgconfig    NA      NA     "no"             "3.4.2"
PKI          NA      NA     "yes"            "3.4.2"
plogr        NA      NA     "no"             "3.4.2"
plyr         NA      NA     "yes"            "3.4.2"
praise       NA      NA     "no"             "3.4.2"
prodlim      NA      NA     "yes"            "3.4.2"
pryr         NA      NA     "yes"            "3.4.2"
psych        NA      NA     "no"             "3.4.2"
purrr        NA      NA     "yes"            "3.4.2"
quantmod     NA      NA     "yes"            "3.4.2"
R6           NA      NA     "no"             "3.4.2"
randomForest NA      NA     "yes"            "3.4.2"
rbokeh       NA      NA     "no"             "3.4.2"
RColorBrewer NA      NA     "no"             "3.4.2"
Rcpp         NA      NA     "yes"            "3.4.2"
RcppRoll     NA      NA     "yes"            "3.4.2"
RCurl        NA      NA     "yes"            "3.4.2"
readr        NA      NA     "yes"            "3.4.2"
readxl       NA      NA     "yes"            "3.4.2"
recipes      NA      NA     "no"             "3.4.2"
rematch      NA      NA     "no"             "3.4.2"
repr         NA      NA     "no"             "3.4.2"
reshape2     NA      NA     "yes"            "3.4.2"
RJSONIO      NA      NA     "yes"            "3.4.2"
rlang        NA      NA     "yes"            "3.4.2"
rmarkdown    NA      NA     "no"             "3.4.2"
robustbase   NA      NA     "yes"            "3.4.2"
rpart        NA      NA     "yes"            "3.4.2"
rprojroot    NA      NA     "no"             "3.4.2"
rsconnect    NA      NA     "no"             "3.4.2"
rstudioapi   NA      NA     "no"             "3.4.2"
rvest        NA      NA     "no"             "3.4.2"
scales       NA      NA     "yes"            "3.4.2"
selectr      NA      NA     "no"             "3.4.2"
sfsmisc      NA      NA     "no"             "3.4.2"
shiny        NA      NA     "no"             "3.4.2"
sourcetools  NA      NA     "yes"            "3.4.2"
spatial      NA      NA     "yes"            "3.4.2"
splines      NA      NA     "yes"            "3.4.2"
stats        NA      NA     "yes"            "3.4.2"
stats4       NA      NA     NA               "3.4.2"
stringi      NA      NA     "yes"            "3.4.0"
stringr      NA      NA     "no"             "3.4.2"
survival     NA      NA     "yes"            "3.4.2"
tcltk        NA      NA     "yes"            "3.4.2"
testthat     NA      NA     "yes"            "3.4.0"
tibble       NA      NA     "yes"            "3.4.2"
tidyr        NA      NA     "yes"            "3.4.2"
tidyselect   NA      NA     "yes"            "3.4.2"
tidyverse    NA      NA     "no"             "3.4.2"
timeDate     NA      NA     "no"             "3.4.2"
tools        NA      NA     "yes"            "3.4.2"
TTR          NA      NA     "yes"            "3.4.2"
utils        NA      NA     "yes"            "3.4.2"
uuid         NA      NA     "yes"            "3.4.2"
viridisLite  NA      NA     "no"             "3.4.2"
whisker      NA      NA     "no"             "3.4.2"
withr        NA      NA     "no"             "3.4.2"
xml2         NA      NA     "yes"            "3.4.2"
xtable       NA      NA     "no"             "3.4.2"
xts          NA      NA     "yes"            "3.4.2"
yaml         NA      NA     "yes"            "3.4.2"
zoo          NA      NA     "yes"            "3.4.2"

**Comment by seankross** [comment]
Are you launching RStudio from within Anaconda? I can’t think of why that would cause a problem for installing these packages, but perhaps that’s the source of the issue.

**Comment by colinastewart** [comment]
Aha!  That was the problem.  Thank you so much!

------
Colin A. Stewart

Ph.D. Candidate
Materials Department
University of California
Santa Barbara, CA 93106

colinstewart@engineering.ucsb.edu
