### ISSUE TITLE
Issue installing "R Programming" 

### ISSUE THREAD

**Issue by lizl90** [swirldev/swirl#662]
I have installed swirl with no problem (version 2.4.3) however when I try and install "R Programming" I get the following error message:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Failed to connect to github.com port 80: Timed out

I'm trying to load it on my work computer, just wondering if this an issue with my permissions? I'd be very grateful for any ideas..

**Comment by seankross** [comment]
Try the manual installation instructions here: http://swirlstats.com/scn/rprog.html

**Comment by lizl90** [comment]
Thanks Sean - all sorted now
