### ISSUE TITLE
unable to install testthat dependency

### ISSUE THREAD

**Issue by couzhei** [swirldev/swirl#670]
Hi, I got a problem installing swirl package and have the following errors
```
make: /home/couzhei/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
make: *** [init.o] Error 127
ERROR: compilation failed for package ‘testthat’
* removing ‘/home/couzhei/anaconda3/lib/R/library/testthat’
Warning in install.packages :
  installation of package ‘testthat’ had non-zero exit status
ERROR: dependency ‘testthat’ is not available for package ‘swirl’
* removing ‘/home/couzhei/anaconda3/lib/R/library/swirl’
Warning in install.packages :
  installation of package ‘swirl’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp56dbnv/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
```

I decided to manually install testthat package and tried this

```
> install.packages(file.choose(), repos = NULL)
* installing *source* package ‘testthat’ ...
** package ‘testthat’ successfully unpacked and MD5 sums checked
** libs
/home/couzhei/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc -I/home/couzhei/anaconda3/lib/R/include -DNDEBUG -I../inst/include -DCOMPILING_TESTTHAT  -D_FORTIFY_SOURCE=2 -O2 -I/home/couzhei/anaconda3/include   -fpic  -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -I/home/couzhei/anaconda3/include  -c init.c -o init.o
make: /home/couzhei/anaconda3/bin/x86_64-conda_cos6-linux-gnu-cc: Command not found
make: *** [init.o] Error 127
ERROR: compilation failed for package ‘testthat’
* removing ‘/home/couzhei/anaconda3/lib/R/library/testthat’
Warning in install.packages :
  installation of package ‘/home/couzhei/Downloads/testthat_2.0.0.tar.gz’ had non-zero exit status
```
Oh  this one also looks tricky, I ran `rstudio &` on the console but after I ran these two commands, the console echoed this
```
couzhei@couzhei-lappy:~$ rstudio &
[1] 12275
couzhei@couzhei-lappy:~$ load glyph failed err=6 face=0x55fbc927c360, glyph=2797
load glyph failed err=6 face=0x55fbc927c360, glyph=2797

```
paralysed my terminal to force me use ^+C to terminate it.
I have an ubuntu 14.04 and running all these codes on RStudio with R 3.4.2 installed, if that helps.

One thing though, I become suspicious of anaconda3, I don't know a lot about it, but as a whole Python ecosystem management tool, I kinda admire it (it has all the packages you need it with an ability to update them all with a single command) and that's the sole reason I'm using it, however [here](https://github.com/JuliaLang/IJulia.jl/issues/616) I'm facing another issue which I somehow blame anaconda3 for it too(not sure, wild guess), but I decided to postpone it for now and run jupyter notebook on JuliaBox (which is a web-based development environment) and come back to it later.

Do you think anaconda3 is causing these kinds of problems? Should I remove it and installed my needed applications separately?

**Comment by mesamiked** [comment]
From your description I assume that you installed R with the anaconda r-essentials package, for I ran into the same problem.  I resolved it by installing the r-testthat package with the command:  conda install r r-testthat    .  For a complete description of the process see my response to Issue #656  at https://github.com/swirldev/swirl/issues/656   .
Hope this helps.

**Comment by couzhei** [comment]
That worked like a charm, I can't be appreciated more. Thx dude

**Comment by ColR** [comment]
Seems to still be a problem but your solution is still working. Thanks
