### ISSUE TITLE
How to manually submit swirl course on Coursera.org? - submit script not working on Windows 7 

### ISSUE THREAD

**Issue by gabrich10** [swirldev/swirl#680]
Hi,

I  completed swirl Lesson 1: Basic Building Blocks from Practical R Exercises in swirl Part 1. I had to download the course manually using the *.zip located at https://github.com/swirldev/swirl_courses. The problem is that in the computer I am using I cannot have access to URLs using curl command. This is due to network configuration. I receive the following error when trying to submit my swirl Lesson:

Error in curl::curl_fetch_memory(url, handle = handle) : 
  Could not resolve host: www.coursera.org

| Leaving swirl now. Type swirl() to resume.

I am not authorized to change network settings on this computer so, I was just wondering if there is any way to manually submit the completed lessons.

I would appreciate orientation on this. Thanks in advance.

Gabriel.

**Comment by seankross** [comment]
Hi @gabrich10,

If you're taking the R Programming course, then there's no way to manually submit. That's why these exercises are for extra credit only.
