### ISSUE TITLE
Error load library(swirl)

### ISSUE THREAD

**Issue by JuanAndresAlban** [swirldev/swirl#692]
Can someone please help me with the following?

When loading library(swirl) I get the following error message:

Error: package or namespace load failed for ‘swirl’ in namespaceExport(ns, exports):
 undefined exports: %s!=%, %s!==%, %s+%, %s<%, %s<=%, %s==%, %s===%, %s>%, %s>=%, %stri!=%, %stri!==%, %stri+%, %stri<%, %stri<=%, %stri==%, %stri===%, %stri>%, %stri>=%, stri_datetime_add<-, stri_sub<-, stri_subset<-, stri_subset_charclass<-, stri_subset_coll<-, stri_subset_fixed<-, stri_subset_regex<-, stri_c, stri_c_list, stri_cmp, stri_cmp_eq, stri_cmp_equiv, stri_cmp_ge, stri_cmp_gt, stri_cmp_le, stri_cmp_lt, stri_cmp_neq, stri_cmp_nequiv, stri_compare, stri_conv, stri_count, stri_count_boundaries, stri_count_charclass, stri_count_coll, stri_count_fixed, stri_count_regex, stri_count_words, stri_datetime_add, stri_datetime_create, stri_datetime_fields, stri_datetime_format, stri_datetime_fstr, stri_datetime_now, stri_datetime_parse, stri_datetime_symbols, stri_detect, stri_detect_charclass, stri_detect_coll, stri_detect_fixed, stri_detect_regex, stri_dup, stri_duplicated, stri_duplicated_any, stri

I am using Windows 10.

Session Info:
R version 3.4.4 (2018-03-15)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.13.5

loaded via a namespace (and not attached):
 [1] httr_1.3.1      compiler_3.4.4  R6_2.2.2        tools_3.4.4     withr_2.1.2     RCurl_1.95-4.10
 [7] curl_3.1        yaml_2.1.18     memoise_1.1.0   git2r_0.21.0    digest_0.6.15   bitops_1.0-6

**Comment by mbaradas** [comment]
@JuanAndresAlban did you find a solution? I get the same error.  thanks

**Comment by JuanAndresAlban** [comment]
Installing the newest version of RStudio solved the problem for me.

**Comment by jnicholsonjr** [comment]
I'm getting the same exact error, windows 10 x64. So far I've reinstalled Rstudio (running 1.1.456) and updated packages and there's no change. Unlike the other swirl errors I've dealt with this one doesn't seem to offer up much in the way of useful info.

**Comment by jnicholsonjr** [comment]
Of course as soon as I posted that I found a workable solution. When I installed swirl originally it wasn't loading the package called "stringi" and I was getting errors related to that. I got that installed with install.packages("stringi") and had to click "no" on the popup box to get it to install correctly. In order to run swirl to load by library(swirl) I had to reinstall stringi and now swirl will load and run.

**Comment by PereiraSostiene** [comment]
For me it worked with the solution provided by jnicholsonjr!

Thanks

**Comment by ShannayR** [comment]
I would like to begin by pointing out that I am new to R and programming in general. The solution provided by @jnicholsonjr worked out fine, and has helped my learn to troubleshoot small bumps and roadblocks like  #803 in a practical manner. 
Thank you so much.
