### ISSUE TITLE
Course ‘R Programming’NULL

### ISSUE THREAD

**Issue by fellasunt** [swirldev/swirl#696]
Hi everyone

I'm new to swirl so please forgive any  deviation from protocol. Not intentional.

I have managed to successfully install swirl on Ubuntu 14.04 64bit. R and swirl, library loading etc seem to be working ok.
 I am currently trying to manually install the lessons after the automatic method failed with:

/*----  Diags:

| To begin, you must install a course. I can install a course for you from the
| internet, or I can send you to a web page
| (https://github.com/swirldev/swirl_courses) which will provide course options
| and directions for installing courses yourself. (If you are not connected to
| the internet, type 0 to exit.)

1: R Programming: The basics of programming in R
2: Regression Models: The basics of regression modeling in R
3: Statistical Inference: The basics of statistical inference in R
4: Exploratory Data Analysis: The basics of exploring data in R
5: Don't install anything for me. I'll do it myself.

Selection: 1
  |======================================================================| 100%

| Sorry, but I'm unable to fetch ‘R Programming: The basics of programming in
| R’ right now. Are you sure you have an internet connection? If so, would you
| like to try again or visit the course repository for instructions on how to
| install a course manually? Type 0 to exit.

1: Try again!
2: Send me to the course repository for manual installation.
 
---- Diags */

My internet connection works fine. I used the same connection to download and install  R and swirl.

So having gone to the manual option, I successfully downloaded the swirl_courses-matser.zip file to my  ~/Downloads directory. I am able to browse and extract items from the zip file so I do believe that it has downloaded successfully

So I tried the  manual option as shown on the website;

/*----  Diags:

> install_course_zip("~/Downloads/swirl_courses-master.zip", multi=TRUE, which_course="R Programming")
Error in install_course_zip("~/Downloads/swirl_courses-master.zip", multi = TRUE,  : 
  Course ‘R Programming’NULL
In addition: Warning message:
In unzip(path, exdir = swirl_courses_dir(), files = unzip_list) :
  error -1 in extracting from zip file

> file.exists("~/Downloads/swirl_courses-master.zip")
[1] TRUE

---- Diags */ 

I've looked on the net for various solutions which have been unsuccessful or duplicates of what I have already tried so I'm not really sure what else to try. 

Any assistance in this regard would be gratefully accepted

Kind regards

Fella

**Comment by seankross** [comment]
Try the manual installation instructions here: swirlstats.com/scn/rprog.html

**Comment by fellasunt** [comment]
Hi Sean

Thanks so much for your help.

The command actually failed:

/*---- Diags

> swirl::install_course("R Programming")
  |======================================================================|
100%
Error in file(con, "wb") : cannot open the connection
In addition: Warning message:
In file(con, "wb") :
  cannot open file
'/usr/local/lib/R/site-library/swirl/Courses/R_Programming/Base_Graphics/customTests.R':
No such file or directory
>

---- Diags */

I went and had a look at the path /usr/local/lib/R/site-library/swirl/ ...
and figured out that this was all owned by root.

 I must have initially installed the system as root  and then tried to
install the courseware as 'R user'


I did:

/* --- Actions

 R

R version 3.4.4 (2018-03-15) -- "Someone to Lean On"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> swirl::install_course("R Programming")
  |======================================================================|
100%

| Course installed successfully!

>


--- Actions */


Thank you so much for your quick response and all your help! I really
appreciate it

Kind regards

Fella
