### ISSUE TITLE
Blank script in Function lesson

### ISSUE THREAD

**Issue by togogh** [swirldev/swirl#702]
In Functions, supposed to be seeing the script of my first function. boring_function.R opens, but is blank. No idea how to progress with the lesson from here. Screenshot below.

![image](https://user-images.githubusercontent.com/5388340/39877481-a3c79c84-54a8-11e8-8dee-0bfc4d55a464.png)

**Comment by sf-rocha** [comment]
Hi Interseksyon,

Have you found a solution to this problem? I'm having a similar issue and cannot progress with the course. If I type in skip() then I get the solution but this isn't quite ideal..

Thanks

**Comment by KaticaR** [comment]
I also have the same problem, but I was just skip() - ing the questions with the scripts.
Don't understand why no one have solved them.

**Comment by togogh** [comment]
Hello everyone! Jumping back in to say I've figured out a fix. Once boring_function opens, click File > Reopen with Encoding > Select UTF-8 and check "Set as default encoding for source files". Now your scripts should load properly.

Blank files are apparently a common issue in Rstudio, and I found the fix here: https://github.com/rstudio/rstudio/issues/1623
