### ISSUE TITLE
swirl courses not installing

### ISSUE THREAD

**Issue by multiiiii** [swirldev/swirl#710]
When i try to install a new course, i get the error message "It looks like your internet connection is not working. Go to http://swirlstats.com/scn/ and
| download the .swc file that corresponds to the course you wish to install. After downloading the
| .swc run install_course() and choose the file you downloaded.
Error in install_course(course_name = "Data_Analysis") : 
  Could not connect to course file.", even though my internet connection works just fine. 

When i try to install the course manually i get the error message "Error in unzip(path, list = TRUE) : 
  zip file 'C:/Users/adria/OneDrive/Documents/Downloads/swirl_courses-master.zip' cannot be opened", even though the path is correct. 

I have also tried uninstalling Rstudio and install it again, but with no sucess. Any ideas what i could try next?

**Comment by zackgmani** [comment]
Were you able to resolve this? I think I'm having a similar issue.

**Comment by SuhasKirani** [comment]
I have just start this course and I am stuck with same Error message. Can any help in resolving this issue ?

<img width="500" alt="Image" src="https://github.com/user-attachments/assets/c167b5c7-0439-405e-8f27-2d7e33fb0da7" />
