### ISSUE TITLE
Error while downloading "R programming" from swirl

### ISSUE THREAD

**Issue by Rimkap** [swirldev/swirl#716]
> install_from_swirl("R Programming")
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Resolving timed out after 10000 milliseconds

**Comment by Rimkap** [comment]
Anyone available to guide on how to get past the error?

**Comment by seankross** [comment]
Try: `install_course("R Programming")`

**Comment by Rimkap** [comment]
Error in install_course("R Programming") : 
  could not find function "install_course"

**Comment by Rimkap** [comment]
Thanks but still got this error :
Error in install_course("R Programming") : 
  could not find function "install_course"

**Comment by seankross** [comment]
Try: `swirl::install_course("R Programming")`

**Comment by Rimkap** [comment]
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Timeout was reached: Resolving timed out after 10015 milliseconds
still the same error.

**Comment by Rimkap** [comment]
I have manually downloaded the folder to my local drive, what is the next step after this please

**Comment by seankross** [comment]
Follow the manual installation instructions here: http://swirlstats.com/scn/rprog.html

**Comment by Rimkap** [comment]
awesome! Worked YAY!
