### ISSUE TITLE
Cannot install R programming course or other versions

### ISSUE THREAD

**Issue by JCRMT-lima** [swirldev/swirl#743]
Hi All,

I am getting an error message both in RStudio and R console:
Course 'R_programming_Alt' not found in course repository! Make sure you've got the name exactly right, then try again.

I've tried with the following but get the same error:
R programming
R_programming
R_ programming_Alt

I have:  
> packageVersion("swirl")
[1] ‘2.4.3’

**Comment by seankross** [comment]
See installation instructions here: https://swirlstats.com/scn/rprog.html
