### ISSUE TITLE
Error in Open Intro module1

### ISSUE THREAD

**Issue by joedonahoe** [swirldev/swirl#85]
I'm getting an error that causes swirl to exit in Open Intro, module1.  

| Here's a dot plot using the variable 'price' from our 'cars' data set. As you may notice, the price
| is reported along the x-axis in $1000s, and each point above the axis represents the price of one of
| the 54 cars in our data set.

Error in plot.new() : figure margins too large

| Leaving swirl now. Type swirl() to resume.

> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same name as you did then. If you are new, call yourself
| something unique.

What shall I call you? Joe

| Would you like to continue with one of these modules?

1: Open Intro module1
2: No. Let me start something new.

Selection: 1
Error in eval(expr, envir, enclos) : 
  could not find function "draw.circle"

| Leaving swirl now. Type swirl() to resume.

**Comment by ClimbsRocks** [comment]
I just ran into the same issue on that exact same Population vs. Sample graph you used as an example. My issue came in the Data Analysis course. Increasing the window size worked perfectly for me. I just added a minor PR https://github.com/swirldev/swirl/issues/85 to give users guidance on what to do if they encounter the same issue.
