### ISSUE TITLE
Swirl Assignment 1

### ISSUE THREAD

**Issue by NonopaMabongo** [swirldev/swirl#878]
I'm having an issue with the swirl assignment id does not want to load the lesson.
![2021-10-18](https://user-images.githubusercontent.com/92318957/137737010-34c72975-a03e-48d2-a983-cce11723bab7.png)

**Comment by MariaAlva** [comment]
I am receiving the following error

WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
trying URL 'https://cran.rstudio.com/bin/windows/contrib/4.1/learnr_0.10.1.zip'
Content type 'application/zip' length 1661745 bytes (1.6 MB)
downloaded 1.6 MB
> https://cran.rstudio.com/bin/windows/Rtools/
Error: unexpected '/' in "https:/"

Could you kindly provide instructions on how to successfully download Rtools? Thank you

**Comment by NonopaMabongo** [comment]
Thank you for your response I will Try it that way.

**Comment by NonopaMabongo** [comment]
thank you it works now
