### ISSUE TITLE
Can't install swirl 

### ISSUE THREAD

**Issue by KristinaBabaian** [swirldev/swirl#902]
macOS Big Sur 11.7.3 R 4.2.2 GUI 1.79 High Sierra build
install.packages("swirl")
also installing the dependency ‘RCurl’

  There is a binary version available but the source version is later:
        binary    source needs_compilation
RCurl 1.98-1.9 1.98-1.10              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) ye
trying URL 'https://cran.rstudio.com/bin/macosx/contrib/4.2/swirl_2.4.5.tgz'
Content type 'application/x-gzip' length 348108 bytes (339 KB)
==================================================
downloaded 339 KB

The downloaded binary packages are in
	/var/folders/59/dgqwp5816dv26fgdxzx5nyd40000gn/T//Rtmpo0GiRB/downloaded_packages
installing the source package ‘RCurl’

trying URL 'https://cran.rstudio.com/src/contrib/RCurl_1.98-1.10.tar.gz'
Content type 'application/x-gzip' length 731446 bytes (714 KB)
==================================================
downloaded 714 KB

* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
** using staged installation
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
checking for curl-config... /usr/bin/curl-config
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/private/var/folders/59/dgqwp5816dv26fgdxzx5nyd40000gn/T/RtmpvYgKOO/R.INSTALLa3583fab7a/RCurl':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘RCurl’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/RCurl’
Warning in install.packages :
  installation of package ‘RCurl’ had non-zero exit status

The downloaded source packages are in
	‘/private/var/folders/59/dgqwp5816dv26fgdxzx5nyd40000gn/T/Rtmpo0GiRB/downloaded_packages’

**Comment by guimondmm** [comment]
This seems to be a problem with the Xcode Command Line Tools.

If you have the full version of Xcode.app, try typing the following in a Terminal to activate it:

```sh
sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license accept
```

If Xcode.app isn't installed, try the following to install the Command Line Tools instead:

```sh
xcode-select --install
sudo xcode-select --switch /Library/Developer/CommandLineTools
```
