### ISSUE TITLE
Google Colab?

### ISSUE THREAD

**Issue by danielsadoc** [swirldev/swirl#923]
Hi Everyone, can we run swirl() using Google Colab? I run swirl() but do not get any output.

install_course("R Programming")

![image](https://github.com/swirldev/swirl/assets/38542060/8f15e072-32f9-45a2-9916-a187fb362279)

then, nothing happens. How to proceed?

https://colab.research.google.com/drive/1JTEfDuwIfQEetwxzSmoeNybbiddkbFWM?usp=sharing

**Comment by seankross** [comment]
Swirl is not compatible with Google Colab.
