### ISSUE TITLE
A course publish method

### ISSUE THREAD

**Issue by lcolladotor** [swirldev/swirl#96]
Hello,

Correct me if I overlooked something, but it seems that there is no function in `swirl` to publish a course. I understand that you can zip a course directory and then distribute it. I also understand that you can have the course in GitHub (in a format whose documentation I haven't found). 

Lets say that you choose to use GitHub for distributing courses (and also version controlling their material as well for managing issues reported by users). One idea is to share them via gist's and have maybe a "course viewer" kind of like http://rcharts.io/viewer/ which is built on pagist (more here http://rcharts.readthedocs.org/en/latest/intro/share.html and here https://github.com/ramnathv/rCharts/issues/363). Or something like `slidify::publish(user="", repo="")` http://slidify.org/publish.html which requires you to have SSL config setup for GitHub + creating the repo before using the function. In a way, using gist's might be easier (no SSL and/or setting the github username/password on the config file is needed) but I think that the repo's offer nice advantages like the issues management + forking for crowd-developing. You could even take the repo idea one step ahead and use slidify to document and create the course main site using "web docs" (see https://github.com/ramnathv/rCharts/issues/362 and here is an example http://rcharts.io/howitworks/) .

Ideally, I think that the publish method should have an argument `share` that when if `TRUE` the gist or repo (depending what you choose to implement) url is added to a website showcasing the available courses (probably part of http://swirlstats.com/). There could also be a function like `list_available_courses()` which shows the publicly shared courses. 

Keep up the great work!
Cheers

**Comment by seankross** [comment]
This has mostly been solved by swirlify and http://swirlstats.com/scn/
